(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 468,
	height: 60,
	fps: 18,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/HTML5rastershad.png", id:"HTML5rastershad"},
		{src:"images/SCU201609_Air_468x60_AdR_atlas_NP_.jpg", id:"SCU201609_Air_468x60_AdR_atlas_NP_"}
	]
};



lib.ssMetadata = [
		{name:"SCU201609_Air_468x60_AdR_atlas_NP_", frames: [[0,0,336,224],[338,0,168,141]]}
];


lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib._336x280air = function() {
	this.spriteSheet = ss["SCU201609_Air_468x60_AdR_atlas_NP_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib._336x280dev = function() {
	this.spriteSheet = ss["SCU201609_Air_468x60_AdR_atlas_NP_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.Tween2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._336x280dev();
	this.instance.setTransform(-35.8,-29.8,0.426,0.426);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-35.8,-29.8,71.6,60.1);


(lib.Tween1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._336x280dev();
	this.instance.setTransform(-35.7,-29.8,0.426,0.426);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-35.7,-29.8,71.6,60.1);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#3F3F3F").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._336x280air();
	this.instance.setTransform(-109,-80,0.65,0.65);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-109,-80,218.5,145.7);


(lib.ncuahorizai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACPAmIADgGQADACAEAAQAGAAADgJIgUgsIAHAAIARAlIAPglIAHAAIgTAuQgFANgLAAQgFAAgFgCgAAwAXQgFgFAAgGQAAgIAFgEQAGgCAJAAQAFAAAKACIAAgBQAAgNgPAAQgGAAgHAEIgDgGQAJgEAIAAQAKAAAGAFQAEAFAAAJIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgFgDgAAyALQAAAKAMAAQAGAAAFgEQAFgDAAgGIAAgEQgIgCgGAAQgOAAAAAJgAgjAUQgHgHAAgLQABgIAGgHQAGgHAKAAQAJAAAHAHQADAHAAAIIAAADIgjAAQABAHAFAEQAEAEAHAAQAIAAAGgGIAEAEQgHAIgLAAQgKAAgHgGgAgFAAQgBgOgNAAQgHAAgDAEQgFAEgBAGIAeAAIAAAAgAhfAUQgGgHAAgLQAAgJAGgHQAHgGAJAAQAKAAAIAKIAAgcIAHAAIAAA/IgHAAIAAgJQgHAKgLAAQgJAAgHgGgAhZgJQgFAFAAAGIAAAAQAAAIAFAFQAFAFAGAAQAHAAAFgFQAFgFAAgIIAAAAQAAgGgFgFQgFgFgHAAQgHAAgEAFgAiUAUQgHgHABgLQAAgIAFgHQAHgHAJAAQALAAAGAHQAGAHAAAIIgBADIglAAQACAPAOAAQAJAAAHgGIADAEQgHAIgMAAQgKAAgGgGgAh1AAQgCgOgOAAQgFAAgFAEQgDAEgCAGIAfAAIAAAAgAB7AZIAAg/IAHAAIAAA/gABjAZIAAg/IAIAAIAAA/gAAMAZIAAgsIAHAAIAAAMQAHgNAMAAIAAAHIAAAAQgIAAgFAGQgFAGgBAIIAAASgAi1AZIAAgmIgHAAIAAgGIAHAAIAAgEQAAgIADgEQAFgEAFAAIAIABIAAAGIgHgBQgHAAgBAKIAAAEIAPAAIAAAGIgPAAIAAAmg");
	this.shape.setTransform(-36.4,4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AA+AlIADgFQADABAEABQAGAAADgJIgUgsIAHAAIARAkIAPgkIAHAAIgTAtQgFANgLAAQgGAAgEgCgAE2AXQgGgFAAgHQAAgNAUAAQAFAAAKACIAAgBQgBgNgOAAQgGAAgHAEIgDgGQAIgEAJAAQALAAAEAFQAFAEAAAKIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgEgDgAE3ALQAAAJAMAAQAGABAFgEQAEgDABgGIAAgFQgIgCgGAAQgOAAAAAKgAD7AIIAAgbIAIAAIAAAZQgBAOANAAQAHAAADgEQAFgEAAgHIAAgYIAGAAIAAAsIgGAAIAAgIQgHAJgKAAQgRAAgBgSgADNATQgHgHAAgKQAAgIAHgIQAHgGAKAAQAKgBAJAJIgFAEQgIgHgGAAQgIABgEAFQgFAFAAAFIAAABQAAAHAFAGQAFAFAHAAQAIAAAGgHIAFAEQgIAJgLAAQgKAAgHgHgAAPAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgLALABQAIgBAGAHQAIAHgBAIIAAABQABALgIAGQgGAHgIAAQgMAAgGgKgAATgJQgEAFAAAFIAAABQAAAHAEAGQAGAFAGAAQAHAAAFgFQAEgFAAgIQAAgGgEgFQgFgFgHAAQgGAAgGAFgAhJATQgHgGAAgLQAAgJAHgHQAHgHAJABQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgHgAhEgJQgEAFAAAFIAAABQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgGABgHIAAgBQgBgFgFgFQgEgFgHAAQgIAAgEAFgAh+ATQgHgGAAgLQAAgIAGgIQAGgGAKAAQAKAAAGAGQAGAIAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEADQgHAJgMAAQgKAAgGgHgAhgAAQgCgPgNAAQgGABgEAEQgEAEgBAGIAeAAIAAAAgAjYAVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOANAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgJAAgEgFgAkNATIADgFQAIAGAIAAQAKAAAAgIQAAgEgMgDQgPgFAAgHQAAgGAFgEQAEgDAHAAQAJgBAIAGIgDAFQgIgEgGgBQgJAAAAAHQAAAFAMADQAPADAAAJQAAAGgFAFQgEADgIAAQgLAAgIgHgACzAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAEQAFAFAAAJIAAAbgAilAZIAAgsIAHAAIAAALQAGgMANAAIAAAHIgBAAQgIAAgEAFQgGAGAAAJIAAASgAkfAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAEQAFAFAAAJIAAAbgAlXAZIAAgsIAHAAIAAAsgAlYgdIAAgIIAIAAIAAAIg");
	this.shape_1.setTransform(20.8,4.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.3,0,110.7,8.1);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F78E1E").s().p("AgKAMIAAgXIAWAAIAAAXg");
	this.shape.setTransform(142,15.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F78E1E").s().p("AgRAtQgNgGgGgFIAJgOQAIAFAIADQAIADAGAAQAHAAADgDQAEgCAAgFQAAgFgGgEIgNgFQgOgEgGgDQgFgDgCgEQgDgFAAgHQAAgHADgFQACgFAFgEQAFgEAGgCQAGgCAFAAQAJAAAJADQAJADAIAFIgIAPIgOgGQgIgDgFAAQgFAAgDADQgEADAAAEIAAAAQAAAFAHADIANAGIAKADIAKAEQAEADADAEQACAFAAAGIAAABQAAAHgCAGQgDAFgFAEQgFAEgGACQgGACgIAAQgIAAgLgEg");
	this.shape_1.setTransform(134.9,11.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F78E1E").s().p("AgRAtQgNgGgGgFIAJgOQAIAFAIADQAIADAGAAQAHAAADgDQAEgCAAgFQAAgFgGgEIgNgFQgOgEgGgDQgFgDgCgEQgDgFAAgHQAAgHADgFQACgFAFgEQAFgEAGgCQAGgCAFAAQAJAAAJADQAJADAIAFIgIAPIgOgGQgIgDgFAAQgFAAgDADQgEADAAAEIAAAAQAAAFAHADIANAGIAKADIAKAEQAEADADAEQACAFAAAGIAAABQAAAHgCAGQgDAFgFAEQgFAEgGACQgGACgIAAQgIAAgLgEg");
	this.shape_2.setTransform(125.9,11.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F78E1E").s().p("AgPAuQgJgEgHgHQgGgGgEgJIgCgJIgCgLIAAAAQAAgIAEgKQAEgIAGgHQAGgIAIgDIAJgDIAIgBIALABIAJADQAGACAIAKQAFAGADAJQAEAJAAAJIgBAGIhEAAQABAGACAEQADAFAEADIAIAFIAIABQAHAAAGgCQAGgEAHgFIAMALIgIAIIgIAFIgLAEIgMABQgIAAgJgDgAAYgFQAAgGgDgEIgFgIQgDgEgDgCQgFgBgFAAQgDAAgEABQgFACgDAEQgDADgCAFIgDAKIAvAAIAAAAg");
	this.shape_3.setTransform(116.2,11.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F78E1E").s().p("AAVAwIAAg0QAAgGgCgEIgEgHQgCgDgEgCQgEgCgFAAQgDAAgDACQgEACgDADQgDADgCAFQgBAEAAAGIAAAzIgWAAIAAhdIAWAAIAAAPQAFgIAGgEIAIgEIAIgBQAIAAAHACQAGADAEAFQAFAFACAGQACAHAAAIIAAA7g");
	this.shape_4.setTransform(105.2,11.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F78E1E").s().p("AgJBBIAAhdIATAAIAABdgAgKgrIAAgVIAVAAIAAAVg");
	this.shape_5.setTransform(97,9.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F78E1E").s().p("AgRAtQgNgGgGgFIAJgOQAIAFAIADQAIADAGAAQAHAAADgDQAEgCAAgFQAAgFgGgEIgNgFQgOgEgGgDQgFgDgCgEQgDgFAAgHQAAgHADgFQACgFAFgEQAFgEAGgCQAGgCAFAAQAJAAAJADQAJADAIAFIgIAPIgOgGQgIgDgFAAQgFAAgDADQgEADAAAEIAAAAQAAAFAHADIANAGIAKADIAKAEQAEADADAEQACAFAAAGIAAABQAAAHgCAGQgDAFgFAEQgFAEgGACQgGACgIAAQgIAAgLgEg");
	this.shape_6.setTransform(89.8,11.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F78E1E").s().p("AgWAuQgGgDgEgFQgFgFgCgGQgCgIAAgHIAAg7IAWAAIAAA0QAAAFABAFQABAEADADQADADADACQAEABAEAAQAEAAAEgBQAEgCACgDQADgDACgFQABgEAAgGIAAgzIAWAAIAABdIgWAAIAAgPQgFAIgGAEIgIAEQgDABgFAAQgIAAgHgCg");
	this.shape_7.setTransform(79.8,11.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F78E1E").s().p("AgEBBIgJgEQgHgEgGgIIAAAPIgWAAIAAiBIAWAAIAAA0QAGgIAHgFQAEgCAFgBQAEgCAEAAQAJAAAIADQAIAEAGAGQAGAHAEAJQAEALAAAIIgBALIgDAKQgDAJgHAGQgGAHgIADQgIADgJAAQgEAAgEgBgAgJgKQgFADgEAEQgEADgCAEQgCAGAAAHQAAAHACAFIAGAKIAJAGQAFACAEAAQAFAAAFgCQAFgCAEgEQADgEACgFQADgGAAgHQAAgHgDgGQgCgEgEgEQgDgEgFgCQgFgCgFAAQgEAAgFACg");
	this.shape_8.setTransform(68.5,9.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#F78E1E").s().p("AAVBBIAAg2QAAgFgCgFIgEgFQgCgDgEgBQgEgCgFAAQgDAAgDACQgEABgDADQgDADgCADQgBAEAAAGIAAA1IgWAAIAAiBIAWAAIAAAzQAFgIAGgEIAIgDIAIgCQAIAAAHADQAGACAEAFQAFAFACAHQACAHAAAGIAAA8g");
	this.shape_9.setTransform(51.3,9.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#F78E1E").s().p("AAAA7QgFgBgDgDQgEgEgCgFQgCgFAAgIIAAgwIgMAAIAAgTIAMAAIAAgaIAUAAIAAAaIAZAAIAAATIgZAAIAAAtQAAAGADADQADACAFAAQAHAAAHgDIAAASIgJAEIgLABQgGAAgDgCg");
	this.shape_10.setTransform(41.9,10.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#F78E1E").s().p("AgJBBIAAhdIATAAIAABdgAgKgrIAAgVIAVAAIAAAVg");
	this.shape_11.setTransform(35.8,9.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#F78E1E").s().p("AAUAwIgUg/IgUA/IgUAAIgeheIAWAAIATA/IAVhAIARAAIAVBAIATg/IAWAAIgfBeg");
	this.shape_12.setTransform(25.6,11.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#F78E1E").s().p("AgRAtQgNgGgGgFIAJgOQAIAFAIADQAIADAGAAQAHAAADgDQAEgCAAgFQAAgFgGgEIgNgFQgOgEgGgDQgFgDgCgEQgDgFAAgHQAAgHADgFQACgFAFgEQAFgEAGgCQAGgCAFAAQAJAAAJADQAJADAIAFIgIAPIgOgGQgIgDgFAAQgFAAgDADQgEADAAAEIAAAAQAAAFAHADIANAGIAKADIAKAEQAEADADAEQACAFAAAGIAAABQAAAHgCAGQgDAFgFAEQgFAEgGACQgGACgIAAQgIAAgLgEg");
	this.shape_13.setTransform(7.8,11.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#F78E1E").s().p("AgRAtQgNgGgGgFIAJgOQAIAFAIADQAIADAGAAQAHAAADgDQAEgCAAgFQAAgFgGgEIgNgFQgOgEgGgDQgFgDgCgEQgDgFAAgHQAAgHADgFQACgFAFgEQAFgEAGgCQAGgCAFAAQAJAAAJADQAJADAIAFIgIAPIgOgGQgIgDgFAAQgFAAgDADQgEADAAAEIAAAAQAAAFAHADIANAGIAKADIAKAEQAEADADAEQACAFAAAGIAAABQAAAHgCAGQgDAFgFAEQgFAEgGACQgGACgIAAQgIAAgLgEg");
	this.shape_14.setTransform(-1.2,11.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#F78E1E").s().p("AgPAuQgJgEgHgHQgGgGgEgJIgCgJIgBgLIAAAAQgBgIAEgKQAEgIAFgHQAHgIAIgDIAJgDIAIgBIAKABIAKADQAFACAJAKQAGAGADAJQADAJAAAJIgBAGIhEAAQABAGACAEQADAFADADIAIAFIAIABQAIAAAHgCQAGgEAFgFIANALIgHAIIgJAFIgLAEIgMABQgIAAgJgDgAAYgFQgBgGgCgEIgEgIQgEgEgDgCQgFgBgFAAQgDAAgEABQgFACgDAEQgDADgCAFIgDAKIAvAAIAAAAg");
	this.shape_15.setTransform(-11,11.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#F78E1E").s().p("AAVAwIAAg0QAAgGgCgEIgEgHQgCgDgEgCQgEgCgFAAQgDAAgDACQgEACgDADQgDADgCAFQgBAEAAAGIAAAzIgWAAIAAhdIAWAAIAAAPQAFgIAGgEIAIgEIAIgBQAIAAAHACQAGADAEAFQAFAFACAGQACAHAAAIIAAA7g");
	this.shape_16.setTransform(-22,11.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#F78E1E").s().p("AgJBBIAAhdIATAAIAABdgAgKgrIAAgVIAVAAIAAAVg");
	this.shape_17.setTransform(-30.1,9.9);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#F78E1E").s().p("AgRAtQgNgGgGgFIAJgOQAIAFAIADQAIADAGAAQAHAAADgDQAEgCAAgFQAAgFgGgEIgNgFQgOgEgGgDQgFgDgCgEQgDgFAAgHQAAgHADgFQACgFAFgEQAFgEAGgCQAGgCAFAAQAJAAAJADQAJADAIAFIgIAPIgOgGQgIgDgFAAQgFAAgDADQgEADAAAEIAAAAQAAAFAHADIANAGIAKADIAKAEQAEADADAEQACAFAAAGIAAABQAAAHgCAGQgDAFgFAEQgFAEgGACQgGACgIAAQgIAAgLgEg");
	this.shape_18.setTransform(-37.3,11.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#F78E1E").s().p("AgWAuQgGgDgEgFQgFgFgCgGQgCgIAAgHIAAg7IAWAAIAAA0QAAAFABAFQABAEADADQADADADACQAEABAEAAQAEAAAEgBQAEgCACgDQADgDACgFQABgEAAgGIAAgzIAWAAIAABdIgWAAIAAgPQgFAIgGAEIgIAEQgDABgFAAQgIAAgHgCg");
	this.shape_19.setTransform(-47.3,11.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#F78E1E").s().p("AgEBBIgJgEQgHgEgGgIIAAAPIgWAAIAAiBIAWAAIAAA0QAGgIAHgFQAEgCAFgBQAEgCAEAAQAJAAAIADQAIAEAGAGQAGAHAEAJQAEALAAAIIgBALIgDAKQgDAJgHAGQgGAHgIADQgIADgJAAQgEAAgEgBgAgJgKQgFADgEAEQgEADgCAEQgCAGAAAHQAAAHACAFIAGAKIAJAGQAFACAEAAQAFAAAFgCQAFgCAEgEQADgEACgFQADgGAAgHQAAgHgDgGQgCgEgEgEQgDgEgFgCQgFgCgFAAQgEAAgFACg");
	this.shape_20.setTransform(-58.6,9.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#F78E1E").s().p("AAVAwIAAg0QAAgGgCgEIgEgHQgCgDgEgCQgEgCgFAAQgDAAgDACQgEACgDADQgDADgCAFQgBAEAAAGIAAAzIgWAAIAAhdIAWAAIAAAPQAFgIAGgEIAIgEIAIgBQAIAAAHACQAGADAEAFQAFAFACAGQACAHAAAIIAAA7g");
	this.shape_21.setTransform(-75.8,11.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#F78E1E").s().p("AgJBBIAAhdIATAAIAABdgAgKgrIAAgVIAVAAIAAAVg");
	this.shape_22.setTransform(-84,9.9);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#F78E1E").s().p("AgPAuQgJgEgGgHQgHgGgEgJIgDgJIgBgLIAAAAQABgIADgKQADgIAHgHQAGgIAIgDIAJgDIAIgBIALABIAJADQAGACAIAKQAFAGADAJQADAJAAAJIAAAGIhEAAQABAGACAEQADAFAEADIAIAFIAIABQAHAAAGgCQAHgEAGgFIAMALIgIAIIgIAFIgLAEIgMABQgIAAgJgDgAAYgFQAAgGgCgEIgGgIQgCgEgFgCQgEgBgFAAQgDAAgFABQgEACgDAEQgDADgCAFIgDAKIAvAAIAAAAg");
	this.shape_23.setTransform(-97.3,11.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#F78E1E").s().p("AgaAwIAAhdIAWAAIAAAWQACgGACgFQACgEAFgDQAEgDAFgCQAFgBAGAAIAAAXIgBAAQgHAAgGADQgGACgEAFQgDAEgCAIQgCAFAAAJIAAAkg");
	this.shape_24.setTransform(-106.1,11.6);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#F78E1E").s().p("AgOAPQAJgBADgEQADgEgBgGIgHAAIAAgYIAVAAIAAAVQAAAGgBAFQgCAFgDAEQgEADgEACQgEACgHABg");
	this.shape_25.setTransform(-112.8,6.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#F78E1E").s().p("AgPAuQgJgEgGgHQgHgGgEgJIgDgJIgBgLIAAAAQABgIADgKQADgIAHgHQAGgIAIgDIAJgDIAIgBIAKABIAKADQAFACAJAKQAGAGACAJQADAJAAAJIAAAGIhEAAQABAGADAEQACAFAEADIAHAFIAJABQAIAAAFgCQAHgEAFgFIANALIgIAIIgIAFIgKAEIgNABQgIAAgJgDgAAYgFQgBgGgBgEIgGgIQgCgEgFgCQgEgBgFAAQgDAAgFABQgEACgDAEQgDADgCAFIgDAKIAvAAIAAAAg");
	this.shape_26.setTransform(-120.4,11.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#F78E1E").s().p("AAfA/IgfhYIgdBYIgTAAIgsh9IAXAAIAfBcIAehcIARAAIAfBcIAehcIAYAAIgsB9g");
	this.shape_27.setTransform(-134.3,10.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-158,0,316,22);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgKAMIAAgXIAVAAIAAAXg");
	this.shape.setTransform(156.6,15.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgIAvIgnhdIAXAAIAYBEIAahEIAWAAIgmBdg");
	this.shape_1.setTransform(148.8,11.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgPAuQgJgEgGgHQgHgGgEgJIgDgJIgBgLIAAAAQAAgIAEgKQADgIAHgHQAGgIAIgDIAJgDIAIgBIALABIAJADQAGACAIAKQAFAGADAJQADAJABAJIgBAGIhEAAQABAGACAEQADAFAEADIAIAFIAIABQAHAAAGgCQAGgEAHgFIAMALIgIAIIgIAFIgLAEIgMABQgIAAgJgDgAAYgFQAAgGgCgEIgGgIQgDgEgDgCQgFgBgFAAQgDAAgFABQgEACgDAEQgDADgCAFIgDAKIAvAAIAAAAg");
	this.shape_2.setTransform(138.1,11.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgUA/QgIgDgGgHQgGgGgEgJIgDgKIgBgLQABgIADgLQAEgJAGgHQAGgGAIgEQAIgDAJAAQADAAAFACQAFABAEACQAHAEAGAIIAAgzIAWAAIAACBIgWAAIAAgQQgGAJgHAEQgFADgEABQgFABgDAAQgJAAgIgDgAgJgKQgFACgEAEQgDAEgCAEQgCAGgBAHQABAHACAFQACAGADAEQAEAEAFACQAFACAEAAQAFAAAFgCQAFgCAEgEQAEgEACgGQACgFAAgHQAAgHgCgGQgCgEgEgEQgEgEgFgCQgFgCgFAAQgEAAgFACg");
	this.shape_3.setTransform(126.4,9.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgEBBIgJgEQgHgEgGgIIAAAPIgWAAIAAiBIAWAAIAAA0QAGgIAHgFQAEgCAFgBQAEgCAEAAQAJAAAIADQAIAEAGAGQAGAHAEAJQAEALAAAIIgBALIgDAKQgDAJgHAGQgGAHgIADQgIADgJAAQgEAAgEgBgAgJgKQgFADgEAEQgEADgCAEQgCAGAAAHQAAAHACAFIAGAKIAJAGQAFACAEAAQAFAAAFgCQAFgCAEgEQADgEACgFQADgGAAgHQAAgHgDgGQgCgEgEgEQgDgEgFgCQgFgCgFAAQgEAAgFACg");
	this.shape_4.setTransform(109.4,9.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgPAuQgJgEgGgHQgHgGgEgJIgDgJIAAgLIAAAAQAAgIADgKQADgIAGgHQAHgIAIgDIAJgDIAIgBIAKABIAKADQAFACAJAKQAGAGADAJQACAJAAAJIAAAGIhEAAQABAGADAEQACAFADADIAIAFIAIABQAJAAAFgCQAGgEAGgFIANALIgHAIIgJAFIgKAEIgNABQgIAAgJgDgAAYgFQgBgGgBgEIgGgIQgCgEgFgCQgEgBgFAAQgDAAgFABQgDACgEAEQgDADgCAFIgDAKIAvAAIAAAAg");
	this.shape_5.setTransform(97.8,11.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAUAwIgUg/IgUA/IgUAAIgeheIAWAAIATA/IAVhAIARAAIAVBAIAUg/IAVAAIgfBeg");
	this.shape_6.setTransform(84.6,11.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgJAwIgKgDQgJgDgHgIQgHgGgEgJIgCgJIgBgKIAAAAQAAgFAEgNQADgIAHgHQAHgIAJgDIAKgDIAJgBQAHAAANAEQAJADAHAIQAHAGADAJQAEANAAAFIgBAKIgDAJQgEAJgGAGQgHAIgKADQgNAEgGAAgAgLgbQgFACgEAFQgDAEgCAFQgDAGAAAFQAAAGADAGQACAFAEAEQAEAFAFACQAFACAFABQAGgBAFgCQAGgCADgFQAEgEACgFQACgGAAgGIAAAAQAAgFgCgFQgCgGgEgEQgEgEgFgDQgGgCgFAAQgFAAgGACg");
	this.shape_7.setTransform(65.6,11.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAAA7QgFgBgDgDQgEgEgCgFQgCgFAAgIIAAgwIgMAAIAAgTIAMAAIAAgaIAUAAIAAAaIAZAAIAAATIgZAAIAAAtQAAAGADADQADACAFAAQAHAAAHgDIAAASIgJAEIgLABQgGAAgDgCg");
	this.shape_8.setTransform(55.9,10.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgRAtQgNgGgGgFIAJgOQAIAFAIADQAIADAGAAQAHAAADgDQAEgCAAgFQAAgFgGgEIgNgFQgOgEgGgDQgFgDgCgEQgDgFAAgHQAAgHADgFQACgFAFgEQAFgEAGgCQAGgCAFAAQAJAAAJADQAJADAIAFIgIAPIgOgGQgIgDgFAAQgFAAgDADQgEADAAAEIAAAAQAAAFAHADIANAGIAKADIAKAEQAEADADAEQACAFAAAGIAAABQAAAHgCAGQgDAFgFAEQgFAEgGACQgGACgIAAQgIAAgLgEg");
	this.shape_9.setTransform(42.3,11.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgaAwIAAhdIAWAAIAAAWQACgGACgFQACgEAFgDQAEgDAFgCQAFgBAGAAIAAAXIgBAAQgHAAgGADQgGACgEAFQgDAEgCAIQgCAFAAAJIAAAkg");
	this.shape_10.setTransform(34.6,11.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgPAuQgJgEgHgHQgGgGgEgJIgCgJIgBgLIAAAAQgBgIAEgKQAEgIAFgHQAHgIAIgDIAJgDIAIgBIAKABIAKADQAGACAIAKQAFAGAEAJQACAJAAAJIAAAGIhEAAQABAGADAEQACAFADADIAIAFIAIABQAIAAAHgCQAGgEAFgFIANALIgHAIIgJAFIgKAEIgNABQgIAAgJgDgAAYgFQgBgGgCgEIgEgIQgDgEgEgCQgFgBgFAAQgDAAgEABQgEACgEAEQgDADgCAFIgDAKIAvAAIAAAAg");
	this.shape_11.setTransform(25.1,11.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgJBBIAAhdIATAAIAABdgAgKgrIAAgVIAVAAIAAAVg");
	this.shape_12.setTransform(17.1,9.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgJBBIAAiBIATAAIAACBg");
	this.shape_13.setTransform(12,9.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgwA+IAAh5IAWAAIAAAPQAGgIAHgFQAEgCAFgBQAEgCAEAAQAJABAIADQAIADAGAHQAGAGAEAJQAEANAAAIIgBALIgDAIQgDAJgHAHQgGAGgIADQgIADgJAAQgEAAgEgBIgJgDQgHgEgGgIIAAArgAgJgoQgFACgEAEQgEAEgCAGQgCAFAAAHQAAAHACAFIAGAIIAJAGQAFACAEAAQAFAAAFgCQAFgBAEgFQADgEACgEQADgFAAgHQAAgHgDgFQgCgGgEgFQgDgEgFgBQgFgCgFAAQgEAAgFACg");
	this.shape_14.setTransform(3.7,13);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgwA+IAAh5IAWAAIAAAPQAGgIAHgFQAEgCAFgBQAEgCAEAAQAJABAIADQAIADAGAHQAGAGAEAJQAEANAAAIIgBALIgDAIQgDAJgHAHQgGAGgIADQgIADgJAAQgEAAgEgBIgJgDQgHgEgGgIIAAArgAgJgoQgFACgEAEQgEAEgCAGQgCAFAAAHQAAAHACAFIAGAIIAJAGQAFACAEAAQAFAAAFgCQAFgBAEgFQADgEACgEQADgFAAgHQAAgHgDgFQgCgGgEgFQgDgEgFgBQgFgCgFAAQgEAAgFACg");
	this.shape_15.setTransform(-8.4,13);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgWAuQgGgDgEgFQgFgFgCgGQgCgIAAgHIAAg7IAWAAIAAA0QAAAFABAFQABAEADADQADADADACQAEABAEAAQAEAAAEgBQAEgCACgDQADgDACgFQABgEAAgGIAAgzIAWAAIAABdIgWAAIAAgPQgFAIgGAEIgIAEQgDABgFAAQgIAAgHgCg");
	this.shape_16.setTransform(-20.3,11.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgRAtQgNgGgGgFIAJgOQAIAFAIADQAIADAGAAQAHAAADgDQAEgCAAgFQAAgFgGgEIgNgFQgOgEgGgDQgFgDgCgEQgDgFAAgHQAAgHADgFQACgFAFgEQAFgEAGgCQAGgCAFAAQAJAAAJADQAJADAIAFIgIAPIgOgGQgIgDgFAAQgFAAgDADQgEADAAAEIAAAAQAAAFAHADIANAGIAKADIAKAEQAEADADAEQACAFAAAGIAAABQAAAHgCAGQgDAFgFAEQgFAEgGACQgGACgIAAQgIAAgLgEg");
	this.shape_17.setTransform(-30.4,11.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAAA7QgFgBgDgDQgEgEgCgFQgCgFAAgIIAAgwIgMAAIAAgTIAMAAIAAgaIAUAAIAAAaIAZAAIAAATIgZAAIAAAtQAAAGADADQADACAFAAQAHAAAHgDIAAASIgJAEIgLABQgGAAgDgCg");
	this.shape_18.setTransform(-44,10.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgQBCIAAhLIgMAAIAAgSIAMAAIAAgHQAAgHACgGQACgGAEgEQADgEAFgCQAEgCAHAAQAKAAAIADIAAASQgHgCgGAAQgGAAgEADQgDAEAAAHIAAAFIAaAAIAAASIgZAAIAABLg");
	this.shape_19.setTransform(-50.7,9.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgVAvQgGgCgEgEQgFgEgDgFQgDgGAAgHQAAgIADgGQADgFAFgCQAFgEAIgCQAHgCAIAAQAJAAAPAEIAAgCQAAgFgBgEQgCgDgDgDQgDgDgEgBQgFgBgDAAQgIAAgGABIgNAFIgGgSIAQgGQAJgCAJAAQAKAAAIADQAIADAFAFQAFAFADAHQADAIAAAJIAAA3IgWAAIAAgMQgFAGgHAEQgJAEgIAAQgHAAgGgCgAgHAEIgHADQgDACgBADQgCACAAAEIAAAAQAAAHAFAEQAFADAIAAQAEAAAEgBQAFgCADgCQAEgDACgEQACgDAAgFIAAgFQgOgEgIAAIgHABg");
	this.shape_20.setTransform(-59.8,11.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgaAwIAAhdIAWAAIAAAWQACgGACgFQACgEAFgDQAEgDAFgCQAFgBAGAAIAAAXIgBAAQgHAAgGADQgGACgEAFQgDAEgCAIQgCAFAAAJIAAAkg");
	this.shape_21.setTransform(-68.1,11.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgEAwIgJgDQgJgDgHgIQgGgGgEgJQgEgJABgKIAAAAQgBgIAEgKQAEgIAGgHQAHgIAJgDIAJgDIAIgBIANABIAKADQAHAEAJAJIgOAOQgFgGgFgDQgHgDgIAAQgEAAgFACQgEADgEAEQgDAEgDAFQgCAGAAAFQAAAGACAGQADAFADAFQAEADAFADQAEACAFABQAIgBAHgDQAFgDAFgFIAOAMQgLAKgFADIgLAEIgNABg");
	this.shape_22.setTransform(-77.2,11.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgaAwIAAhdIAWAAIAAAWQACgGACgFQACgEAFgDQAEgDAFgCQAFgBAGAAIAAAXIgBAAQgHAAgGADQgGACgEAFQgDAEgCAIQgCAFAAAJIAAAkg");
	this.shape_23.setTransform(-85.8,11.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgJBBIAAhdIATAAIAABdgAgKgrIAAgVIAVAAIAAAVg");
	this.shape_24.setTransform(-92.4,9.9);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgVAvQgGgCgEgEQgFgEgDgFQgDgGAAgHQAAgIADgGQADgFAFgCQAFgEAIgCQAHgCAIAAQAJAAAPAEIAAgCQAAgFgBgEQgCgDgDgDQgDgDgEgBQgFgBgDAAQgIAAgGABIgNAFIgGgSIAQgGQAJgCAJAAQAKAAAIADQAIADAFAFQAFAFADAHQADAIAAAJIAAA3IgWAAIAAgMQgFAGgHAEQgJAEgIAAQgHAAgGgCgAgHAEIgHADQgDACgBADQgCACAAAEIAAAAQAAAHAFAEQAFADAIAAQAEAAAEgBQAFgCADgCQAEgDACgEQACgDAAgFIAAgFQgOgEgIAAIgHABg");
	this.shape_25.setTransform(-100.5,11.7);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AAyAwIAAg0QAAgGgBgEQgBgEgDgDIgGgFQgEgCgEAAQgFAAgDACQgEACgDADIgEAHQgBAFAAAGIAAAzIgUAAIAAg0QAAgGgCgEQgBgEgCgDQgDgDgDgCQgEgCgEAAQgFAAgEACQgDACgDADQgDADgBAFQgCAEAAAGIAAAzIgWAAIAAhdIAWAAIAAAPQAGgIAGgEQADgCAEgCQAFgBAFAAIAKABIAIADQACADACADQADADABAEQAHgIAHgFIAJgDIAKgBQAHAAAHACQAGADAEAFQAEAEADAHQACAGAAAJIAAA7g");
	this.shape_26.setTransform(-119.5,11.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgJAwIgKgDQgJgDgHgIQgHgGgEgJIgCgJIgBgKIAAAAQAAgFAEgNQADgIAHgHQAHgIAJgDIAKgDIAJgBQAHAAANAEQAJADAHAIQAHAGADAJQAEANAAAFIgBAKIgDAJQgEAJgGAGQgHAIgKADQgNAEgGAAgAgLgbQgFACgEAFQgDAEgCAFQgDAGAAAFQAAAGADAGQACAFAEAEQAEAFAFACQAFACAFABQAGgBAFgCQAGgCADgFQAEgEACgFQACgGAAgGIAAAAQAAgFgCgFQgCgGgEgEQgEgEgFgDQgGgCgFAAQgFAAgGACg");
	this.shape_27.setTransform(-133.9,11.7);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgaAwIAAhdIAWAAIAAAWQACgGACgFQACgEAFgDQAEgDAFgCQAFgBAGAAIAAAXIgBAAQgHAAgGADQgGACgEAFQgDAEgCAIQgCAFAAAJIAAAkg");
	this.shape_28.setTransform(-143.1,11.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgtA+IAAh8IBbAAIAAAUIhFAAIAAAjIA9AAIAAASIg9AAIAAAzg");
	this.shape_29.setTransform(-152.7,10.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-169.8,0,339.6,22);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#5169A8").s().p("A8lFJIAAqSMA5LAAAIAAKSg");
	this.shape.setTransform(238,33,1.3,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,476,66);


(lib.EqualHousingOpportunityrevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// EqualHousingOpportunity-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyZSUIAAw4IixAAIAAlsIU+uDIAZAAIU+ODIAAFwIivAAIAAQ0gAtyhwIAAOUIbpAAIAAuPIt3pUgAnQJ9IAAmDIOmAAIAAGDgAnSC9IAAl/IOmAAIAAF/g");
	this.shape.setTransform(135.6,117.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AEDBvQgWgLgIgWQgKgWAAgmIAAiHIAfAAIAACHQAAAgAHANQAFAPAOAJQAPAHAUAAQAiAAAPgPQAPgQAAgtIAAiHIAfAAIAACHQABAjgJAWQgIAUgVAOQgVAOgjAAQghAAgVgMgAmwBrQgbgSgNgbQgOgbAAghQABg4AfgiQAgghAzgBQAgAAAaAQQAbAQAOAcQAOAcAAAiQAAAkgOAcQgPAdgbAPQgaAOggABQghAAgbgQgAmthHQgYAXAAAzQAAAsAXAYQAXAZAjAAQAkAAAWgZQAYgZAAguQgBgbgJgWQgKgWgTgLQgSgMgYgBQgiAAgYAYgAxoBrQgbgRgNgcQgOgbAAghQAAg4AggiQAfghAzgBQAhAAAaAQQAbAQAOAcQANAcAAAiQABAlgPAbQgNAcgcAQQgaAOggABQgiAAgagQgAxmhHQgYAXAAAzQAAAqAYAaQAXAZAiAAQAlAAAWgZQAXgZAAguQAAgcgKgVQgJgVgUgMQgSgMgYgBQggAAgaAYgAQhB2IAAhkIhciHIAmAAIBHBvIBIhvIAlAAIhfCHIAABkgANPB2IAAjPIhOAAIAAgcIC9AAIAAAcIhPAAIAADPgAK7B2IAAjrIAfAAIAADrgAJkB2Ih9i5IAAC5IgeAAIAAjrIAhAAIB9C4IAAi4IAeAAIAADrgABMB2IAAjPIhMAAIAAgcIC6AAIAAAcIhPAAIAADPgAgwB2IgggxIgWghQgLgMgFgEQgGgDgJgDIgSgBIgkAAIAABpIgfAAIAAjrIBpAAQAfgBASAHQARAHAJAQQAKAQAAAUQAAAYgRATQgPAOgjAFQAMAGAHAGQAPAOALASIApBAgAi7gNIBEAAQAWABAMgFQAMgEAGgKQAHgJgBgMQAAgRgMgLQgLgLgbAAIhMAAgAq5B2IAAjrIBaAAQAWAAAOACQASADAMAIQALAIAHAPQAIAOAAASQgBAggSASQgUAVgyAAIg+AAIAABggAqagEIA+AAQAfAAANgMQAMgLAAgVQAAgPgIgKQgHgLgMgDQgHgCgWAAIg+AAgAuTB2IAAjrIBaAAQAXAAANACQASADAMAIQALAIAIAPQAHAPAAARQAAAfgUATQgTAVgyAAIg9AAIAABggAtzgEIA9AAQAeAAAOgMQANgLAAgVQgBgPgHgKQgJgLgLgDQgIgCgVAAIg9AAg");
	this.shape_1.setTransform(135.7,277.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AtCBXQgXANgcAAQgcAAgWgOQgXgNgMgZQgNgYAAgdQAAgeANgZQALgYAYgOQAXgNAcAAQAcAAAXAOQAWANANAZQAMAYAAAeQAAAYgIAUQgIAUgPAPQAQAMATAHIgIATQgWgHgWgSgAunhDQgUAWAAAoQAAAnAUAVQAUAVAfAAQAOABANgGQgMgIgPgEIAHgUQAYAIAPAMQAYgWAAgqQAAgZgJgSQgIgTgRgKQgPgKgVAAQgeAAgVAUgAP7BWQgZgNgMgYQgNgZAAgcQAAgdANgaQAMgaAYgNQAXgNAfAAQAYABARAGQARAIALAMQAKAMAFAWIgYAHQgEgPgIgKQgHgJgMgFQgOgFgPAAQgSgBgOAHQgNAFgJAJQgJALgEAJQgIAVAAAVQAAAZAKASQAJATASAJQATAJAUAAQASAAAQgHQARgGAJgIIAAgmIg9AAIAAgWIBXAAIAABJQgTARgWAIQgVAIgXAAQgfgBgYgNgAIXBcQgSgJgMgQQgKgQgBgVIAagCQACAQAGAKQAHAIAOAHQANAGASAAQARAAALgEQAMgFAGgIQAFgIAAgKQAAgJgFgIQgFgHgOgFQgKgEgagFQgbgFgNgGQgOgIgIgMQgHgKAAgPQAAgQAJgNQAJgOARgHQAPgGAWgBQAWABATAGQARAIAJAPQAKAOABARIgbACQgBgSgNgLQgLgKgZAAQgYAAgLAKQgMAIAAANQAAALAIAHQAIAIAhAHQAfAHAPAGQARAIAJALQAJANAAAQQAAARgKAOQgJAPgSAIQgQAIgXAAQgdAAgSgIgAFPBaQgTgLgHgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAFAMAMAHQAMAHASAAQAeAAAMgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgGATgTAMQgSAKgeABQgegBgRgJgAB1BVQgWgNgNgZQgLgYAAgZQAAgzAbgdQAcgdArAAQAdAAAWAOQAXANAMAZQAMAYAAAfQAAAbgMAaQgNAZgXANQgXANgbAAQgegBgWgOgAB4hEQgVAUAAAuQAAAlAUAUQAUAVAeAAQAeAAAUgVQAUgWAAgmQAAgYgIgTQgKgUgPgJQgRgKgUAAQgdAAgUATgArOBaQgSgLgIgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAGAMALAHQANAHARAAQAeAAANgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgHATgTAMQgRAKgfABQgdgBgSgJgAOGBgIhsifIAACfIgaAAIAAjLIAcAAIBsCfIAAifIAaAAIAADLgAK3BgIAAjLIAcAAIAADLgAALBgIAAhgIhpAAIAABgIgbAAIAAjLIAbAAIAABUIBpAAIAAhUIAbAAIAADLgAliBgIAAjLIAcAAIAACzIBlAAIAAAYgAmXBgIgYg+IhWAAIgWA+IgdAAIBPjLIAdAAIBUDLgAm3AMIgVg3IgPgrQgEAWgHARIgXA7IBGAAgAyGBgIAAjLICUAAIAAAYIh5AAIAAA/IByAAIAAAWIhyAAIAABGIB+AAIAAAYg");
	this.shape_2.setTransform(135.2,250.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,271.2,289.4);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.Close = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F78E1E").s().p("AgLAMIAAgXIAXAAIAAAXg");
	this.shape.setTransform(111.5,33.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F78E1E").s().p("AgaAwIAAhdIAWAAIAAAWQACgGACgFQACgEAFgDQAEgDAFgCQAFgBAGAAIAAAXIgBAAQgHAAgGADQgGACgEAFQgDAEgCAIQgCAFAAAJIAAAkg");
	this.shape_1.setTransform(105.8,29.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F78E1E").s().p("AgPAuQgJgEgGgHQgHgGgEgJIgDgJIgBgLIAAAAQAAgIAEgKQADgIAHgHQAGgIAIgDIAJgDIAIgBIALABIAJADQAGACAIAKQAFAGADAJQADAJABAJIgBAGIhEAAQABAGACAEQADAFAEADIAIAFIAIABQAHAAAGgCQAGgEAHgFIAMALIgIAIIgIAFIgLAEIgMABQgIAAgJgDgAAYgFQAAgGgCgEIgGgIQgCgEgEgCQgFgBgFAAQgDAAgFABQgEACgDAEQgDADgCAFIgDAKIAvAAIAAAAg");
	this.shape_2.setTransform(96.3,29.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F78E1E").s().p("AAAA7QgFgBgDgDQgEgEgCgFQgCgFAAgIIAAgwIgMAAIAAgTIAMAAIAAgaIAUAAIAAAaIAZAAIAAATIgZAAIAAAtQAAAGADADQADACAFAAQAHAAAHgDIAAASIgJAEIgLABQgGAAgDgCg");
	this.shape_3.setTransform(87,28.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F78E1E").s().p("AgRAtQgNgGgGgFIAJgOQAIAFAIADQAIADAGAAQAHAAADgDQAEgCAAgFQAAgFgGgEIgNgFQgOgEgGgDQgFgDgCgEQgDgFAAgHQAAgHADgFQACgFAFgEQAFgEAGgCQAGgCAFAAQAJAAAJADQAJADAIAFIgIAPIgOgGQgIgDgFAAQgFAAgDADQgEADAAAEIAAAAQAAAFAHADIANAGIAKADIAKAEQAEADADAEQACAFAAAGIAAABQAAAHgCAGQgDAFgFAEQgFAEgGACQgGACgIAAQgIAAgLgEg");
	this.shape_4.setTransform(78.8,29.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F78E1E").s().p("AgVAvQgGgCgEgEQgFgEgDgFQgDgGAAgHQAAgIADgGQADgFAFgCQAFgEAIgCQAHgCAIAAQAJAAAPAEIAAgCQAAgFgBgEQgCgDgDgDQgDgDgEgBQgFgBgDAAQgIAAgGABIgNAFIgGgSIAQgGQAJgCAJAAQAKAAAIADQAIADAFAFQAFAFADAHQADAIAAAJIAAA3IgWAAIAAgMQgFAGgHAEQgJAEgIAAQgHAAgGgCgAgHAEIgHADQgDACgBADQgCACAAAEIAAAAQAAAHAFAEQAFADAIAAQAEAAAEgBQAFgCADgCQAEgDACgEQACgDAAgFIAAgFQgOgEgIAAIgHABg");
	this.shape_5.setTransform(68.9,29.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F78E1E").s().p("AgQBCIAAhLIgMAAIAAgSIAMAAIAAgHQAAgHACgGQACgGAEgEQAEgEAEgCQAEgCAHAAQAJAAAJADIAAASQgHgCgGAAQgGAAgDADQgDAEgBAHIAAAFIAZAAIAAASIgYAAIAABLg");
	this.shape_6.setTransform(60.8,27.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F78E1E").s().p("AgJA/QgHgBgHgDQgGgCgGgEIgMgJIANgQQAGAFAMAIIAKACIAKABIAJgBIAHgCIAFgGQABgDAAgDIAAgBIgBgFQgBgDgEgDQgDgCgFgBIgMgFIgSgFQgIgEgGgBQgFgEgDgGQgDgHAAgJQABgHADgIQADgGAGgFQAFgFAIgDQAJgDAIABIAMABQAGABAGACQAIACAMAKIgLARQgJgHgIgDQgJgEgHAAIgIABQgEACgDACQgFAEAAAGIAAABIABAGQACADADACIAJAEIANAEIASAGQAHADAFADQAFAEACAGQADAGAAAHQAAAJgDAHQgDAIgGAEQgGAFgJACQgIADgKAAQgFAAgHgBg");
	this.shape_7.setTransform(45.9,28.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F78E1E").s().p("AguA+IAAh8IBcAAIAAAUIhFAAIAAAhIA9AAIAAASIg9AAIAAAhIBGAAIAAAUg");
	this.shape_8.setTransform(34.5,28.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#F78E1E").s().p("AgKA+IAAgxIgyhLIAaAAIAiA4IAjg4IAZAAIgyBLIAAAxg");
	this.shape_9.setTransform(21.8,28.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#F78E1E").s().p("AgJAwIgKgDQgJgDgHgIQgHgGgEgJIgCgJIgBgKIAAAAQAAgFAEgNQADgIAHgHQAHgIAJgDIAKgDIAJgBQAHAAANAEQAJADAHAIQAHAGADAJQAEANAAAFIgBAKIgDAJQgEAJgGAGQgHAIgKADQgNAEgGAAgAgLgbQgFACgEAFQgDAEgCAFQgDAGAAAFQAAAGADAGQACAFAEAEQAEAFAFACQAFACAFABQAGgBAFgCQAGgCADgFQAEgEACgFQACgGAAgGIAAAAQAAgFgCgFQgCgGgEgEQgEgEgFgDQgGgCgFAAQgFAAgGACg");
	this.shape_10.setTransform(4.1,29.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#F78E1E").s().p("AAAA7QgFgBgDgDQgEgEgCgFQgCgFAAgIIAAgwIgMAAIAAgTIAMAAIAAgaIAUAAIAAAaIAZAAIAAATIgZAAIAAAtQAAAGADADQADACAFAAQAHAAAHgDIAAASIgJAEIgLABQgGAAgDgCg");
	this.shape_11.setTransform(-5.6,28.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#F78E1E").s().p("AAAA7QgFgBgDgDQgEgEgCgFQgCgFAAgIIAAgwIgMAAIAAgTIAMAAIAAgaIAUAAIAAAaIAZAAIAAATIgZAAIAAAtQAAAGADADQADACAFAAQAHAAAHgDIAAASIgJAEIgLABQgGAAgDgCg");
	this.shape_12.setTransform(-18.4,28.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#F78E1E").s().p("AgPAuQgJgEgGgHQgHgGgEgJIgDgJIgBgLIAAAAQABgIADgKQADgIAGgHQAHgIAIgDIAJgDIAIgBIAKABIAKADQAFACAJAKQAGAGADAJQACAJAAAJIAAAGIhEAAQABAGADAEQACAFADADIAIAFIAIABQAJAAAFgCQAGgEAGgFIANALIgHAIIgJAFIgKAEIgNABQgIAAgJgDgAAYgFQgBgGgBgEIgGgIQgCgEgFgCQgEgBgFAAQgDAAgFABQgDACgEAEQgDADgCAFIgDAKIAvAAIAAAAg");
	this.shape_13.setTransform(-27.3,29.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#F78E1E").s().p("AgXA8QgLgDgJgGIAIgQQAIAFAIACQAJADAJAAQAFAAAGgCQAFgBAEgEQAEgEACgFQACgGAAgHIAAgIQgIAKgGADQgEADgEAAIgKACQgIAAgHgDQgIgDgHgGQgFgFgEgJQgEgHABgKIAAAAQgBgHAEgMQAEgIAFgGQAHgFAIgDQAHgDAIgBQAFAAAFACIAJADQAGAEAHAHIAAgNIAWAAIAABJQgBAMgDAJQgCAJgHAGIgHAGIgJADQgOADgGAAQgMAAgLgCgAgJgpQgFACgEADQgEADgCAFQgCAFAAAGIAAAAQAAAGACAFQACAFAEACQAEADAFABQAFACAEAAQAFAAAFgCQAFgBAEgDQAEgDACgEQACgFAAgGIAAAAQAAgGgCgFQgCgEgEgEQgEgDgFgCQgFgCgFAAQgFAAgEACg");
	this.shape_14.setTransform(-39,31);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#F78E1E").s().p("AAVAwIAAg0QAAgGgCgEIgEgHQgCgDgEgCQgEgCgFAAQgDAAgDACQgEACgDADQgDADgCAFQgBAEAAAGIAAAzIgWAAIAAhdIAWAAIAAAPQAFgIAGgEIAIgEIAIgBQAIAAAHACQAGADAEAFQAFAFACAGQACAHAAAJIAAA6g");
	this.shape_15.setTransform(-55.8,29.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#F78E1E").s().p("AgVAvQgGgCgEgEQgFgEgDgFQgDgGAAgHQAAgIADgGQADgFAFgCQAFgEAIgCQAHgCAIAAQAJAAAPAEIAAgCQAAgFgBgEQgCgDgDgDQgDgDgEgBQgFgBgDAAQgIAAgGABIgNAFIgGgSIAQgGQAJgCAJAAQAKAAAIADQAIADAFAFQAFAFADAHQADAIAAAJIAAA3IgWAAIAAgMQgFAGgHAEQgJAEgIAAQgHAAgGgCgAgHAEIgHADQgDACgBADQgCACAAAEIAAAAQAAAHAFAEQAFADAIAAQAEAAAEgBQAFgCADgCQAEgDACgEQACgDAAgFIAAgFQgOgEgIAAIgHABg");
	this.shape_16.setTransform(-66.9,29.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#F78E1E").s().p("AgEAwIgJgDQgJgDgGgIQgHgGgEgJQgDgJgBgKIAAAAQABgIADgKQAEgIAHgHQAGgIAJgDIAJgDIAJgBIAMABIAKADQAHAEAJAJIgOAOQgGgGgFgDQgFgDgIAAQgFAAgFACQgFADgDAEQgDAEgCAFQgDAGAAAFQAAAGADAGQACAFADAFQAEADAFADQAEACAGABQAHgBAGgDQAGgDAFgFIAOAMQgKAKgHADIgKAEIgMABg");
	this.shape_17.setTransform(-76.9,29.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#F78E1E").s().p("AgPAuQgJgEgHgHQgGgGgEgJIgCgJIgBgLIAAAAQAAgIADgKQAEgIAFgHQAHgIAIgDIAJgDIAIgBIALABIAJADQAFACAJAKQAFAGADAJQAEAJAAAJIgBAGIhEAAQABAGACAEQADAFADADIAJAFIAHABQAJAAAGgCQAFgEAHgFIAMALIgIAIIgIAFIgLAEIgMABQgIAAgJgDgAAYgFQgBgGgCgEIgEgIQgEgEgDgCQgFgBgFAAQgDAAgEABQgEACgEAEQgDADgCAFIgDAKIAvAAIAAAAg");
	this.shape_18.setTransform(-93,29.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#F78E1E").s().p("AAVAwIgVg/IgUA/IgUAAIgeheIAWAAIATA/IAVhAIARAAIAVBAIATg/IAWAAIgfBeg");
	this.shape_19.setTransform(-106.1,29.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#F78E1E").s().p("AgOAQQAJgCAEgEQACgEgBgGIgIAAIAAgYIAXAAIAAAVQgBAFgBAGQgCAFgEAEQgDADgEACQgEACgHABg");
	this.shape_20.setTransform(121.2,16.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#F78E1E").s().p("AgaAwIAAhdIAWAAIAAAWQACgGACgFQACgEAFgDQAEgDAFgCQAFgBAGAAIAAAXIgBAAQgHAAgGADQgGACgEAFQgDAEgCAIQgCAFAAAJIAAAkg");
	this.shape_21.setTransform(115.8,11.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#F78E1E").s().p("AgPAuQgJgEgHgHQgGgGgEgJIgCgJIgCgLIAAAAQAAgIAEgKQAEgIAGgHQAGgIAIgDIAJgDIAIgBIALABIAJADQAGACAIAKQAFAGADAJQAEAJAAAJIgBAGIhEAAQABAGACAEQADAFAEADIAIAFIAIABQAHAAAGgCQAGgEAHgFIAMALIgIAIIgIAFIgLAEIgMABQgIAAgJgDgAAYgFQAAgGgDgEIgFgIQgDgEgDgCQgFgBgFAAQgDAAgEABQgFACgDAEQgDADgCAFIgDAKIAvAAIAAAAg");
	this.shape_22.setTransform(106.3,11.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#F78E1E").s().p("AgUA/QgIgDgGgHQgGgGgEgJIgDgKIgBgLQABgIADgLQAEgJAGgHQAGgGAIgEQAIgDAIAAQAEAAAFACQAFABAEACQAHAEAGAIIAAgzIAVAAIAACBIgVAAIAAgQQgGAJgHAEQgFADgEABQgFABgEAAQgIAAgIgDgAgJgKQgFACgEAEQgEAEgBAEQgCAGAAAHQAAAHACAFQABAGAEAEQAEAEAFACQAFACAEAAQAFAAAFgCQAFgCAEgEQAEgEACgGQACgFAAgHQAAgHgCgGQgCgEgEgEQgEgEgFgCQgFgCgFAAQgEAAgFACg");
	this.shape_23.setTransform(94.6,9.9);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#F78E1E").s().p("AAVAwIAAg0QAAgGgCgEIgEgHQgCgDgEgCQgEgCgFAAQgDAAgDACQgEACgDADQgDADgCAFQgBAEAAAGIAAAzIgWAAIAAhdIAWAAIAAAPQAFgIAGgEIAIgEIAIgBQAIAAAHACQAGADAEAFQAFAFACAGQACAHAAAIIAAA7g");
	this.shape_24.setTransform(83.2,11.6);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#F78E1E").s().p("AgPAuQgJgEgGgHQgHgGgEgJIgDgJIgBgLIAAAAQABgIADgKQADgIAHgHQAGgIAIgDIAJgDIAIgBIAKABIAKADQAFACAJAKQAGAGADAJQACAJAAAJIAAAGIhEAAQABAGADAEQACAFAEADIAHAFIAJABQAIAAAFgCQAHgEAFgFIANALIgIAIIgIAFIgKAEIgNABQgIAAgJgDgAAYgFQgBgGgBgEIgGgIQgCgEgFgCQgEgBgFAAQgDAAgFABQgEACgDAEQgDADgCAFIgDAKIAvAAIAAAAg");
	this.shape_25.setTransform(72.2,11.7);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#F78E1E").s().p("AgrA+IAAh8IAXAAIAABoIBAAAIAAAUg");
	this.shape_26.setTransform(61.7,10.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#F78E1E").s().p("AAqA/IgNgfIg6AAIgNAfIgWAAIA3h9IATAAIA3B9gAAVANIgVgwIgVAwIAqAAg");
	this.shape_27.setTransform(43.2,10.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#F78E1E").s().p("AgzA+IAAh8IA2AAQALAAAJAEQAIADAGAEQAEAFACAFQACAFAAAHIAAAAQAAAGgBAEQgCAEgDAEQgEAGgIAEIAKACQAFADADADQAEAEABAFQACAFAAAGIAAABQAAAIgDAHQgDAGgHAEQgGAFgIACQgJACgLAAgAgdArIAiAAIALgBIAHgDQAEgDABgDQACgDAAgFIAAAAQAAgEgCgDQgBgDgEgCQgDgDgEgBIgMgBIghAAgAgdgJIAdAAIAJAAIAIgDIAEgGQACgDAAgFIAAAAQAAgEgCgDQgBgDgDgBIgHgEIgJgBIgeAAg");
	this.shape_28.setTransform(30,10.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#F78E1E").s().p("AgJA/QgHgBgHgDQgGgCgGgEIgNgJIAOgQQAGAFANAIIAKACIAJABIAJgBIAHgCIAEgGQACgDAAgDIAAgBIgBgFQgCgDgCgDQgDgCgGgBIgMgFIgSgFQgJgEgFgBQgFgEgDgGQgCgHAAgJQgBgHAEgIQADgGAGgFQAFgFAJgDQAHgDAJAAIAMACQAGABAGACQAHACAOAKIgNARQgIgHgJgDQgIgEgHAAIgIABQgEACgCACQgGAEAAAGIAAABIABAGQABADAEACIAJAEIANAEIASAGQAHADAFADQAFAEADAGQACAGAAAHQAAAJgDAHQgDAIgGAEQgHAFgIACQgIADgKAAQgFAAgHgBg");
	this.shape_29.setTransform(17.3,10.1);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#F78E1E").s().p("AgUA/QgIgDgGgHQgGgGgEgJIgDgKIgBgLQABgIADgLQAEgJAGgHQAGgGAIgEQAIgDAJAAQADAAAFACQAFABAEACQAHAEAGAIIAAgzIAWAAIAACBIgWAAIAAgQQgGAJgHAEQgFADgEABQgFABgDAAQgJAAgIgDgAgJgKQgFACgEAEQgDAEgCAEQgCAGgBAHQABAHACAFQACAGADAEQAEAEAFACQAFACAEAAQAFAAAFgCQAFgCAEgEQAEgEACgGQACgFAAgHQAAgHgCgGQgCgEgEgEQgEgEgFgCQgFgCgFAAQgEAAgFACg");
	this.shape_30.setTransform(0,9.9);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#F78E1E").s().p("AgPAuQgJgEgHgHQgGgGgEgJIgDgJIAAgLIAAAAQAAgIADgKQAEgIAFgHQAHgIAIgDIAJgDIAIgBIAKABIAKADQAGACAIAKQAGAGADAJQACAJAAAJIAAAGIhEAAQABAGADAEQACAFADADIAIAFIAIABQAIAAAHgCQAFgEAGgFIANALIgHAIIgJAFIgKAEIgNABQgIAAgJgDgAAYgFQAAgGgDgEIgEgIQgEgEgEgCQgEgBgFAAQgDAAgFABQgDACgEAEQgDADgCAFIgDAKIAvAAIAAAAg");
	this.shape_31.setTransform(-11.2,11.7);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#F78E1E").s().p("AgaAwIAAhdIAWAAIAAAWQACgGACgFQACgEAFgDQAEgDAFgCQAFgBAGAAIAAAXIgBAAQgHAAgGADQgGACgEAFQgDAEgCAIQgCAFAAAJIAAAkg");
	this.shape_32.setTransform(-20,11.6);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#F78E1E").s().p("AgaAwIAAhdIAWAAIAAAWQACgGACgFQACgEAFgDQAEgDAFgCQAFgBAGAAIAAAXIgBAAQgHAAgGADQgGACgEAFQgDAEgCAIQgCAFAAAJIAAAkg");
	this.shape_33.setTransform(-27.4,11.6);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#F78E1E").s().p("AgPAuQgJgEgHgHQgGgGgEgJIgDgJIAAgLIAAAAQAAgIADgKQAEgIAFgHQAHgIAIgDIAJgDIAIgBIAKABIAKADQAGACAIAKQAGAGADAJQACAJAAAJIAAAGIhEAAQABAGADAEQACAFADADIAIAFIAIABQAIAAAHgCQAFgEAGgFIANALIgHAIIgJAFIgKAEIgNABQgIAAgJgDgAAYgFQAAgGgDgEIgEgIQgEgEgEgCQgEgBgFAAQgDAAgFABQgDACgEAEQgDADgCAFIgDAKIAvAAIAAAAg");
	this.shape_34.setTransform(-36.9,11.7);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#F78E1E").s().p("AgQBCIAAhLIgMAAIAAgSIAMAAIAAgHQAAgHACgGQACgGAEgEQADgEAFgCQAEgCAHAAQAKAAAIADIAAASQgHgCgGAAQgGAAgEADQgCAEAAAHIAAAFIAZAAIAAASIgZAAIAABLg");
	this.shape_35.setTransform(-45.5,9.8);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#F78E1E").s().p("AgPAuQgJgEgGgHQgHgGgEgJIgDgJIgBgLIAAAAQAAgIAEgKQADgIAHgHQAGgIAIgDIAJgDIAIgBIALABIAJADQAGACAIAKQAFAGADAJQADAJABAJIgBAGIhEAAQABAGACAEQADAFAEADIAIAFIAIABQAHAAAGgCQAGgEAHgFIAMALIgIAIIgIAFIgLAEIgMABQgIAAgJgDgAAYgFQAAgGgCgEIgGgIQgDgEgDgCQgFgBgFAAQgDAAgFABQgEACgDAEQgDADgCAFIgDAKIAvAAIAAAAg");
	this.shape_36.setTransform(-54.5,11.7);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#F78E1E").s().p("AgaAwIAAhdIAWAAIAAAWQACgGACgFQACgEAFgDQAEgDAFgCQAFgBAGAAIAAAXIgBAAQgHAAgGADQgGACgEAFQgDAEgCAIQgCAFAAAJIAAAkg");
	this.shape_37.setTransform(-63.2,11.6);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#F78E1E").s().p("AgvA+IAAh8IAwAAQAKAAAKAEQAIADAHAFQAGAFADAIQADAIAAAKIAAAAIAAAKIgDAIQgEAHgHAFQgHAFgJADQgJADgJAAIgZAAIAAAogAgZACIAZAAQAFAAAFgCQAFAAAEgCQADgDACgEQACgFAAgFIAAAAQAAgGgCgDQgCgEgDgEQgEgDgFgBQgFgCgFAAIgZAAg");
	this.shape_38.setTransform(-72.9,10.1);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#F78E1E").s().p("AgVAvQgGgCgEgEQgFgEgDgFQgDgGAAgHQAAgIADgGQADgFAFgCQAFgEAIgCQAHgCAIAAQAJAAAPAEIAAgCQAAgFgBgEQgCgDgDgDQgDgDgEgBQgFgBgDAAQgIAAgGABIgNAFIgGgSIAQgGQAJgCAJAAQAKAAAIADQAIADAFAFQAFAFADAHQADAIAAAJIAAA3IgWAAIAAgMQgFAGgHAEQgJAEgIAAQgHAAgGgCgAgHAEIgHADQgDACgBADQgCACAAAEIAAAAQAAAHAFAEQAFADAIAAQAEAAAEgBQAFgCADgCQAEgDACgEQACgDAAgFIAAgFQgOgEgIAAIgHABg");
	this.shape_39.setTransform(-90.3,11.7);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#F78E1E").s().p("AgRAtQgNgGgGgFIAJgOQAIAFAIADQAIADAGAAQAHAAADgDQAEgCAAgFQAAgFgGgEIgNgFQgOgEgGgDQgFgDgCgEQgDgFAAgHQAAgHADgFQACgFAFgEQAFgEAGgCQAGgCAFAAQAJAAAJADQAJADAIAFIgIAPIgOgGQgIgDgFAAQgFAAgDADQgEADAAAEIAAAAQAAAFAHADIANAGIAKADIAKAEQAEADADAEQACAFAAAGIAAABQAAAHgCAGQgDAFgFAEQgFAEgGACQgGACgIAAQgIAAgLgEg");
	this.shape_40.setTransform(-105.3,11.7);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#F78E1E").s().p("AAqA/IgNgfIg6AAIgNAfIgWAAIA3h9IATAAIA3B9gAAVANIgVgwIgVAwIAqAAg");
	this.shape_41.setTransform(-116.8,10.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-255.2,0,510.5,40);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border468x60 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("EgkZgEhMBIzAAAIAAJDMhIzAAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-234,-30,468,60);


(lib._2016TAG = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIQATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAIYgKQgEAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgFAFgADbATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgADjgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgGAAgFAFgAgpATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAGAIAAAKQAAALgGAIQgIAIgMAAQgMAAgIgIgAgggKQgFAEAAAGQAAAGAFAFQAFAFAGAAQAHAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgHAAgEAFgAtIATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAs/gKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgEAFgAL+AaIgMggIgLAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIALAiIALgiIAMAAIgSAzgAJJADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAAOADIAAgcIAMAAIAAAcQAAANALAAQAMAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgXAAAAgXgAk7ASIAHgIQAIAGAIAAQAHAAAAgFQAAgEgKgCQgJgDgEgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAJAAQAMAAAHAGIgGAJQgIgFgGAAQgGAAAAAEQAAAFALACQARAEAAAKQAAAQgUAAQgNAAgJgIgAsPADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAN5AaIAAgMIAMAAIAAAMgANdAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgANDAaIgFgMIgWAAIgFAMIgMAAIAXgzIAKAAIAXAzgAM6AEIgHgPIgHAPIAOAAgAKiAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgAKOAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAHoAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVgAGsAaIAAgMIAMAAIAAAMgAGQAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAFQAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAE5AaIgZggIAAAgIgLAAIAAgzIAKAAIAZAfIAAgfIALAAIAAAzgAC9AaIAAggIgPAUIgOgUIAAAgIgMAAIAAgzIANAAIANAWIAOgWIANAAIAAAzgABoAaIgMgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgABTAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAhRAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAiNAaIAAgMIAMAAIAAAMgAi2AaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAFQgGAFgJAAIgJAAIAAAQgAiqAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAjOAaIAAgzIALAAIAAAzgAjnAaIAAgVIgVAAIAAAVIgLAAIAAgzIALAAIAAAVIAVAAIAAgVIAMAAIAAAzgAlOAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAliAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAmfAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAnVAaIAAgzIAYAAQAJAAAFAFQADADAAAGIAAAAQAAAIgHADQAKACAAAJQAAAPgTAAgAnKAQIAOAAQAIAAAAgGQAAgGgJAAIgNAAgAnKgEIALAAQAIAAAAgFQAAgGgIAAIgLAAgAntAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgApIAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgApgAaIAAggIgPAUIAAAAIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgAq2AaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgArKAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAtwAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(0,2.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-90.1,0,180.4,5.5);


(lib._2016_SCU_logoruleai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F78E1E").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,0,162.9,1);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib._2016_SCU_BBShorizai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("ArbAhIAAhBIW3AAIAABBg");
	mask.setTransform(73.2,3.4);

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AKoAXIAJgKQAJAHAKAAQAJAAAAgGQAAgDgCgBQgDgCgIgCQgLgDgEgDQgHgDAAgJQABgJAGgFQAGgGAKAAQAOAAAKAIIgHALQgKgGgHAAQgIAAAAAFIAAABQgBAEAOAEQALADAFACQAGAFAAAIQAAAJgHAGQgHAFgKAAQgQAAgMgKgAIwAYQgKgKABgOQgBgMAKgKQAKgKAOAAQAPAAALAKIgJALQgIgIgJAAQgHAAgGAGQgFAGgBAHIAAAAQAAAIAGAGQAFAGAIAAQAKAAAHgIIAJAKQgKALgQAAQgOAAgKgJgAEEAXIAJgKQAKAHAJAAQAKAAAAgGQAAgFgNgDQgMgDgEgDQgGgDAAgJQAAgJAGgFQAHgGAKAAQAOAAAKAIIgHALQgKgGgHAAQgJAAAAAFIAAABQABADACABQADACAJACQAUAFAAANQAAAJgHAGQgGAFgLAAQgPAAgNgKgACrAYQgKgKAAgOQAAgMAKgKQAKgKAOAAQAQAAAKAJIgJALQgIgHgJAAQgIAAgFAGQgFAGAAAHIAAAAQAAAJAFAGQAGAFAIAAQAIAAAGgEIAAgJIgPAAIAAgKIAcAAIAAAaQgMAKgQAAQgOAAgKgJgAk5AXIAJgKQAKAHAKAAQAJAAAAgGQAAgDgDgBIgKgEQgMgDgEgDQgGgDAAgJQAAgJAGgFQAHgGAKAAQAOAAAKAIIgIALQgJgGgHAAQgJAAAAAFIAAABQAAADADABQADACAJACQAKADAFACQAFAFAAAIQAAAJgHAGQgGAFgLAAQgQAAgMgKgAlzAXIAJgKQAKAHAJAAQAJAAAAgGQABgDgDgBIgLgEQgLgDgEgDQgHgDAAgJQABgJAGgFQAHgGAKAAQANAAAKAIIgHALQgJgGgIAAQgIAAAAAFIAAABQAAADACABQADACAJACQAUAFABANQAAAJgHAGQgHAFgKAAQgQAAgMgKgApVAXIAIgKQAKAHAKAAQAJAAAAgGQgBgDgCgBQgCgCgJgCQgKgDgFgDQgGgDAAgJQAAgJAHgFQAGgGAKAAQANAAALAIIgIALQgIgGgIAAQgIAAAAAFIAAABQAAADACABQADACAIACQAVAFAAANQAAAJgGAGQgIAFgKAAQgPAAgMgKgAqZAEIAAgjIAPAAIAAAjQAAAQAOAAQAOAAAAgQIAAgjIAPAAIAAAjQAAAdgdAAQgdAAAAgdgAHZAhIgahAIAQAAIARAsIARgsIAPAAIgbBAgAJuAgIAAg/IAxAAIAAANIgjAAIAAANIAfAAIAAALIgfAAIAAANIAjAAIAAANgAIKAgIAAg/IAPAAIAAA/gAGrAgIgPgVIgLAAIAAAVIgOAAIAAg/IAeAAQAMAAAHAHQAFAFAAAKQAAANgNAFIAPAXgAGRAAIAPAAQAKAAABgJQgBgJgKAAIgPAAgAFEAgIAAg/IAyAAIAAANIgjAAIAAANIAeAAIAAALIgeAAIAAANIAjAAIAAANgACJAgIgggnIAAAnIgOAAIAAg/IANAAIAeAmIAAgmIAPAAIAAA/gAA8AgIAAg/IAPAAIAAA/gAAhAgIgTgcIgIAIIAAAUIgNAAIAAg/IANAAIAAAdIAagdIASAAIgbAcIAcAjgAgiAgIgfgnIAAAnIgPAAIAAg/IAOAAIAeAmIAAgmIAOAAIAAA/gAhpAgIgGgOIgbAAIgHAOIgOAAIAcg/IANAAIAcA/gAh0AFIgJgTIgIATIARAAgAjcAgIAAg/IAdAAQAMAAAGAGQAEAFAAAGIAAAAQAAAKgJAEQANADAAALQAAASgZAAgAjPAUIARAAQALAAgBgHIAAgBQAAgHgKAAIgRAAgAjPgFIAOAAQAKAAAAgGIAAgBQAAgGgJAAIgPAAgAmtAgIAAg/IAxAAIAAANIgjAAIAAANIAfAAIAAALIgfAAIAAANIAjAAIAAANgAnJAgIgfgnIAAAnIgPAAIAAg/IAOAAIAeAmIAAgmIAPAAIAAA/gAoVAgIAAg/IAPAAIAAA/gArbAgIAAg/IAeAAQAMAAAFAGQAFAEAAAHIAAAAQAAAKgIAEQAMADAAALQAAASgZAAgArMAUIAQAAQALAAAAgHIAAgBQAAgHgLAAIgQAAgArMgFIANAAQAKAAAAgGIAAgBQAAgGgKAAIgNAAg");
	this.shape.setTransform(73.2,3.4);

	this.shape.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,146.4,6.8);


// stage content:
(lib.SCU201609_Air_468x60_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_179 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(179).call(this.frame_179).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.setTransform(449,39,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.setTransform(0,0,1.393,0.214);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},180).wait(1));

	// com
	this.instance = new lib.comhoriz();
	this.instance.setTransform(385,53.9,0.687,0.687,0,0,0,0,4.5);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

	// ncua
	this.instance_1 = new lib.ncuahorizai();
	this.instance_1.setTransform(228,51.2,1.11,1.11,0,0,0,0,3.6);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_2 = new lib.border468x60();
	this.instance_2.setTransform(234,30);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({_off:true},180).wait(1));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("AokEsIAApXIRJAAIAAJXg");
	var mask_graphics_40 = new cjs.Graphics().p("AokEsIAApXIRJAAIAAJXg");
	var mask_graphics_41 = new cjs.Graphics().p("AoFEsIAApVIQMAAIAAJVg");
	var mask_graphics_42 = new cjs.Graphics().p("AnmEsIAApUIPOAAIAAJUg");
	var mask_graphics_43 = new cjs.Graphics().p("AnHEsIAApTIORAAIAAJTg");
	var mask_graphics_44 = new cjs.Graphics().p("AmnEsIAApRINSAAIAAJRg");
	var mask_graphics_45 = new cjs.Graphics().p("AmIEsIAApQIMVAAIAAJQg");
	var mask_graphics_46 = new cjs.Graphics().p("AlpEsIAApPILXAAIAAJPg");
	var mask_graphics_47 = new cjs.Graphics().p("AlKEtIAApOIKaAAIAAJOg");
	var mask_graphics_48 = new cjs.Graphics().p("AkrEtIAApNIJcAAIAAJNg");
	var mask_graphics_49 = new cjs.Graphics().p("AkNEsIAApMIIfAAIAAJMg");
	var mask_graphics_80 = new cjs.Graphics().p("AkNEsIAApMIIfAAIAAJMg");
	var mask_graphics_81 = new cjs.Graphics().p("AkPEsIAApMIIfAAIAAJMg");
	var mask_graphics_82 = new cjs.Graphics().p("AkPEsIAApMIIfAAIAAJMg");
	var mask_graphics_83 = new cjs.Graphics().p("AkPEsIAApMIIfAAIAAJMg");
	var mask_graphics_84 = new cjs.Graphics().p("AkPEsIAApMIIfAAIAAJMg");
	var mask_graphics_85 = new cjs.Graphics().p("AkREsIAApMIIfAAIAAJMg");
	var mask_graphics_86 = new cjs.Graphics().p("AlIEsIAApMIIfAAIAAJMg");
	var mask_graphics_87 = new cjs.Graphics().p("Al/EsIAApMIIfAAIAAJMg");
	var mask_graphics_88 = new cjs.Graphics().p("Am2EsIAApMIIfAAIAAJMg");
	var mask_graphics_89 = new cjs.Graphics().p("AnuEsIAApMIIfAAIAAJMg");
	var mask_graphics_90 = new cjs.Graphics().p("AolEsIAApMIIhAAIAAJMg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:55.1,y:30}).wait(40).to({graphics:mask_graphics_40,x:55,y:30}).wait(1).to({graphics:mask_graphics_41,x:51.9,y:30}).wait(1).to({graphics:mask_graphics_42,x:48.9,y:30}).wait(1).to({graphics:mask_graphics_43,x:45.8,y:30.1}).wait(1).to({graphics:mask_graphics_44,x:42.8,y:30.1}).wait(1).to({graphics:mask_graphics_45,x:39.7,y:30.1}).wait(1).to({graphics:mask_graphics_46,x:36.7,y:30.1}).wait(1).to({graphics:mask_graphics_47,x:33.6,y:30.1}).wait(1).to({graphics:mask_graphics_48,x:30.6,y:30.1}).wait(1).to({graphics:mask_graphics_49,x:27.5,y:30}).wait(31).to({graphics:mask_graphics_80,x:27.5,y:30}).wait(1).to({graphics:mask_graphics_81,x:16.7,y:30}).wait(1).to({graphics:mask_graphics_82,x:5.6,y:30}).wait(1).to({graphics:mask_graphics_83,x:-5.5,y:30}).wait(1).to({graphics:mask_graphics_84,x:-16.5,y:30}).wait(1).to({graphics:mask_graphics_85,x:-27.4,y:30}).wait(1).to({graphics:mask_graphics_86,x:-32.9,y:30}).wait(1).to({graphics:mask_graphics_87,x:-38.5,y:30}).wait(1).to({graphics:mask_graphics_88,x:-44,y:30}).wait(1).to({graphics:mask_graphics_89,x:-49.5,y:30}).wait(1).to({graphics:mask_graphics_90,x:-55,y:30}).wait(1).to({graphics:null,x:0,y:0}).wait(90));

	// PIC1
	this.instance_3 = new lib.pic();
	this.instance_3.setTransform(56.8,30.4,0.518,0.518,0,0,0,0.5,1);

	this.instance_3.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(40).to({regX:0.3,regY:0.8,scaleX:0.49,scaleY:0.49,x:24,y:28},9).wait(31).to({x:-86.6},10).to({_off:true},1).wait(90));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_0 = new cjs.Graphics().p("AClEsIm3AAIAApXIIlAAIAAALIAAJMg");
	var mask_1_graphics_80 = new cjs.Graphics().p("AkSEmIAApLIIlAAIAAJLg");
	var mask_1_graphics_81 = new cjs.Graphics().p("AkSEmIAApLIIlAAIAAJLg");
	var mask_1_graphics_82 = new cjs.Graphics().p("AkSEmIAApLIIlAAIAAJLg");
	var mask_1_graphics_83 = new cjs.Graphics().p("AkSEmIAApLIIlAAIAAJLg");
	var mask_1_graphics_84 = new cjs.Graphics().p("AkSEmIAApLIIlAAIAAJLg");
	var mask_1_graphics_85 = new cjs.Graphics().p("AkSEmIAApLIIlAAIAAJLg");
	var mask_1_graphics_86 = new cjs.Graphics().p("AkSEmIAApLIIlAAIAAJLg");
	var mask_1_graphics_87 = new cjs.Graphics().p("AkSEmIAApLIIlAAIAAJLg");
	var mask_1_graphics_88 = new cjs.Graphics().p("AkSEmIAApLIIlAAIAAJLg");
	var mask_1_graphics_89 = new cjs.Graphics().p("AkSEmIAApLIIlAAIAAJLg");
	var mask_1_graphics_90 = new cjs.Graphics().p("AkSEmIAApLIIlAAIAAJLg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:mask_1_graphics_0,x:82.5,y:30}).wait(80).to({graphics:mask_1_graphics_80,x:82.4,y:30.6}).wait(1).to({graphics:mask_1_graphics_81,x:71.4,y:30.6}).wait(1).to({graphics:mask_1_graphics_82,x:60.3,y:30.6}).wait(1).to({graphics:mask_1_graphics_83,x:49.3,y:30.6}).wait(1).to({graphics:mask_1_graphics_84,x:38.2,y:30.6}).wait(1).to({graphics:mask_1_graphics_85,x:27.2,y:30.6}).wait(1).to({graphics:mask_1_graphics_86,x:16.1,y:30.6}).wait(1).to({graphics:mask_1_graphics_87,x:5.1,y:30.6}).wait(1).to({graphics:mask_1_graphics_88,x:-6,y:30.6}).wait(1).to({graphics:mask_1_graphics_89,x:-17,y:30.6}).wait(1).to({graphics:mask_1_graphics_90,x:-28.1,y:30.6}).wait(1).to({graphics:null,x:0,y:0}).wait(90));

	// PIC2
	this.instance_4 = new lib._336x280dev();
	this.instance_4.setTransform(44,0,0.426,0.426);

	this.instance_5 = new lib.Tween1("synched",0);
	this.instance_5.setTransform(79.8,29.8);
	this.instance_5._off = true;

	this.instance_6 = new lib.Tween2("synched",0);
	this.instance_6.setTransform(-31.2,29.8);

	this.instance_4.mask = this.instance_5.mask = this.instance_6.mask = mask_1;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_4}]},40).to({state:[{t:this.instance_5}]},40).to({state:[{t:this.instance_6}]},10).to({state:[]},1).wait(90));
	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(80).to({_off:false},0).to({_off:true,x:-31.2},10).wait(91));

	// pic shad
	this.instance_7 = new lib.HTML5rastershad_1();
	this.instance_7.setTransform(120.1,30,1,1,-90,0,0,0,10);
	this.instance_7.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(80).to({x:9},10).to({_off:true},90).wait(1));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_0 = new cjs.Graphics().p("AxuHBIAAuBMAjdAAAIAAOBg");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:mask_2_graphics_0,x:223.6,y:31}).wait(49).to({graphics:null,x:0,y:0}).wait(132));

	// HEAD
	this.instance_8 = new lib.HEAD1();
	this.instance_8.setTransform(406.5,47,1,1,0,0,0,119.5,27);

	this.instance_8.mask = mask_2;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({_off:true},80).wait(101));

	// HEAD2
	this.instance_9 = new lib.HEAD2();
	this.instance_9.setTransform(160.5,52.3,1,1,0,0,0,-1.5,31.9);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(91).to({_off:false},0).to({_off:true},78).wait(12));

	// Close
	this.instance_10 = new lib.Close();
	this.instance_10.setTransform(300.5,30,1,1,0,0,0,-1.5,24);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(178).to({_off:false},0).to({_off:true},2).wait(1));

	// shad
	this.instance_11 = new lib.HTML5rastershad_1();
	this.instance_11.setTransform(155,45,1,1,-90,0,0,0,10);
	this.instance_11.alpha = 0.199;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(178).to({_off:false},0).to({_off:true},2).wait(1));

	// head bkgd
	this.instance_12 = new lib.headbkgd();
	this.instance_12.setTransform(146.5,124.8,1.005,0.891,0,0,0,167.9,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(80).to({scaleX:0.68,x:112.6},9).wait(80).to({x:258.6},9).to({_off:true},2).wait(1));

	// tag
	this.instance_13 = new lib._2016_SCU_BBShorizai();
	this.instance_13.setTransform(394.6,51.3,0.878,0.878,0,0,0,73.2,3.5);

	this.instance_14 = new lib._2016TAG();
	this.instance_14.setTransform(71.7,51,0.716,0.716,0,0,0,0,2.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_13}]},81).to({state:[{t:this.instance_14},{t:this.instance_13}]},88).to({state:[]},11).wait(1));

	// logo
	this.instance_15 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_15.setTransform(237.4,55.6,0.771,0.771,0,0,0,215.2,63.1);

	this.instance_16 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_16.setTransform(559.8,55.8,0.771,0.771,0,0,0,215.2,63.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_16},{t:this.instance_15}]},81).to({state:[]},99).wait(1));

	// logo rule
	this.instance_17 = new lib._2016_SCU_logoruleai();
	this.instance_17.setTransform(136.4,42.8,0.797,0.797,0,0,0,81.4,0.5);

	this.instance_18 = new lib._2016_SCU_logoruleai();
	this.instance_18.setTransform(458.8,43,0.797,0.797,0,0,0,81.4,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_18},{t:this.instance_17}]},81).to({state:[]},99).wait(1));

	// shad
	this.instance_19 = new lib.HTML5rastershad_1();
	this.instance_19.setTransform(466.2,71,1,1,-90,0,0,0,10);
	this.instance_19.alpha = 0.301;

	this.timeline.addTween(cjs.Tween.get(this.instance_19).wait(80).to({y:70.5},0).to({x:331,y:71},9).to({_off:true},91).wait(1));

	// logo box
	this.instance_20 = new lib.box1();
	this.instance_20.setTransform(209,19.8,1.393,0.429,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_20).to({_off:true},180).wait(1));

	// EHO
	this.instance_21 = new lib.EqualHousingOpportunityrevai("synched",0);
	this.instance_21.setTransform(164.5,46.2,0.07,0.07,0,0,0,135,145);
	this.instance_21._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_21).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(211.7,-108,498.5,377);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;