(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 160,
	height: 600,
	fps: 18,
	color: "#CCCCCC",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/HTML5rastershad.png", id:"HTML5rastershad"},
		{src:"images/SCU201609_Air_160x600_AdR_atlas_NP_.jpg", id:"SCU201609_Air_160x600_AdR_atlas_NP_"}
	]
};



lib.ssMetadata = [
		{name:"SCU201609_Air_160x600_AdR_atlas_NP_", frames: [[0,0,336,224],[338,0,168,141]]}
];


lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib._336x280air = function() {
	this.spriteSheet = ss["SCU201609_Air_160x600_AdR_atlas_NP_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib._336x280dev = function() {
	this.spriteSheet = ss["SCU201609_Air_160x600_AdR_atlas_NP_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.Tween6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._336x280air();
	this.instance.setTransform(-124.8,-83.2,0.743,0.743);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-124.8,-83.2,249.8,166.5);


(lib.Tween5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._336x280air();
	this.instance.setTransform(-124.8,-83.2,0.743,0.743);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-124.8,-83.2,249.8,166.5);


(lib.Tween2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._336x280dev();
	this.instance.setTransform(-84,-70);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-84,-70,168,141);


(lib.Tween1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._336x280dev();
	this.instance.setTransform(-84,-70);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-84,-70,168,141);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#3F3F3F").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.ncuahorizai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AEOAmIADgGQADACAEAAQAGAAADgJIgUgsIAHAAIARAlIAPglIAHAAIgTAuQgFANgLAAQgGAAgEgCgAjbAmIADgGQACACAFAAQAGAAADgJIgVgsIAHAAIARAlIAQglIAHAAIgUAuQgFANgKAAQgGAAgEgCgAIGAXQgGgFAAgGQAAgOAUAAQAFAAAKACIAAgBQgBgNgOAAQgGAAgHAEIgDgGQAIgEAJAAQALAAAEAFQAFAFAAAJIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgEgDgAIHALQAAAKAMAAQAGAAAFgEQAEgDABgGIAAgEQgIgCgGAAQgOAAAAAJgAHLAIIAAgbIAIAAIAAAZQgBAOANAAQAHAAADgEQAFgEAAgHIAAgYIAGAAIAAAsIgGAAIAAgIQgHAJgKAAQgRAAgBgSgAGdATQgHgHAAgKQAAgIAHgHQAHgHAKAAQAKAAAJAIIgFAFQgIgHgGAAQgIAAgEAFQgFAFAAAGIAAAAQAAAIAFAFQAFAFAHAAQAIAAAGgHIAFAEQgIAJgLAAQgKAAgHgHgADfAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgKALAAQAIAAAGAGQAIAHgBAJIAAAAQABALgIAHQgGAGgIAAQgMAAgGgKgADjgJQgEAFAAAGIAAAAQAAAIAEAFQAGAFAGAAQAHAAAFgFQAEgFAAgIQAAgGgEgFQgFgFgHAAQgGAAgGAFgACFAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgACKgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgABQAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgABuAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAgIAVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOALAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgHAAgEgFgAg9ATIADgFQAIAGAIAAQAKAAAAgHQAAgFgMgDQgPgFAAgHQAAgGAFgDQAEgEAHAAQAJAAAIAFIgDAFQgIgEgGAAQgJAAAAAHQAAAEAMADQAPADAAAJQAAAHgFAEQgEADgIAAQgLAAgIgHgAk6AXQgGgFAAgGQAAgIAGgEQAGgCAJAAQAFAAAJACIAAgBQAAgNgOAAQgHAAgHAEIgCgGQAIgEAJAAQAKAAAFAFQAEAFABAJIAAAaIgHAAIAAgHQgGAIgLAAQgHAAgFgDgAk5ALQABAKALAAQAHAAAFgEQAEgDAAgGIAAgEQgHgCgGAAQgOAAgBAJgAmPAUQgHgHAAgLQAAgIAGgHQAHgHAJAAQAKAAAGAHQAGAHAAAIIAAADIglAAQABAHAEAEQAFAEAGAAQAIAAAHgGIAEAEQgIAIgLAAQgKAAgGgGgAlxAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAnLAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgAnGgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgAoAAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQACAPAOAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgAniAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAGDAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAApAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIgBAAQgIAAgEAGQgGAGAAAIIAAASgAhPAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAiHAZIAAgsIAHAAIAAAsgAjwAZIAAg/IAHAAIAAA/gAkHAZIAAg/IAHAAIAAA/gAleAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIAAAAQgIAAgGAGQgFAGAAAIIAAASgAoiAZIAAgmIgGAAIAAgGIAGAAIAAgEQAAgIAEgEQAEgEAGAAIAIABIAAAGIgHgBQgIAAAAAKIAAAEIAPAAIAAAGIgPAAIAAAmgAiIgdIAAgIIAIAAIAAAIg");
	this.shape.setTransform(0,4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.3,0,110.7,8.1);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F78E1E").s().p("AgPARIAAghIAfAAIAAAhg");
	this.shape.setTransform(57.5,99.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F78E1E").s().p("AgYA/QgTgIgIgHIANgUQAKAIAMAEQALAEAIAAQAKAAAGgEQAFgDAAgIIAAAAQAAgGgJgFQgFgDgOgFQgUgFgHgFQgHgEgDgGQgEgHAAgJIAAAAQAAgKAEgHQAEgIAGgFQAGgFAJgDQAJgDAIAAQALAAANAFQANAEAKAGIgLAVQgKgFgJgEQgLgDgHAAQgHABgFADQgFADAAAGIAAABQAAAGAJAFIATAIIAOAEIAOAGQAGAFADAGQAEAHAAAIIAAABQAAAKgEAIQgEAHgGAFQgHAGgJACQgJADgKAAQgNAAgOgFg");
	this.shape_1.setTransform(47.8,94.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F78E1E").s().p("AgYA/QgTgIgIgHIANgUQALAIALAEQALAEAIAAQAKAAAGgEQAFgDAAgIIAAAAQAAgGgJgFQgEgDgPgFQgTgFgIgFQgHgEgDgGQgDgHAAgJIAAAAQAAgKADgHQAEgIAGgFQAHgFAIgDQAJgDAIAAQAMAAANAFQAMAEAKAGIgLAVQgKgFgJgEQgLgDgHAAQgHABgFADQgFADAAAGIAAABQAAAGAJAFIATAIIAPAEIAMAGQAHAFADAGQAEAHAAAIIAAABQAAAKgEAIQgEAHgGAFQgHAGgJACQgJADgLAAQgMAAgOgFg");
	this.shape_2.setTransform(35.3,94.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F78E1E").s().p("AgWA/QgLgEgKgKQgJgJgFgMIgEgNIgBgPIAAAAQAAgNAEgMQAFgMAJgKQAIgJAMgGIANgEIALgCQAIABAHABQAHACAGADQAHADAMAMQAIAKAFAMQADAOAAAMIAAAIIhfAAQABAIAEAHQADAFAFAFQAFAEAGADQAGACAGAAQALAAAJgFQAHgDAIgIIASAQIgKAKQgGAFgGADQgHADgIABQgHACgKABQgMgBgNgFgAAigHQgBgIgDgHQgCgGgEgFQgFgEgFgDQgHgCgHgBQgFABgGACQgGACgEAFQgEAFgDAGQgEAGgBAJIBDAAIAAAAg");
	this.shape_3.setTransform(21.6,94.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F78E1E").s().p("AAdBDIAAhJQAAgIgCgFQgCgGgEgFQgEgEgFgCQgFgDgHABQgEgBgGADQgFACgEAFQgEAEgCAGQgDAGAAAHIAABJIgeAAIAAiCIAeAAIAAAUQAIgKAJgGIALgFQAEgCAIAAQALAAAJAEQAIADAGAHQAGAGAEAKQADAJAAAMIAABSg");
	this.shape_4.setTransform(6.4,94.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F78E1E").s().p("AgNBaIAAiCIAcAAIAACCgAgPg8IAAgdIAfAAIAAAdg");
	this.shape_5.setTransform(-5,92);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F78E1E").s().p("AgYA/QgTgIgIgHIANgUQAKAIAMAEQALAEAJAAQAJAAAFgEQAGgDAAgIIAAAAQAAgGgJgFQgFgDgNgFQgVgFgHgFQgHgEgDgGQgDgHgBgJIAAAAQABgKADgHQADgIAHgFQAHgFAIgDQAJgDAHAAQAMAAANAFQANAEALAGIgMAVQgKgFgKgEQgJgDgIAAQgHABgFADQgFADAAAGIAAABQAAAGAJAFIATAIIAOAEIAOAGQAGAFADAGQAEAHAAAIIAAABQAAAKgEAIQgEAHgGAFQgHAGgJACQgJADgKAAQgMAAgPgFg");
	this.shape_6.setTransform(-15,94.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F78E1E").s().p("AgfA/QgIgEgGgGQgGgGgEgKQgDgJAAgMIAAhSIAeAAIAABJQAAAHACAHQACAFAEAFQADAEAGACQAFACAGAAQAFAAAGgCQAFgCAEgEQAEgFACgFQACgHAAgIIAAhIIAfAAIAACCIgfAAIAAgVQgHALgJAGIgLAFQgEACgIAAQgLAAgJgEg");
	this.shape_7.setTransform(-28.9,94.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F78E1E").s().p("AgHBaQgGgCgGgDQgKgGgIgKIAAAUIgeAAIAAi0IAeAAIAABIQAJgLAKgGQAFgEAHgCQAGgCAGAAQAMAAALAFQALAFAJAIQAJAJAFANQAFAQAAALIAAAAIgCAQIgDAOQgFAMgJAJQgJAJgLAEQgLAFgMAAQgGAAgHgCgAgNgOQgHADgGAFQgFAGgDAGQgDAIAAAJIAAAAQAAAKADAIQADAHAFAGQAGAGAHADQAHADAGAAQAHAAAHgDQAHgDAFgGQAFgFADgIQADgIAAgKIAAAAQAAgJgDgIQgDgGgFgGQgFgFgHgDQgHgDgHAAQgGAAgHADg");
	this.shape_8.setTransform(-44.6,92);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#F78E1E").s().p("AAdBbIAAhLQAAgIgCgGQgCgEgEgEQgEgEgFgCQgFgDgHAAQgEAAgGADQgFACgEAEQgEAFgCADQgDAHAAAHIAABLIgeAAIAAi1IAeAAIAABHQAIgKAJgGIALgFQAEgCAIAAQALAAAJAEQAIADAGAHQAGAGAEAKQADAJAAAKIAABUg");
	this.shape_9.setTransform(19.5,66.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#F78E1E").s().p("AAABSQgHgCgFgDQgFgGgDgHQgDgHAAgLIAAhDIgRAAIAAgaIARAAIAAgkIAcAAIAAAkIAkAAIAAAaIgkAAIAAA+QAAAJAFAEQAEAEAIAAQAJAAAJgFIAAAZQgGAEgGABQgHACgIAAQgJAAgEgDg");
	this.shape_10.setTransform(6.4,67.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#F78E1E").s().p("AgNBaIAAiCIAcAAIAACCgAgPg8IAAgdIAfAAIAAAdg");
	this.shape_11.setTransform(-2.1,67);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#F78E1E").s().p("AAdBCIgdhYIgcBYIgbAAIgriDIAfAAIAaBZIAdhZIAYAAIAeBZIAbhZIAeAAIgrCDg");
	this.shape_12.setTransform(-16.4,69.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#F78E1E").s().p("AgYA/QgTgIgIgGIANgVQALAHALAFQALAEAJAAQAJAAAFgEQAGgDAAgIIAAAAQAAgHgJgEQgEgDgOgFQgVgGgIgEQgGgEgDgGQgDgHgBgJIAAgBQABgJADgIQAEgGAGgGQAGgFAJgDQAIgDAIAAQAMAAAOAFQAMADALAHIgMAWQgKgGgKgDQgKgEgHAAQgHABgFADQgFADAAAHIAAAAQAAAHAJAEIATAIIAPAEIAMAGQAHAFADAGQAEAGAAAJIAAAAQAAALgEAHQgDAIgIAGQgGAFgJACQgJADgLAAQgMAAgOgFg");
	this.shape_13.setTransform(47.4,42.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#F78E1E").s().p("AgYA/QgTgIgIgGIANgVQAKAHAMAFQALAEAJAAQAJAAAFgEQAGgDAAgIIAAAAQAAgHgJgEQgEgDgOgFQgVgGgHgEQgHgEgDgGQgDgHgBgJIAAgBQABgJADgIQAEgGAGgGQAHgFAIgDQAJgDAHAAQAMAAANAFQANADALAHIgMAWQgKgGgKgDQgKgEgHAAQgHABgFADQgFADAAAHIAAAAQAAAHAJAEIATAIIAOAEIAOAGQAGAFADAGQAEAGAAAJIAAAAQAAALgEAHQgDAIgIAGQgGAFgJACQgJADgKAAQgMAAgPgFg");
	this.shape_14.setTransform(34.9,42.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#F78E1E").s().p("AgWA/QgMgFgIgIQgKgJgFgNIgEgNIgCgPIAAAAQABgMAFgNQAEgMAJgKQAJgJAMgGIALgEIANgCQAHAAAHACQAHABAGADQAIAEAMAMQAHAJAEANQAFANAAANIgBAIIhfAAQABAIADAHQAEAFAFAFQAFAFAHACQAFACAGAAQALAAAIgEQAIgEAIgIIASAQIgKAKQgGAFgGACQgHAEgHACQgJACgIAAQgMAAgOgGgAAhgIQAAgHgDgGQgCgHgFgFQgEgEgGgDQgFgCgIgBQgFABgGACQgGACgEAFQgFAFgDAGQgCAHgBAHIBBAAIAAAAg");
	this.shape_15.setTransform(21.2,42.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#F78E1E").s().p("AAdBDIAAhJQAAgHgCgHQgCgFgEgFQgEgEgFgCQgFgCgHgBQgEABgGACQgFACgEAEQgEAFgCAFQgDAHAAAIIAABIIgeAAIAAiCIAeAAIAAAVQAIgLAJgGIALgFQAEgCAIAAQALAAAJAEQAIAEAGAGQAGAGAEAKQADAJAAAMIAABSg");
	this.shape_16.setTransform(6,42.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#F78E1E").s().p("AgNBaIAAiCIAcAAIAACCgAgPg8IAAgdIAfAAIAAAdg");
	this.shape_17.setTransform(-5.4,40);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#F78E1E").s().p("AgYA/QgTgIgIgGIANgVQALAHALAFQALAEAIAAQAKAAAFgEQAGgDAAgIIAAAAQAAgHgJgEQgEgDgPgFQgTgGgJgEQgGgEgDgGQgEgHABgJIAAgBQgBgJAEgIQADgGAHgGQAGgFAJgDQAIgDAIAAQANAAANAFQAMADAKAHIgLAWQgKgGgJgDQgLgEgHAAQgHABgFADQgFADAAAHIAAAAQAAAHAJAEIATAIIAPAEIAMAGQAHAFADAGQAEAGAAAJIAAAAQAAALgEAHQgDAIgIAGQgGAFgJACQgJADgLAAQgLAAgPgFg");
	this.shape_18.setTransform(-15.4,42.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#F78E1E").s().p("AgfA/QgIgDgGgHQgGgGgEgKQgDgJAAgMIAAhSIAeAAIAABJQAAAIACAFQACAGAEAFQADAEAGACQAFACAGAAQAFAAAGgCQAFgCAEgFQAEgDACgHQACgGAAgHIAAhJIAfAAIAACCIgfAAIAAgUQgHAKgJAGIgLAFQgEACgIAAQgLAAgJgEg");
	this.shape_19.setTransform(-29.3,42.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#F78E1E").s().p("AgHBaQgGgCgGgDQgKgGgIgKIAAAUIgeAAIAAi0IAeAAIAABIQAJgLAKgGQAFgEAHgCQAGgCAGAAQAMAAALAFQALAFAJAIQAJAJAFANQAFAQAAALIAAAAIgCAQIgDAOQgFAMgJAJQgJAJgLAEQgLAFgMAAQgGAAgHgCgAgNgOQgHADgGAFQgFAGgDAGQgDAIAAAJIAAAAQAAAKADAIQADAHAFAGQAGAGAHADQAHADAGAAQAHAAAHgDQAHgDAFgGQAFgFADgIQADgIAAgKIAAAAQAAgJgDgIQgDgGgFgGQgFgFgHgDQgHgDgHAAQgGAAgHADg");
	this.shape_20.setTransform(-45,40);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#F78E1E").s().p("AAdBDIAAhJQAAgHgCgHQgCgFgEgFQgEgEgFgCQgFgCgHgBQgEABgGACQgFACgEAEQgEAFgCAFQgDAHAAAIIAABIIgeAAIAAiCIAeAAIAAAVQAIgLAJgGIALgFQAEgCAIAAQALAAAJAEQAIAEAGAGQAGAGAEAKQADAJAAAMIAABSg");
	this.shape_21.setTransform(44.4,15.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#F78E1E").s().p("AgNBaIAAiCIAcAAIAACCgAgPg8IAAgdIAfAAIAAAdg");
	this.shape_22.setTransform(33,13);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#F78E1E").s().p("AgWA/QgLgFgKgIQgJgJgFgNIgEgNIgBgPIAAAAQAAgMAEgNQAFgMAJgKQAIgJAMgGIANgEIALgCQAIAAAHACQAHABAGADQAHAEAMAMQAIAJAFANQADANAAANIAAAIIhfAAQABAIAEAHQADAFAFAFQAFAFAGACQAGACAGAAQALAAAJgEQAHgEAIgIIASAQIgKAKQgGAFgGADQgHADgIACQgHACgKAAQgMAAgNgGgAAigIQgBgHgDgGQgCgHgEgFQgFgEgFgDQgHgCgHgBQgFABgGACQgGACgEAFQgEAFgDAGQgEAHgBAHIBDAAIAAAAg");
	this.shape_23.setTransform(14.4,15.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#F78E1E").s().p("AglBDIAAiCIAeAAIAAAdQADgHAEgGQAEgGAFgEQAGgFAHgCQAIgCAIAAIAAAgIgCAAQgKAAgIAEQgJADgFAGQgEAHgEAKQgDAIAAAMIAAAzg");
	this.shape_24.setTransform(2.3,15.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#F78E1E").s().p("AgTAWQALgDAFgFQAEgGgBgIIgLAAIAAgiIAfAAIAAAdQAAAJgCAHQgDAIgFAEQgEAFgGADQgHADgJABg");
	this.shape_25.setTransform(-7.1,8.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#F78E1E").s().p("AgVA/QgMgFgKgIQgJgJgFgNIgEgNIgCgPIAAAAQAAgMAGgNQAEgMAJgKQAIgJANgGIAMgEIALgCQAIAAAHACQAHABAGADQAIAEAMAMQAHAJAEANQAEANAAANIAAAIIhfAAQABAIADAHQAEAFAFAFQAFAFAGACQAHACAFAAQAKAAAJgEQAJgEAIgIIASAQIgLAKQgGAFgGADQgHADgHACQgJACgIAAQgMAAgNgGgAAhgIQAAgHgDgGQgDgHgEgFQgEgEgFgDQgHgCgHgBQgFABgGACQgFACgFAFQgFAFgDAGQgCAHgBAHIBBAAIAAAAg");
	this.shape_26.setTransform(-17.7,15.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#F78E1E").s().p("AAqBYIgqh8IgpB8IgbAAIg9iuIAhAAIAqB/IAriAIAYAAIArCAIAqh/IAgAAIg9Cug");
	this.shape_27.setTransform(-38.2,13.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,0,160,108);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgPARIAAghIAfAAIAAAhg");
	this.shape.setTransform(57.5,120.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgMBCIg2iDIAgAAIAiBfIAjhfIAgAAIg2CDg");
	this.shape_1.setTransform(46.7,115.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgWA/QgLgFgJgIQgKgKgFgMIgEgNIgBgPIAAAAQAAgMAEgNQAFgMAJgKQAJgJALgGIAMgEIANgBQAHAAAHABQAHABAGADQAHAEAMAMQAJAJADANQAFANAAANIgBAIIhfAAQABAIAEAHQADAFAFAFQAFAFAHACQAFACAGAAQALAAAIgEQAJgEAHgIIASAQIgKAKQgFAEgHADQgHAEgIACQgHACgKAAQgMAAgNgGgAAigIQgBgHgDgGQgDgHgEgFQgEgEgGgDQgFgDgIAAQgFAAgGADQgGADgEAEQgFAFgDAGQgDAHAAAHIBCAAIAAAAg");
	this.shape_2.setTransform(31.8,115.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgcBXQgLgEgIgJQgJgJgGgMIgDgOIgCgQIAAAAQAAgLAFgQQAFgNAJgJQAJgIALgFQALgFALAAQAHAAAGACQAHACAFAEQALAFAHALIAAhHIAfAAIAAC0IgfAAIAAgWQgHAMgLAGIgMAFQgGACgHAAQgLAAgLgFgAgNgOQgHADgFAFQgGAGgCAFQgDAIgBAKIAAAAQABAKADAIQACAHAGAGQAGAGAGADQAHADAGAAQAIAAAGgDQAHgDAFgGQAGgGADgHQADgIAAgKIAAAAQAAgJgDgIQgDgGgGgGQgFgFgHgDQgGgDgIAAQgGAAgHADg");
	this.shape_3.setTransform(15.5,113);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgHBaQgGgCgGgDQgKgGgIgKIAAAUIgeAAIAAi0IAeAAIAABIQAJgLAKgGQAFgEAHgCQAGgCAGAAQAMAAALAFQALAFAJAIQAJAJAFANQAFAQAAALIAAAAIgCAQIgDAOQgFAMgJAJQgJAJgLAEQgLAFgMAAQgGAAgHgCgAgNgOQgHADgGAFQgFAGgDAGQgDAIAAAJIAAAAQAAAKADAIQADAHAFAGQAGAGAHADQAHADAGAAQAHAAAHgDQAHgDAFgGQAFgFADgIQADgIAAgKIAAAAQAAgJgDgIQgDgGgFgGQgFgFgHgDQgHgDgHAAQgGAAgHADg");
	this.shape_4.setTransform(-8.1,113);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgVA/QgNgFgIgIQgKgKgFgMIgEgNIgCgPIAAAAQABgMAFgNQAEgMAJgKQAJgJAMgGIALgEIANgBQAHAAAHABQAHABAGADQAIAEAMAMQAHAJAEANQAEANABANIgBAIIhfAAQABAIADAHQAEAFAFAFQAFAFAGACQAHACAFAAQAKAAAJgEQAIgEAJgIIASAQIgLAKQgGAEgGADQgHAEgHACQgIACgJAAQgMAAgNgGgAAhgIQAAgHgDgGQgDgHgEgFQgEgEgGgDQgFgDgIAAQgFAAgGADQgFADgFAEQgFAFgDAGQgCAHgBAHIBBAAIAAAAg");
	this.shape_5.setTransform(-24.3,115.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAdBCIgdhYIgcBYIgbAAIgriDIAfAAIAaBZIAdhZIAYAAIAeBZIAbhZIAeAAIgrCDg");
	this.shape_6.setTransform(-42.6,115.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgOBDIgMgEQgNgFgKgJQgJgKgGgNIgEgMIgBgOIAAAAQAAgHAFgSQAFgNAKgJQAKgKANgFIANgEIANgBQAKgBASAGQAMAFAKAKQAJAKAGALQAFASAAAIIAAAAIgCANIgDANQgGANgJAJQgKAKgMAFQgTAFgJAAgAgPgmQgIAEgFAFQgFAHgCAHQgEAIAAAHIAAAAQAAAIAEAIQADAIAFAGQAFAFAIAEQAHAEAHgBQAJABAIgEQAGgEAGgFQAFgGADgIQADgHgBgJIAAAAQABgHgDgHQgDgJgFgFQgGgGgIgEQgHgDgIAAQgHAAgIADg");
	this.shape_7.setTransform(5.1,90.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAABTQgHgDgFgEQgFgFgDgGQgDgJAAgKIAAhDIgRAAIAAgbIARAAIAAgkIAcAAIAAAkIAkAAIAAAbIgkAAIAAA+QAAAJAFAEQAEADAIAAQAJAAAJgEIAAAZQgGADgGACQgHABgIAAQgJAAgEgBg");
	this.shape_8.setTransform(-8.4,88.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgYA/QgTgIgIgHIANgUQAKAHAMAFQALAEAIAAQAKAAAGgEQAFgEAAgGIAAgBQAAgGgJgFQgFgDgNgEQgVgHgHgEQgHgEgDgGQgEgHAAgJIAAAAQAAgKAEgHQAEgIAGgFQAGgFAJgDQAJgDAIAAQALAAANAFQANAEAKAGIgLAVQgKgFgJgEQgLgCgHAAQgHgBgFAEQgFAEAAAFIAAABQAAAGAJAFIATAHIAOAGIAOAFQAGAFADAGQAEAGAAAJIAAABQAAAJgEAJQgEAHgGAFQgHAGgJACQgJADgKAAQgNAAgOgFg");
	this.shape_9.setTransform(50.5,65.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AglBDIAAiCIAeAAIAAAdQADgHAEgGQADgGAGgEQAGgFAHgCQAHgCAJAAIAAAgIgCAAQgKAAgIAEQgIADgGAGQgEAHgDAKQgEAIAAAMIAAAzg");
	this.shape_10.setTransform(39.8,65.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgVBAQgNgGgIgJQgKgIgFgNIgEgOIgCgOIAAAAQABgMAFgNQAEgNAJgJQAJgJAMgGIALgEIANgCQAHABAHABQAHABAGAEQAIADAMAMQAHAKAEANQAEAMABANIgBAIIhfAAQABAIADAGQAEAHAFAEQAFAEAGACQAHADAFAAQAKAAAJgFQAIgDAJgIIASAQIgLAKQgGAFgGADQgHADgHABQgIACgJAAQgMAAgNgEgAAhgHQAAgIgDgHQgDgGgEgEQgEgFgGgDQgFgDgIABQgFgBgGADQgFADgFAEQgFAFgDAGQgCAGgBAJIBBAAIAAAAg");
	this.shape_11.setTransform(26.5,65.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgNBaIAAiCIAcAAIAACCgAgPg8IAAgdIAfAAIAAAdg");
	this.shape_12.setTransform(15.4,63);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgOBbIAAi1IAcAAIAAC1g");
	this.shape_13.setTransform(8.3,62.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AhDBXIAAiqIAeAAIAAAWQAJgLAKgHQAFgDAHgCQAGgCAGAAQAMAAALAFQALAEAJAJQAJAJAFANQAFASAAAKIAAABIgCAQIgDALQgFANgJAJQgJAIgLAFQgLAFgMAAQgGAAgHgCQgGgCgGgEQgKgFgIgLIAAA9gAgNg4QgHADgGAFQgFAGgDAHQgDAIAAAJIAAABQAAAKADAHQADAGAFAGQAGAGAHADQAHADAGAAQAHAAAHgDQAHgDAFgGQAFgGADgGQADgIAAgJIAAgBQAAgJgDgIQgDgHgFgGQgFgFgHgDQgHgDgHgBQgGABgHADg");
	this.shape_14.setTransform(-3.4,67.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AhDBXIAAiqIAeAAIAAAWQAJgLAKgHQAFgDAHgCQAGgCAGAAQAMAAALAFQALAEAJAJQAJAJAFANQAFASAAAKIAAABIgCAQIgDALQgFANgJAJQgJAIgLAFQgLAFgMAAQgGAAgHgCQgGgCgGgEQgKgFgIgLIAAA9gAgNg4QgHADgGAFQgFAGgDAHQgDAIAAAJIAAABQAAAKADAHQADAGAFAGQAGAGAHADQAHADAGAAQAHAAAHgDQAHgDAFgGQAFgGADgGQADgIAAgJIAAgBQAAgJgDgIQgDgHgFgGQgFgFgHgDQgHgDgHgBQgGABgHADg");
	this.shape_15.setTransform(-20.1,67.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgfA/QgIgEgGgGQgGgHgEgJQgDgJAAgMIAAhSIAeAAIAABJQAAAHACAHQACAFAEAFQADAEAGACQAFACAGAAQAFAAAGgCQAFgCAEgEQAEgFACgFQACgHAAgIIAAhIIAfAAIAACCIgfAAIAAgVQgHALgJAGIgLAFQgEACgIAAQgLAAgJgEg");
	this.shape_16.setTransform(-36.7,65.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgYA/QgTgIgIgHIANgUQALAHALAFQALAEAJAAQAJAAAFgEQAGgEAAgGIAAgBQAAgGgJgFQgEgDgOgEQgVgHgIgEQgGgEgDgGQgDgHgBgJIAAAAQABgKADgHQAEgIAGgFQAGgFAJgDQAIgDAIAAQAMAAANAFQANAEALAGIgMAVQgKgFgKgEQgKgCgHAAQgHgBgFAEQgFAEAAAFIAAABQAAAGAJAFIATAHIAOAGIANAFQAHAFADAGQAEAGAAAJIAAABQAAAJgEAJQgDAHgIAFQgGAGgJACQgJADgLAAQgMAAgOgFg");
	this.shape_17.setTransform(-50.7,65.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAABSQgHgCgFgDQgFgGgDgHQgDgIAAgKIAAhEIgRAAIAAgZIARAAIAAgkIAcAAIAAAkIAkAAIAAAZIgkAAIAAA/QAAAJAFAEQAEADAIAAQAJABAJgFIAAAZQgGADgGACQgHABgIAAQgJAAgEgCg");
	this.shape_18.setTransform(40.2,38.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgWBbIAAhoIgRAAIAAgYIARAAIAAgKQAAgLACgJQADgHAFgGQAFgFAHgDQAGgDAKABQANgBALAEIAAAaQgJgDgIAAQgJgBgEAFQgFAFAAAKIAAAIIAjAAIAAAYIgiAAIAABog");
	this.shape_19.setTransform(30.8,37.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgeBBQgIgDgGgEQgHgGgEgIQgDgHgBgKIAAgBQABgKADgJQAFgHAHgEQAHgFAKgDQAKgDALAAQAOAAAUAFIAAgCQAAgGgBgGQgCgFgFgDQgEgFgGgBQgGgCgGAAQgLAAgJACQgIACgKAEIgIgYQAMgGALgCQANgDANAAQANAAAMAEQALAEAHAGQAHAIAEAKQADALAAANIAABMIgeAAIAAgQQgHAJgKAEQgOAGgKAAQgJAAgJgDgAgLAGQgFACgFACQgDACgCAEQgDAEAAAFIAAAAQAAAKAIAFQAHAFALAAQAFAAAHgCQAHgCAEgDQAFgFADgEQACgGAAgGIAAgHQgTgGgLABQgGAAgFABg");
	this.shape_20.setTransform(18.2,40.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AglBDIAAiCIAeAAIAAAdQADgHAEgGQADgGAGgEQAGgFAHgCQAHgCAJAAIAAAgIgCAAQgKAAgIAEQgIADgGAGQgEAHgDAKQgEAIAAAMIAAAzg");
	this.shape_21.setTransform(6.6,40.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgFBDIgOgEQgMgFgJgKQgJgJgFgMQgGgNAAgOIAAAAQAAgMAGgNQAFgMAJgKQAJgJANgGIANgEIAMgCQAJAAAIACQAIACAGADQAJAEANANIgTATQgIgIgHgDQgJgFgKAAQgHAAgGAEQgHADgGAGQgFAFgCAIQgDAIAAAHIAAAAQAAAJADAIQACAHAGAGQAFAGAHADQAGAEAIAAQAKgBAJgFQAIgDAHgIIATASQgOANgIAFQgHADgIABQgIACgJABg");
	this.shape_22.setTransform(-6.1,40.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AglBDIAAiCIAeAAIAAAdQADgHAEgGQADgGAGgEQAGgFAHgCQAIgCAIAAIAAAgIgCAAQgKAAgIAEQgJADgFAGQgEAHgEAKQgDAIAAAMIAAAzg");
	this.shape_23.setTransform(-17.9,40.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgNBaIAAiCIAcAAIAACCgAgPg8IAAgdIAfAAIAAAdg");
	this.shape_24.setTransform(-27.3,38);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgdBBQgJgDgHgEQgGgGgEgIQgDgHAAgKIAAgBQAAgKADgJQAEgHAIgEQAGgFAKgDQALgDALAAQAOAAAVAFIAAgCQgBgGgCgGQgCgFgEgDQgEgFgGgBQgGgCgGAAQgKAAgKACQgIACgJAEIgJgYQAMgGAKgCQANgDANAAQAOAAAMAEQALAEAHAGQAHAIADAKQAFALAAANIAABMIgfAAIAAgQQgHAJgKAEQgNAGgKAAQgKAAgIgDgAgLAGQgFACgEACQgFACgCAEQgBAEAAAFIAAAAQAAAKAHAFQAHAFALAAQAFAAAHgCQAGgCAFgDQAFgFACgEQADgGAAgGIAAgHQgSgGgMABQgFAAgGABg");
	this.shape_25.setTransform(-38.5,40.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("ABGBDIAAhJQAAgIgCgGQgCgGgDgEQgEgEgFgCQgFgCgGgBQgGABgFACQgGACgDAEQgEAFgCAFQgCAHAAAIIAABIIgdAAIAAhJQAAgIgBgGQgCgGgEgEQgDgEgFgCQgFgCgGgBQgGABgGACQgFACgEAEQgDAFgCAGQgDAGAAAIIAABIIgeAAIAAiCIAeAAIAAAUQAIgKAIgGIALgFQAHgCAHAAQAHAAAGACQAGABAFAEQAEADADAEIAGAKQAJgMAKgFIAMgFQAGgCAIAAQAKAAAJADQAJAEAGAGQAGAHADAJQADAKAAAMIAABSg");
	this.shape_26.setTransform(21.6,15.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgOBDIgNgEQgMgFgKgJQgKgKgEgNIgFgMIgBgOIAAAAQAAgIAGgRQAEgMALgKQAJgJAMgGIAOgEIANgCQAKAAASAGQANAGAJAJQAKAJAEAMQAGASAAAIIAAAAIgBAOIgFAMQgEAMgKAKQgKAKgNAFQgRAFgKABgAgPglQgHACgGAHQgFAFgDAIQgCAHAAAIIAAAAQAAAIACAIQADAIAGAFQAGAHAGADQAIADAHABQAIgBAIgDQAHgDAGgHQAFgFADgHQADgJAAgIIAAAAQAAgHgDgIQgDgHgGgGQgFgGgHgDQgIgEgIAAQgIAAgHAEg");
	this.shape_27.setTransform(1.5,15.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AglBDIAAiCIAeAAIAAAdQAEgHADgGQAEgGAFgEQAGgFAHgCQAIgCAIAAIAAAgIgCAAQgKAAgIAEQgJADgFAGQgEAHgDAKQgEAIAAAMIAAAzg");
	this.shape_28.setTransform(-11.3,15.3);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AhABXIAAitICBAAIAAAcIhiAAIAAAwIBXAAIAAAZIhXAAIAABIg");
	this.shape_29.setTransform(-24.7,13.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-91,0,182,129);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#5169A8").s().p("EgMfAo7MAAAhR2IY/AAMAAABR2g");
	this.shape.setTransform(80,262);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,160,524);


(lib.EqualHousingOpportunityrevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// EqualHousingOpportunity-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyZSUIAAw4IixAAIAAlsIU+uDIAZAAIU+ODIAAFwIivAAIAAQ0gAtyhwIAAOUIbpAAIAAuPIt3pUgAnQJ9IAAmDIOmAAIAAGDgAnSC9IAAl/IOmAAIAAF/g");
	this.shape.setTransform(135.6,117.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AEDBvQgWgLgIgWQgKgWAAgmIAAiHIAfAAIAACHQAAAgAHANQAFAPAOAJQAPAHAUAAQAiAAAPgPQAPgQAAgtIAAiHIAfAAIAACHQABAjgJAWQgIAUgVAOQgVAOgjAAQghAAgVgMgAmwBrQgbgSgNgbQgOgbAAghQABg4AfgiQAgghAzgBQAgAAAaAQQAbAQAOAcQAOAcAAAiQAAAkgOAcQgPAdgbAPQgaAOggABQghAAgbgQgAmthHQgYAXAAAzQAAAsAXAYQAXAZAjAAQAkAAAWgZQAYgZAAguQgBgbgJgWQgKgWgTgLQgSgMgYgBQgiAAgYAYgAxoBrQgbgRgNgcQgOgbAAghQAAg4AggiQAfghAzgBQAhAAAaAQQAbAQAOAcQANAcAAAiQABAlgPAbQgNAcgcAQQgaAOggABQgiAAgagQgAxmhHQgYAXAAAzQAAAqAYAaQAXAZAiAAQAlAAAWgZQAXgZAAguQAAgcgKgVQgJgVgUgMQgSgMgYgBQggAAgaAYgAQhB2IAAhkIhciHIAmAAIBHBvIBIhvIAlAAIhfCHIAABkgANPB2IAAjPIhOAAIAAgcIC9AAIAAAcIhPAAIAADPgAK7B2IAAjrIAfAAIAADrgAJkB2Ih9i5IAAC5IgeAAIAAjrIAhAAIB9C4IAAi4IAeAAIAADrgABMB2IAAjPIhMAAIAAgcIC6AAIAAAcIhPAAIAADPgAgwB2IgggxIgWghQgLgMgFgEQgGgDgJgDIgSgBIgkAAIAABpIgfAAIAAjrIBpAAQAfgBASAHQARAHAJAQQAKAQAAAUQAAAYgRATQgPAOgjAFQAMAGAHAGQAPAOALASIApBAgAi7gNIBEAAQAWABAMgFQAMgEAGgKQAHgJgBgMQAAgRgMgLQgLgLgbAAIhMAAgAq5B2IAAjrIBaAAQAWAAAOACQASADAMAIQALAIAHAPQAIAOAAASQgBAggSASQgUAVgyAAIg+AAIAABggAqagEIA+AAQAfAAANgMQAMgLAAgVQAAgPgIgKQgHgLgMgDQgHgCgWAAIg+AAgAuTB2IAAjrIBaAAQAXAAANACQASADAMAIQALAIAIAPQAHAPAAARQAAAfgUATQgTAVgyAAIg9AAIAABggAtzgEIA9AAQAeAAAOgMQANgLAAgVQgBgPgHgKQgJgLgLgDQgIgCgVAAIg9AAg");
	this.shape_1.setTransform(135.7,277.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AtCBXQgXANgcAAQgcAAgWgOQgXgNgMgZQgNgYAAgdQAAgeANgZQALgYAYgOQAXgNAcAAQAcAAAXAOQAWANANAZQAMAYAAAeQAAAYgIAUQgIAUgPAPQAQAMATAHIgIATQgWgHgWgSgAunhDQgUAWAAAoQAAAnAUAVQAUAVAfAAQAOABANgGQgMgIgPgEIAHgUQAYAIAPAMQAYgWAAgqQAAgZgJgSQgIgTgRgKQgPgKgVAAQgeAAgVAUgAP7BWQgZgNgMgYQgNgZAAgcQAAgdANgaQAMgaAYgNQAXgNAfAAQAYABARAGQARAIALAMQAKAMAFAWIgYAHQgEgPgIgKQgHgJgMgFQgOgFgPAAQgSgBgOAHQgNAFgJAJQgJALgEAJQgIAVAAAVQAAAZAKASQAJATASAJQATAJAUAAQASAAAQgHQARgGAJgIIAAgmIg9AAIAAgWIBXAAIAABJQgTARgWAIQgVAIgXAAQgfgBgYgNgAIXBcQgSgJgMgQQgKgQgBgVIAagCQACAQAGAKQAHAIAOAHQANAGASAAQARAAALgEQAMgFAGgIQAFgIAAgKQAAgJgFgIQgFgHgOgFQgKgEgagFQgbgFgNgGQgOgIgIgMQgHgKAAgPQAAgQAJgNQAJgOARgHQAPgGAWgBQAWABATAGQARAIAJAPQAKAOABARIgbACQgBgSgNgLQgLgKgZAAQgYAAgLAKQgMAIAAANQAAALAIAHQAIAIAhAHQAfAHAPAGQARAIAJALQAJANAAAQQAAARgKAOQgJAPgSAIQgQAIgXAAQgdAAgSgIgAFPBaQgTgLgHgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAFAMAMAHQAMAHASAAQAeAAAMgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgGATgTAMQgSAKgeABQgegBgRgJgAB1BVQgWgNgNgZQgLgYAAgZQAAgzAbgdQAcgdArAAQAdAAAWAOQAXANAMAZQAMAYAAAfQAAAbgMAaQgNAZgXANQgXANgbAAQgegBgWgOgAB4hEQgVAUAAAuQAAAlAUAUQAUAVAeAAQAeAAAUgVQAUgWAAgmQAAgYgIgTQgKgUgPgJQgRgKgUAAQgdAAgUATgArOBaQgSgLgIgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAGAMALAHQANAHARAAQAeAAANgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgHATgTAMQgRAKgfABQgdgBgSgJgAOGBgIhsifIAACfIgaAAIAAjLIAcAAIBsCfIAAifIAaAAIAADLgAK3BgIAAjLIAcAAIAADLgAALBgIAAhgIhpAAIAABgIgbAAIAAjLIAbAAIAABUIBpAAIAAhUIAbAAIAADLgAliBgIAAjLIAcAAIAACzIBlAAIAAAYgAmXBgIgYg+IhWAAIgWA+IgdAAIBPjLIAdAAIBUDLgAm3AMIgVg3IgPgrQgEAWgHARIgXA7IBGAAgAyGBgIAAjLICUAAIAAAYIh5AAIAAA/IByAAIAAAWIhyAAIAABGIB+AAIAAAYg");
	this.shape_2.setTransform(135.2,250.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,271.2,289.4);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.Close = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F78E1E").s().p("AgPARIAAghIAfAAIAAAhg");
	this.shape.setTransform(36.9,157.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F78E1E").s().p("AglBDIAAiCIAeAAIAAAdQAEgHADgGQAEgGAFgEQAGgFAHgCQAHgCAJAAIAAAgIgCAAQgKAAgIAEQgIADgGAGQgEAHgEAKQgDAIAAAMIAAAzg");
	this.shape_1.setTransform(30,152.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F78E1E").s().p("AgVA/QgMgEgKgJQgJgKgFgMIgEgOIgBgOIAAAAQgBgNAGgMQAEgMAJgKQAIgJAMgGIANgEIALgBQAIAAAHABQAHABAGADQAIAEALAMQAIAJAFAOQADANAAAMIAAAIIhfAAQABAIAEAGQADAGAFAFQAFAEAGACQAHADAFAAQAKAAAKgEQAHgEAJgIIASAQIgLAKQgGAEgGADQgHAEgIACQgIACgIAAQgMAAgNgGgAAigIQgBgHgDgGQgCgHgEgEQgFgFgFgDQgHgDgHAAQgFAAgGADQgGACgEAFQgEAFgDAGQgDAHgCAHIBDAAIAAAAg");
	this.shape_2.setTransform(17.7,152.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F78E1E").s().p("AAABTQgHgCgFgFQgFgEgDgHQgDgJAAgKIAAhDIgRAAIAAgaIARAAIAAglIAcAAIAAAlIAkAAIAAAaIgkAAIAAA+QAAAJAFAEQAEADAIABQAJgBAJgEIAAAZQgGADgGACQgHABgIABQgJAAgEgCg");
	this.shape_3.setTransform(5.8,150.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F78E1E").s().p("AgYA/QgTgIgIgGIANgVQAKAIAMAEQALAEAJAAQAJAAAGgEQAFgEAAgGIAAgBQAAgGgJgFQgFgCgNgFQgVgGgHgFQgHgEgDgGQgEgHAAgJIAAgBQAAgIAEgJQADgGAHgGQAGgFAJgDQAJgDAIAAQALAAANAEQANAFALAGIgMAWQgKgGgKgDQgJgDgIgBQgHAAgFAEQgFAEAAAGIAAAAQAAAGAJAFIATAHIAOAGIAOAFQAGAFADAGQAEAHAAAIIAAAAQAAALgEAHQgEAIgGAGQgHAFgJADQgJACgKAAQgMAAgPgFg");
	this.shape_4.setTransform(-4.5,152.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F78E1E").s().p("AgeBBQgIgDgGgFQgHgFgDgHQgFgJAAgJIAAAAQAAgLAFgIQAEgIAHgEQAHgGAKgCQAJgDAMAAQAOAAAUAGIAAgDQAAgGgBgGQgCgFgFgEQgEgDgGgCQgGgCgGAAQgLAAgJADQgIABgKAEIgIgYQAMgFALgDQANgDAMAAQAOAAAMAEQALADAHAIQAHAHADAKQAEAKAAAOIAABMIgeAAIAAgQQgHAJgKAFQgNAFgLAAQgJAAgJgDgAgLAGQgGABgEADQgDACgCAFQgCADgBAFIAAABQAAAIAIAGQAHAFALAAQAFAAAHgCQAGgCAFgEQAFgEADgFQACgFAAgFIAAgJQgTgEgLgBQgGAAgFACg");
	this.shape_5.setTransform(-17.3,152.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F78E1E").s().p("AgWBcIAAhoIgRAAIAAgaIARAAIAAgJQAAgLACgIQADgJAFgFQAFgFAHgDQAGgCAKgBQANABALADIAAAZQgJgDgIAAQgJABgEAEQgFAFAAAKIAAAHIAjAAIAAAaIgiAAIAABog");
	this.shape_6.setTransform(-27.7,149.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F78E1E").s().p("AgNBXQgJgBgKgDIgSgJIgQgNIATgVQAIAGARALIAOAEIAOABQAHAAAGgCQAFgBAEgDQAEgDADgDQACgFAAgFQAAgFgCgDQgCgEgEgEIgMgGIgSgFQgPgEgKgEQgLgEgHgDQgHgHgEgIQgEgJAAgLIAAgBQAAgLAEgJQAFgKAIgGQAIgHALgEQALgEAMAAQAIAAAJACIAQAEQALAEASANIgQAXQgMgJgMgEQgMgFgKgBQgGAAgGADQgFABgEADQgHAFAAAKIAAAAQAAAFACAEQABAEAFADQAFADAIACIASAHQAPADAKAFQAKAEAHAEQAHAFAEAJQADAIAAAKIAAABQAAAMgEALQgFAJgIAHQgIAGgMAEQgLAEgOgBQgIAAgKgCg");
	this.shape_7.setTransform(55,122.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F78E1E").s().p("AhABXIAAitIB/AAIAAAcIhhAAIAAAtIBWAAIAAAaIhWAAIAAAvIBjAAIAAAbg");
	this.shape_8.setTransform(40.3,122.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#F78E1E").s().p("AgOBXIAAhFIhFhoIAkAAIAvBNIAyhNIAjAAIhGBnIAABGg");
	this.shape_9.setTransform(23.5,122.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#F78E1E").s().p("AgNBDIgOgEQgMgFgKgJQgJgKgGgNIgDgMIgCgOIAAAAQAAgHAFgSQAGgMAKgKQAJgJAMgGIAOgEIANgBQAKgBASAGQAMAGAKAJQAJAJAGAMQAFASAAAIIAAAAIgCAOIgDAMQgGAMgJAKQgKAKgMAFQgTAFgJABgAgPglQgHACgGAHQgFAFgDAIQgDAHAAAIIAAAAQAAAIADAIQAEAIAFAGQAFAGAIADQAHADAHAAQAJAAAHgDQAIgDAFgGQAFgGADgIQACgHABgJIAAAAQgBgHgCgIQgDgHgFgGQgGgGgIgDQgHgEgIAAQgHAAgIAEg");
	this.shape_10.setTransform(0.9,124.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#F78E1E").s().p("AAABTQgHgDgFgDQgFgFgDgHQgDgIAAgLIAAhDIgRAAIAAgaIARAAIAAgkIAcAAIAAAkIAkAAIAAAaIgkAAIAAA+QAAAJAFAEQAEADAIABQAJgBAJgEIAAAZQgGAEgGABQgHABgIABQgJAAgEgCg");
	this.shape_11.setTransform(-11.6,122.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#F78E1E").s().p("AAABTQgHgDgFgDQgFgFgDgHQgDgIAAgLIAAhDIgRAAIAAgaIARAAIAAgkIAcAAIAAAkIAkAAIAAAaIgkAAIAAA+QAAAJAFAEQAEADAIABQAJgBAJgEIAAAZQgGAEgGABQgHABgIABQgJAAgEgCg");
	this.shape_12.setTransform(-27.4,122.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#F78E1E").s().p("AgWA/QgLgFgJgIQgKgKgFgMIgEgNIgBgPIAAAAQAAgMAEgNQAFgMAJgKQAJgJALgGIAMgEIANgBQAHAAAHABQAHABAGADQAHAEAMAMQAJAJADANQAFANAAANIgBAIIhfAAQABAIAEAHQADAFAFAFQAFAFAHACQAFACAGAAQALAAAIgEQAJgEAHgIIASAQIgKAKQgFAEgHADQgHAEgIACQgHACgKAAQgMAAgNgGgAAigIQgBgHgDgGQgDgHgEgFQgEgEgGgDQgFgDgIAAQgFAAgGADQgGADgEAEQgFAFgDAGQgDAHgBAHIBDAAIAAAAg");
	this.shape_13.setTransform(-38.9,124.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#F78E1E").s().p("AggBTQgQgEgMgHIALgXQALAHALADQAMAEANAAQAIAAAIgDQAHgCAGgGQAFgFADgHQADgIAAgKIAAgKQgMANgIAEQgFAEgHABQgGACgHAAQgLAAgLgEQgLgEgIgIQgJgIgFgMQgFgJAAgPIAAAAQAAgKAFgQQAFgLAJgJQAIgIALgEQALgEALAAQAHAAAGACQAHABAGAEQAKAFAJAKIAAgTIAeAAIAABnQAAAQgFANQgEAMgIAIIgKAIQgGAEgGACQgVAEgJAAQgRAAgOgEgAgNg6QgHADgGAFQgEAEgEAHQgDAHAAAIIAAAAQAAAIADAHQAEAHAEADQAGAEAHADQAGADAHAAQAHAAAHgDQAHgDAFgEQAGgDADgHQADgHAAgIIAAAAQAAgIgDgHQgDgGgGgFQgFgFgHgDQgHgDgHAAQgHAAgGADg");
	this.shape_14.setTransform(-54.1,126.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#F78E1E").s().p("AAdBDIAAhJQAAgHgCgHQgCgFgEgFQgEgEgFgCQgFgCgHgBQgEABgGACQgFACgEAFQgEAEgCAFQgDAHAAAIIAABIIgeAAIAAiCIAeAAIAAAVQAIgLAJgGIALgFQAEgCAIAAQALAAAJAEQAIAEAGAGQAGAGAEAKQADAJAAAMIAABSg");
	this.shape_15.setTransform(34.6,96.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#F78E1E").s().p("AgdBBQgJgDgHgFQgGgFgEgHQgDgJAAgJIAAAAQAAgLADgIQAEgIAIgEQAGgGAKgCQAKgDAMAAQAOAAAVAFIAAgCQAAgGgDgGQgBgFgFgDQgEgEgGgCQgGgCgGAAQgKAAgKACQgIACgJAEIgJgYQAMgGAKgCQANgDAOAAQAOAAALAEQAKADAIAIQAHAHAEAKQADALABANIAABMIgfAAIAAgQQgHAIgKAGQgNAFgKAAQgKAAgIgDgAgLAGQgGABgDADQgEADgDAEQgCADABAFIAAABQAAAIAHAGQAHAFALAAQAFAAAHgCQAGgCAFgDQAFgEACgFQADgFAAgGIAAgIQgSgGgMAAQgFABgGABg");
	this.shape_16.setTransform(20.1,96.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#F78E1E").s().p("AgFBDIgOgEQgMgFgJgJQgJgKgFgNQgGgMAAgOIAAAAQAAgMAGgNQAFgMAJgKQAJgJANgGIANgEIAMgCQAJABAIACQAIABAGADQAJAEANAMIgTAUQgIgHgHgEQgJgFgKAAQgHAAgGAEQgHADgGAGQgFAFgCAIQgDAHAAAIIAAAAQAAAIADAIQACAIAGAGQAFAFAHAEQAGADAIABQAKAAAJgGQAIgDAHgJIATATQgOANgIAEQgHAEgIACQgIACgJAAg");
	this.shape_17.setTransform(7.1,96.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#F78E1E").s().p("AgVA/QgMgFgKgIQgJgJgFgNIgEgNIgCgPIAAAAQAAgMAGgNQAEgMAJgKQAIgJANgGIAMgEIALgCQAIAAAHACQAHABAGADQAIAEAMAMQAHAJAEANQAEANAAANIAAAIIhfAAQABAIADAHQAEAFAFAFQAFAFAGACQAHACAFAAQAKAAAJgEQAJgEAIgIIASAQIgLAKQgGAFgGACQgHAEgHACQgJACgIAAQgMAAgNgGgAAhgIQAAgHgDgGQgDgHgEgFQgEgEgFgDQgHgCgHgBQgFABgGACQgFACgFAFQgFAFgDAGQgCAHgBAHIBBAAIAAAAg");
	this.shape_18.setTransform(-13.2,96.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#F78E1E").s().p("AAdBCIgdhYIgcBYIgbAAIgriDIAfAAIAaBZIAdhZIAYAAIAeBZIAbhZIAeAAIgrCDg");
	this.shape_19.setTransform(-30.5,96.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#F78E1E").s().p("AgTAWQALgDAGgFQADgGgBgIIgLAAIAAgiIAfAAIAAAeQAAAIgDAHQgBAIgGAEQgEAGgGACQgHADgKABg");
	this.shape_20.setTransform(69.9,76.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#F78E1E").s().p("AglBDIAAiCIAeAAIAAAdQAEgHADgGQAEgGAFgEQAGgFAHgCQAHgCAJAAIAAAgIgCAAQgKAAgIAEQgJADgFAGQgEAHgEAKQgDAIAAAMIAAAzg");
	this.shape_21.setTransform(63.4,69.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#F78E1E").s().p("AgVA/QgMgFgKgIQgJgJgFgNIgEgNIgCgPIAAAAQAAgMAGgNQAEgMAJgKQAJgJALgGIANgEIALgCQAIAAAHACQAHABAGADQAHAEANAMQAIAJAEANQADANAAANIAAAIIhfAAQABAIADAHQAEAFAFAFQAFAFAGACQAHACAFAAQAKAAAKgEQAHgEAJgIIASAQIgLAKQgFAFgHACQgHAEgHACQgJACgIAAQgMAAgNgGgAAigIQgBgHgDgGQgDgHgDgFQgFgEgFgDQgHgCgHgBQgFABgGACQgFACgFAFQgEAFgDAGQgDAHgCAHIBDAAIAAAAg");
	this.shape_22.setTransform(51.1,69.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#F78E1E").s().p("AgcBXQgLgEgJgJQgIgJgFgMIgFgOIgBgQIAAAAQAAgLAGgQQAEgNAJgJQAJgIAKgFQALgFAMAAQAHAAAHACQAGACAFAEQAKAFAIALIAAhHIAfAAIAAC0IgfAAIAAgWQgIAMgKAGIgLAFQgHACgHAAQgLAAgLgFgAgNgOQgHADgFAFQgFAGgDAFQgDAIAAAKIAAAAQAAAKADAIQADAHAFAGQAGAGAGADQAHADAGAAQAHAAAHgDQAHgDAGgGQAFgGADgHQADgIAAgKIAAAAQAAgJgDgIQgDgGgFgGQgGgFgHgDQgHgDgHAAQgGAAgHADg");
	this.shape_23.setTransform(35.8,67);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#F78E1E").s().p("AAdBDIAAhJQAAgHgCgHQgCgFgEgFQgEgEgFgCQgFgCgHgBQgEABgGACQgFACgEAFQgEAEgCAFQgDAHAAAIIAABIIgeAAIAAiCIAeAAIAAAVQAIgLAJgGIALgFQAEgCAIAAQALAAAJAEQAIAEAGAGQAGAGAEAKQADAJAAAMIAABSg");
	this.shape_24.setTransform(21.1,69.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#F78E1E").s().p("AgVA/QgNgFgIgIQgKgJgFgNIgEgNIgCgPIAAAAQABgMAFgNQAEgMAJgKQAJgJAMgGIAMgEIAMgCQAHAAAHACQAHABAGADQAIAEAMAMQAHAJAEANQAEANABANIgBAIIhfAAQABAIADAHQAEAFAFAFQAFAFAGACQAHACAFAAQAKAAAJgEQAJgEAIgIIASAQIgLAKQgGAFgGACQgHAEgHACQgIACgJAAQgMAAgNgGgAAhgIQAAgHgDgGQgDgHgEgFQgEgEgGgDQgFgCgIgBQgFABgGACQgFACgFAFQgFAFgDAGQgCAHgBAHIBBAAIAAAAg");
	this.shape_25.setTransform(6.7,69.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#F78E1E").s().p("Ag8BXIAAitIAfAAIAACRIBaAAIAAAcg");
	this.shape_26.setTransform(-6.9,67.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#F78E1E").s().p("AA6BYIgRgqIhRAAIgSAqIggAAIBNivIAbAAIBNCvgAAdASIgdhEIgdBEIA6AAg");
	this.shape_27.setTransform(-30.7,67.2);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#F78E1E").s().p("AhHBXIAAitIBMAAQAPAAAMAEQALAEAIAHQAGAHADAHQADAHAAAIIAAABQAAAIgCAGQgCAGgEAFQgGAIgLAGQAIACAGADQAGADAFAFQAFAFACAHQACAHAAAJIAAAAQAAALgEAKQgFAJgIAGQgJAGgMADQgMADgOAAgAgpA8IAxAAQAIAAAGgCQAGgCAFgDQAEgDACgEQADgEAAgHIAAAAQAAgGgCgEQgDgEgEgDQgFgDgGgBQgHgCgJAAIgvAAgAgpgMIApAAQAGAAAHgBQAGgCAEgDQAEgDADgFQACgEAAgGIAAAAQAAgFgCgFQgCgEgEgDQgEgDgGgBQgFgBgIAAIgqAAg");
	this.shape_28.setTransform(-48.1,67.3);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#F78E1E").s().p("AgNBXQgJgBgKgEIgSgIIgQgNIATgVQAIAGARALIAOAEIAOABQAHAAAGgCQAFgBAEgDQAEgCADgEQACgFAAgFQAAgFgCgDQgCgFgEgCIgMgHIgSgFQgPgEgKgDQgLgFgHgDQgHgHgEgIQgEgIAAgMIAAAAQAAgMAEgJQAFgKAIgGQAIgHALgEQALgDAMgBQAIABAJABIAQAEQALAEASANIgQAXQgMgJgMgEQgMgGgKAAQgGAAgGACQgFACgEADQgHAGAAAJIAAAAQAAAFACAEQABAEAFADQAFADAIACIASAHQAPADAKAFQAKAEAHAEQAHAFAEAJQADAIAAAKIAAABQAAAMgEALQgFAJgIAHQgIAGgMAEQgLAEgOgBQgIAAgKgCg");
	this.shape_29.setTransform(-64.8,67.3);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#F78E1E").s().p("AgcBXQgLgEgJgJQgJgJgEgMIgFgOIgBgQIAAAAQAAgLAGgQQAEgNAJgJQAIgIALgFQAMgFAMAAQAFAAAHACQAHACAGAEQAKAFAIALIAAhHIAeAAIAAC0IgeAAIAAgWQgIAMgKAGIgNAFQgHACgFAAQgMAAgLgFgAgNgOQgHADgFAFQgFAGgDAFQgEAIAAAKIAAAAQAAAKAEAIQADAHAFAGQAGAGAGADQAHADAGAAQAHAAAHgDQAHgDAGgGQAFgGADgHQADgIAAgKIAAAAQAAgJgDgIQgDgGgFgGQgGgFgHgDQgHgDgHAAQgGAAgHADg");
	this.shape_30.setTransform(47.3,40);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#F78E1E").s().p("AgVA/QgMgFgKgIQgJgJgFgNIgEgNIgCgPIAAAAQAAgMAGgNQAEgMAJgKQAIgJANgGIAMgEIALgCQAIAAAHACQAHABAGADQAIAEAMAMQAHAJAFANQADANAAANIAAAIIhfAAQABAIADAHQAEAFAFAFQAFAFAGACQAHACAFAAQAKAAAJgEQAJgEAIgIIASAQIgLAKQgGAFgGACQgHAEgHACQgJACgIAAQgMAAgNgGgAAhgIQAAgHgDgGQgDgHgEgFQgEgEgFgDQgHgCgHgBQgFABgGACQgFACgFAFQgFAFgDAGQgCAHgBAHIBBAAIAAAAg");
	this.shape_31.setTransform(32.7,42.4);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#F78E1E").s().p("AglBDIAAiCIAeAAIAAAdQAEgHADgGQAEgGAFgEQAGgFAHgCQAIgCAIAAIAAAgIgCAAQgKAAgIAEQgJADgFAGQgEAHgEAKQgDAIAAAMIAAAzg");
	this.shape_32.setTransform(21.6,42.3);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#F78E1E").s().p("AglBDIAAiCIAeAAIAAAdQADgHAEgGQADgGAGgEQAGgFAHgCQAIgCAIAAIAAAgIgCAAQgKAAgIAEQgIADgGAGQgEAHgEAKQgDAIAAAMIAAAzg");
	this.shape_33.setTransform(12.3,42.3);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#F78E1E").s().p("AgWA/QgLgFgKgIQgJgJgFgNIgEgNIgBgPIAAAAQAAgMAEgNQAFgMAJgKQAIgJAMgGIANgEIALgCQAIAAAHACQAHABAGADQAHAEAMAMQAIAJAFANQADANAAANIAAAIIhfAAQABAIAEAHQADAFAFAFQAFAFAGACQAGACAGAAQALAAAJgEQAHgEAIgIIASAQIgKAKQgGAFgGACQgHAEgIACQgHACgKAAQgMAAgNgGgAAigIQgBgHgDgGQgCgHgEgFQgFgEgFgDQgHgCgHgBQgFABgGACQgGACgEAFQgEAFgDAGQgEAHgBAHIBDAAIAAAAg");
	this.shape_34.setTransform(0,42.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#F78E1E").s().p("AgWBbIAAhnIgRAAIAAgZIARAAIAAgKQAAgLACgIQADgJAFgFQAFgFAHgDQAGgCAKAAQANAAALADIAAAZQgJgCgIAAQgJAAgEAEQgFAFAAAKIAAAIIAjAAIAAAZIgiAAIAABng");
	this.shape_35.setTransform(-11,39.8);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#F78E1E").s().p("AgWA/QgLgFgKgIQgJgJgFgNIgEgNIgBgPIAAAAQAAgMAEgNQAFgMAJgKQAIgJAMgGIANgEIALgCQAIAAAHACQAHABAGADQAHAEAMAMQAIAJAFANQADANAAANIAAAIIhfAAQABAIAEAHQADAFAFAFQAFAFAGACQAGACAGAAQALAAAJgEQAHgEAIgIIASAQIgKAKQgGAFgGACQgHAEgIACQgHACgKAAQgMAAgNgGgAAigIQgBgHgDgGQgCgHgEgFQgFgEgFgDQgHgCgHgBQgFABgGACQgGACgEAFQgEAFgDAGQgEAHgBAHIBDAAIAAAAg");
	this.shape_36.setTransform(-22.5,42.4);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#F78E1E").s().p("AglBDIAAiCIAeAAIAAAdQADgHAEgGQADgGAGgEQAGgFAHgCQAHgCAJAAIAAAgIgCAAQgKAAgIAEQgIADgGAGQgEAHgEAKQgDAIAAAMIAAAzg");
	this.shape_37.setTransform(-33.6,42.3);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#F78E1E").s().p("AhCBXIAAitIBDAAQAPAAAMAEQAMAFAJAHQAJAIAFAKQAEALAAANIAAABIgBAOIgEAMQgGAJgJAHQgKAIgNAEQgMAEgNAAIgjAAIAAA4gAgkADIAkAAQAHAAAHgDQAHAAAFgEQAFgEACgFQADgHAAgGIAAgBQAAgHgDgGQgCgGgFgEQgFgEgHgCQgHgCgHAAIgkAAg");
	this.shape_38.setTransform(-46,40.3);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#F78E1E").s().p("AgdBBQgJgDgHgFQgGgFgDgHQgEgJgBgJIAAAAQABgLAEgIQADgIAIgEQAGgGAKgCQALgDALAAQAOAAAUAFIAAgCQAAgGgCgGQgCgFgEgDQgEgEgGgCQgGgCgGAAQgKAAgKACQgIACgJAEIgJgYQAMgGAKgCQANgDANAAQAOAAAMAEQAKADAIAIQAHAHADAKQAFALAAANIAABMIgfAAIAAgQQgHAIgKAGQgOAFgJAAQgKAAgIgDgAgLAGQgFABgEADQgFADgCAEQgBADAAAFIAAABQAAAIAHAGQAHAFALAAQAGAAAGgCQAHgCAEgDQAFgEACgFQADgFAAgGIAAgIQgSgGgMAAQgFABgGABg");
	this.shape_39.setTransform(18.6,15.5);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#F78E1E").s().p("AgYA/QgTgIgIgGIANgVQALAHALAFQALAEAJAAQAJAAAFgEQAGgDAAgIIAAAAQAAgHgJgEQgEgDgOgFQgVgGgIgEQgGgEgDgGQgDgHgBgJIAAgBQABgJADgIQAEgGAGgGQAGgFAJgDQAIgDAIAAQAMAAANAEQANAEALAHIgMAWQgKgGgKgDQgKgEgHAAQgHABgFADQgFADAAAHIAAAAQAAAHAJAEIATAIIAOAEIANAGQAHAFADAGQAEAGAAAJIAAAAQAAALgEAHQgDAIgIAGQgGAFgJACQgJADgLAAQgMAAgOgFg");
	this.shape_40.setTransform(-0.3,15.4);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#F78E1E").s().p("AA6BYIgRgqIhRAAIgSAqIggAAIBNivIAbAAIBNCvgAAdASIgdhEIgdBEIA6AAg");
	this.shape_41.setTransform(-15.3,13.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,0,160,166);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border160x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("EgMVgutIYrAAMAAABdbI4rAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,-300,160,600);


(lib._2016_SCU_tagvertai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACAATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgACJgKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgGgFgEQgEgFgHAAQgHAAgEAFgAizATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAiqgKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgGgFgEQgEgFgHAAQgHAAgEAFgAm4ATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgAmwgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgGgEgEQgFgFgHAAQgGAAgFAFgAC5ADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAl/ADIAAgcIALAAIAAAcQAAANAMAAQALAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgWAAAAgXgAHpAaIAAgMIAMAAIAAAMgAHOAaIAAgVIgUgeIANAAIANAVIAMgVIANAAIgUAeIAAAVgAGzAaIgFgMIgWAAIgEAMIgMAAIAWgzIALAAIAWAzgAGqAEIgHgPIgHAPIAOAAgAFvAaIgMggIgMAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIAMAiIAKgiIAMAAIgRAzgAESAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAD+AAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgABYAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAAcAaIAAgMIAMAAIAAAMgAABAaIAAgVIgSgeIANAAIALAVIAMgVIANAAIgUAeIAAAVgAg+AaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgAhUAaIgaggIAAAgIgLAAIAAgzIALAAIAYAfIAAgfIALAAIAAAzgAjRAaIAAghIgOAVIgBAAIgOgUIAAAgIgLAAIAAgzIAMAAIAOAWIANgWIANAAIAAAzgAkmAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAFAGQAFAEAAAIQAAAKgLAEIAMATgAk6AAIALAAQAJAAAAgHQAAgHgJAAIgLAAgAngAaIAAgVIgUgeIANAAIANAVIAMgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(50.2,12.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AkLADIAAgcIALAAIAAAcQAAANAMAAQALAAAAgNIAAgcIALAAIAAAcQAAAYgWAAQgXAAAAgYgAlEATQgIgIAAgLQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKIAAAAQAAALgHAIQgIAIgMAAQgMAAgIgIgAk8gKQgEAEAAAGIAAAAQAAAHAEAEQAFAFAHAAQAHAAAEgFQAEgEAAgHQAAgFgEgFQgFgFgGAAQgHAAgFAFgADHASIAHgIQAHAGAIAAQAIAAAAgFQAAgEgLgCQgJgDgDgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAIAAQAMAAAIAGIgGAJQgIgFgGAAQgHAAAAAEIAAABQAAAEAMACQAQAEAAAKQAAAQgTAAQgNAAgJgIgAF1AaIAAgMIAMAAIAAAMgAFMAaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAGQgGAEgJAAIgJAAIAAAQgAFYAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAE0AaIAAgzIALAAIAAAzgAEbAaIAAgVIgVAAIAAAVIgMAAIAAgzIAMAAIAAAVIAVAAIAAgVIAMAAIAAAzgAC0AaIgLgRIgJAAIAAARIgLAAIAAgzIAXAAQAKAAAGAGQAEAEAAAIQAAAKgLAEIANATgACgAAIAMAAQAJAAAAgHQAAgHgKAAIgLAAgABiAaIAAgzIAoAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAAtAaIAAgzIAYAAQAIAAAFAFQAEADAAAGIAAAAQAAAHgHAEQAKACAAAJQAAAPgUAAgAA4AQIANAAQAJAAAAgGQAAgGgJAAIgNAAgAA4gDIAKAAQAJAAAAgGIAAAAQAAgGgIAAIgLAAgAAUAaIAAggIgOAUIgBAAIgMgUIAAAgIgLAAIAAgzIAMAAIAMAXIAOgXIAMAAIAAAzgAhEAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAhcAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAXIAOgXIAMAAIAAAzgAiyAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAFAGQAFAEAAAIQAAAKgLAEIAMATgAjGAAIALAAQAJAAAAgHQAAgHgJAAIgLAAgAlsAaIAAgVIgUgeIANAAIANAVIAMgVIAOAAIgVAeIAAAVg");
	this.shape_1.setTransform(50.2,2.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,100.4,14.9);


(lib._2016_SCU_logoruleTHICKai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F78E1E").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0,1,2.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,-1,162.9,2);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib._2016_SCU_BBSvertai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AmFBLIAAiVIMLAAIAACVg");
	mask.setTransform(39,7.6);

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AFbAUQgIgJAAgLQAAgKAIgIQAHgIAMAAQAOAAAHAHIgHAJQgFgFgJAAQgHAAgDAFQgFAEAAAGQAAAHAFAFQAEAEAHAAQAGAAAFgDIAAgIIgMAAIAAgIIAYAAIAAAWQgLAIgNAAQgMAAgHgHgAgvATIAHgJQAHAHAIgBQAIAAAAgEQAAgEgLgEQgJgBgDgDQgGgCAAgIIAAAAQABgHAFgFQAFgEAIAAQALAAAJAHIgGAIQgIgEgGAAQgHgBAAAFQAAAEAMADQAQAEABAKIAAABQgBAQgTAAQgMAAgKgIgAhfATIAGgJQAJAHAHgBQAIAAAAgEQAAgEgKgEQgKgBgDgDQgFgCAAgIIAAAAQAAgHAFgFQAFgEAJAAQALAAAIAHIgGAIQgIgEgFAAQgIgBAAAFQAAAEAMADQARAEAAAKIAAABQAAAQgUAAQgMAAgKgIgAkYATIAHgJQAIAHAIgBQAHAAAAgEQAAgEgLgEQgIgBgEgDQgFgCAAgIIAAAAQAAgHAGgFQAFgEAHAAQAMAAAJAHIgGAIQgJgEgGAAQgGgBAAAFQgBAEAMADQARAEAAAKIAAABQAAAQgTAAQgNAAgKgIgAlOADIAAgcIALAAIAAAcQAAANAMAAQALAAAAgNIAAgcIALAAIAAAcQAAAYgWAAQgXAAAAgYgAE/AaIgaggIAAAgIgMAAIAAgzIALAAIAZAeIAAgeIAMAAIAAAzgAEAAaIAAgzIAMAAIAAAzgADqAaIgQgXIgGAHIAAAQIgLAAIAAgzIALAAIAAAXIAVgXIAPAAIgWAWIAXAdgACxAaIgZggIAAAgIgMAAIAAgzIALAAIAZAeIAAgeIALAAIAAAzgAB4AaIgFgMIgWAAIgGAMIgLAAIAWgzIAMAAIAWAzgABvAEIgHgQIgIAQIAPAAgAAZAaIAAgzIAZAAQAKAAAEAEQAEAEAAAFIAAABQAAAHgHAEQAJACAAAKQAAAOgTAAgAAlAQIAOAAQAIAAAAgGQAAgGgJAAIgNAAgAAlgEIALAAQAIAAAAgFIAAgBQAAgFgHAAIgMAAgAiPAaIAAgzIApAAIAAALIgdAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgAilAaIgaggIAAAgIgLAAIAAgzIALAAIAZAeIAAgeIALAAIAAAzgAjjAaIAAgzIALAAIAAAzgAmFAaIAAgzIAZAAQAJAAAFAEQAEAEAAAFIAAABQgBAHgGAEQAKACgBAKQAAAOgTAAgAl6AQIAPAAQAIAAAAgGQAAgGgIAAIgPAAgAl6gEIALAAQAJAAAAgFIAAgBQAAgFgHAAIgNAAg");
	this.shape.setTransform(39,2.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACVASIAHgIQAIAGAJAAQAHAAAAgEQAAgFgKgCQgKgDgEgCQgEgCAAgHIAAgBQgBgHAGgEQAFgFAJAAQAKAAAJAHIgGAJQgHgGgHAAQgGAAAAAFIAAABQAAAAAAABQAAAAAAABQAAAAABABQAAAAAAAAIAKAEQAQADAAAKQABARgUAAQgNAAgKgJgAA0ATQgIgIAAgLQAAgKAIgIQAIgIAMAAQAMAAAIAIIgHAJQgGgGgHAAQgHAAgFAFQgEAFAAAFQAAAHAEAFQAFAEAHAAQAHAAAGgGIAIAHQgIAKgNAAQgMAAgIgIgAi/ASIAHgIQAIAGAJAAQAHAAAAgEQAAgFgKgCQgKgDgEgCQgEgCAAgHIAAgBQgBgHAGgEQAFgFAJAAQAKAAAJAHIgGAJQgIgGgGAAQgGAAAAAFIAAABQgBADALAEQARADABAKQgBAIgFAFQgFAEgJAAQgNAAgKgJgAgRAaIgWgzIAOAAIANAjIAMgjIAMAAIgTAzgABmAaIAAgzIApAAIAAAKIgdAAIAAALIAZAAIAAAJIgZAAIAAAKIAdAAIAAALgAAVAaIAAgzIAMAAIAAAzgAg3AaIgMgRIgJAAIAAARIgLAAIAAgzIAYAAQAKAAAFAGQAFAEAAAHQAAALgMAEIAOATgAhMAAIAMAAQAJAAAAgHIAAAAQAAgIgJAAIgMAAgAiKAaIAAgzIAoAAIAAAKIgdAAIAAALIAZAAIAAAJIgZAAIAAAKIAdAAIAAALg");
	this.shape_1.setTransform(38.9,12.4);

	this.shape.mask = this.shape_1.mask = mask;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,78,15.1);


(lib._2016TAGvert = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._2016_SCU_tagvertai();
	this.instance.setTransform(-0.1,7.5,1,1,0,0,0,50.1,7.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-50.2,0,100.4,14.9);


// stage content:
(lib.SCU201609_Air_160x600_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_177 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(177).call(this.frame_177).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.setTransform(142,448,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(177).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.setTransform(0,0,0.476,2.143);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},178).wait(1));

	// ncua
	this.instance = new lib.ncuahorizai();
	this.instance.setTransform(80,587.9,1.35,1.35,0,0,0,0,3.6);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(177).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_1 = new lib.border160x600();
	this.instance_1.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({_off:true},178).wait(1));

	// PIC1
	this.instance_2 = new lib._336x280air();
	this.instance_2.setTransform(-56,1,0.743,0.743);

	this.instance_3 = new lib.Tween5("synched",0);
	this.instance_3.setTransform(68.9,84.3);
	this.instance_3._off = true;

	this.instance_4 = new lib.Tween6("synched",0);
	this.instance_4.setTransform(68.9,65.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2}]}).to({state:[{t:this.instance_3}]},169).to({state:[{t:this.instance_4}]},8).to({state:[]},1).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(169).to({_off:false},0).to({_off:true,y:65.3},8).wait(2));

	// PIC2
	this.instance_5 = new lib.Tween1("synched",0);
	this.instance_5.setTransform(80,98);
	this.instance_5._off = true;

	this.instance_6 = new lib.Tween2("synched",0);
	this.instance_6.setTransform(80,237.5);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(39).to({_off:false},0).to({_off:true,y:237.5},7).wait(133));
	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(39).to({_off:false},7).wait(123).to({startPosition:0},0).to({y:201.5},8).to({_off:true},1).wait(1));

	// pic shad
	this.instance_7 = new lib.HTML5rastershad_1();
	this.instance_7.setTransform(80,176.5,1,1,0,0,0,0,10);
	this.instance_7.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(39).to({y:177.5},0).to({y:317},7).wait(123).to({y:281},8).to({_off:true},1).wait(1));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("AubHKIAAuTIc3AAIAAOTg");
	var mask_graphics_39 = new cjs.Graphics().p("AubHQIAAufIc3AAIAAOfg");
	var mask_graphics_40 = new cjs.Graphics().p("AubHKIAAuTIc3AAIAAOTg");
	var mask_graphics_41 = new cjs.Graphics().p("AubHEIAAuHIc3AAIAAOHg");
	var mask_graphics_42 = new cjs.Graphics().p("AubG9IAAt5Ic3AAIAAN5g");
	var mask_graphics_43 = new cjs.Graphics().p("AubG3IAAttIc3AAIAANtg");
	var mask_graphics_44 = new cjs.Graphics().p("AubGwIAAtfIc3AAIAANfg");
	var mask_graphics_45 = new cjs.Graphics().p("AubGqIAAtTIc3AAIAANTg");
	var mask_graphics_46 = new cjs.Graphics().p("AubGkIAAtHIc3AAIAANHg");
	var mask_graphics_88 = new cjs.Graphics().p("AtLLjIAA3FIaXAAIAAXFg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:81.5,y:238}).wait(39).to({graphics:mask_graphics_39,x:81.5,y:238.4}).wait(1).to({graphics:mask_graphics_40,x:81.5,y:255.9}).wait(1).to({graphics:mask_graphics_41,x:81.5,y:273.4}).wait(1).to({graphics:mask_graphics_42,x:81.5,y:290.9}).wait(1).to({graphics:mask_graphics_43,x:81.5,y:308.4}).wait(1).to({graphics:mask_graphics_44,x:81.5,y:325.9}).wait(1).to({graphics:mask_graphics_45,x:81.5,y:343.4}).wait(1).to({graphics:mask_graphics_46,x:81.5,y:360.9}).wait(1).to({graphics:null,x:0,y:0}).wait(41).to({graphics:mask_graphics_88,x:80.5,y:392}).wait(8).to({graphics:null,x:0,y:0}).wait(83));

	// HEAD
	this.instance_8 = new lib.HEAD1();
	this.instance_8.setTransform(199.5,236,1,1,0,0,0,119.5,27);

	this.instance_8.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(39).to({y:354},7).wait(42).to({y:493},7).to({_off:true},1).wait(83));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_169 = new cjs.Graphics().p("AuMLeIAA28IcaAAIAAW8g");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(169).to({graphics:mask_1_graphics_169,x:80,y:393.5}).wait(9).to({graphics:null,x:0,y:0}).wait(1));

	// HEAD2
	this.instance_9 = new lib.HEAD2();
	this.instance_9.setTransform(78.5,233.9,1,1,0,0,0,-1.5,31.9);
	this.instance_9._off = true;

	this.instance_9.mask = mask_1;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(88).to({_off:false},0).to({y:365.9},7).wait(74).to({y:501.9},8).to({_off:true},1).wait(1));

	// Close
	this.instance_10 = new lib.Close();
	this.instance_10.setTransform(80,213,1,1,0,0,0,0,54);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(169).to({_off:false},0).to({y:342},8).to({_off:true},1).wait(1));

	// head bkgd
	this.instance_11 = new lib.headbkgd();
	this.instance_11.setTransform(168,124.8,1,0.891,0,0,0,168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({_off:true},178).wait(1));

	// tag
	this.instance_12 = new lib._2016TAGvert();
	this.instance_12.setTransform(80.1,536.9,1.35,1.35,0,0,0,0,2.6);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(177).to({_off:false},0).to({_off:true},1).wait(1));

	// BBS
	this.instance_13 = new lib._2016_SCU_BBSvertai();
	this.instance_13.setTransform(80.3,544.6,1.511,1.511,0,0,0,39.1,7.7);
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(88).to({_off:false},0).to({_off:true},89).wait(2));

	// logo
	this.instance_14 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_14.setTransform(272.9,540.1,0.897,0.897,0,0,0,215.2,63.1);
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(88).to({_off:false},0).to({_off:true},90).wait(1));

	// logo rule
	this.instance_15 = new lib._2016_SCU_logoruleTHICKai();
	this.instance_15.setTransform(155.6,525.9,0.927,0.927,0,0,0,81.5,0.5);
	this.instance_15._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(88).to({_off:false},0).to({_off:true},90).wait(1));

	// shad
	this.instance_16 = new lib.HTML5rastershad_1();
	this.instance_16.setTransform(61.1,476.9,1,1,0,0,0,0,10);
	this.instance_16.alpha = 0.301;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).to({_off:true},178).wait(1));

	// logo box
	this.instance_17 = new lib.box1();
	this.instance_17.setTransform(71.2,197.4,0.475,4.282,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_17).to({_off:true},178).wait(1));

	// EHO
	this.instance_18 = new lib.EqualHousingOpportunityrevai("synched",0);
	this.instance_18.setTransform(14.1,454,0.07,0.07,0,0,0,135,145);
	this.instance_18._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(177).to({_off:false},0).to({_off:true},1).wait(1));

	// com
	this.instance_19 = new lib.comhoriz();
	this.instance_19.setTransform(80.1,585.7,0.8,0.8,0,0,0,0.1,0.9);
	this.instance_19._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_19).wait(177).to({_off:false},0).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-26.9,300,355,600);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;