(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 728,
	height: 90,
	fps: 18,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/HTML5rastershad.png", id:"HTML5rastershad"},
		{src:"images/SCU201609_Elec_728x90_AdR_atlas_NP_.jpg", id:"SCU201609_Elec_728x90_AdR_atlas_NP_"}
	]
};



lib.ssMetadata = [
		{name:"SCU201609_Elec_728x90_AdR_atlas_NP_", frames: [[0,0,336,224],[338,0,168,140]]}
];


lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib._336x280elec = function() {
	this.spriteSheet = ss["SCU201609_Elec_728x90_AdR_atlas_NP_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib._336x280retail = function() {
	this.spriteSheet = ss["SCU201609_Elec_728x90_AdR_atlas_NP_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.Tween15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._336x280retail();
	this.instance.setTransform(-55,-45.8,0.655,0.655);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55,-45.8,110.1,91.7);


(lib.Tween14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._336x280retail();
	this.instance.setTransform(-55,-45.8,0.655,0.655);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55,-45.8,110.1,91.7);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#3F3F3F").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.pic = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._336x280elec();
	this.instance.setTransform(-109,-72,0.65,0.65);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-109,-72,218.5,145.7);


(lib.ncuahorizai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACPAmIADgGQADACAEAAQAGAAADgJIgUgsIAHAAIARAlIAPglIAHAAIgTAuQgFANgLAAQgFAAgFgCgAAwAXQgFgFAAgGQAAgIAFgEQAGgCAJAAQAFAAAKACIAAgBQAAgNgPAAQgGAAgHAEIgDgGQAJgEAIAAQAKAAAGAFQAEAFAAAJIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgFgDgAAyALQAAAKAMAAQAGAAAFgEQAFgDAAgGIAAgEQgIgCgGAAQgOAAAAAJgAgjAUQgHgHAAgLQABgIAGgHQAGgHAKAAQAJAAAHAHQADAHAAAIIAAADIgjAAQABAHAFAEQAEAEAHAAQAIAAAGgGIAEAEQgHAIgLAAQgKAAgHgGgAgFAAQgBgOgNAAQgHAAgDAEQgFAEgBAGIAeAAIAAAAgAhfAUQgGgHAAgLQAAgJAGgHQAHgGAJAAQAKAAAIAKIAAgcIAHAAIAAA/IgHAAIAAgJQgHAKgLAAQgJAAgHgGgAhZgJQgFAFAAAGIAAAAQAAAIAFAFQAFAFAGAAQAHAAAFgFQAFgFAAgIIAAAAQAAgGgFgFQgFgFgHAAQgHAAgEAFgAiUAUQgHgHABgLQAAgIAFgHQAHgHAJAAQALAAAGAHQAGAHAAAIIgBADIglAAQACAPAOAAQAJAAAHgGIADAEQgHAIgMAAQgKAAgGgGgAh1AAQgCgOgOAAQgFAAgFAEQgDAEgCAGIAfAAIAAAAgAB7AZIAAg/IAHAAIAAA/gABjAZIAAg/IAIAAIAAA/gAAMAZIAAgsIAHAAIAAAMQAHgNAMAAIAAAHIAAAAQgIAAgFAGQgFAGgBAIIAAASgAi1AZIAAgmIgHAAIAAgGIAHAAIAAgEQAAgIADgEQAFgEAFAAIAIABIAAAGIgHgBQgHAAgBAKIAAAEIAPAAIAAAGIgPAAIAAAmg");
	this.shape.setTransform(-36.4,4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AA+AlIADgFQADABAEABQAGAAADgJIgUgsIAHAAIARAkIAPgkIAHAAIgTAtQgFANgLAAQgGAAgEgCgAE2AXQgGgFAAgHQAAgNAUAAQAFAAAKACIAAgBQgBgNgOAAQgGAAgHAEIgDgGQAIgEAJAAQALAAAEAFQAFAEAAAKIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgEgDgAE3ALQAAAJAMAAQAGABAFgEQAEgDABgGIAAgFQgIgCgGAAQgOAAAAAKgAD7AIIAAgbIAIAAIAAAZQgBAOANAAQAHAAADgEQAFgEAAgHIAAgYIAGAAIAAAsIgGAAIAAgIQgHAJgKAAQgRAAgBgSgADNATQgHgHAAgKQAAgIAHgIQAHgGAKAAQAKgBAJAJIgFAEQgIgHgGAAQgIABgEAFQgFAFAAAFIAAABQAAAHAFAGQAFAFAHAAQAIAAAGgHIAFAEQgIAJgLAAQgKAAgHgHgAAPAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgLALABQAIgBAGAHQAIAHgBAIIAAABQABALgIAGQgGAHgIAAQgMAAgGgKgAATgJQgEAFAAAFIAAABQAAAHAEAGQAGAFAGAAQAHAAAFgFQAEgFAAgIQAAgGgEgFQgFgFgHAAQgGAAgGAFgAhJATQgHgGAAgLQAAgJAHgHQAHgHAJABQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgHgAhEgJQgEAFAAAFIAAABQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgGABgHIAAgBQgBgFgFgFQgEgFgHAAQgIAAgEAFgAh+ATQgHgGAAgLQAAgIAGgIQAGgGAKAAQAKAAAGAGQAGAIAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEADQgHAJgMAAQgKAAgGgHgAhgAAQgCgPgNAAQgGABgEAEQgEAEgBAGIAeAAIAAAAgAjYAVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOANAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgJAAgEgFgAkNATIADgFQAIAGAIAAQAKAAAAgIQAAgEgMgDQgPgFAAgHQAAgGAFgEQAEgDAHAAQAJgBAIAGIgDAFQgIgEgGgBQgJAAAAAHQAAAFAMADQAPADAAAJQAAAGgFAFQgEADgIAAQgLAAgIgHgACzAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAEQAFAFAAAJIAAAbgAilAZIAAgsIAHAAIAAALQAGgMANAAIAAAHIgBAAQgIAAgEAFQgGAGAAAJIAAASgAkfAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAEQAFAFAAAJIAAAbgAlXAZIAAgsIAHAAIAAAsgAlYgdIAAgIIAIAAIAAAIg");
	this.shape_1.setTransform(20.8,4.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.3,0,110.7,8.1);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#003E7E").s().p("AgRATIAAglIAjAAIAAAlg");
	this.shape.setTransform(221.6,22.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#003E7E").s().p("AgbBHQgVgKgJgHIAPgWQALAIANAFQANAEAJABQALgBAGgEQAGgEAAgIIAAAAQAAgIgKgFQgFgCgQgGQgXgGgIgGQgHgFgEgGQgEgIAAgKIAAgBQAAgKAEgIQAEgJAHgGQAHgGAKgDQAJgDAJAAQAOAAAPAEQAOAFAMAIIgOAYQgLgGgKgFQgLgDgJAAQgIAAgGAEQgFAEAAAHIAAABQAAAHAKAFQAFADAQAFIAQAGQAJAEAGACQAHAFAEAIQAEAHAAAJIAAABQAAALgEAJQgEAJgIAGQgHAGgKADQgKACgMAAQgOAAgQgFg");
	this.shape_1.setTransform(210.6,17);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#003E7E").s().p("AgbBHQgVgKgJgHIAPgWQALAIANAFQANAEAJABQALgBAGgEQAGgEAAgIIAAAAQAAgIgKgFQgFgCgQgGQgXgGgIgGQgHgFgEgGQgEgIAAgKIAAgBQAAgKAEgIQAEgJAHgGQAHgGAKgDQAJgDAJAAQAOAAAPAEQAOAFAMAIIgOAYQgLgGgKgFQgLgDgJAAQgIAAgGAEQgFAEAAAHIAAABQAAAHAKAFQAFADAQAFIAQAGQAJAEAGACQAHAFAEAIQAEAHAAAJIAAABQAAALgEAJQgEAJgIAGQgHAGgKADQgKACgMAAQgOAAgQgFg");
	this.shape_2.setTransform(196.6,17);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#003E7E").s().p("AgYBHQgOgFgKgLQgLgKgFgOIgFgPIgBgQIAAAAQAAgOAFgPQAGgNAJgLQAKgLANgGIAOgEIANgCQAJAAAIACIAOAFQAJAEANANQAJALAFAPQAEAOAAAOIgBAJIhqAAQABAJAEAHQAEAHAFAFQAGAFAHACQAHADAGAAQAMAAAKgFQAJgEAJgJIAUASIgLALIgOAJQgIAEgIACQgJACgKAAQgOAAgOgGgAAlgJQAAgIgDgHQgDgIgFgFQgFgFgGgDQgHgDgIAAQgGAAgGADQgHADgFAFQgFAFgDAHQgDAHgBAJIBJAAIAAAAg");
	this.shape_3.setTransform(181.4,17);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#003E7E").s().p("AAgBLIAAhSQAAgIgCgIQgCgGgEgEQgFgGgFgCQgGgCgIAAQgFAAgGACQgGADgFAFQgEAEgDAHQgCAHAAAJIAABRIgiAAIAAiSIAiAAIAAAXQAIgMAKgGQAGgEAHgBQAFgDAIAAQANAAAJAEQAKAEAHAIQAHAHADAKQAEALAAANIAABcg");
	this.shape_4.setTransform(164.3,16.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#003E7E").s().p("AgQBlIAAiSIAhAAIAACSgAgQhEIAAggIAiAAIAAAgg");
	this.shape_5.setTransform(151.6,14.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#003E7E").s().p("AgbBHQgVgKgJgHIAPgWQALAIANAFQANAEAJABQALgBAGgEQAGgEAAgIIAAAAQAAgIgKgFQgFgCgQgGQgXgGgIgGQgHgFgEgGQgEgIAAgKIAAgBQAAgKAEgIQAEgJAHgGQAHgGAKgDQAJgDAJAAQAOAAAPAEQAOAFAMAIIgOAYQgLgGgKgFQgLgDgJAAQgIAAgGAEQgFAEAAAHIAAABQAAAHAKAFQAFADAQAFIAQAGQAJAEAGACQAHAFAEAIQAEAHAAAJIAAABQAAALgEAJQgEAJgIAGQgHAGgKADQgKACgMAAQgOAAgQgFg");
	this.shape_6.setTransform(140.4,17);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#003E7E").s().p("AgiBHQgKgEgHgHQgHgIgDgKQgEgLAAgNIAAhcIAiAAIAABSQAAAJACAHQACAGAFAFQADAFAGACQAGACAHAAQAGAAAGgCQAGgDAEgEQAFgFADgHQACgHAAgIIAAhSIAiAAIAACSIgiAAIAAgXQgIAMgKAHQgGADgGACQgGACgJAAQgMAAgJgEg");
	this.shape_7.setTransform(124.8,17.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#003E7E").s().p("AgIBlQgHgCgGgEQgLgGgJgMIAAAXIgiAAIAAjKIAiAAIAABRQAJgNALgHQAHgDAHgCQAHgDAHAAQANAAANAFQAMAGAKAJQAKALAFANQAGATAAAMIAAABIgCARIgEAPQgFAOgKAKQgKAKgMAFQgNAFgNAAQgHAAgIgCgAgPgQQgIAEgGAGQgGAGgDAHQgEAJAAAKIAAABQAAAKAEAJQADAJAGAGQAGAGAIAEQAIADAHAAQAIAAAIgDQAHgEAGgGQAGgGADgJQADgJAAgKIAAgBQAAgKgDgJQgDgHgGgGQgGgHgHgDQgIgDgIAAQgHAAgIADg");
	this.shape_8.setTransform(107.2,14.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#003E7E").s().p("AAgBmIAAhUQAAgJgCgHQgCgEgEgFQgFgFgFgCQgGgCgIAAQgFAAgGACQgGADgFAEQgEAFgDAFQgCAHAAAIIAABUIgiAAIAAjLIAiAAIAABQQAIgMAKgGQAGgEAHgCQAFgCAIAAQANAAAJAEQAKAEAHAHQAHAIADAKQAEALAAALIAABeg");
	this.shape_9.setTransform(80.5,14.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#003E7E").s().p("AgBBdQgIgDgFgEQgGgGgDgIQgDgJAAgMIAAhLIgTAAIAAgeIATAAIAAgoIAgAAIAAAoIAoAAIAAAeIgoAAIAABGQAAAKAFAEQAEAEAJAAQALAAAKgEIAAAcIgOAFQgHACgJAAQgKAAgGgCg");
	this.shape_10.setTransform(65.8,15.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#003E7E").s().p("AgQBlIAAiSIAhAAIAACSgAgQhEIAAggIAhAAIAAAgg");
	this.shape_11.setTransform(56.3,14.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#003E7E").s().p("AAgBKIgghjIggBjIgeAAIgwiTIAiAAIAeBkIAhhkIAbAAIAhBkIAehkIAiAAIgwCTg");
	this.shape_12.setTransform(40.2,17);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#003E7E").s().p("AgbBHQgVgKgJgHIAPgWQALAIANAFQANAEAJABQALgBAGgEQAGgEAAgIIAAAAQAAgIgKgFQgFgCgQgGQgXgGgIgGQgHgFgEgGQgEgIAAgKIAAgBQAAgKAEgIQAEgJAHgGQAHgGAKgDQAJgDAJAAQAOAAAPAEQAOAFAMAIIgOAYQgLgGgKgFQgLgDgJAAQgIAAgGAEQgFAEAAAHIAAABQAAAHAKAFQAFADAQAFIAQAGQAJAEAGACQAHAFAEAIQAEAHAAAJIAAABQAAALgEAJQgEAJgIAGQgHAGgKADQgKACgMAAQgOAAgQgFg");
	this.shape_13.setTransform(12.6,17);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#003E7E").s().p("AgbBHQgVgKgJgHIAPgWQALAIANAFQANAEAJABQALgBAGgEQAGgEAAgIIAAAAQAAgIgKgFQgFgCgQgGQgXgGgIgGQgHgFgEgGQgEgIAAgKIAAgBQAAgKAEgIQAEgJAHgGQAHgGAKgDQAJgDAJAAQAOAAAPAEQAOAFAMAIIgOAYQgLgGgKgFQgLgDgJAAQgIAAgGAEQgFAEAAAHIAAABQAAAHAKAFQAFADAQAFIAQAGQAJAEAGACQAHAFAEAIQAEAHAAAJIAAABQAAALgEAJQgEAJgIAGQgHAGgKADQgKACgMAAQgOAAgQgFg");
	this.shape_14.setTransform(-1.4,17);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#003E7E").s().p("AgYBHQgOgFgKgLQgLgKgFgOIgFgPIgBgQIAAAAQAAgOAFgPQAGgNAJgLQAKgLANgGIAOgEIANgCQAJAAAIACIAOAFQAJAEANANQAJALAFAPQAEAOAAAOIgBAJIhqAAQABAJAEAHQAEAHAFAFQAGAFAHACQAHADAGAAQAMAAAKgFQAJgEAJgJIAUASIgLALIgOAJQgIAEgIACQgJACgKAAQgOAAgOgGgAAlgJQAAgIgDgHQgDgIgFgFQgFgFgGgDQgHgDgIAAQgGAAgGADQgHADgFAFQgFAFgDAHQgDAHgBAJIBJAAIAAAAg");
	this.shape_15.setTransform(-16.7,17);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#003E7E").s().p("AAgBLIAAhSQAAgIgCgIQgCgGgEgEQgFgGgFgCQgGgCgIAAQgFAAgGACQgGADgFAFQgEAEgDAHQgCAHAAAJIAABRIgiAAIAAiSIAiAAIAAAXQAIgMAKgGQAGgEAHgBQAFgDAIAAQANAAAJAEQAKAEAHAIQAHAHADAKQAEALAAANIAABcg");
	this.shape_16.setTransform(-33.7,16.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#003E7E").s().p("AgQBlIAAiSIAgAAIAACSgAgRhEIAAggIAiAAIAAAgg");
	this.shape_17.setTransform(-46.5,14.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#003E7E").s().p("AgbBHQgVgKgJgHIAPgWQALAIANAFQANAEAJABQALgBAGgEQAGgEAAgIIAAAAQAAgIgKgFQgFgCgQgGQgXgGgIgGQgHgFgEgGQgEgIAAgKIAAgBQAAgKAEgIQAEgJAHgGQAHgGAKgDQAJgDAJAAQAOAAAPAEQAOAFAMAIIgOAYQgLgGgKgFQgLgDgJAAQgIAAgGAEQgFAEAAAHIAAABQAAAHAKAFQAFADAQAFIAQAGQAJAEAGACQAHAFAEAIQAEAHAAAJIAAABQAAALgEAJQgEAJgIAGQgHAGgKADQgKACgMAAQgOAAgQgFg");
	this.shape_18.setTransform(-57.7,17);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#003E7E").s().p("AgjBHQgKgEgGgHQgHgIgEgKQgDgLAAgNIAAhcIAiAAIAABSQAAAJACAHQACAGAEAFQAFAFAFACQAGACAHAAQAGAAAGgCQAGgDAFgEQAEgFACgHQADgHAAgIIAAhSIAiAAIAACSIgiAAIAAgXQgIAMgKAHQgGADgHACQgFACgIAAQgMAAgLgEg");
	this.shape_19.setTransform(-73.2,17.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#003E7E").s().p("AgIBlQgHgCgGgEQgLgGgJgMIAAAXIgiAAIAAjKIAiAAIAABRQAJgNALgHQAHgDAHgCQAHgDAHAAQANAAANAFQAMAGAKAJQAKALAFANQAGATAAAMIAAABIgCARIgEAPQgFAOgKAKQgKAKgMAFQgNAFgNAAQgHAAgIgCgAgPgQQgIAEgGAGQgGAGgDAHQgEAJAAAKIAAABQAAAKAEAJQADAJAGAGQAGAGAIAEQAIADAHAAQAIAAAIgDQAHgEAGgGQAGgGADgJQADgJAAgKIAAgBQAAgKgDgJQgDgHgGgGQgGgHgHgDQgIgDgIAAQgHAAgIADg");
	this.shape_20.setTransform(-90.8,14.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#003E7E").s().p("AAgBLIAAhSQAAgIgCgIQgCgGgEgEQgFgGgFgCQgGgCgIAAQgFAAgGACQgGADgFAFQgEAEgDAHQgCAHAAAJIAABRIgiAAIAAiSIAiAAIAAAXQAIgMAKgGQAGgEAHgBQAFgDAIAAQANAAAJAEQAKAEAHAIQAHAHADAKQAEALAAANIAABcg");
	this.shape_21.setTransform(-117.6,16.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#003E7E").s().p("AgPBlIAAiSIAgAAIAACSgAgQhEIAAggIAiAAIAAAgg");
	this.shape_22.setTransform(-130.3,14.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#003E7E").s().p("AgYBHQgOgFgKgLQgLgKgFgOIgFgPIgBgQIAAAAQAAgOAFgPQAGgNAJgLQAKgLANgGIAOgEIANgCQAJAAAIACIAOAFQAJAEANANQAJALAFAPQAEAOAAAOIgBAJIhqAAQABAJAEAHQAEAHAFAFQAGAFAHACQAHADAGAAQAMAAAKgFQAJgEAJgJIAUASIgLALIgOAJQgIAEgIACQgJACgKAAQgOAAgOgGgAAlgJQAAgIgDgHQgDgIgFgFQgFgFgGgDQgHgDgIAAQgGAAgGADQgHADgFAFQgFAFgDAHQgDAHgBAJIBJAAIAAAAg");
	this.shape_23.setTransform(-151.2,17);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#003E7E").s().p("AgpBLIAAiSIAhAAIAAAhQADgIAFgHQAEgHAGgEQAHgGAHgCQAJgCAJAAIAAAkIgCAAQgLAAgJAEQgJADgHAIQgEAHgEALQgEAJAAAOIAAA5g");
	this.shape_24.setTransform(-164.7,16.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#003E7E").s().p("AgWAZQANgDAGgGQAEgHgBgJIgMAAIAAgmIAjAAIAAAhQAAAJgDAJQgDAIgFAGQgFAFgHAEQgHADgLAAg");
	this.shape_25.setTransform(-175.3,8.7);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#003E7E").s().p("AgYBHQgOgFgKgLQgLgKgFgOIgFgPIgBgQIAAAAQAAgOAFgPQAGgNAJgLQAKgLANgGIAOgEIANgCQAJAAAIACIAOAFQAJAEANANQAJALAFAPQAEAOAAAOIgBAJIhqAAQABAJAEAHQAEAHAFAFQAGAFAHACQAHADAGAAQAMAAAKgFQAJgEAJgJIAUASIgLALIgOAJQgIAEgIACQgJACgKAAQgOAAgOgGgAAlgJQAAgIgDgHQgDgIgFgFQgFgFgGgDQgHgDgIAAQgGAAgGADQgHADgFAFQgFAFgDAHQgDAHgBAJIBJAAIAAAAg");
	this.shape_26.setTransform(-187.1,17);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#003E7E").s().p("AAwBiIgwiKIgvCKIgdAAIhFjDIAmAAIAuCPIAwiQIAcAAIAwCQIAviPIAkAAIhFDDg");
	this.shape_27.setTransform(-209.7,14.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-257,0,514,32);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgOAQIAAgfIAdAAIAAAfg");
	this.shape.setTransform(213.9,19.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgXA8QgSgIgIgGIANgTQAKAHALAEQALAEAIAAQAIAAAGgEQAFgDAAgHIAAAAQAAgHgIgEQgEgCgOgFQgTgGgIgEQgGgEgDgGQgEgGAAgJQAAgJAEgIQADgHAHgFQAGgFAHgCQAJgDAHAAQAMAAANAEQALAEALAGIgMAVQgJgGgJgDQgJgDgIAAQgGAAgFADQgFAEAAAGIAAAAQAAAGAIAFIASAHIAPAFIAMAFQAGAFADAFQAEAHAAAIIAAAAQAAAKgEAIQgEAHgGAFQgGAFgJADQgJACgJAAQgMAAgOgFg");
	this.shape_1.setTransform(204.5,14.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgjBAIAAh8IAcAAIAAAcIAHgNQADgGAGgEQAFgEAHgCQAHgCAIAAIAAAfIgBAAQgKAAgIADQgIADgFAGQgEAHgDAJQgEAIAAAMIAAAwg");
	this.shape_2.setTransform(194.3,14.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgVA9QgLgFgJgJQgJgIgFgMIgEgNIgBgOIAAAAQAAgMAFgMQAEgMAIgJQAJgJALgFIAMgEIALgCQAHAAAHACIAMAEQAIADALAMQAIAJAEANQAEAMAAAMIgBAIIhbAAQABAHADAGQAEAGAEAFQAFAEAGACQAGACAGAAQAKAAAIgEQAIgEAIgHIARAPIgKAKQgGAEgGADQgGADgIACQgHACgJAAQgMAAgMgFgAAggHQgBgIgCgGQgDgGgEgEQgEgFgFgCQgGgDgHAAQgFAAgGADQgFACgEAEQgFAFgCAGQgDAGgBAIIA/AAIAAAAg");
	this.shape_3.setTransform(181.6,14.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgNBXIAAitIAbAAIAACtg");
	this.shape_4.setTransform(170.9,12.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgNBXIAAh9IAbAAIAAB9gAgOg6IAAgcIAdAAIAAAcg");
	this.shape_5.setTransform(164.1,12.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgcA/QgIgDgGgFQgHgFgDgHQgEgIAAgJIAAgBQAAgJAEgJQAEgHAHgEQAHgFAJgDQAJgCALAAQAOAAATAFIAAgCQAAgHgBgEQgDgFgEgEQgEgEgGgCQgFgCgFAAQgKABgKACQgIACgJADIgIgXQAMgFAJgCQANgDAMAAQAOAAALAEQAKADAHAHQAHAHAEAKQADAJAAANIAABKIgdAAIAAgQQgHAIgKAFQgMAFgKAAQgJAAgIgCgAgLAGQgEABgFADQgDACgCAEQgCADAAAFIAAAAQAAAKAHAFQAHAEAKAAQAFAAAHgCQAGgCAFgDQAEgDADgFQACgGAAgGIAAgGQgSgGgLAAQgFABgGABg");
	this.shape_6.setTransform(153.3,14.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAABPQgHgCgFgEQgFgEgCgHQgDgIAAgKIAAhAIgQAAIAAgZIAQAAIAAgjIAbAAIAAAjIAiAAIAAAZIgiAAIAAA8QAAAIAEAEQAEADAIAAQAJAAAJgEIAAAYQgGADgGACQgHABgIAAQgIAAgEgCg");
	this.shape_7.setTransform(141.5,13.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgVA9QgLgFgJgJQgJgIgFgMIgEgNIgBgOIAAAAQAAgMAFgMQAEgMAIgJQAJgJALgFIAMgEIALgCQAHAAAHACIAMAEQAIADALAMQAIAJAEANQAEAMAAAMIgBAIIhbAAQABAHADAGQAEAGAEAFQAFAEAGACQAGACAGAAQAKAAAIgEQAIgEAIgHIARAPIgKAKQgGAEgGADQgGADgIACQgHACgJAAQgMAAgMgFgAAggHQgBgIgCgGQgDgGgEgEQgEgFgFgCQgGgDgHAAQgFAAgGADQgFACgEAEQgFAFgCAGQgDAGgBAIIA/AAIAAAAg");
	this.shape_8.setTransform(129.6,14.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgjBAIAAh8IAcAAIAAAcIAHgNQADgGAGgEQAFgEAHgCQAHgCAIAAIAAAfIgBAAQgKAAgIADQgIADgFAGQgEAHgDAJQgEAIAAAMIAAAwg");
	this.shape_9.setTransform(117.9,14.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgVA9QgLgFgJgJQgJgIgFgMIgEgNIgBgOIAAAAQAAgMAFgMQAEgMAIgJQAJgJALgFIAMgEIALgCQAHAAAHACIAMAEQAIADALAMQAIAJAEANQAEAMAAAMIgBAIIhbAAQABAHADAGQAEAGAEAFQAFAEAGACQAGACAGAAQAKAAAIgEQAIgEAIgHIARAPIgKAKQgGAEgGADQgGADgIACQgHACgJAAQgMAAgMgFgAAggHQgBgIgCgGQgDgGgEgEQgEgFgFgCQgGgDgHAAQgFAAgGADQgFACgEAEQgFAFgCAGQgDAGgBAIIA/AAIAAAAg");
	this.shape_10.setTransform(98,14.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAbBAIAAhGQAAgHgCgGQgBgGgEgEQgDgEgFgCQgFgCgHAAQgEAAgFACQgGADgDAEQgEAEgCAGQgDAGAAAHIAABFIgcAAIAAh8IAcAAIAAATQAIgKAIgFQAFgEAGgBQAEgCAHAAQALAAAIADQAJAEAFAGQAGAHADAJQADAJAAALIAABOg");
	this.shape_11.setTransform(83.4,14.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgNBXIAAh9IAbAAIAAB9gAgOg6IAAgcIAdAAIAAAcg");
	this.shape_12.setTransform(72.5,12.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgNBXIAAitIAbAAIAACtg");
	this.shape_13.setTransform(65.7,12.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAbBAIAAhGQAAgHgCgGQgBgGgEgEQgDgEgFgCQgFgCgHAAQgEAAgFACQgGADgDAEQgEAEgCAGQgDAGAAAHIAABFIgcAAIAAh8IAcAAIAAATQAIgKAIgFQAFgEAGgBQAEgCAHAAQALAAAIADQAJAEAFAGQAGAHADAJQADAJAAALIAABOg");
	this.shape_14.setTransform(54.9,14.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgNBAIgNgEQgMgFgJgJQgJgJgFgMIgEgMIgBgNIAAAAQAAgHAFgRQAFgMAJgJQAKgJAMgFIAMgEIANgCQAJAAASAGQAMAFAJAJQAJAJAFAMQAFAQAAAIIAAAAIgCANIgDAMQgFAMgKAJQgIAJgNAFQgRAGgJAAgAgPgkQgGADgGAGQgFAFgCAIQgDAHAAAHIAAAAQAAAIADAHQACAIAGAFQAFAGAHADQAHADAHAAQAIAAAIgDQAHgDAEgGQAFgFADgHQADgIAAgIIAAAAQAAgHgDgHQgDgHgFgGQgGgGgGgDQgIgDgHAAQgHAAgIADg");
	this.shape_15.setTransform(39.5,14.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgNBAIgNgEQgMgFgJgJQgJgJgFgMIgEgMIgBgNIAAAAQAAgHAFgRQAFgMAJgJQAKgJAMgFIAMgEIANgCQAJAAASAGQAMAFAJAJQAJAJAFAMQAFAQAAAIIAAAAIgCANIgDAMQgFAMgKAJQgIAJgNAFQgRAGgJAAgAgPgkQgGADgGAGQgFAFgCAIQgDAHAAAHIAAAAQAAAIADAHQACAIAGAFQAFAGAHADQAHADAHAAQAIAAAIgDQAHgDAFgGQAEgFADgHQADgIAAgIIAAAAQAAgHgDgHQgDgHgFgGQgGgGgGgDQgIgDgHAAQgHAAgIADg");
	this.shape_16.setTransform(16.6,14.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAABPQgHgCgFgEQgFgEgCgHQgDgIAAgKIAAhAIgQAAIAAgZIAQAAIAAgjIAbAAIAAAjIAiAAIAAAZIgiAAIAAA8QAAAIAEAEQAEADAIAAQAJAAAJgEIAAAYQgGADgGACQgHABgIAAQgIAAgEgCg");
	this.shape_17.setTransform(3.6,13.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgXA8QgSgIgIgGIANgTQAKAHALAEQALAEAHAAQAKAAAFgEQAFgDAAgHIAAAAQAAgHgIgEQgFgCgNgFQgUgGgHgEQgGgEgEgGQgDgGAAgJQAAgJADgIQAEgHAGgFQAGgFAIgCQAJgDAHAAQAMAAANAEQAMAEAKAGIgLAVQgKgGgJgDQgKgDgHAAQgHAAgFADQgEAEAAAGIAAAAQAAAGAJAFIARAHIAPAFIAMAFQAGAFADAFQAEAHAAAIIAAAAQAAAKgEAIQgEAHgGAFQgGAFgJADQgJACgKAAQgLAAgOgFg");
	this.shape_18.setTransform(-14.5,14.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAbBAIAAhGQAAgHgCgGQgBgGgEgEQgDgEgFgCQgFgCgHAAQgEAAgFACQgGADgDAEQgEAEgCAGQgDAGAAAHIAABFIgcAAIAAh8IAcAAIAAATQAIgKAIgFQAFgEAGgBQAEgCAHAAQALAAAIADQAJAEAFAGQAGAHADAJQADAJAAALIAABOg");
	this.shape_19.setTransform(-27.7,14.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgcA/QgIgDgHgFQgFgFgFgHQgDgIAAgJIAAgBQAAgJAEgJQADgHAIgEQAGgFAKgDQAJgCAMAAQANAAATAFIAAgCQAAgHgCgEQgCgFgDgEQgFgEgGgCQgFgCgGAAQgKABgJACQgHACgKADIgIgXQAMgFAJgCQANgDAMAAQAOAAALAEQAKADAHAHQAHAHADAKQAEAJAAANIAABKIgdAAIAAgQQgHAIgJAFQgNAFgKAAQgJAAgIgCgAgKAGQgFABgEADQgEACgCAEQgCADAAAFIAAAAQAAAKAHAFQAHAEALAAQAEAAAGgCQAHgCAEgDQAFgDACgFQADgGAAgGIAAgGQgRgGgMAAQgFABgFABg");
	this.shape_20.setTransform(-42.5,14.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgNBXIAAh9IAbAAIAAB9gAgOg6IAAgcIAdAAIAAAcg");
	this.shape_21.setTransform(-52.6,12.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgGBAIgMgEQgMgFgIgJQgJgJgGgMQgEgMAAgNIAAAAQAAgMAEgMQAGgMAJgJQAIgJAMgFIANgEQAFgCAGAAQAKAAAHACIANAEQAJAEAMAMIgSAUQgHgIgHgEQgIgEgLAAQgGAAgHADQgGADgFAGQgFAFgDAIQgCAHAAAHIAAAAQAAAIACAIQADAHAFAGQAFAFAHADQAGADAIAAQAJAAAJgEQAHgEAIgHIARARQgNANgIAEQgHADgHACQgHACgKAAg");
	this.shape_22.setTransform(-62.8,14.9);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgNBXIAAh9IAbAAIAAB9gAgOg6IAAgcIAdAAIAAAcg");
	this.shape_23.setTransform(-73.2,12.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgjBAIAAh8IAcAAIAAAcIAHgNQADgGAGgEQAFgEAHgCQAHgCAIAAIAAAfIgBAAQgKAAgIADQgIADgFAGQgEAHgDAJQgEAIAAAMIAAAwg");
	this.shape_24.setTransform(-81,14.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAABPQgHgCgFgEQgFgEgCgHQgDgIAAgKIAAhAIgQAAIAAgZIAQAAIAAgjIAbAAIAAAjIAiAAIAAAZIgiAAIAAA8QAAAIAEAEQAEADAIAAQAJAAAJgEIAAAYQgGADgGACQgHABgIAAQgIAAgEgCg");
	this.shape_25.setTransform(-91.6,13.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgGBAIgMgEQgMgFgIgJQgKgJgFgMQgEgMAAgNIAAAAQAAgMAEgMQAFgMAKgJQAIgJAMgFIANgEQAFgCAHAAQAIAAAIACIANAEQAJAEAMAMIgSAUQgHgIgHgEQgIgEgKAAQgHAAgHADQgGADgFAGQgFAFgDAIQgCAHAAAHIAAAAQAAAIACAIQAEAHAFAGQAFAFAGADQAGADAIAAQAKAAAIgEQAHgEAIgHIARARQgNANgIAEQgGADgIACQgIACgIAAg");
	this.shape_26.setTransform(-103,14.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgVA9QgLgFgJgJQgJgIgFgMIgEgNIgBgOIAAAAQAAgMAFgMQAEgMAIgJQAJgJALgFIAMgEIALgCQAHAAAHACIAMAEQAIADALAMQAIAJAEANQAEAMAAAMIgBAIIhbAAQABAHADAGQAEAGAEAFQAFAEAGACQAGACAGAAQAKAAAIgEQAIgEAIgHIARAPIgKAKQgGAEgGADQgGADgIACQgHACgJAAQgMAAgMgFgAAggHQgBgIgCgGQgDgGgEgEQgEgFgFgCQgGgDgHAAQgFAAgGADQgFACgEAEQgFAFgCAGQgDAGgBAIIA/AAIAAAAg");
	this.shape_27.setTransform(-117.2,14.9);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgNBXIAAitIAbAAIAACtg");
	this.shape_28.setTransform(-127.9,12.5);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgVA9QgLgFgJgJQgJgIgFgMIgEgNIgBgOIAAAAQAAgMAFgMQAEgMAIgJQAJgJALgFIAMgEIALgCQAHAAAHACIAMAEQAIADALAMQAIAJAEANQAEAMAAAMIgBAIIhbAAQABAHADAGQAEAGAEAFQAFAEAGACQAGACAGAAQAKAAAIgEQAIgEAIgHIARAPIgKAKQgGAEgGADQgGADgIACQgHACgJAAQgMAAgMgFgAAggHQgBgIgCgGQgDgGgEgEQgEgFgFgCQgGgDgHAAQgFAAgGADQgFACgEAEQgFAFgCAGQgDAGgBAIIA/AAIAAAAg");
	this.shape_29.setTransform(-138.5,14.9);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("ABDBAIAAhGQAAgHgCgGQgCgGgDgEQgDgEgFgCQgFgCgGAAQgGAAgFACQgFACgDAEQgEAEgCAGQgCAGAAAIIAABFIgbAAIAAhGQAAgHgCgGQgCgGgDgEQgDgEgFgCQgFgCgGAAQgGAAgFACQgFADgDAEQgEAEgCAGQgCAGAAAHIAABFIgdAAIAAh8IAdAAIAAATQAHgKAIgFQAFgEAGgBQAGgCAHAAQAGAAAGACIALAEQAEADACAEIAGAJQAJgLAKgFIALgEQAGgCAHAAQALAAAIADQAIADAGAHQAGAGADAJQADAJAAALIAABPg");
	this.shape_30.setTransform(-164.3,14.7);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgNBAIgNgEQgMgFgJgJQgJgJgFgMIgEgMIgBgNIAAAAQAAgHAFgRQAFgMAJgJQAKgJALgFIAOgEIAMgCQAJAAARAGQANAFAJAJQAJAJAFAMQAFAQAAAIIAAAAIgBANIgEAMQgFAMgJAJQgKAJgMAFQgRAGgJAAgAgPgkQgGADgGAGQgFAFgDAIQgCAHAAAHIAAAAQAAAIACAHQAEAIAEAFQAGAGAHADQAHADAHAAQAIAAAHgDQAHgDAGgGQAFgFACgHQADgIAAgIIAAAAQAAgHgDgHQgDgHgFgGQgFgGgIgDQgGgDgIAAQgHAAgIADg");
	this.shape_31.setTransform(-183.6,14.9);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgjBAIAAh8IAcAAIAAAcIAHgNQADgGAGgEQAFgEAHgCQAHgCAIAAIAAAfIgBAAQgKAAgIADQgIADgFAGQgEAHgDAJQgEAIAAAMIAAAwg");
	this.shape_32.setTransform(-195.9,14.7);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("Ag9BUIAAimIB7AAIAAAbIhdAAIAAAtIBSAAIAAAZIhSAAIAABFg");
	this.shape_33.setTransform(-208.7,12.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-239.5,0,479,28);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F78E1E").s().p("EgoTAHzIAAvmMBQnAAAIAAPmg");
	this.shape.setTransform(432,50);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(174,0,516,100);


(lib.EqualHousingOpportunityrevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// EqualHousingOpportunity-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyZSUIAAw4IixAAIAAlsIU+uDIAZAAIU+ODIAAFwIivAAIAAQ0gAtyhwIAAOUIbpAAIAAuPIt3pUgAnQJ9IAAmDIOmAAIAAGDgAnSC9IAAl/IOmAAIAAF/g");
	this.shape.setTransform(135.6,117.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AEDBvQgWgLgIgWQgKgWAAgmIAAiHIAfAAIAACHQAAAgAHANQAFAPAOAJQAPAHAUAAQAiAAAPgPQAPgQAAgtIAAiHIAfAAIAACHQABAjgJAWQgIAUgVAOQgVAOgjAAQghAAgVgMgAmwBrQgbgSgNgbQgOgbAAghQABg4AfgiQAgghAzgBQAgAAAaAQQAbAQAOAcQAOAcAAAiQAAAkgOAcQgPAdgbAPQgaAOggABQghAAgbgQgAmthHQgYAXAAAzQAAAsAXAYQAXAZAjAAQAkAAAWgZQAYgZAAguQgBgbgJgWQgKgWgTgLQgSgMgYgBQgiAAgYAYgAxoBrQgbgRgNgcQgOgbAAghQAAg4AggiQAfghAzgBQAhAAAaAQQAbAQAOAcQANAcAAAiQABAlgPAbQgNAcgcAQQgaAOggABQgiAAgagQgAxmhHQgYAXAAAzQAAAqAYAaQAXAZAiAAQAlAAAWgZQAXgZAAguQAAgcgKgVQgJgVgUgMQgSgMgYgBQggAAgaAYgAQhB2IAAhkIhciHIAmAAIBHBvIBIhvIAlAAIhfCHIAABkgANPB2IAAjPIhOAAIAAgcIC9AAIAAAcIhPAAIAADPgAK7B2IAAjrIAfAAIAADrgAJkB2Ih9i5IAAC5IgeAAIAAjrIAhAAIB9C4IAAi4IAeAAIAADrgABMB2IAAjPIhMAAIAAgcIC6AAIAAAcIhPAAIAADPgAgwB2IgggxIgWghQgLgMgFgEQgGgDgJgDIgSgBIgkAAIAABpIgfAAIAAjrIBpAAQAfgBASAHQARAHAJAQQAKAQAAAUQAAAYgRATQgPAOgjAFQAMAGAHAGQAPAOALASIApBAgAi7gNIBEAAQAWABAMgFQAMgEAGgKQAHgJgBgMQAAgRgMgLQgLgLgbAAIhMAAgAq5B2IAAjrIBaAAQAWAAAOACQASADAMAIQALAIAHAPQAIAOAAASQgBAggSASQgUAVgyAAIg+AAIAABggAqagEIA+AAQAfAAANgMQAMgLAAgVQAAgPgIgKQgHgLgMgDQgHgCgWAAIg+AAgAuTB2IAAjrIBaAAQAXAAANACQASADAMAIQALAIAIAPQAHAPAAARQAAAfgUATQgTAVgyAAIg9AAIAABggAtzgEIA9AAQAeAAAOgMQANgLAAgVQgBgPgHgKQgJgLgLgDQgIgCgVAAIg9AAg");
	this.shape_1.setTransform(135.7,277.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AtCBXQgXANgcAAQgcAAgWgOQgXgNgMgZQgNgYAAgdQAAgeANgZQALgYAYgOQAXgNAcAAQAcAAAXAOQAWANANAZQAMAYAAAeQAAAYgIAUQgIAUgPAPQAQAMATAHIgIATQgWgHgWgSgAunhDQgUAWAAAoQAAAnAUAVQAUAVAfAAQAOABANgGQgMgIgPgEIAHgUQAYAIAPAMQAYgWAAgqQAAgZgJgSQgIgTgRgKQgPgKgVAAQgeAAgVAUgAP7BWQgZgNgMgYQgNgZAAgcQAAgdANgaQAMgaAYgNQAXgNAfAAQAYABARAGQARAIALAMQAKAMAFAWIgYAHQgEgPgIgKQgHgJgMgFQgOgFgPAAQgSgBgOAHQgNAFgJAJQgJALgEAJQgIAVAAAVQAAAZAKASQAJATASAJQATAJAUAAQASAAAQgHQARgGAJgIIAAgmIg9AAIAAgWIBXAAIAABJQgTARgWAIQgVAIgXAAQgfgBgYgNgAIXBcQgSgJgMgQQgKgQgBgVIAagCQACAQAGAKQAHAIAOAHQANAGASAAQARAAALgEQAMgFAGgIQAFgIAAgKQAAgJgFgIQgFgHgOgFQgKgEgagFQgbgFgNgGQgOgIgIgMQgHgKAAgPQAAgQAJgNQAJgOARgHQAPgGAWgBQAWABATAGQARAIAJAPQAKAOABARIgbACQgBgSgNgLQgLgKgZAAQgYAAgLAKQgMAIAAANQAAALAIAHQAIAIAhAHQAfAHAPAGQARAIAJALQAJANAAAQQAAARgKAOQgJAPgSAIQgQAIgXAAQgdAAgSgIgAFPBaQgTgLgHgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAFAMAMAHQAMAHASAAQAeAAAMgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgGATgTAMQgSAKgeABQgegBgRgJgAB1BVQgWgNgNgZQgLgYAAgZQAAgzAbgdQAcgdArAAQAdAAAWAOQAXANAMAZQAMAYAAAfQAAAbgMAaQgNAZgXANQgXANgbAAQgegBgWgOgAB4hEQgVAUAAAuQAAAlAUAUQAUAVAeAAQAeAAAUgVQAUgWAAgmQAAgYgIgTQgKgUgPgJQgRgKgUAAQgdAAgUATgArOBaQgSgLgIgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAGAMALAHQANAHARAAQAeAAANgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgHATgTAMQgRAKgfABQgdgBgSgJgAOGBgIhsifIAACfIgaAAIAAjLIAcAAIBsCfIAAifIAaAAIAADLgAK3BgIAAjLIAcAAIAADLgAALBgIAAhgIhpAAIAABgIgbAAIAAjLIAbAAIAABUIBpAAIAAhUIAbAAIAADLgAliBgIAAjLIAcAAIAACzIBlAAIAAAYgAmXBgIgYg+IhWAAIgWA+IgdAAIBPjLIAdAAIBUDLgAm3AMIgVg3IgPgrQgEAWgHARIgXA7IBGAAgAyGBgIAAjLICUAAIAAAYIh5AAIAAA/IByAAIAAAWIhyAAIAABGIB+AAIAAAYg");
	this.shape_2.setTransform(135.2,250.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,271.2,289.4);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.Close = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#003E7E").s().p("AgRATIAAglIAjAAIAAAlg");
	this.shape.setTransform(173.5,50.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#003E7E").s().p("AgpBLIAAiSIAhAAIAAAhQADgIAFgHQAEgHAGgEQAHgGAHgCQAJgCAJAAIAAAkIgBAAQgMAAgJAEQgJADgHAIQgEAHgEALQgEAJAAAOIAAA5g");
	this.shape_1.setTransform(164.7,44.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#003E7E").s().p("AgYBHQgOgFgKgLQgLgKgFgOIgFgPIgBgQIAAAAQAAgOAFgPQAGgNAJgLQAKgLANgGIAOgEIANgCQAJAAAIACIAOAFQAJAEANANQAJALAFAPQAEAOAAAOIgBAJIhqAAQABAJAEAHQAEAHAFAFQAGAFAHACQAHADAGAAQAMAAAKgFQAJgEAJgJIAUASIgLALIgOAJQgIAEgIACQgJACgKAAQgOAAgOgGgAAlgJQAAgIgDgHQgDgIgFgFQgFgFgGgDQgHgDgIAAQgGAAgGADQgHADgFAFQgFAFgDAHQgDAHgBAJIBJAAIAAAAg");
	this.shape_2.setTransform(149.8,44.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#003E7E").s().p("AgBBdQgIgDgFgFQgGgFgDgIQgDgJAAgLIAAhMIgTAAIAAgdIATAAIAAgpIAgAAIAAApIAoAAIAAAdIgoAAIAABHQAAAJAFAFQAEADAJABQALAAAKgGIAAAdIgOAFQgHACgJAAQgKAAgGgCg");
	this.shape_3.setTransform(135.4,43);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#003E7E").s().p("AgbBHQgVgJgJgIIAPgXQALAJANAFQANAFAJgBQALABAGgFQAGgEAAgHIAAgBQAAgIgKgFQgFgDgQgFQgXgHgIgFQgHgFgEgHQgEgHAAgKIAAgBQAAgKAEgJQAEgIAHgGQAHgFAKgDQAJgEAJAAQAOAAAPAFQAOAEAMAIIgOAYQgLgGgKgEQgLgEgJAAQgIAAgGAEQgFAEAAAHIAAAAQAAAIAKAEQAFADAQAGIAQAGQAJAEAGACQAHAGAEAGQAEAIAAAJIAAABQAAALgEAKQgEAHgIAHQgHAFgKADQgKADgMAAQgOAAgQgFg");
	this.shape_4.setTransform(122.7,44.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#003E7E").s().p("AghBJQgKgDgHgFQgHgHgEgIQgFgIAAgLIAAgBQAAgMAFgKQAEgIAJgEQAHgHALgCQALgDANgBQAQABAXAFIAAgCQAAgIgCgGQgCgFgFgFQgFgDgHgCQgGgDgHAAQgMAAgKADQgJACgLAEIgKgbQAOgGALgDQAPgDAPAAQAQAAAMAEQAMAEAIAJQAJAIAEALQAEAMAAAPIAABVIgiAAIAAgSQgIAJgLAGQgQAGgLAAQgLAAgJgDgAgMAHQgHACgEADQgEACgDAFQgCAEAAAFIAAABQAAAKAIAGQAIAFANAAQAGAAAHgBQAHgDAGgEQAFgEADgGQADgGAAgGIAAgJQgVgGgNAAQgGAAgGACg");
	this.shape_5.setTransform(107.3,45);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#003E7E").s().p("AgZBmIAAh0IgTAAIAAgcIATAAIAAgLQAAgMADgKQADgJAGgGQAGgFAHgDQAHgEALAAQAOAAANAFIAAAcQgKgEgJAAQgKABgFAEQgFAGAAAMIAAAIIAnAAIAAAcIgmAAIAAB0g");
	this.shape_6.setTransform(94.5,42);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#003E7E").s().p("AgPBjQgKgCgLgEQgLgEgJgGQgKgGgJgIIAWgYQAIAIAUAKQAIAEAIABQAIACAHAAQAIAAAGgCQAHgBAEgEQAFgDACgEQADgFAAgGIAAAAQAAgGgCgEQgCgEgEgDQgGgEgIgDIgUgGQgSgEgKgEQgNgFgIgFQgIgGgEgKQgFgJAAgOIAAAAQABgNAFgKQAEgLAJgHQAJgIANgEQAMgEAOAAQAJAAAJACQALABAIADQAMAEAVAPIgTAaQgNgKgNgFQgOgGgLAAQgHAAgHACQgGACgEADQgIAHAAAKIAAAAQAAAGACAEQACAFAFADIAOAHIAVAGQARAEAKAFQAMAFAJAEQAIAHAEAJQADAJAAAMIAAABQABAOgGALQgFAKgKAIQgJAIgMAEQgNADgPAAQgKAAgLgBg");
	this.shape_7.setTransform(71.5,42.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#003E7E").s().p("AhIBhIAAjCICPAAIAAAgIhsAAIAAAyIBgAAIAAAdIhgAAIAAA1IBuAAIAAAeg");
	this.shape_8.setTransform(53.8,42.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#003E7E").s().p("AgQBhIAAhMIhOh2IApAAIA1BXIA3hXIAoAAIhOB0IAABOg");
	this.shape_9.setTransform(33.9,42.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#003E7E").s().p("AgPBLIgPgEQgPgGgKgLQgKgKgHgOIgEgOIgBgQIAAAAQAAgJAFgTQAHgOAKgLQALgLAOgGIAPgEIAPgCQALAAAUAGQAOAGALALQAKAKAHAOQAFATAAAKIAAAAIgBAPIgEAOQgHAOgKALQgLALgPAGQgTAGgLAAgAgSgqQgIADgFAHQgGAGgDAJQgDAIAAAJIAAAAQAAAJADAJQADAIAGAHQAHAHAIADQAIAEAIAAQAJAAAJgEQAJgDAFgHQAGgGADgJQAEgIAAgKIAAAAQAAgIgEgJQgDgIgGgHQgHgHgHgDQgJgEgJAAQgJAAgJAEg");
	this.shape_10.setTransform(6.4,44.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#003E7E").s().p("AgBBdQgIgDgFgFQgGgFgDgIQgDgJAAgLIAAhMIgTAAIAAgdIATAAIAAgpIAgAAIAAApIAoAAIAAAdIgoAAIAABHQAAAJAFAFQAEADAJABQALAAAKgGIAAAdIgOAFQgHACgJAAQgKAAgGgCg");
	this.shape_11.setTransform(-8.7,43);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#003E7E").s().p("AgBBdQgIgDgFgFQgGgFgDgIQgDgJAAgLIAAhMIgTAAIAAgdIATAAIAAgpIAgAAIAAApIAoAAIAAAdIgoAAIAABHQAAAJAFAFQAEADAJABQALAAAKgGIAAAdIgOAFQgHACgJAAQgKAAgGgCg");
	this.shape_12.setTransform(-28.6,43);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#003E7E").s().p("AgYBHQgOgFgKgLQgLgKgFgOIgFgPIgBgQIAAAAQAAgOAFgPQAGgNAJgLQAKgLANgGIAOgEIANgCQAJAAAIACIAOAFQAJAEANANQAJALAFAPQAEAOAAAOIgBAJIhqAAQABAJAEAHQAEAHAFAFQAGAFAHACQAHADAGAAQAMAAAKgFQAJgEAJgJIAUASIgLALIgOAJQgIAEgIACQgJACgKAAQgOAAgOgGgAAlgJQAAgIgDgHQgDgIgFgFQgFgFgGgDQgHgDgIAAQgGAAgGADQgHADgFAFQgFAFgDAHQgDAHgBAJIBJAAIAAAAg");
	this.shape_13.setTransform(-42.6,44.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#003E7E").s().p("AglBdQgQgEgOgJIAMgaQANAIAMAEQANAEAPAAQAJAAAJgDQAIgDAHgFQAFgGAEgJQACgIAAgLIAAgMQgNAPgIAFQgHAEgHABQgHACgIAAQgNAAgLgEQgNgFgJgJQgKgJgFgNQgGgLAAgQIAAAAQAAgLAGgSQAFgNAKgJQAJgJANgFQALgFANAAQAIAAAHACQAIACAHAEQAKAGAKALIAAgWIAiAAIAAB0QAAATgFAOQgEANgJAKQgFAFgHAEIgOAGQgWAFgMAAQgSAAgRgFgAgPhBQgHADgHAFQgFAGgEAHQgCAIAAAIIAAABQAAAJACAIQAEAHAFAEQAHAFAHADQAIADAHAAQAIAAAIgDQAIgDAGgFQAGgEADgHQAEgIAAgJIAAAAQAAgJgEgIQgDgHgGgGQgGgFgIgDQgIgDgIAAQgHAAgIADg");
	this.shape_14.setTransform(-60.8,47);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#003E7E").s().p("AAgBLIAAhSQAAgJgCgGQgCgHgEgFQgFgEgFgCQgGgDgIAAQgFAAgGADQgGACgFAEQgEAGgDAGQgCAHAAAIIAABSIgiAAIAAiSIAiAAIAAAXQAIgMAKgGQAGgEAHgCQAFgCAIAAQANAAAJAEQAKAEAHAIQAHAHADALQAEAKAAANIAABcg");
	this.shape_15.setTransform(-86.8,44.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#003E7E").s().p("AghBJQgKgDgHgFQgHgHgEgIQgFgIAAgLIAAgBQAAgMAFgKQAEgIAJgEQAHgHALgCQALgDANgBQAQABAXAFIAAgCQAAgIgCgGQgCgFgFgFQgFgDgHgCQgGgDgHAAQgMAAgKADQgJACgLAEIgKgbQAOgGALgDQAPgDAPAAQAQAAAMAEQAMAEAIAJQAJAIAEALQAEAMAAAPIAABVIgiAAIAAgSQgIAJgLAGQgQAGgLAAQgLAAgJgDgAgMAHQgHACgEADQgEACgDAFQgCAEAAAFIAAABQAAAKAIAGQAIAFANAAQAGAAAHgBQAHgDAGgEQAFgEADgGQADgGAAgGIAAgJQgVgGgNAAQgGAAgGACg");
	this.shape_16.setTransform(-104.1,45);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#003E7E").s().p("AgGBLIgPgEQgNgGgLgLQgLgKgFgOQgGgOAAgQIAAAAQAAgOAGgOQAFgOALgLQALgLANgGIAPgEIAOgCQAKAAAJACIAQAFQAJAFAPAOIgVAWQgJgJgHgEQgLgFgMAAQgHAAgIAEQgHADgGAHQgFAGgEAJQgDAIAAAJIAAAAQAAAJADAJQAEAJAFAGQAGAHAJADQAGAEAKAAQAKAAALgFQAIgEAJgJIAUAUQgPAPgKAFQgHAEgJACQgJACgLAAg");
	this.shape_17.setTransform(-119.7,44.9);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#003E7E").s().p("AgYBHQgOgFgKgLQgLgKgFgOIgFgPIgBgQIAAAAQAAgOAFgPQAGgNAJgLQAKgLANgGIAOgEIANgCQAJAAAIACIAOAFQAJAEANANQAJALAFAPQAEAOAAAOIgBAJIhqAAQABAJAEAHQAEAHAFAFQAGAFAHACQAHADAGAAQAMAAAKgFQAJgEAJgJIAUASIgLALIgOAJQgIAEgIACQgJACgKAAQgOAAgOgGgAAlgJQAAgIgDgHQgDgIgFgFQgFgFgGgDQgHgDgIAAQgGAAgGADQgHADgFAFQgFAFgDAHQgDAHgBAJIBJAAIAAAAg");
	this.shape_18.setTransform(-144.7,44.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#003E7E").s().p("AAhBKIghhjIggBjIgeAAIgwiTIAiAAIAfBkIAghkIAbAAIAhBkIAehkIAiAAIgwCTg");
	this.shape_19.setTransform(-165.2,44.9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#003E7E").s().p("AgWAZQANgCAGgIQAEgGgBgJIgNAAIAAgmIAkAAIAAAhQAAAJgDAIQgDAJgFAGQgGAFgGAEQgIADgLAAg");
	this.shape_20.setTransform(188.7,24.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#003E7E").s().p("AgpBLIAAiSIAhAAIAAAhQAEgIAEgHQAEgHAGgEQAHgGAHgCQAJgCAJAAIAAAkIgBAAQgLAAgKAEQgJADgHAIQgFAHgDALQgEAJAAAOIAAA5g");
	this.shape_21.setTransform(180.3,16.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#003E7E").s().p("AgYBHQgOgFgKgLQgLgKgFgOIgFgPIgBgQIAAAAQAAgOAFgPQAGgNAJgLQAKgLANgGIAOgEIANgCQAJAAAIACIAOAFQAJAEANANQAJALAFAPQAEAOAAAOIgBAJIhqAAQABAJAEAHQAEAHAFAFQAGAFAHACQAHADAGAAQAMAAAKgFQAJgEAJgJIAUASIgLALIgOAJQgIAEgIACQgJACgKAAQgOAAgOgGgAAlgJQAAgIgDgHQgDgIgFgFQgFgFgGgDQgHgDgIAAQgGAAgGADQgHADgFAFQgFAFgDAHQgDAHgBAJIBJAAIAAAAg");
	this.shape_22.setTransform(165.4,17);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#003E7E").s().p("AgfBiQgNgFgKgKQgJgKgGgOIgFgPIgBgRIAAgBQAAgMAGgTQAGgNAJgLQAKgJAMgGQAMgFAOAAQAHAAAIADQAGABAHAEQALAHAJALIAAhPIAiAAIAADKIgiAAIAAgYQgJAMgLAHQgHAEgGACQgIACgHAAQgNAAgMgFgAgOgQQgIADgGAGQgGAHgDAGQgDAJAAALIAAABQAAAKADAJQADAJAGAGQAGAGAIAEQAHADAHAAQAIAAAIgEQAIgDAGgGQAGgHADgIQAEgJAAgKIAAgBQAAgKgEgJQgDgHgGgGQgGgHgIgDQgIgDgIAAQgHAAgHADg");
	this.shape_23.setTransform(147.2,14.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#003E7E").s().p("AAgBLIAAhSQAAgIgCgIQgCgGgEgEQgFgGgFgCQgGgCgIAAQgFAAgGACQgGADgFAFQgEAEgDAHQgCAHAAAJIAABRIgiAAIAAiSIAiAAIAAAXQAIgMAKgGQAGgEAHgBQAFgDAIAAQANAAAJAEQAKAEAHAIQAHAHADAKQAEALAAANIAABcg");
	this.shape_24.setTransform(129.6,16.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#003E7E").s().p("AgYBHQgOgFgKgLQgLgKgFgOIgFgPIgBgQIAAAAQAAgOAFgPQAGgNAJgLQAKgLANgGIAOgEIANgCQAJAAAIACIAOAFQAJAEANANQAJALAFAPQAEAOAAAOIgBAJIhqAAQABAJAEAHQAEAHAFAFQAGAFAHACQAHADAGAAQAMAAAKgFQAJgEAJgJIAUASIgLALIgOAJQgIAEgIACQgJACgKAAQgOAAgOgGgAAlgJQAAgIgDgHQgDgIgFgFQgFgFgGgDQgHgDgIAAQgGAAgGADQgHADgFAFQgFAFgDAHQgDAHgBAJIBJAAIAAAAg");
	this.shape_25.setTransform(112.4,17);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#003E7E").s().p("AhDBiIAAjCIAiAAIAACiIBlAAIAAAgg");
	this.shape_26.setTransform(96,14.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#003E7E").s().p("ABBBiIgTgvIhbAAIgVAvIgjAAIBXjDIAdAAIBXDDgAAhAUIghhMIggBMIBBAAg");
	this.shape_27.setTransform(67.2,14.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#003E7E").s().p("AhQBiIAAjCIBWAAQARgBANAFQANAFAIAIQAHAHADAHQADAJAAAJIAAABQAAAJgCAGQgCAHgEAGQgHAJgNAGQAJADAHACQAHAFAFAFQAGAGACAIQADAHAAAKIAAABQAAAMgFALQgFAKgKAGQgJAHgOAEQgNAEgQAAgAguBDIA3AAQAJAAAHgCQAHgCAFgDQAFgDACgGQADgFAAgGIAAgBQAAgGgDgEQgCgFgFgEQgFgDgIgCQgIgBgKgBIg0AAgAgugOIAuAAQAHAAAHgBQAHgDAFgDQAFgDACgFQADgFAAgHIAAAAQAAgGgCgEQgDgFgEgDQgFgEgGgCQgGgBgJAAIgvAAg");
	this.shape_28.setTransform(46.6,14.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#003E7E").s().p("AgPBjQgLgCgKgEQgLgEgJgGIgSgOIAUgYQAJAIAUAKQAIAEAIABQAIACAHAAQAIAAAHgCQAGgBAFgEQAEgDADgEQACgFAAgGIAAAAQAAgGgCgEQgCgEgFgDQgEgEgJgDIgVgGQgQgEgLgEQgNgFgHgFQgJgGgFgKQgDgJAAgOIAAAAQAAgNAEgKQAFgLAJgHQAJgIAMgEQANgEAOAAQAJAAAJACQAKABAJADQAMAEAUAPIgSAaQgNgKgOgFQgNgGgLAAQgHAAgHACQgFACgEADQgJAHAAAKIAAAAQAAAGACAEQACAFAFADIAOAHIAWAGQAPAEAMAFQALAFAIAEQAJAHADAJQAFAJAAAMIAAABQgBAOgFALQgFAKgJAIQgKAIgNAEQgNADgPAAQgJAAgLgBg");
	this.shape_29.setTransform(26.9,14.5);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#003E7E").s().p("AggBiQgMgFgJgKQgLgKgFgOIgEgPIgCgRIAAgBQAAgMAGgTQAGgNAJgLQAKgJAMgGQANgFANAAQAGAAAJADQAGABAHAEQALAHAKALIAAhPIAhAAIAADKIghAAIAAgYQgKAMgLAHQgHAEgGACQgJACgGAAQgNAAgNgFgAgPgQQgHADgGAGQgGAHgDAGQgDAJgBALIAAABQABAKADAJQADAJAGAGQAGAGAHAEQAJADAGAAQAJAAAHgEQAIgDAGgGQAGgHADgIQAEgJAAgKIAAgBQAAgKgEgJQgDgHgGgGQgGgHgIgDQgHgDgJAAQgGAAgJADg");
	this.shape_30.setTransform(-0.1,14.3);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#003E7E").s().p("AgYBHQgOgFgKgLQgLgKgFgOIgFgPIgBgQIAAAAQAAgOAFgPQAGgNAJgLQAKgLANgGIAOgEIANgCQAJAAAIACIAOAFQAJAEANANQAJALAFAPQAEAOAAAOIgBAJIhqAAQABAJAEAHQAEAHAFAFQAGAFAHACQAHADAGAAQAMAAAKgFQAJgEAJgJIAUASIgLALIgOAJQgIAEgIACQgJACgKAAQgOAAgOgGgAAlgJQAAgIgDgHQgDgIgFgFQgFgFgGgDQgHgDgIAAQgGAAgGADQgHADgFAFQgFAFgDAHQgDAHgBAJIBJAAIAAAAg");
	this.shape_31.setTransform(-17.5,17);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#003E7E").s().p("AgpBLIAAiSIAhAAIAAAhQADgIAFgHQAEgHAGgEQAHgGAHgCQAJgCAJAAIAAAkIgCAAQgLAAgJAEQgJADgHAIQgEAHgEALQgEAJAAAOIAAA5g");
	this.shape_32.setTransform(-31.1,16.8);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#003E7E").s().p("AgqBLIAAiSIAiAAIAAAhQAEgIAEgHQADgHAHgEQAHgGAIgCQAIgCAKAAIAAAkIgCAAQgLAAgKAEQgJADgHAIQgEAHgEALQgEAJAAAOIAAA5g");
	this.shape_33.setTransform(-42.6,16.8);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#003E7E").s().p("AgYBHQgOgFgKgLQgLgKgFgOIgFgPIgBgQIAAAAQAAgOAFgPQAGgNAJgLQAKgLANgGIAOgEIANgCQAJAAAIACIAOAFQAJAEANANQAJALAFAPQAEAOAAAOIgBAJIhqAAQABAJAEAHQAEAHAFAFQAGAFAHACQAHADAGAAQAMAAAKgFQAJgEAJgJIAUASIgLALIgOAJQgIAEgIACQgJACgKAAQgOAAgOgGgAAlgJQAAgIgDgHQgDgIgFgFQgFgFgGgDQgHgDgIAAQgGAAgGADQgHADgFAFQgFAFgDAHQgDAHgBAJIBJAAIAAAAg");
	this.shape_34.setTransform(-57.5,17);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#003E7E").s().p("AgZBnIAAh1IgTAAIAAgdIATAAIAAgKQAAgNADgIQADgKAGgGQAGgGAHgDQAHgCALAAQAOAAANADIAAAdQgKgDgJAAQgKAAgFAEQgFAHAAAKIAAAJIAnAAIAAAcIgmAAIAAB1g");
	this.shape_35.setTransform(-70.9,14.1);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#003E7E").s().p("AgYBHQgOgFgKgLQgLgKgFgOIgFgPIgBgQIAAAAQAAgOAFgPQAGgNAJgLQAKgLANgGIAOgEIANgCQAJAAAIACIAOAFQAJAEANANQAJALAFAPQAEAOAAAOIgBAJIhqAAQABAJAEAHQAEAHAFAFQAGAFAHACQAHADAGAAQAMAAAKgFQAJgEAJgJIAUASIgLALIgOAJQgIAEgIACQgJACgKAAQgOAAgOgGgAAlgJQAAgIgDgHQgDgIgFgFQgFgFgGgDQgHgDgIAAQgGAAgGADQgHADgFAFQgFAFgDAHQgDAHgBAJIBJAAIAAAAg");
	this.shape_36.setTransform(-84.9,17);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#003E7E").s().p("AgpBLIAAiSIAhAAIAAAhQADgIAFgHQAEgHAGgEQAHgGAHgCQAJgCAJAAIAAAkIgCAAQgLAAgJAEQgJADgHAIQgEAHgEALQgEAJAAAOIAAA5g");
	this.shape_37.setTransform(-98.5,16.8);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#003E7E").s().p("AhKBiIAAjCIBLAAQARgBAOAFQANAEALAKQAJAIAFAMQAFAMABAPIAAAAQgBAJgBAHQgCAHgDAGQgFALgMAJQgKAIgPAEQgOAFgOAAIgnAAIAAA/gAgoADIAoAAQAHABAJgDQAHgBAGgFQAGgEADgGQADgHAAgIIAAAAQAAgIgDgIQgDgGgGgEQgFgFgJgCQgHgCgIAAIgoAAg");
	this.shape_38.setTransform(-113.5,14.6);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#003E7E").s().p("AghBJQgKgDgHgGQgHgFgEgJQgFgJAAgLIAAAAQAAgMAFgJQAEgJAJgFQAHgGALgDQALgCANAAQAQgBAXAHIAAgDQAAgIgCgFQgCgHgFgDQgFgFgHgCQgGgCgHAAQgMAAgKACQgJACgLAGIgKgcQAOgGALgCQAPgEAPAAQAQAAAMAEQAMAEAIAIQAJAJAEALQAEAMAAAOIAABWIgiAAIAAgSQgIAJgLAGQgQAGgLAAQgLAAgJgDgAgMAHQgHABgEADQgEADgDAEQgCAFAAAFIAAAAQAAALAIAGQAIAGANAAQAGgBAHgCQAHgCAGgEQAFgEADgGQADgFAAgIIAAgIQgVgGgNAAQgGAAgGACg");
	this.shape_39.setTransform(-140.6,17);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#003E7E").s().p("AgbBHQgVgKgJgHIAPgWQALAIANAFQANAEAJABQALgBAGgEQAGgEAAgIIAAAAQAAgIgKgFQgFgCgQgGQgXgGgIgGQgHgFgEgGQgEgIAAgKIAAgBQAAgKAEgIQAEgJAHgGQAHgGAKgDQAJgDAJAAQAOAAAPAEQAOAFAMAIIgOAYQgLgGgKgFQgLgDgJAAQgIAAgGAEQgFAEAAAHIAAABQAAAHAKAFQAFADAQAFIAQAGQAJAEAGACQAHAFAEAIQAEAHAAAJIAAABQAAALgEAJQgEAJgIAGQgHAGgKADQgKACgMAAQgOAAgQgFg");
	this.shape_40.setTransform(-164,17);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#003E7E").s().p("ABBBiIgUgvIhaAAIgVAvIgiAAIBVjDIAfAAIBVDDgAAhAUIghhMIghBMIBCAAg");
	this.shape_41.setTransform(-181.9,14.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-255.2,0,510.5,59.9);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border728x90 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("Eg4tgG3MBxbAAAIAANvMhxbAAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-364,-45,728,90);


(lib._2016TAG = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIQATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAIYgKQgEAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgFAFgADbATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgADjgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgGAAgFAFgAgpATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAGAIAAAKQAAALgGAIQgIAIgMAAQgMAAgIgIgAgggKQgFAEAAAGQAAAGAFAFQAFAFAGAAQAHAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgHAAgEAFgAtIATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAs/gKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgEAFgAL+AaIgMggIgLAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIALAiIALgiIAMAAIgSAzgAJJADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAAOADIAAgcIAMAAIAAAcQAAANALAAQAMAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgXAAAAgXgAk7ASIAHgIQAIAGAIAAQAHAAAAgFQAAgEgKgCQgJgDgEgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAJAAQAMAAAHAGIgGAJQgIgFgGAAQgGAAAAAEQAAAFALACQARAEAAAKQAAAQgUAAQgNAAgJgIgAsPADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAN5AaIAAgMIAMAAIAAAMgANdAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgANDAaIgFgMIgWAAIgFAMIgMAAIAXgzIAKAAIAXAzgAM6AEIgHgPIgHAPIAOAAgAKiAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgAKOAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAHoAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVgAGsAaIAAgMIAMAAIAAAMgAGQAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAFQAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAE5AaIgZggIAAAgIgLAAIAAgzIAKAAIAZAfIAAgfIALAAIAAAzgAC9AaIAAggIgPAUIgOgUIAAAgIgMAAIAAgzIANAAIANAWIAOgWIANAAIAAAzgABoAaIgMgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgABTAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAhRAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAiNAaIAAgMIAMAAIAAAMgAi2AaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAFQgGAFgJAAIgJAAIAAAQgAiqAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAjOAaIAAgzIALAAIAAAzgAjnAaIAAgVIgVAAIAAAVIgLAAIAAgzIALAAIAAAVIAVAAIAAgVIAMAAIAAAzgAlOAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAliAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAmfAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAnVAaIAAgzIAYAAQAJAAAFAFQADADAAAGIAAAAQAAAIgHADQAKACAAAJQAAAPgTAAgAnKAQIAOAAQAIAAAAgGQAAgGgJAAIgNAAgAnKgEIALAAQAIAAAAgFQAAgGgIAAIgLAAgAntAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgApIAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgApgAaIAAggIgPAUIAAAAIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgAq2AaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgArKAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAtwAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(0,2.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-90.1,0,180.4,5.5);


(lib._2016_SCU_logoruleai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F78E1E").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,0,162.9,1);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib._2016_SCU_BBShorizai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("ArbAhIAAhBIW3AAIAABBg");
	mask.setTransform(73.2,3.4);

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AKoAXIAJgKQAJAHAKAAQAJAAAAgGQAAgDgCgBQgDgCgIgCQgLgDgEgDQgHgDAAgJQABgJAGgFQAGgGAKAAQAOAAAKAIIgHALQgKgGgHAAQgIAAAAAFIAAABQgBAEAOAEQALADAFACQAGAFAAAIQAAAJgHAGQgHAFgKAAQgQAAgMgKgAIwAYQgKgKABgOQgBgMAKgKQAKgKAOAAQAPAAALAKIgJALQgIgIgJAAQgHAAgGAGQgFAGgBAHIAAAAQAAAIAGAGQAFAGAIAAQAKAAAHgIIAJAKQgKALgQAAQgOAAgKgJgAEEAXIAJgKQAKAHAJAAQAKAAAAgGQAAgFgNgDQgMgDgEgDQgGgDAAgJQAAgJAGgFQAHgGAKAAQAOAAAKAIIgHALQgKgGgHAAQgJAAAAAFIAAABQABADACABQADACAJACQAUAFAAANQAAAJgHAGQgGAFgLAAQgPAAgNgKgACrAYQgKgKAAgOQAAgMAKgKQAKgKAOAAQAQAAAKAJIgJALQgIgHgJAAQgIAAgFAGQgFAGAAAHIAAAAQAAAJAFAGQAGAFAIAAQAIAAAGgEIAAgJIgPAAIAAgKIAcAAIAAAaQgMAKgQAAQgOAAgKgJgAk5AXIAJgKQAKAHAKAAQAJAAAAgGQAAgDgDgBIgKgEQgMgDgEgDQgGgDAAgJQAAgJAGgFQAHgGAKAAQAOAAAKAIIgIALQgJgGgHAAQgJAAAAAFIAAABQAAADADABQADACAJACQAKADAFACQAFAFAAAIQAAAJgHAGQgGAFgLAAQgQAAgMgKgAlzAXIAJgKQAKAHAJAAQAJAAAAgGQABgDgDgBIgLgEQgLgDgEgDQgHgDAAgJQABgJAGgFQAHgGAKAAQANAAAKAIIgHALQgJgGgIAAQgIAAAAAFIAAABQAAADACABQADACAJACQAUAFABANQAAAJgHAGQgHAFgKAAQgQAAgMgKgApVAXIAIgKQAKAHAKAAQAJAAAAgGQgBgDgCgBQgCgCgJgCQgKgDgFgDQgGgDAAgJQAAgJAHgFQAGgGAKAAQANAAALAIIgIALQgIgGgIAAQgIAAAAAFIAAABQAAADACABQADACAIACQAVAFAAANQAAAJgGAGQgIAFgKAAQgPAAgMgKgAqZAEIAAgjIAPAAIAAAjQAAAQAOAAQAOAAAAgQIAAgjIAPAAIAAAjQAAAdgdAAQgdAAAAgdgAHZAhIgahAIAQAAIARAsIARgsIAPAAIgbBAgAJuAgIAAg/IAxAAIAAANIgjAAIAAANIAfAAIAAALIgfAAIAAANIAjAAIAAANgAIKAgIAAg/IAPAAIAAA/gAGrAgIgPgVIgLAAIAAAVIgOAAIAAg/IAeAAQAMAAAHAHQAFAFAAAKQAAANgNAFIAPAXgAGRAAIAPAAQAKAAABgJQgBgJgKAAIgPAAgAFEAgIAAg/IAyAAIAAANIgjAAIAAANIAeAAIAAALIgeAAIAAANIAjAAIAAANgACJAgIgggnIAAAnIgOAAIAAg/IANAAIAeAmIAAgmIAPAAIAAA/gAA8AgIAAg/IAPAAIAAA/gAAhAgIgTgcIgIAIIAAAUIgNAAIAAg/IANAAIAAAdIAagdIASAAIgbAcIAcAjgAgiAgIgfgnIAAAnIgPAAIAAg/IAOAAIAeAmIAAgmIAOAAIAAA/gAhpAgIgGgOIgbAAIgHAOIgOAAIAcg/IANAAIAcA/gAh0AFIgJgTIgIATIARAAgAjcAgIAAg/IAdAAQAMAAAGAGQAEAFAAAGIAAAAQAAAKgJAEQANADAAALQAAASgZAAgAjPAUIARAAQALAAgBgHIAAgBQAAgHgKAAIgRAAgAjPgFIAOAAQAKAAAAgGIAAgBQAAgGgJAAIgPAAgAmtAgIAAg/IAxAAIAAANIgjAAIAAANIAfAAIAAALIgfAAIAAANIAjAAIAAANgAnJAgIgfgnIAAAnIgPAAIAAg/IAOAAIAeAmIAAgmIAPAAIAAA/gAoVAgIAAg/IAPAAIAAA/gArbAgIAAg/IAeAAQAMAAAFAGQAFAEAAAHIAAAAQAAAKgIAEQAMADAAALQAAASgZAAgArMAUIAQAAQALAAAAgHIAAgBQAAgHgLAAIgQAAgArMgFIANAAQAKAAAAgGIAAgBQAAgGgKAAIgNAAg");
	this.shape.setTransform(73.2,3.4);

	this.shape.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,146.4,6.8);


// stage content:
(lib.SCU201609_Elec_728x90_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_179 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(179).call(this.frame_179).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.setTransform(708,6,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.setTransform(0,0,2.167,0.321);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},180).wait(1));

	// ncua
	this.instance = new lib.ncuahorizai();
	this.instance.setTransform(472,80,1.11,1.11,0,0,0,0,3.6);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_1 = new lib.border728x90();
	this.instance_1.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({_off:true},180).wait(1));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("AvhG9IAAt5IfDAAIAAN5g");
	var mask_graphics_40 = new cjs.Graphics().p("AvhG9IAAt5IfDAAIAAN5g");
	var mask_graphics_41 = new cjs.Graphics().p("AupG+IAAt6IdUAAIAAN6g");
	var mask_graphics_42 = new cjs.Graphics().p("AtxG/IAAt6IblAAIAAN6g");
	var mask_graphics_43 = new cjs.Graphics().p("As4HBIAAt8IZ0AAIAAN8g");
	var mask_graphics_44 = new cjs.Graphics().p("AsAHCIAAt9IYEAAIAAN9g");
	var mask_graphics_45 = new cjs.Graphics().p("ArIHDIAAt9IWVAAIAAN9g");
	var mask_graphics_46 = new cjs.Graphics().p("AqQHEIAAt+IUlAAIAAN+g");
	var mask_graphics_47 = new cjs.Graphics().p("ApYHGIAAuAIS2AAIAAOAg");
	var mask_graphics_48 = new cjs.Graphics().p("AogHHIAAuAIRGAAIAAOAg");
	var mask_graphics_49 = new cjs.Graphics().p("AnoHHIAAuCIPWAAIAAOCg");
	var mask_graphics_80 = new cjs.Graphics().p("AnoHHIAAuCIPWAAIAAOCg");
	var mask_graphics_81 = new cjs.Graphics().p("AnrHHIAAuCIPXAAIAAOCg");
	var mask_graphics_82 = new cjs.Graphics().p("AnrHHIAAuCIPXAAIAAOCg");
	var mask_graphics_83 = new cjs.Graphics().p("AnrHHIAAuCIPXAAIAAOCg");
	var mask_graphics_84 = new cjs.Graphics().p("AnrHHIAAuCIPXAAIAAOCg");
	var mask_graphics_85 = new cjs.Graphics().p("AnwHHIAAuCIPWAAIAAOCg");
	var mask_graphics_86 = new cjs.Graphics().p("ApUHHIAAuCIPWAAIAAOCg");
	var mask_graphics_87 = new cjs.Graphics().p("Aq4HHIAAuCIPWAAIAAOCg");
	var mask_graphics_88 = new cjs.Graphics().p("AscHHIAAuCIPWAAIAAOCg");
	var mask_graphics_89 = new cjs.Graphics().p("AuAHHIAAuCIPWAAIAAOCg");
	var mask_graphics_90 = new cjs.Graphics().p("AvkHHIAAuCIPYAAIAAOCg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:99.6,y:44.6}).wait(40).to({graphics:mask_graphics_40,x:99.6,y:44.6}).wait(1).to({graphics:mask_graphics_41,x:94,y:44.7}).wait(1).to({graphics:mask_graphics_42,x:88.4,y:44.8}).wait(1).to({graphics:mask_graphics_43,x:82.9,y:44.9}).wait(1).to({graphics:mask_graphics_44,x:77.3,y:45}).wait(1).to({graphics:mask_graphics_45,x:71.7,y:45.2}).wait(1).to({graphics:mask_graphics_46,x:66.2,y:45.3}).wait(1).to({graphics:mask_graphics_47,x:60.6,y:45.4}).wait(1).to({graphics:mask_graphics_48,x:55.1,y:45.5}).wait(1).to({graphics:mask_graphics_49,x:49.5,y:45.5}).wait(31).to({graphics:mask_graphics_80,x:49.5,y:45.5}).wait(1).to({graphics:mask_graphics_81,x:29.7,y:45.5}).wait(1).to({graphics:mask_graphics_82,x:9.7,y:45.5}).wait(1).to({graphics:mask_graphics_83,x:-10.3,y:45.5}).wait(1).to({graphics:mask_graphics_84,x:-30.3,y:45.5}).wait(1).to({graphics:mask_graphics_85,x:-49.8,y:45.5}).wait(1).to({graphics:mask_graphics_86,x:-59.8,y:45.5}).wait(1).to({graphics:mask_graphics_87,x:-69.8,y:45.5}).wait(1).to({graphics:mask_graphics_88,x:-79.8,y:45.5}).wait(1).to({graphics:mask_graphics_89,x:-89.8,y:45.5}).wait(1).to({graphics:mask_graphics_90,x:-99.8,y:45.5}).wait(1).to({graphics:null,x:0,y:0}).wait(90));

	// PIC1
	this.instance_2 = new lib.pic();
	this.instance_2.setTransform(104.2,47.1,1,1,0,0,0,0.2,0.8);

	this.instance_2.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(40).to({scaleX:0.74,scaleY:0.74,x:36.3,y:48.2},9).wait(31).to({x:-163.7},10).to({_off:true},1).wait(90));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_0 = new cjs.Graphics().p("AnzHCIAAuCIPmAAIAAOCg");
	var mask_1_graphics_80 = new cjs.Graphics().p("AnyHCIAAuDIPlAAIAAODg");
	var mask_1_graphics_81 = new cjs.Graphics().p("AnzHBIAAuBIPnAAIAAOBg");
	var mask_1_graphics_82 = new cjs.Graphics().p("AnyHBIAAuBIPlAAIAAOBg");
	var mask_1_graphics_83 = new cjs.Graphics().p("AnyHBIAAuBIPlAAIAAOBg");
	var mask_1_graphics_84 = new cjs.Graphics().p("AnyHBIAAuBIPlAAIAAOBg");
	var mask_1_graphics_85 = new cjs.Graphics().p("AnyHBIAAuBIPlAAIAAOBg");
	var mask_1_graphics_86 = new cjs.Graphics().p("AnyHCIAAuDIPlAAIAAODg");
	var mask_1_graphics_87 = new cjs.Graphics().p("AnyHCIAAuDIPlAAIAAODg");
	var mask_1_graphics_88 = new cjs.Graphics().p("AnyHBIAAuBIPlAAIAAOBg");
	var mask_1_graphics_89 = new cjs.Graphics().p("AnyHBIAAuBIPlAAIAAOBg");
	var mask_1_graphics_90 = new cjs.Graphics().p("AnzHBIAAuBIPnAAIAAOBg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:mask_1_graphics_0,x:149,y:46.1}).wait(80).to({graphics:mask_1_graphics_80,x:149,y:46.1}).wait(1).to({graphics:mask_1_graphics_81,x:129.1,y:46}).wait(1).to({graphics:mask_1_graphics_82,x:109.3,y:45.9}).wait(1).to({graphics:mask_1_graphics_83,x:89.4,y:45.9}).wait(1).to({graphics:mask_1_graphics_84,x:69.6,y:45.8}).wait(1).to({graphics:mask_1_graphics_85,x:49.7,y:45.8}).wait(1).to({graphics:mask_1_graphics_86,x:29.9,y:45.7}).wait(1).to({graphics:mask_1_graphics_87,x:10,y:45.7}).wait(1).to({graphics:mask_1_graphics_88,x:-9.8,y:45.6}).wait(1).to({graphics:mask_1_graphics_89,x:-29.7,y:45.6}).wait(1).to({graphics:mask_1_graphics_90,x:-49.5,y:45.5}).wait(1).to({graphics:null,x:0,y:0}).wait(90));

	// PIC2
	this.instance_3 = new lib._336x280retail();
	this.instance_3.setTransform(99,-3,0.655,0.655);

	this.instance_4 = new lib.Tween14("synched",0);
	this.instance_4.setTransform(154,42.9);
	this.instance_4._off = true;

	this.instance_5 = new lib.Tween15("synched",0);
	this.instance_5.setTransform(-46,42.9);

	this.instance_3.mask = this.instance_4.mask = this.instance_5.mask = mask_1;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_3}]},40).to({state:[{t:this.instance_4}]},40).to({state:[{t:this.instance_5}]},10).to({state:[]},1).wait(90));
	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(80).to({_off:false},0).to({_off:true,x:-46},10).wait(91));

	// PIC shad
	this.instance_6 = new lib.HTML5rastershad_1();
	this.instance_6.setTransform(208.5,55.1,1,1,-90,0,0,0,10);
	this.instance_6.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(80).to({x:8.5},10).to({_off:true},1).wait(90));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_0 = new cjs.Graphics().p("AyvHBIAAuBMAlfAAAIAAOBg");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:mask_2_graphics_0,x:319,y:46.1}).wait(49).to({graphics:null,x:0,y:0}).wait(132));

	// HEAD
	this.instance_7 = new lib.HEAD1();
	this.instance_7.setTransform(564.5,55,1,1,0,0,0,119.5,27);

	this.instance_7.mask = mask_2;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({_off:true},80).wait(101));

	// HEAD2
	this.instance_8 = new lib.HEAD2();
	this.instance_8.setTransform(239.5,58.8,1,1,0,0,0,-1.5,31.9);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(91).to({_off:false},0).to({_off:true},78).wait(12));

	// Close
	this.instance_9 = new lib.Close();
	this.instance_9.setTransform(469.5,37.1,1,1,0,0,0,-1.5,24);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(178).to({_off:false},0).to({_off:true},2).wait(1));

	// shad
	this.instance_10 = new lib.HTML5rastershad_1();
	this.instance_10.setTransform(221,45,1,1,-90,0,0,0,10);
	this.instance_10.alpha = 0.199;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(178).to({_off:false},0).to({_off:true},2).wait(1));

	// head bkgd
	this.instance_11 = new lib.headbkgd();
	this.instance_11.setTransform(168,124.8,1,0.891,0,0,0,168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(80).to({x:-24},9).wait(80).to({x:205},9).to({_off:true},2).wait(1));

	// tag
	this.instance_12 = new lib._2016_SCU_BBShorizai();
	this.instance_12.setTransform(612,76.5,1.158,1.158,0,0,0,73.2,3.4);

	this.instance_13 = new lib._2016TAG();
	this.instance_13.setTransform(105.5,76.4,1.037,1.037,0,0,0,0,2.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_12}]},81).to({state:[{t:this.instance_13},{t:this.instance_12}]},88).to({state:[]},11).wait(1));

	// logo
	this.instance_14 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_14.setTransform(852.4,83,1.116,1.116,0,0,0,215.3,63.1);

	this.instance_15 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_15.setTransform(852.4,83.5,1.116,1.116,0,0,0,215.3,63.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_14,p:{x:852.4}}]},81).to({state:[{t:this.instance_15},{t:this.instance_14,p:{x:345.6}}]},88).to({state:[]},11).wait(1));

	// logo rule
	this.instance_16 = new lib._2016_SCU_logoruleai();
	this.instance_16.setTransform(706,64.5,1.154,1.154,0,0,0,81.4,0.5);

	this.instance_17 = new lib._2016_SCU_logoruleai();
	this.instance_17.setTransform(706,65,1.154,1.154,0,0,0,81.4,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_16,p:{x:706}}]},81).to({state:[{t:this.instance_17},{t:this.instance_16,p:{x:199.3}}]},88).to({state:[]},11).wait(1));

	// shad
	this.instance_18 = new lib.HTML5rastershad_1();
	this.instance_18.setTransform(700,92,1,1,-90,0,0,0,10);
	this.instance_18.alpha = 0.301;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(80).to({y:98},0).to({x:508,y:79.1},9).to({_off:true},81).wait(11));

	// logo box
	this.instance_19 = new lib.box1();
	this.instance_19.setTransform(324.8,29.5,2.165,0.639,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_19).to({_off:true},180).wait(1));

	// EHO
	this.instance_20 = new lib.EqualHousingOpportunityrevai("synched",0);
	this.instance_20.setTransform(466.5,75,0.07,0.07,0,0,0,135,145);
	this.instance_20._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_20).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

	// com
	this.instance_21 = new lib.comhoriz();
	this.instance_21.setTransform(661,82.7,0.687,0.687,0,0,0,0,4.5);
	this.instance_21._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_21).wait(179).to({_off:false},0).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(364,-67.9,728,372.9);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;