(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 250,
	height: 250,
	fps: 18,
	color: "#CCCCCC",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/HTML5rastershad.png", id:"HTML5rastershad"},
		{src:"images/SCU201609_Air_250x250_AdR_atlas_NP_.jpg", id:"SCU201609_Air_250x250_AdR_atlas_NP_"}
	]
};



lib.ssMetadata = [
		{name:"SCU201609_Air_250x250_AdR_atlas_NP_", frames: [[0,0,336,224],[338,0,168,141]]}
];


lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib._336x280air = function() {
	this.spriteSheet = ss["SCU201609_Air_250x250_AdR_atlas_NP_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib._336x280dev = function() {
	this.spriteSheet = ss["SCU201609_Air_250x250_AdR_atlas_NP_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.Tween15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._336x280dev();
	this.instance.setTransform(-84,-70);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-84,-70,168,141);


(lib.Tween11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._336x280air();
	this.instance.setTransform(-151.5,-101,0.902,0.902);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-151.5,-101,303,202);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BFBFBF").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.ncuahorizai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A5AFD4").s().p("AEOAmIADgGQADACAEAAQAGAAADgJIgUgsIAHAAIARAlIAPglIAHAAIgTAuQgFANgLAAQgGAAgEgCgAjbAmIADgGQACACAFAAQAGAAADgJIgVgsIAHAAIARAlIAQglIAHAAIgUAuQgFANgKAAQgGAAgEgCgAIGAXQgGgFAAgGQAAgOAUAAQAFAAAKACIAAgBQgBgNgOAAQgGAAgHAEIgDgGQAIgEAJAAQALAAAEAFQAFAFAAAJIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgEgDgAIHALQAAAKAMAAQAGAAAFgEQAEgDABgGIAAgEQgIgCgGAAQgOAAAAAJgAHLAIIAAgbIAIAAIAAAZQgBAOANAAQAHAAADgEQAFgEAAgHIAAgYIAGAAIAAAsIgGAAIAAgIQgHAJgKAAQgRAAgBgSgAGdATQgHgHAAgKQAAgIAHgHQAHgHAKAAQAKAAAJAIIgFAFQgIgHgGAAQgIAAgEAFQgFAFAAAGIAAAAQAAAIAFAFQAFAFAHAAQAIAAAGgHIAFAEQgIAJgLAAQgKAAgHgHgADfAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgKALAAQAIAAAGAGQAIAHgBAJIAAAAQABALgIAHQgGAGgIAAQgMAAgGgKgADjgJQgEAFAAAGIAAAAQAAAIAEAFQAGAFAGAAQAHAAAFgFQAEgFAAgIQAAgGgEgFQgFgFgHAAQgGAAgGAFgACFAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgACKgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgABQAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgABuAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAgIAVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOALAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgHAAgEgFgAg9ATIADgFQAIAGAIAAQAKAAAAgHQAAgFgMgDQgPgFAAgHQAAgGAFgDQAEgEAHAAQAJAAAIAFIgDAFQgIgEgGAAQgJAAAAAHQAAAEAMADQAPADAAAJQAAAHgFAEQgEADgIAAQgLAAgIgHgAk6AXQgGgFAAgGQAAgIAGgEQAGgCAJAAQAFAAAJACIAAgBQAAgNgOAAQgHAAgHAEIgCgGQAIgEAJAAQAKAAAFAFQAEAFABAJIAAAaIgHAAIAAgHQgGAIgLAAQgHAAgFgDgAk5ALQABAKALAAQAHAAAFgEQAEgDAAgGIAAgEQgHgCgGAAQgOAAgBAJgAmPAUQgHgHAAgLQAAgIAGgHQAHgHAJAAQAKAAAGAHQAGAHAAAIIAAADIglAAQABAHAEAEQAFAEAGAAQAIAAAHgGIAEAEQgIAIgLAAQgKAAgGgGgAlxAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAnLAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgAnGgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgAoAAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQACAPAOAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgAniAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAGDAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAApAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIgBAAQgIAAgEAGQgGAGAAAIIAAASgAhPAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAiHAZIAAgsIAHAAIAAAsgAjwAZIAAg/IAHAAIAAA/gAkHAZIAAg/IAHAAIAAA/gAleAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIAAAAQgIAAgGAGQgFAGAAAIIAAASgAoiAZIAAgmIgGAAIAAgGIAGAAIAAgEQAAgIAEgEQAEgEAGAAIAIABIAAAGIgHgBQgIAAAAAKIAAAEIAPAAIAAAGIgPAAIAAAmgAiIgdIAAgIIAIAAIAAAIg");
	this.shape.setTransform(0,4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.3,0,110.7,8.1);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMAOIAAgbIAZAAIAAAbg");
	this.shape.setTransform(72.7,38.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgUA1QgQgHgGgGIALgRQAIAHAKADQAJAEAHAAQAIAAAFgEQAEgDAAgFIAAgBQAAgFgHgEIgQgGQgQgFgHgEQgFgDgDgFQgDgGAAgHIAAgBQAAgIADgGQADgHAGgEQAEgEAIgDQAHgCAHAAQAKAAAKAEQALADAJAGIgKASQgIgFgIgDQgIgDgHAAQgFABgFADQgEACAAAGIAAAAQAAAFAIAEIAPAGIAMAFQAHADAEABQAGAEACAFQADAGABAHIAAAAQgBAJgDAHQgDAGgFAEQgGAEgHADQgIACgJAAQgJAAgNgEg");
	this.shape_1.setTransform(64.5,34.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgUA1QgPgHgIgGIAMgRQAJAHAJADQAKAEAGAAQAJAAAEgEQAFgDgBgFIAAgBQABgFgIgEIgPgGQgSgFgGgEQgFgDgDgFQgDgGAAgHIAAgBQAAgIADgGQADgHAFgEQAFgEAIgDQAHgCAGAAQALAAAKAEQALADAJAGIgKASQgIgFgIgDQgIgDgHAAQgGABgDADQgFACAAAGIAAAAQAAAFAIAEIAPAGIAMAFQAHADAFABQAFAEADAFQADAGAAAHIAAAAQAAAJgDAHQgDAGgGAEQgGAEgIADQgGACgKAAQgKAAgMgEg");
	this.shape_2.setTransform(54,34.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgSA1QgKgEgIgIQgHgHgEgLIgEgLIgBgMIAAAAQAAgLAEgKQAEgLAHgHQAIgJAJgEIAKgDIAKgBIANABIAKADQAHADAKAKQAHAIADALQADALAAAKIAAAHIhQAAQABAHADAFQADAGAEADQAEAEAFACQAGABAEAAQAJAAAIgDQAGgDAHgHIAPANIgIAJIgLAHIgMAEIgOABQgKAAgLgEgAAcgGQAAgHgDgFQgCgFgDgEQgEgEgFgCQgFgDgGAAQgEAAgFADQgEACgFADQgDAEgCAGQgDAFgBAHIA3AAIAAAAg");
	this.shape_3.setTransform(42.6,34.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAYA4IAAg9QAAgGgCgGQgBgFgDgDQgDgDgFgCQgEgCgGAAQgDAAgFACQgFACgDAEQgDADgCAFQgCAFAAAHIAAA8IgZAAIAAhtIAZAAIAAARQAGgIAIgFIAJgFQAEgBAGAAQAJAAAHADQAIACAFAGQAFAGADAIQACAIAAAKIAABEg");
	this.shape_4.setTransform(29.8,34.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgLBLIAAhsIAXAAIAABsgAgMgzIAAgYIAZAAIAAAYg");
	this.shape_5.setTransform(20.3,32.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgUA1QgQgHgGgGIALgRQAIAHAKADQAJAEAHAAQAIAAAFgEQAEgDAAgFIAAgBQAAgFgHgEIgQgGQgQgFgHgEQgFgDgDgFQgDgGAAgHIAAgBQAAgIADgGQADgHAGgEQAEgEAIgDQAHgCAHAAQAKAAAKAEQALADAJAGIgKASQgIgFgIgDQgIgDgHAAQgFABgFADQgEACAAAGIAAAAQAAAFAIAEIAPAGIAMAFQAHADAEABQAGAEACAFQADAGABAHIAAAAQgBAJgDAHQgDAGgFAEQgGAEgHADQgIACgJAAQgJAAgNgEg");
	this.shape_6.setTransform(11.9,34.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgZA1QgIgDgFgGQgFgFgCgIQgDgIAAgKIAAhEIAZAAIAAA9QAAAGACAFQACAFADAEQADADAEACQAEACAFAAQAFAAAEgCQAFgCADgDQADgEACgFQACgFAAgHIAAg8IAZAAIAABtIgZAAIAAgRQgGAJgHAEQgFADgFABQgDACgHAAQgJAAgHgDg");
	this.shape_7.setTransform(0.2,34.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgFBMQgGgBgFgEQgIgEgGgJIAAARIgaAAIAAiXIAaAAIAAA8QAGgJAJgFQAFgDAFgCQAFgBAFAAQAKAAAJAEQAKAEAHAHQAHAIAEAKQAFANAAAKIgBANIgEALQgEALgHAHQgHAHgKAFQgJADgKAAQgFAAgFgBgAgLgLQgGACgEAFQgFAEgCAFQgDAHAAAIQAAAIADAGQACAHAFAEQAEAFAGACQAGADAFAAQAGAAAGgDQAFgBAFgGQAEgEADgHQACgGAAgIQAAgIgDgHQgCgFgEgEQgFgFgFgCQgGgDgGAAQgFAAgGADg");
	this.shape_8.setTransform(-13,32.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAYBMIAAg/QAAgGgCgFQgBgDgDgEQgDgDgFgCQgEgCgGAAQgDAAgFACQgFACgDAEQgDADgCADQgCAFAAAHIAAA+IgZAAIAAiXIAZAAIAAA8QAGgJAIgFIAJgEQAEgCAGAAQAJAAAHADQAIADAFAGQAFAFADAIQACAIAAAIIAABGg");
	this.shape_9.setTransform(-33,32.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAABFQgGgBgEgEQgEgEgDgGQgCgGAAgJIAAg5IgOAAIAAgWIAOAAIAAgeIAXAAIAAAeIAeAAIAAAWIgeAAIAAA1QAAAHAEADQADADAHAAQAIAAAIgDIAAAUQgFADgGACQgFABgHAAQgHAAgEgCg");
	this.shape_10.setTransform(-44,32.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgLBLIAAhsIAYAAIAABsgAgMgzIAAgYIAZAAIAAAYg");
	this.shape_11.setTransform(-51.2,32.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAYA4IgYhKIgYBKIgXAAIgjhuIAZAAIAXBKIAZhLIATAAIAZBLIAWhKIAaAAIglBug");
	this.shape_12.setTransform(-63.2,34.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgUA1QgPgHgIgFIAMgRQAJAGAJADQAJAEAHAAQAJAAAEgEQAFgCgBgGIAAAAQABgGgIgEIgPgGQgSgFgGgEQgFgDgDgFQgDgGAAgHIAAgBQAAgHADgHQADgGAFgFQAFgEAIgDQAHgCAGAAQALAAALADQAKAEAJAGIgKASQgIgFgIgDQgIgCgHgBQgGAAgDADQgFAEAAAEIAAABQAAAFAIAEIAPAGIANAFQAGADAFABQAFAEADAFQACAGAAAHIAAABQAAAIgCAGQgEAHgFAFQgGAEgIACQgGACgKAAQgJAAgNgEg");
	this.shape_13.setTransform(84.7,13.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgUA1QgQgHgGgFIALgRQAJAGAJADQAKAEAGAAQAIAAAFgEQAEgCABgGIAAAAQAAgGgIgEIgQgGQgRgFgGgEQgFgDgDgFQgDgGAAgHIAAgBQAAgHADgHQADgGAFgFQAGgEAHgDQAHgCAHAAQAJAAAMADQAKAEAJAGIgKASQgIgFgIgDQgJgCgGgBQgFAAgFADQgEAEAAAEIAAABQAAAFAIAEIAPAGIANAFQAGADAEABQAGAEACAFQADAGAAAHIAAABQAAAIgDAGQgCAHgGAFQgGAEgHACQgIACgIAAQgLAAgMgEg");
	this.shape_14.setTransform(74.2,13.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgRA1QgLgEgHgIQgIgHgFgLIgDgLIgBgMIAAAAQAAgLAEgKQAEgLAHgHQAIgJAJgEIALgDIAJgBIAMABIALADQAHADAKAKQAGAIAEALQADALAAAKIAAAHIhPAAQAAAHADAFQADAGAEADQAFAEAFACQAFABAEAAQAJAAAHgDQAIgDAGgHIAPANIgJAJIgKAHIgMAEIgOABQgKAAgKgEgAAcgGQgBgHgCgFQgCgFgEgEQgDgEgFgCQgFgDgGAAQgEAAgFADQgEACgEADQgFAEgCAGQgCAFgBAHIA3AAIAAAAg");
	this.shape_15.setTransform(62.8,13.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAYA4IAAg9QAAgHgCgFQgBgEgDgEQgDgEgFgBQgEgCgGAAQgDAAgFACQgFABgDAEQgDAEgCAFQgCAFAAAGIAAA9IgZAAIAAhtIAZAAIAAARQAGgIAIgGIAJgDQAEgCAGAAQAJAAAHADQAIADAFAFQAFAGADAIQACAIAAAKIAABEg");
	this.shape_16.setTransform(50,13.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgLBMIAAhtIAYAAIAABtgAgMgyIAAgZIAZAAIAAAZg");
	this.shape_17.setTransform(40.5,11.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgUA1QgPgHgIgFIAMgRQAJAGAJADQAJAEAHAAQAJAAAEgEQAFgCgBgGIAAAAQABgGgIgEIgPgGQgSgFgGgEQgFgDgDgFQgDgGAAgHIAAgBQAAgHADgHQADgGAFgFQAFgEAIgDQAHgCAGAAQALAAALADQAKAEAJAGIgKASQgIgFgIgDQgIgCgHgBQgGAAgDADQgFAEAAAEIAAABQAAAFAIAEIAPAGIANAFQAGADAFABQAFAEADAFQACAGABAHIAAABQgBAIgCAGQgEAHgFAFQgGAEgIACQgGACgKAAQgJAAgNgEg");
	this.shape_18.setTransform(32.1,13.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgZA1QgIgDgFgGQgFgFgCgIQgDgIAAgKIAAhEIAZAAIAAA9QAAAGACAFQACAFADAEQADADAEACQAEACAFAAQAFAAAEgCQAFgCADgDQADgEACgFQACgFAAgHIAAg8IAZAAIAABtIgZAAIAAgRQgGAJgHAEQgFADgFABQgDACgHAAQgJAAgHgDg");
	this.shape_19.setTransform(20.4,13.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgFBLQgGgBgFgDQgIgEgGgJIAAARIgaAAIAAiYIAaAAIAAA9QAGgJAJgFQAFgDAFgBQAFgCAFAAQAKAAAJADQAKAFAHAHQAHAIAEAKQAFANAAAJIgBAOIgEALQgEAKgHAIQgHAIgKADQgJAFgKAAQgFAAgFgDgAgLgLQgGACgEAEQgFAFgCAFQgDAHAAAHQAAAIADAIQACAGAFAEQAEAFAGADQAGACAFAAQAGAAAGgCQAFgDAFgFQAEgEADgGQACgIAAgIQAAgHgDgHQgCgFgEgFQgFgEgFgCQgGgDgGAAQgFAAgGADg");
	this.shape_20.setTransform(7.2,11.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAYA4IAAg9QAAgHgCgFQgBgEgDgEQgDgEgFgBQgEgCgGAAQgDAAgFACQgFABgDAEQgDAEgCAFQgCAFAAAGIAAA9IgZAAIAAhtIAZAAIAAARQAGgIAIgGIAJgDQAEgCAGAAQAJAAAHADQAIADAFAFQAFAGADAIQACAIAAAKIAABEg");
	this.shape_21.setTransform(-12.8,13.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgLBMIAAhtIAYAAIAABtgAgMgyIAAgZIAZAAIAAAZg");
	this.shape_22.setTransform(-22.4,11.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgRA1QgLgEgHgIQgIgHgFgLIgDgLIgBgMIAAAAQAAgLAEgKQAEgLAHgHQAIgJAJgEIALgDIAJgBIAMABIALADQAHADAKAKQAGAIAEALQADALAAAKIAAAHIhPAAQAAAHADAFQADAGAEADQAFAEAFACQAFABAEAAQAJAAAHgDQAIgDAGgHIAPANIgJAJIgKAHIgMAEIgOABQgKAAgKgEgAAcgGQgBgHgCgFQgCgFgEgEQgDgEgFgCQgFgDgGAAQgEAAgFADQgEACgEADQgFAEgCAGQgCAFgBAHIA3AAIAAAAg");
	this.shape_23.setTransform(-38,13.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgfA4IAAhtIAaAAIAAAZQACgGADgFQADgFAFgEQAFgDAGgCQAGgCAHAAIAAAbIgCAAQgIAAgHADQgHADgFAFQgDAGgDAIQgCAGAAALIAAAqg");
	this.shape_24.setTransform(-48.2,13.1);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgQASQAKgBAEgFQADgFgBgHIgJAAIAAgcIAaAAIAAAYQAAAHgCAGQgCAHgEAEQgEAEgFACQgFADgIAAg");
	this.shape_25.setTransform(-56,7.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgRA1QgLgEgHgIQgIgHgFgLIgDgLIgBgMIAAAAQAAgLAEgKQAEgLAHgHQAIgJAJgEIALgDIAJgBIAMABIAMADQAGADAKAKQAGAIAEALQADALAAAKIAAAHIhPAAQAAAHADAFQADAGAEADQAFAEAEACQAGABAEAAQAJAAAHgDQAIgDAGgHIAPANIgJAJIgKAHIgMAEIgOABQgKAAgKgEgAAcgGQgBgHgCgFQgCgFgEgEQgDgEgFgCQgFgDgGAAQgEAAgFADQgEACgEADQgFAEgCAGQgCAFgBAHIA3AAIAAAAg");
	this.shape_26.setTransform(-64.9,13.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAkBKIgkhoIgjBoIgWAAIgziSIAcAAIAjBrIAkhsIAUAAIAkBsIAjhrIAbAAIgzCSg");
	this.shape_27.setTransform(-81.4,11.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-170,0,337,46);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMANIAAgZIAYAAIAAAZg");
	this.shape.setTransform(58.9,36.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgJA0IgrhnIAaAAIAaBLIAchLIAZAAIgqBng");
	this.shape_1.setTransform(50.4,32.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgRAyQgJgEgIgHQgHgIgEgJIgDgLIgBgLQAAgKAEgKQAEgJAGgIQAHgHAJgFIAKgDIAJgBIAMABIAKADQAGADAJAKQAHAIADAKQADAKAAAJIAAAHIhLAAQABAGACAFQADAFAEAEQAEADAFABQAFADAEAAQAIAAAHgEQAHgDAGgGIAOANIgIAIIgKAFIgLAFQgGABgHAAQgKAAgKgEgAAagGQAAgGgCgEQgCgGgEgDQgDgFgFgCQgEgBgGAAQgEAAgEABQgFACgDAEIgGAJIgDALIAzAAIAAAAg");
	this.shape_2.setTransform(38.6,32.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgWBFQgJgDgGgIQgIgGgDgLIgEgKIgBgMIAAgBQAAgIAFgNQADgKAIgHQAGgHAJgEQAJgDAJAAIAKACIAKADQAHAFAGAJIAAg4IAYAAIAACOIgYAAIAAgSQgGAJgHAFIgKAEQgGABgEABQgJgBgJgDgAgKgLQgFADgEADQgFAFgCAEQgCAHAAAHIAAABQAAAHACAGQACAHAFAEQAEAEAGACQAFADAEAAQAFAAAGgDQAFgCAFgFQAEgEACgGQADgGAAgHIAAgBQAAgHgDgHQgCgEgEgEQgFgFgFgCQgFgCgGAAQgEAAgGACg");
	this.shape_3.setTransform(25.8,30.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgFBHQgFgBgEgDQgIgFgHgHIAAAQIgYAAIAAiOIAYAAIAAA5QAHgJAIgGIAKgDQAEgCAFAAQAJAAAJADQAIAEAIAHQAGAHAEAKQAFANgBAIIAAABIgBAMIgDAKQgEALgGAGQgIAIgIADQgJADgJABQgFgBgFgBgAgLgLQgFACgEAFQgFAEgCAEQgCAHAAAHIAAABQAAAHACAGQACAHAFAEQAEAEAFACQAGADAFAAQAGAAAFgDQAFgCAFgEQAEgEACgHQACgGAAgHIAAgBQAAgHgDgHQgBgEgFgEQgEgFgFgCQgGgCgFAAQgFAAgGACg");
	this.shape_4.setTransform(7.2,30.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgRAyQgJgEgIgHQgHgIgEgJIgDgLIgBgLQAAgKAEgKQAEgJAGgIQAHgHAJgFIAKgDIAJgBIAMABIAKADQAGADAJAKQAHAIADAKQADAKAAAJIAAAHIhLAAQABAGACAFQADAFAEAEQAEADAFABQAFADAEAAQAIAAAHgEQAHgDAGgGIAOANIgIAIIgKAFIgLAFQgGABgHAAQgKAAgKgEgAAagGQAAgGgCgEQgCgGgEgDQgDgFgFgCQgEgBgGAAQgEAAgEABQgFACgDAEIgGAJIgDALIAzAAIAAAAg");
	this.shape_5.setTransform(-5.7,32.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAWA0IgWhFIgWBFIgWAAIghhnIAYAAIAVBFIAXhFIASAAIAYBFIAVhFIAYAAIgiBng");
	this.shape_6.setTransform(-20.1,32.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgLA1IgKgEQgKgEgIgHQgHgIgEgJIgDgKIgBgLIAAAAQAAgGAEgOQAEgJAHgIQAJgHAJgFIALgDIAKgBQAIAAAOAEQAKAFAHAHQAIAIAEAJQAEAOAAAGIAAAAIgBAKIgDAKQgFALgHAHQgHAHgKAEQgPAFgHAAgAgMgeQgFADgFAFQgEAFgCAFQgDAHABAFIAAAAQgBAGADAGQADAHAEAEQAEAFAFACQAGADAGAAQAGAAAHgDQAFgCAEgFQAEgEADgHQACgFAAgHIAAAAQAAgFgCgHQgCgFgFgFQgEgFgGgDQgGgCgGAAQgGAAgGACg");
	this.shape_7.setTransform(-41,32.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAABBQgGgBgEgEQgEgDgCgGQgCgGAAgJIAAg0IgNAAIAAgVIANAAIAAgdIAWAAIAAAdIAcAAIAAAVIgcAAIAAAxQAAAGAEAEQACADAHAAQAIAAAGgEIAAAUIgJAEIgMABQgHAAgDgCg");
	this.shape_8.setTransform(-51.6,30.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgSAyQgQgHgGgFIALgQQAIAGAJADQAJAEAGgBQAHAAAFgCQAEgDAAgGQAAgFgHgEIgOgGQgQgFgHgDQgEgDgDgFQgDgFAAgHIAAgBQAAgHADgGQADgGAFgEQAFgEAGgCQAIgDAFAAQAKAAAKAEQAKADAIAGIgJAQQgHgFgIgCQgIgDgGAAQgFABgEADQgEACAAAFQAAAFAHAEIAPAGIALAEQAGACAEACQAGADACAFQADAGAAAGIAAABQAAAHgDAHQgDAGgFAEQgGAFgHABQgHACgIAAQgJAAgLgDg");
	this.shape_9.setTransform(108,12.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgdA1IAAhnIAYAAIAAAYQADgGACgFQACgFAFgDQAEgDAHgCQAFgCAHAAIAAAaIgBAAQgJAAgGACQgHADgEAFQgDAFgDAIQgCAGAAAKIAAAog");
	this.shape_10.setTransform(99.6,12.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgRAyQgJgEgIgHQgHgHgEgKIgDgKIgBgMQAAgKAEgKQAEgKAGgHQAHgIAJgDIAKgEIAJgBIAMABIAKAEQAGACAJAKQAHAHADAKQADALAAAJIAAAHIhLAAQABAGACAFQADAFAEADQAEAEAFACQAFABAEAAQAIABAHgEQAHgDAGgGIAOAMIgIAIIgKAHIgLADQgGACgHAAQgKAAgKgEgAAagGQAAgGgCgFQgCgFgEgEQgDgDgFgCQgEgCgGgBQgEABgEACQgFACgDADIgGAJIgDALIAzAAIAAAAg");
	this.shape_11.setTransform(89.1,12.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgKBHIAAhnIAWAAIAABngAgLgwIAAgWIAXAAIAAAWg");
	this.shape_12.setTransform(80.4,10.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgLBHIAAiOIAXAAIAACOg");
	this.shape_13.setTransform(74.8,10.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("Ag1BEIAAiGIAYAAIAAASQAHgJAIgFIAKgEQAEgCAFABQAJgBAJAEQAIAEAIAGQAGAIAEAJQAFAPgBAJIAAAAIgBAMIgDAJQgEAKgGAHQgIAHgIADQgJAEgJAAQgFAAgFgBQgFgCgEgDQgJgEgGgIIAAAvgAgLgtQgFADgEAEQgFAFgCAGQgCAGAAAIIAAAAQAAAHACAGQACAFAFAFQAEAEAFACQAGADAFAAQAGAAAFgDQAFgCAFgEQAEgFACgFQACgGAAgHIAAAAQAAgIgDgGQgCgGgEgFQgEgEgFgDQgGgCgFAAQgFAAgGACg");
	this.shape_14.setTransform(65.6,13.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("Ag0BEIAAiGIAXAAIAAASQAHgJAIgFIAJgEQAFgCAFABQAJgBAJAEQAIAEAHAGQAHAIAEAJQAFAPAAAJIAAAAIgBAMIgEAJQgEAKgHAHQgHAHgIADQgJAEgJAAQgFAAgFgBQgFgCgEgDQgJgEgGgIIAAAvgAgLgtQgFADgEAEQgFAFgBAGQgDAGAAAIIAAAAQAAAHADAGQABAFAFAFQAEAEAFACQAGADAFAAQAFAAAGgDQAFgCAFgEQADgFADgFQACgGAAgHIAAAAQAAgIgCgGQgCgGgFgFQgEgEgFgDQgGgCgFAAQgFAAgGACg");
	this.shape_15.setTransform(52.4,13.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgYAyQgHgDgFgFQgEgFgDgIQgCgHAAgJIAAhBIAXAAIAAA6QAAAGACAFQABAEADAEIAHAFQAFABAEAAQAEAAAEgCQAFgBADgEIAFgIQABgFAAgGIAAg5IAYAAIAABnIgYAAIAAgQQgFAIgHAEQgFADgEABQgDACgGAAQgJAAgHgDg");
	this.shape_16.setTransform(39.3,12.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgSAyQgQgHgGgFIAKgQQAJAGAJADQAIAEAHgBQAHAAAFgCQAEgDAAgGQAAgFgHgEIgOgGQgQgFgGgDQgFgDgDgFQgDgFAAgHIAAgBQAAgHADgGQADgGAFgEQAFgEAGgCQAIgDAGAAQAJAAAKAEQAKADAIAGIgJAQQgIgFgHgCQgIgDgGAAQgFABgEADQgEACAAAFQAAAFAHAEIAPAGIALAEQAGACAEACQAFADADAFQADAGAAAGIAAABQAAAHgDAHQgDAGgFAEQgGAFgGABQgIACgIAAQgJAAgLgDg");
	this.shape_17.setTransform(28.2,12.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAABBQgGgBgDgEQgEgDgDgGQgCgGAAgJIAAg0IgNAAIAAgVIANAAIAAgdIAWAAIAAAdIAcAAIAAAVIgcAAIAAAxQAAAGAEAEQACADAHAAQAHAAAHgEIAAAUIgJAEIgMABQgHAAgDgCg");
	this.shape_18.setTransform(13.3,11.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgRBIIAAhRIgOAAIAAgUIAOAAIAAgIQAAgJACgGQACgHAEgEQAEgEAFgCQAFgCAIAAQAKAAAJADIAAAUQgIgDgGAAQgHAAgDAEQgEAEAAAIIAAAGIAcAAIAAAUIgbAAIAABRg");
	this.shape_19.setTransform(5.9,10.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgXAzQgHgBgFgFQgFgEgDgGQgDgGAAgHIAAgBQAAgIADgHQADgGAGgCQAGgFAIgCQAHgCAJAAQALAAAQAEIAAgCQAAgFgBgFIgFgHIgIgDQgFgCgEAAQgJAAgHACIgOAEIgHgTQAKgEAIgCQAKgDAKAAQALAAAJAEQAJADAFAFQAGAGADAIQADAIAAAKIAAA8IgYAAIAAgMQgGAHgIAEQgKADgIAAQgHAAgHgCgAgIAFIgIADQgDACgBADQgCADAAAEQAAAIAGAEQAFADAJAAQAEAAAFgBQAFgBAEgDQAEgEACgDQACgEAAgFIAAgGQgPgFgJABQgEgBgEACg");
	this.shape_20.setTransform(-4.1,12.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgdA1IAAhnIAYAAIAAAYQADgGACgFQACgFAFgDQAFgDAFgCQAGgCAHAAIAAAaIgBAAQgIAAgHACQgGADgFAFQgDAFgCAIQgDAGAAAKIAAAog");
	this.shape_21.setTransform(-13.2,12.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgEA1IgLgDQgJgEgIgIQgHgHgEgKQgEgKAAgLIAAAAQAAgJAEgLQAEgKAHgHQAIgIAKgDIAKgEIAJgBQAHAAAHABQAGACAFACQAHADAKAKIgPAQQgGgHgGgDQgHgDgIAAQgFAAgFADQgFACgFAFQgEAFgCAGQgCAFAAAGIAAAAQAAAGACAHQACAGAFAEQAEAFAGADQAEACAGAAQAIAAAHgDQAGgEAGgGIAPAOQgLALgHAEIgLADQgHACgHAAg");
	this.shape_22.setTransform(-23.2,12.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgdA1IAAhnIAYAAIAAAYQADgGACgFQACgFAFgDQAEgDAHgCQAFgCAHAAIAAAaIgCAAQgIAAgGACQgHADgEAFQgDAFgDAIQgCAGAAAKIAAAog");
	this.shape_23.setTransform(-32.6,12.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgKBHIAAhnIAWAAIAABngAgLgwIAAgWIAXAAIAAAWg");
	this.shape_24.setTransform(-40,10.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgXAzQgHgBgFgFQgFgEgDgGQgDgGAAgHIAAgBQAAgIADgHQADgGAGgCQAGgFAIgCQAHgCAJAAQALAAAQAEIAAgCQAAgFgBgFIgFgHIgIgDQgFgCgEAAQgJAAgHACIgOAEIgHgTQAKgEAIgCQAKgDAKAAQALAAAJAEQAJADAFAFQAGAGADAIQADAIAAAKIAAA8IgYAAIAAgMQgGAHgIAEQgKADgIAAQgHAAgHgCgAgIAFIgIADQgDACgBADQgCADAAAEQAAAIAGAEQAFADAJAAQAEAAAFgBQAFgBAEgDQAEgEACgDQACgEAAgFIAAgGQgPgFgJABQgEgBgEACg");
	this.shape_25.setTransform(-48.8,12.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AA3A1IAAg5IgBgLQgCgFgDgDQgCgEgEgBQgEgCgFAAQgFAAgEACQgEABgDAEQgDADgCAFQgBAFAAAGIAAA5IgWAAIAAg6QAAgGgCgEQgBgFgDgDQgDgEgEgBQgEgCgFAAQgEAAgFACQgEACgDADQgDADgBAFQgCAFAAAGIAAA5IgYAAIAAhnIAYAAIAAAQQAGgIAHgEIAIgEQAFgCAGAAQAGAAAEACQAFABAEACIAFAGIAFAIQAHgJAIgFQAEgCAFgBIALgCQAJAAAHADQAGADAFAFQAFAFACAHQADAIAAAJIAABBg");
	this.shape_26.setTransform(-69.6,12.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgKA1IgLgDQgKgEgHgIQgIgHgEgKIgDgKIgBgLIAAAAQAAgGAEgOQAEgKAIgHQAHgIALgDIAKgEIAKgBQAIAAANAFQAKADAIAIQAIAIAEAJQAEANAAAHIAAAAIgBALIgDAKQgFAJgHAIQgIAIgKAEQgOAEgHAAgAgMgdQgFACgFAFQgEAFgCAGQgDAFAAAGIAAAAQAAAGADAHQACAFAEAFQAFAFAGADQAFACAGAAQAHAAAFgCQAGgDAFgFQAEgFACgFQACgHAAgGIAAAAQAAgFgDgGQgCgGgEgFQgFgFgFgCQgGgDgGAAQgGAAgGADg");
	this.shape_27.setTransform(-85.5,12.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgdA1IAAhnIAYAAIAAAYQADgGACgFQACgFAFgDQAFgDAFgCQAGgCAHAAIAAAaIgBAAQgIAAgHACQgGADgFAFQgDAFgCAIQgDAGAAAKIAAAog");
	this.shape_28.setTransform(-95.5,12.3);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgyBFIAAiJIBlAAIAAAXIhMAAIAAAlIBDAAIAAAUIhDAAIAAA5g");
	this.shape_29.setTransform(-106.1,10.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-158.5,0,317,43.3);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F78E1E").s().p("AgUA1QgKgDgIgFIAHgOIAOAGQAIACAJABQAEAAAFgCQAEgBAEgEQAEgDABgFQACgFAAgGIAAgHQgHAJgGACIgHAEQgEABgEAAQgHAAgHgDQgHgCgGgFQgFgGgDgHQgDgGAAgJIAAAAQAAgHADgKQADgHAFgGQAGgEAHgDQAHgDAHABIAIAAIAIADQAGAEAGAGIAAgMIATAAIAABBQAAALgCAIQgDAIgFAFIgHAFIgIAEQgMACgGAAQgKAAgKgCgAgIglQgFACgDADQgDADgCAEQgCAFAAAFQAAAFACAEQACAFADABQADADAFACQAFACADAAQAEAAAFgCQAEgCAEgDQAEgBABgFQACgDAAgGIAAAAQAAgFgCgFQgBgEgEgDQgEgDgEgBQgFgCgEAAQgDAAgFABg");
	this.shape.setTransform(92.3,11.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F78E1E").s().p("AASAqIAAguIgBgJQgBgDgCgDIgGgEIgIgBQgCAAgDABQgEABgCADQgDADgCAEQgBAEAAAFIAAAtIgUAAIAAhSIAUAAIAAANQAEgGAGgFIAHgDIAHAAQAIAAAFABQAGADAEAEQADAFACAFQACAGABAIIAAAzg");
	this.shape_1.setTransform(82.2,10.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F78E1E").s().p("AgIA5IAAhSIARAAIAABSgAgJgmIAAgSIATAAIAAASg");
	this.shape_2.setTransform(75,9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F78E1E").s().p("AARA6IgYgkIgLAMIAAAYIgUAAIAAhzIAUAAIAABEIAhgjIAXAAIghAgIAiAyg");
	this.shape_3.setTransform(68.5,9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F78E1E").s().p("AASAqIAAguIgBgJQgBgDgDgDIgFgEIgIgBQgCAAgDABQgEABgDADQgCADgBAEQgCAEAAAFIAAAtIgUAAIAAhSIAUAAIAAANQAEgGAHgFIAGgDIAHAAQAIAAAFABQAFADAFAEQADAFACAFQADAGAAAIIAAAzg");
	this.shape_4.setTransform(58.5,10.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F78E1E").s().p("AgSApQgGgBgEgDQgEgEgCgEQgDgFAAgHQAAgHADgGQACgEAFgCQAEgDAHgCQAGgCAHAAQAJAAANADIAAgBQAAgFgCgCQgBgEgDgDIgGgDIgHgBQgHAAgGABIgLAEIgFgPIAOgGQAIgBAIAAQAJgBAHADQAHADAFAEQAEAFADAGQACAHAAAJIAAAvIgTAAIAAgKQgFAGgGADQgIAEgHAAQgGAAgFgDgAgGADQgEABgDADQgCABgBACQgCADAAADQAAAGAFAEQAFACAHABIAHgBIAHgEQADgCABgEQACgDAAgEIAAgFQgMgDgHAAIgGAAg");
	this.shape_5.setTransform(48.6,10.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F78E1E").s().p("AgtA3IAAhuIAwAAQAKABAHACQAIADAEAEQAEAEACAFQACAEAAAGIAAAAIgBAJQgBAEgDADQgEAGgHADIAJACQAEADADADQADADABAFQACAEAAAFIAAABQAAAHgDAGQgDAFgFAFQgGADgHACQgIACgJAAgAgaAmIAfAAIAJgBIAHgDIAEgEQABgEAAgDQAAgEgBgDQgBgDgDgBQgDgDgFgBIgJgBIgeAAgAgagIIAaAAIAIAAIAGgDQADgCACgDQACgCAAgEIAAgBQgBgDgBgCQgBgDgDgCIgGgDIgIgBIgbAAg");
	this.shape_6.setTransform(38.7,9.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F78E1E").s().p("AgPAoQgMgFgFgEIAIgNQAHAFAIACQAGADAFAAQAGAAAEgCQADgDAAgEQAAgFgFgDIgMgEQgNgEgFgDQgEgCgBgEQgDgEAAgGQAAgGADgFQABgFAEgDQAFgEAFgBQAFgCAFAAQAIAAAIACQAIADAHAEIgIAOQgGgEgGgCQgHgCgEAAQgEAAgDADQgEACAAAEQABAEAFADQADACAJADIAJADIAJADQADADACAEQADAEAAAFIAAABQAAAGgDAFQgCAFgEAEQgEADgGACQgGABgGAAQgIAAgJgDg");
	this.shape_7.setTransform(23.7,10.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F78E1E").s().p("AgPAoQgMgFgFgEIAIgNQAHAFAIACQAGADAFAAQAHAAADgCQADgDAAgEQAAgFgGgDIgKgEQgNgEgFgDQgFgCgBgEQgDgEAAgGQAAgGADgFQABgFAFgDQAEgEAFgBQAGgCAEAAQAIAAAIACQAIADAHAEIgHAOQgHgEgGgCQgHgCgEAAQgEAAgDADQgDACAAAEQAAAEAFADQADACAJADIAJADIAJADQADADACAEQADAEAAAFIAAABQAAAGgDAFQgCAFgEAEQgFADgFACQgFABgIAAQgHAAgJgDg");
	this.shape_8.setTransform(15.7,10.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#F78E1E").s().p("AgNAoQgIgDgGgGQgGgGgDgHIgCgJIgBgJIAAAAQAAgHACgJQADgIAGgGQAFgGAIgDIAIgDIAHAAIAJAAIAIADQAGACAHAIQAFAGACAJQAEAIAAAHIgBAFIg8AAQAAAFADAFIAFAGQADADAFABQAEABACABQAHgBAGgCQAFgDAFgEIALAKIgGAGIgIAFIgJAEIgLABQgHAAgIgEgAAVgFIgCgJQgBgDgDgEQgDgDgEgBQgEgCgEAAQgCAAgFACQgDABgDADIgFAHIgCAJIApAAIAAAAg");
	this.shape_9.setTransform(7,10.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#F78E1E").s().p("AASAqIAAguIgBgJQgBgDgDgDIgFgEIgIgBQgCAAgEABQgDABgDADQgCADgCAEQgBAEAAAFIAAAtIgTAAIAAhSIATAAIAAANQAFgGAFgFIAHgDIAIAAQAGAAAGABQAFADAEAEQAFAFACAFQABAGAAAIIAAAzg");
	this.shape_10.setTransform(-2.8,10.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#F78E1E").s().p("AgIA5IAAhSIARAAIAABSgAgJgmIAAgSIATAAIAAASg");
	this.shape_11.setTransform(-10,9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#F78E1E").s().p("AgPAoQgMgFgFgEIAIgNQAHAFAHACQAIADAEAAQAGAAAEgCQADgDAAgEQAAgFgGgDIgKgEQgOgEgEgDQgEgCgDgEQgCgEAAgGQAAgGACgFQADgFAEgDQAEgEAFgBQAFgCAFAAQAIAAAIACQAIADAHAEIgHAOQgHgEgGgCQgGgCgFAAQgEAAgDADQgDACAAAEQgBAEAHADQADACAIADIAJADIAIADQAFADACAEQACAEAAAFIAAABQAAAGgCAFQgDAFgEAEQgEADgGACQgFABgIAAQgGAAgKgDg");
	this.shape_12.setTransform(-16.4,10.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#F78E1E").s().p("AgTAoQgGgCgEgEQgEgFgCgGQgCgGAAgHIAAg0IAUAAIAAAuQAAAFABAEQACAEACADQACACADACIAHABQADAAAEgCQADgBADgDQADgCABgEIABgJIAAguIAUAAIAABTIgUAAIAAgNQgEAHgGADIgIADQgCACgEAAQgIAAgFgDg");
	this.shape_13.setTransform(-25.3,10.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#F78E1E").s().p("AgtA3IAAhuIAwAAQAKABAHACQAIADAEAEQAEAEACAFQACAEAAAGIAAAAIgBAJQgBAEgDADQgEAGgHADIAJACQAEADADADQADADABAFQACAEAAAFIAAABQAAAHgDAGQgDAFgFAFQgGADgHACQgIACgJAAgAgaAmIAfAAIAJgBIAHgDIAEgEQABgEAAgDQAAgEgBgDQgCgDgCgBQgDgDgEgBIgKgBIgeAAgAgagIIAaAAIAIAAIAGgDQADgCABgDQADgCAAgEIAAgBQAAgDgCgCQgBgDgDgCIgGgDIgJgBIgaAAg");
	this.shape_14.setTransform(-35.7,9.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#F78E1E").s().p("AgSA4QgGgDgGgFQgGgHgDgIIgCgIIgBgKIAAgBQAAgGADgKQADgIAGgGQAGgFAGgDQAIgDAHAAIAHABIAIAEQAGADAGAHIAAguIATAAIAABzIgTAAIAAgOQgGAHgGAEIgIADQgEACgDAAQgHAAgIgDgAgHgJQgFADgDADQgEADgCADQgBAFAAAGIAAABQAAAGABAFQACAFAEADQADAEAFACQAEACADAAQAFAAAEgCQAEgCAEgEQADgDACgFQACgFAAgGIAAgBQAAgGgCgFQgCgDgDgDQgEgDgEgDQgEgCgFAAQgEAAgDACg");
	this.shape_15.setTransform(-52.1,9.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#F78E1E").s().p("AASAqIAAguIgBgJQgBgDgDgDIgFgEIgIgBQgCAAgEABQgDABgDADQgCADgCAEQgBAEAAAFIAAAtIgTAAIAAhSIATAAIAAANQAFgGAFgFIAHgDIAIAAQAGAAAGABQAFADAEAEQAFAFACAFQABAGAAAIIAAAzg");
	this.shape_16.setTransform(-62.2,10.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#F78E1E").s().p("AgTAoQgFgCgFgEQgEgFgBgGQgCgGAAgHIAAg0IATAAIAAAuQAAAFACAEQABAEACADQACACAEACIAGABQAEAAADgCQADgBADgDQACgCACgEIABgJIAAguIATAAIAABTIgTAAIAAgNQgEAHgGADIgHADQgCACgFAAQgIAAgFgDg");
	this.shape_17.setTransform(-72.2,10.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#F78E1E").s().p("AgIArIgJgDQgIgDgGgHQgGgGgDgHIgDgIIgBgJQABgFADgKQADgJAGgGQAGgGAIgDIAJgDIAIAAQAGAAALACQAJAEAGAGQAGAGADAIQADALAAAFIAAAAIAAAIIgDAJQgDAHgGAGQgGAHgJADQgLAEgGAAgAgJgYQgFADgDADQgEAEgCAFQgBAFAAAEIAAAAQAAAFACAFQABAFAEAEQAEADAFADQAEACAEAAQAFAAAFgCQAFgDADgDQAEgEACgFQABgFAAgFQAAgEgBgFQgCgFgEgDQgEgFgEgCQgFgCgFAAQgEAAgFACg");
	this.shape_18.setTransform(-82.3,10.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#F78E1E").s().p("AgIA4IgMgEQgGgCgFgDIgLgIIAMgOQAFAEALAHIAJADIAIABIAJgBIAGgDIAEgEIABgHIgBgFIgEgEQgCgDgFgBIgLgEIgQgEQgHgEgFgBQgFgEgCgFQgCgFAAgJQAAgGACgHQADgFAFgFQAGgFAGgCQAIgCAHAAIALABIAKACQAHADALAIIgKAPQgIgGgHgDQgIgCgGAAIgHABIgGACQgFAEAAAFIAAABIABAGIAFAEIAIAEIALADIAPAGQAHACAFACQAEAEADAFQACAFAAAIQAAAHgDAHQgDAGgFAEQgGAEgHADQgHACgJAAIgLgBg");
	this.shape_19.setTransform(-92.8,9.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-167,0,334,20);


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A5AFD4").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.Close = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJAKIAAgTIATAAIAAATg");
	this.shape.setTransform(97.6,29.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgXArIAAhTIATAAIAAATQACgFACgDQACgEAEgDQADgDAFgBQAFgCAFABIAAAUIgBAAQgGAAgGACQgFACgEAEQgCAFgCAGQgCAEAAAJIAAAgg");
	this.shape_1.setTransform(92.5,26.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNAoQgIgDgGgGQgGgFgDgIIgDgJIgBgJIAAAAQAAgIAEgIQADgIAFgGQAGgGAHgDIAIgDIAHAAIAJAAIAJADQAEACAIAIQAFAGACAJQADAHAAAIIAAAFIg8AAQAAAFADAEIAFAHQADADAEABQAFACACAAQAHAAAGgDQAFgCAFgFIALAKIgGAGIgIAFIgKADIgKABQgHAAgIgDgAAVgEIgCgJQgCgEgCgEQgDgDgEgBQgEgCgEAAQgCAAgFACQgDABgDADIgFAIIgDAJIAqAAIAAAAg");
	this.shape_2.setTransform(84.1,26.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAAA0QgEgBgDgCQgEgDgBgFQgCgFAAgHIAAgqIgLAAIAAgRIALAAIAAgXIARAAIAAAXIAXAAIAAARIgXAAIAAAnQAAAFADADQADACAFAAQAGAAAGgCIAAAQIgIADIgKABQgFAAgDgCg");
	this.shape_3.setTransform(75.8,25.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgPAoQgMgFgFgEIAJgNQAGAFAHACQAIADAEAAQAGAAAEgCQADgDAAgEQAAgFgFgDIgMgEQgMgEgGgDQgDgCgCgEQgDgEAAgGQAAgGADgFQACgFADgDQAFgEAFgBQAFgCAFAAQAIAAAIACQAJADAGAEIgIAOQgGgEgGgCQgGgCgFAAQgEAAgDADQgEACAAAEQABAEAFADQADACAJADIAJADIAIADQAFADABAEQADAEAAAFIAAABQAAAGgDAFQgCAFgEAEQgEADgGACQgGABgGAAQgIAAgJgDg");
	this.shape_4.setTransform(68.6,26.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgSApQgGgBgEgDQgEgEgCgEQgDgGAAgGQAAgHADgGQACgEAFgCQAEgEAHgBQAGgCAHAAQAJAAANAEIAAgCQAAgEgCgDQgBgEgDgDIgGgDIgHgBQgHAAgGACIgLADIgFgPIAOgFQAIgCAIAAQAJAAAHACQAHADAFAEQAEAFADAGQACAHAAAJIAAAvIgTAAIAAgKQgFAFgGAEQgIADgHAAQgGAAgFgCgAgGADQgEABgDACQgCACgBADQgCACAAADQAAAGAFADQAFAEAHAAIAHgBIAHgEQADgCABgEQACgDAAgEIAAgFQgMgDgHAAIgGAAg");
	this.shape_5.setTransform(59.8,26.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgOA6IAAhCIgLAAIAAgQIALAAIAAgGQAAgHACgFQACgFADgEQADgDAEgCQAEgBAGAAQAIAAAHACIAAAQQgFgCgGAAQgFAAgDADQgDADAAAHIAAAEIAWAAIAAAQIgVAAIAABCg");
	this.shape_6.setTransform(52.5,24.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgIA4IgMgDQgGgCgFgEIgLgIIAMgOQAFAFALAGIAJACIAIABIAJgBIAGgCIAEgEIABgGIgBgGIgEgEQgCgCgFgCIgLgEIgQgFQgHgDgFgBQgFgEgCgFQgCgFAAgJQAAgGACgHQADgGAFgEQAGgEAGgCQAIgDAHAAIALABIAKACQAHADALAIIgKAPQgIgGgHgCQgIgDgGAAIgHABIgGACQgFAEAAAGIAAAAIABAGIAFAEIAIAEIALADIAPAGQAHACAFACQAEAEADAFQACAFAAAIQAAAHgDAHQgDAGgFAEQgGAEgHADQgHACgJAAIgLgBg");
	this.shape_7.setTransform(39.3,25.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgoA3IAAhtIBRAAIAAARIg+AAIAAAdIA2AAIAAAQIg2AAIAAAeIA+AAIAAARg");
	this.shape_8.setTransform(29.2,25.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgIA3IAAgsIgthBIAXAAIAeAxIAfgxIAXAAIgtBBIAAAsg");
	this.shape_9.setTransform(17.9,25.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgIAqIgJgCQgHgEgHgGQgGgFgDgJIgDgHIgBgJQAAgFAEgKQADgIAHgHQAGgGAHgDIAJgDIAIAAQAGAAALACQAJAEAGAGQAGAGADAIQAEALgBAFIAAAAIgBAIIgCAIQgDAJgGAFQgGAGgJAEQgLADgGAAgAgJgXQgFACgDADQgDAEgCAEQgCAGAAAEIAAAAQAAAFACAFQACAFADAEQAEADAEACQAFACAEABQAFgBAGgCQAEgCADgDQAEgEACgFQABgFAAgFQAAgEgBgFQgDgFgDgEQgEgEgEgBQgFgDgFAAQgEAAgFADg");
	this.shape_10.setTransform(2.1,26.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAAA0QgEgBgDgCQgEgDgBgFQgCgFAAgHIAAgqIgLAAIAAgRIALAAIAAgXIARAAIAAAXIAXAAIAAARIgXAAIAAAnQAAAFADADQADACAFAAQAGAAAGgCIAAAQIgIADIgKABQgFAAgDgCg");
	this.shape_11.setTransform(-6.5,25.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAAA0QgEgBgDgCQgEgDgBgFQgCgFAAgHIAAgqIgLAAIAAgRIALAAIAAgXIARAAIAAAXIAXAAIAAARIgXAAIAAAnQAAAFADADQADACAFAAQAGAAAGgCIAAAQIgIADIgKABQgFAAgDgCg");
	this.shape_12.setTransform(-17.9,25.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgNAoQgIgDgGgGQgGgFgDgIIgDgJIgBgJIAAAAQAAgIAEgIQADgIAFgGQAFgGAIgDIAIgDIAHAAIAKAAIAIADQAEACAIAIQAFAGACAJQADAHAAAIIAAAFIg8AAQABAFACAEIAFAHQAEADADABQAEACADAAQAHAAAFgDQAGgCAFgFIAMAKIgHAGIgIAFIgKADIgKABQgHAAgIgDgAAVgEIgCgJQgBgEgEgEQgCgDgEgBQgEgCgEAAQgDAAgDACQgEABgDADIgFAIIgDAJIAqAAIAAAAg");
	this.shape_13.setTransform(-25.8,26.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgUA1QgKgDgIgFIAHgOIAOAGQAIACAIAAQAFAAAFgBQAEgCAEgDQADgDACgFQACgFAAgGIAAgHQgHAJgFACIgIADQgEACgDAAQgIAAgHgDQgHgDgFgFQgGgFgDgHQgDgFAAgKIAAAAQAAgHADgKQADgHAGgFQAFgFAHgDQAHgCAIAAIAHABIAIACQAGAEAGAGIAAgMIATAAIAABBQAAALgCAIQgDAHgFAGIgHAFIgIAEQgNACgFAAQgKABgKgDgAgIglQgEACgEADQgDADgCAEQgBAEAAAGQAAAFABAEQACAFADABQAEADAEABQAFADADAAQAEAAAFgDQAEgBAEgDQADgBACgFQACgEAAgFIAAAAQAAgFgCgFQgCgEgDgDQgEgDgEgBQgFgCgEgBQgDAAgFACg");
	this.shape_14.setTransform(-36.2,27.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AASAqIAAgtIgBgJQgBgEgCgDIgGgEIgIgBQgCAAgEACQgDABgCACQgDADgCAEQgBAEAAAFIAAAtIgUAAIAAhSIAUAAIAAANQAFgHAFgEIAHgCIAHgBQAIAAAFACQAFACAFAEQADAEACAHQACAFAAAIIAAAzg");
	this.shape_15.setTransform(-51.1,26.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgSApQgGgBgEgDQgEgEgCgEQgDgGAAgGQAAgHADgGQACgEAFgCQAEgEAHgBQAGgCAHAAQAJAAANAEIAAgCQAAgEgCgDQgBgEgDgDIgGgDIgHgBQgHAAgGACIgLADIgFgPIAOgFQAIgCAIAAQAJAAAHACQAHADAFAEQAEAFADAGQACAHAAAJIAAAvIgTAAIAAgKQgFAFgGAEQgIADgHAAQgGAAgFgCgAgGADQgEABgDACQgCACgBADQgCACAAADQAAAGAFADQAFAEAHAAIAHgBIAHgEQADgCABgEQACgDAAgEIAAgFQgMgDgHAAIgGAAg");
	this.shape_16.setTransform(-61,26.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgDAqIgIgCQgIgEgGgGQgGgFgDgJQgEgIAAgIQAAgIAEgHQADgIAGgHQAGgGAIgDIAIgDIAHAAIALABIAJACQAGADAIAIIgMANQgFgFgFgDQgFgDgHAAQgEAAgEADQgEACgDADQgEAEgCAEQgBAGAAAEIAAAAQAAAFACAFQABAFAEAEQADADAFACQADACAFABQAGgBAGgDQAFgCAFgFIAMAMQgJAIgGADIgJADIgLABg");
	this.shape_17.setTransform(-69.9,26.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgNAoQgIgDgGgGQgGgFgDgIIgCgJIgCgJIAAAAQABgIADgIQADgIAFgGQAGgGAHgDIAIgDIAHAAIAJAAIAIADQAFACAIAIQAFAGACAJQADAHABAIIgBAFIg8AAQAAAFADAEIAFAHQADADAEABQAEACADAAQAHAAAGgDQAFgCAFgFIALAKIgGAGIgIAFIgKADIgKABQgHAAgIgDgAAVgEIgCgJQgBgEgDgEQgDgDgEgBQgEgCgEAAQgDAAgEACQgDABgDADIgFAIIgCAJIApAAIAAAAg");
	this.shape_18.setTransform(-84.1,26.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AASAqIgSg3IgRA3IgSAAIgbhTIAUAAIARA4IASg4IAPAAIATA4IARg4IATAAIgbBTg");
	this.shape_19.setTransform(-95.9,26.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgMAOQAIgBADgEQABgEAAgFIgGAAIAAgVIATAAIAAATQAAAEgCAFQgBAFgDADQgDADgEACIgKACg");
	this.shape_20.setTransform(106.2,14.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgXArIAAhTIATAAIAAATQACgFACgDQACgEAEgDQADgDAFgBQAFgCAFABIAAAUIgBAAQgGAAgGACQgFACgEAEQgCAFgCAGQgCAEAAAJIAAAgg");
	this.shape_21.setTransform(101.4,10.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgNAoQgIgDgGgGQgGgGgDgHIgDgJIgBgJIAAAAQAAgHAEgJQADgIAFgGQAFgGAIgDIAIgDIAHAAIAKAAIAIADQAEACAIAIQAFAGADAJQACAIAAAHIAAAFIg8AAQABAFACAFIAFAGQAEADADABQAEABADABQAHgBAFgCQAGgDAFgEIAMAKIgHAGIgIAFIgKAEIgKABQgHAAgIgEgAAVgFIgCgJQgBgDgEgEQgCgDgEgBQgEgCgEAAQgDAAgDACQgEABgDADIgFAHIgDAJIAqAAIAAAAg");
	this.shape_22.setTransform(93,10.6);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgSA4QgGgDgGgFQgGgHgDgIIgDgIIAAgKIAAgBQAAgGADgKQADgIAGgGQAGgFAGgDQAIgDAHAAIAIABIAIAEQAFADAGAHIAAguIATAAIAABzIgTAAIAAgOQgGAHgFAEIgIADQgFACgDAAQgHAAgIgDgAgIgJQgEADgEADQgDADgBADQgCAFAAAGIAAABQAAAGACAFQABAFADADQAEAEAEACQAFACADAAQAEAAAFgCQAEgCAEgEQADgDACgFQACgFAAgGIAAgBQAAgGgCgFQgCgDgDgDQgEgDgEgDQgFgCgEAAQgDAAgFACg");
	this.shape_23.setTransform(82.6,9.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AASAqIAAguIgBgJQgBgDgDgDIgFgEIgIgBQgCAAgDABQgEABgDADQgCADgBAEQgCAEAAAFIAAAtIgUAAIAAhSIAUAAIAAANQAEgGAHgFIAGgDIAHAAQAIAAAFABQAGADAEAEQADAFADAFQACAGAAAIIAAAzg");
	this.shape_24.setTransform(72.5,10.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgNAoQgIgDgGgGQgGgGgDgHIgDgJIgBgJIAAAAQAAgHADgJQADgIAGgGQAGgGAHgDIAIgDIAHAAIAKAAIAIADQAEACAIAIQAFAGADAJQACAIAAAHIAAAFIg8AAQABAFACAFIAFAGQAEADADABQAEABADABQAHgBAFgCQAGgDAFgEIAMAKIgHAGIgIAFIgKAEIgKABQgHAAgIgEgAAVgFIgCgJQgBgDgEgEQgCgDgEgBQgDgCgFAAQgDAAgDACQgEABgDADIgFAHIgDAJIAqAAIAAAAg");
	this.shape_25.setTransform(62.7,10.6);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgmA3IAAhuIAUAAIAABcIA5AAIAAASg");
	this.shape_26.setTransform(53.3,9.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAlA4IgLgbIgzAAIgMAbIgUAAIAxhvIARAAIAxBvgAATALIgTgrIgSArIAlAAg");
	this.shape_27.setTransform(36.9,9.2);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgtA3IAAhuIAwAAQAJABAIACQAHADAGAEQADAEACAFQACAEAAAGIAAAAIgCAJQAAAEgDADQgEAGgHADIAJACQAEADADADQADADACAFQABAEAAAFIAAABQAAAHgDAGQgCAFgGAFQgGADgHACQgIACgJAAgAgZAmIAeAAIAJgBIAHgDIAEgEQABgEABgDQgBgEgBgDQgCgDgCgBQgDgDgFgBIgKgBIgcAAgAgZgIIAZAAIAIAAIAHgDQADgCAAgDQACgCAAgEIAAgBQABgDgCgCQgCgDgCgCIgGgDIgJgBIgZAAg");
	this.shape_28.setTransform(25.1,9.2);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgIA4IgMgEQgGgCgFgDIgLgIIAMgOQAFAEALAHIAJADIAIABIAJgBIAGgDIAEgEIABgHIgBgFIgEgEQgCgDgFgBIgLgEIgQgEQgHgEgFgBQgFgEgCgFQgCgFAAgJQAAgGACgHQADgFAFgFQAGgFAGgCQAIgCAHAAIALABIAKACQAHADALAIIgKAPQgIgGgHgDQgIgCgGAAIgHABIgGACQgFAEAAAFIAAABIABAGIAFAEIAIAEIALADIAPAGQAHACAFACQAEAEADAFQACAFAAAIQAAAHgDAHQgDAGgFAEQgGAEgHADQgHACgJAAIgLgBg");
	this.shape_29.setTransform(13.8,9.2);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgRA4QgIgDgFgFQgGgHgDgIIgDgIIAAgKIAAgBQAAgGADgKQADgIAGgGQAFgFAIgDQAGgDAIAAIAHABIAIAEQAHADAFAHIAAguIATAAIAABzIgTAAIAAgOQgFAHgHAEIgIADQgEACgDAAQgIAAgGgDgAgHgJQgFADgDADQgEADgCADQgCAFAAAGIAAABQAAAGACAFQACAFAEADQADAEAFACQAEACADAAQAEAAAFgCQAFgCADgEQADgDACgFQACgFAAgGIAAgBQAAgGgCgFQgCgDgDgDQgDgDgFgDQgFgCgEAAQgEAAgDACg");
	this.shape_30.setTransform(-1.5,9.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgNAoQgIgDgGgGQgGgGgDgHIgCgJIgBgJIAAAAQAAgHACgJQADgIAGgGQAFgGAIgDIAIgDIAHAAIAJAAIAIADQAGACAHAIQAFAGACAJQAEAIAAAHIgBAFIg8AAQAAAFADAFIAFAGQADADAFABQAEABACABQAHgBAGgCQAFgDAFgEIALAKIgGAGIgIAFIgJAEIgLABQgHAAgIgEgAAVgFIgCgJQgBgDgDgEQgDgDgEgBQgEgCgEAAQgCAAgFACQgDABgDADIgFAHIgCAJIApAAIAAAAg");
	this.shape_31.setTransform(-11.5,10.6);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgXArIAAhTIATAAIAAATQACgFACgDQACgEAEgDQADgDAFgBQAFgCAFABIAAAUIgBAAQgGAAgGACQgFACgEAEQgCAFgCAGQgCAEAAAJIAAAgg");
	this.shape_32.setTransform(-19.3,10.5);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgXArIAAhTIATAAIAAATQACgFACgDQACgEAEgDQADgDAFgBQAFgCAFABIAAAUIgBAAQgGAAgGACQgFACgEAEQgCAFgCAGQgCAEAAAJIAAAgg");
	this.shape_33.setTransform(-25.9,10.5);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgNAoQgIgDgGgGQgGgGgDgHIgCgJIgBgJIAAAAQAAgHACgJQADgIAGgGQAFgGAIgDIAIgDIAHAAIAJAAIAIADQAGACAHAIQAFAGADAJQADAIAAAHIgBAFIg8AAQAAAFADAFIAFAGQAEADAEABQAEABACABQAHgBAFgCQAGgDAFgEIALAKIgGAGIgIAFIgJAEIgLABQgHAAgIgEgAAVgFIgCgJQgCgDgDgEQgCgDgEgBQgDgCgFAAQgCAAgFACQgDABgDADIgFAHIgCAJIApAAIAAAAg");
	this.shape_34.setTransform(-34.3,10.6);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgOA6IAAhCIgLAAIAAgQIALAAIAAgGQAAgHACgFQACgFADgEQADgDAEgCQAEgBAGAAQAIAAAHACIAAAQQgFgCgGAAQgFAAgDADQgDADAAAHIAAAEIAWAAIAAAQIgVAAIAABCg");
	this.shape_35.setTransform(-42,8.9);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgNAoQgIgDgGgGQgGgGgDgHIgDgJIAAgJIAAAAQAAgHACgJQADgIAGgGQAGgGAHgDIAIgDIAHAAIAKAAIAHADQAGACAHAIQAFAGADAJQACAIAAAHIAAAFIg8AAQABAFACAFIAFAGQADADAFABQAEABACABQAHgBAFgCQAGgDAFgEIAMAKIgHAGIgIAFIgJAEIgLABQgHAAgIgEgAAVgFIgCgJQgCgDgDgEQgCgDgEgBQgDgCgFAAQgDAAgDACQgEABgDADIgFAHIgDAJIAqAAIAAAAg");
	this.shape_36.setTransform(-50,10.6);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgXArIAAhTIATAAIAAATQACgFACgDQACgEAEgDQADgDAFgBQAFgCAFABIAAAUIgBAAQgGAAgGACQgFACgEAEQgCAFgCAGQgCAEAAAJIAAAgg");
	this.shape_37.setTransform(-57.8,10.5);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgqA3IAAhuIAqAAQAKABAIACQAIADAFAFQAGAFADAGQADAIAAAIIAAAAIgBAJIgDAIQgDAFgGAFQgGAEgIADQgJACgHAAIgWAAIAAAkgAgWACIAWAAQAEAAAFgCQAEAAADgCIAFgGIACgIIAAgBQAAgEgCgEQgCgEgDgCQgDgDgEgCIgJAAIgWAAg");
	this.shape_38.setTransform(-66.3,9.2);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgSApQgGgBgEgDQgEgEgCgEQgDgFAAgHQAAgHADgGQACgEAFgCQAEgDAHgCQAGgCAHAAQAJAAANADIAAgBQAAgFgCgCQgBgEgDgDIgGgDIgHgBQgHAAgGABIgLAEIgFgPIAOgGQAIgBAIAAQAJgBAHADQAHADAFAEQAEAFADAGQACAHAAAJIAAAvIgTAAIAAgKQgFAGgGADQgIAEgHAAQgGAAgFgDgAgGADQgEABgDADQgCABgBACQgCADAAADQAAAGAFAEQAFACAHABIAHgBIAHgEQADgCABgEQACgDAAgEIAAgFQgMgDgHAAIgGAAg");
	this.shape_39.setTransform(-81.8,10.6);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgPAoQgMgFgFgEIAIgNQAHAFAIACQAGADAFAAQAGAAAEgCQADgDAAgEQAAgFgFgDIgMgEQgNgEgFgDQgEgCgBgEQgDgEAAgGQAAgGADgFQABgFAEgDQAFgEAFgBQAFgCAFAAQAIAAAIACQAIADAHAEIgIAOQgGgEgGgCQgHgCgEAAQgEAAgDADQgEACAAAEQABAEAFADQADACAJADIAJADIAJADQADADACAEQADAEAAAFIAAABQAAAGgDAFQgCAFgEAEQgFADgFACQgGABgHAAQgHAAgJgDg");
	this.shape_40.setTransform(-95.1,10.6);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AAlA4IgLgbIgzAAIgMAbIgUAAIAxhvIARAAIAxBvgAATALIgTgrIgSArIAlAAg");
	this.shape_41.setTransform(-105.3,9.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-170,0,337,36);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border336x280 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("AzXzXMAmvAAAMAAAAmvMgmvAAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-125,-125,250,250);


(lib._2016TAG = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIQATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAIYgKQgEAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgFAFgADbATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgADjgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgGAAgFAFgAgpATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAGAIAAAKQAAALgGAIQgIAIgMAAQgMAAgIgIgAgggKQgFAEAAAGQAAAGAFAFQAFAFAGAAQAHAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgHAAgEAFgAtIATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAs/gKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgEAFgAL+AaIgMggIgLAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIALAiIALgiIAMAAIgSAzgAJJADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAAOADIAAgcIAMAAIAAAcQAAANALAAQAMAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgXAAAAgXgAk7ASIAHgIQAIAGAIAAQAHAAAAgFQAAgEgKgCQgJgDgEgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAJAAQAMAAAHAGIgGAJQgIgFgGAAQgGAAAAAEQAAAFALACQARAEAAAKQAAAQgUAAQgNAAgJgIgAsPADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAN5AaIAAgMIAMAAIAAAMgANdAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgANDAaIgFgMIgWAAIgFAMIgMAAIAXgzIAKAAIAXAzgAM6AEIgHgPIgHAPIAOAAgAKiAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgAKOAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAHoAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVgAGsAaIAAgMIAMAAIAAAMgAGQAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAFQAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAE5AaIgZggIAAAgIgLAAIAAgzIAKAAIAZAfIAAgfIALAAIAAAzgAC9AaIAAggIgPAUIgOgUIAAAgIgMAAIAAgzIANAAIANAWIAOgWIANAAIAAAzgABoAaIgMgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgABTAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAhRAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAiNAaIAAgMIAMAAIAAAMgAi2AaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAFQgGAFgJAAIgJAAIAAAQgAiqAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAjOAaIAAgzIALAAIAAAzgAjnAaIAAgVIgVAAIAAAVIgLAAIAAgzIALAAIAAAVIAVAAIAAgVIAMAAIAAAzgAlOAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAliAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAmfAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAnVAaIAAgzIAYAAQAJAAAFAFQADADAAAGIAAAAQAAAIgHADQAKACAAAJQAAAPgTAAgAnKAQIAOAAQAIAAAAgGQAAgGgJAAIgNAAgAnKgEIALAAQAIAAAAgFQAAgGgIAAIgLAAgAntAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgApIAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgApgAaIAAggIgPAUIAAAAIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgAq2AaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgArKAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAtwAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(0,2.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-90.1,0,180.4,5.5);


(lib._2016_SCU_logoruleai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F78E1E").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,0,162.9,1);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#5169A8").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(150,140,0.893,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// shad
	this.instance = new lib.HTML5rastershad_1();
	this.instance.setTransform(168,290,1,1,0,0,0,0,10);
	this.instance.alpha = 0.398;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,300);


// stage content:
(lib.SCU201609_Air_250x250_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_181 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(181).call(this.frame_181).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.setTransform(229,148.6,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.setTransform(0,0,0.744,0.893);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},182).wait(1));

	// ncua
	this.instance = new lib.ncuahorizai();
	this.instance.setTransform(125,240.4,1.03,1.03,0,0,0,0,3.6);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_1 = new lib.border336x280();
	this.instance_1.setTransform(125,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({_off:true},182).wait(1));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("A6OLuIAA3bMA0eAAAIAAXbg");
	var mask_graphics_40 = new cjs.Graphics().p("A6OLuIAA3bMA0eAAAIAAXbg");
	var mask_graphics_41 = new cjs.Graphics().p("A4nLuIAA3bMAxPAAAIAAXbg");
	var mask_graphics_42 = new cjs.Graphics().p("A3ALuIAA3bMAuBAAAIAAXbg");
	var mask_graphics_43 = new cjs.Graphics().p("A1YLuIAA3bMAqxAAAIAAXbg");
	var mask_graphics_44 = new cjs.Graphics().p("AzxLuIAA3bMAnjAAAIAAXbg");
	var mask_graphics_45 = new cjs.Graphics().p("AyJLuIAA3bMAkTAAAIAAXbg");
	var mask_graphics_46 = new cjs.Graphics().p("AwiLuIAA3bMAhFAAAIAAXbg");
	var mask_graphics_47 = new cjs.Graphics().p("Au7LuIAA3bId3AAIAAXbg");
	var mask_graphics_48 = new cjs.Graphics().p("AtTLuIAA3bIanAAIAAXbg");
	var mask_graphics_49 = new cjs.Graphics().p("ArsLuIAA3bIXZAAIAAXbg");
	var mask_graphics_80 = new cjs.Graphics().p("ArsLuIAA3bIXZAAIAAXbg");
	var mask_graphics_81 = new cjs.Graphics().p("ArsLtIAA3ZIXZAAIAAXZg");
	var mask_graphics_82 = new cjs.Graphics().p("ArsLuIAA3bIXZAAIAAXbg");
	var mask_graphics_83 = new cjs.Graphics().p("ArsLtIAA3ZIXZAAIAAXZg");
	var mask_graphics_84 = new cjs.Graphics().p("ArsLuIAA3bIXZAAIAAXbg");
	var mask_graphics_85 = new cjs.Graphics().p("ArsLtIAA3ZIXZAAIAAXZg");
	var mask_graphics_86 = new cjs.Graphics().p("ArsLuIAA3bIXZAAIAAXbg");
	var mask_graphics_87 = new cjs.Graphics().p("ArsLuIAA3aIXZAAIAAXag");
	var mask_graphics_88 = new cjs.Graphics().p("ArsLtIAA3aIXZAAIAAXag");
	var mask_graphics_89 = new cjs.Graphics().p("ArsLuIAA3bIXZAAIAAXbg");
	var mask_graphics_90 = new cjs.Graphics().p("ArsLtIAA3ZIXZAAIAAXZg");
	var mask_graphics_169 = new cjs.Graphics().p("ArsLtIAA3ZIXZAAIAAXZg");
	var mask_graphics_170 = new cjs.Graphics().p("ArrLaIAA2zIXXAAIAAWzg");
	var mask_graphics_171 = new cjs.Graphics().p("ArrLHIAA2NIXXAAIAAWNg");
	var mask_graphics_172 = new cjs.Graphics().p("ArqKzIAA1lIXVAAIAAVlg");
	var mask_graphics_173 = new cjs.Graphics().p("ArqKgIAA0/IXVAAIAAU/g");
	var mask_graphics_174 = new cjs.Graphics().p("ArpKMIAA0XIXTAAIAAUXg");
	var mask_graphics_175 = new cjs.Graphics().p("ArpJ5IAAzxIXTAAIAATxg");
	var mask_graphics_176 = new cjs.Graphics().p("AroJlIAAzJIXRAAIAATJg");
	var mask_graphics_177 = new cjs.Graphics().p("AroJSIAAyjIXRAAIAASjg");
	var mask_graphics_178 = new cjs.Graphics().p("ArnI+IAAx7IXPAAIAAR7g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:167.2,y:57}).wait(40).to({graphics:mask_graphics_40,x:167.2,y:57}).wait(1).to({graphics:mask_graphics_41,x:154.1,y:57}).wait(1).to({graphics:mask_graphics_42,x:141.1,y:57}).wait(1).to({graphics:mask_graphics_43,x:128.1,y:57}).wait(1).to({graphics:mask_graphics_44,x:115.1,y:57}).wait(1).to({graphics:mask_graphics_45,x:102.1,y:57}).wait(1).to({graphics:mask_graphics_46,x:89.1,y:57}).wait(1).to({graphics:mask_graphics_47,x:76.1,y:57}).wait(1).to({graphics:mask_graphics_48,x:63.1,y:57}).wait(1).to({graphics:mask_graphics_49,x:50.1,y:57}).wait(31).to({graphics:mask_graphics_80,x:52.1,y:57}).wait(1).to({graphics:mask_graphics_81,x:52,y:53}).wait(1).to({graphics:mask_graphics_82,x:51.9,y:49}).wait(1).to({graphics:mask_graphics_83,x:51.9,y:45}).wait(1).to({graphics:mask_graphics_84,x:51.8,y:41}).wait(1).to({graphics:mask_graphics_85,x:51.8,y:37}).wait(1).to({graphics:mask_graphics_86,x:51.7,y:33}).wait(1).to({graphics:mask_graphics_87,x:51.6,y:29}).wait(1).to({graphics:mask_graphics_88,x:51.6,y:25}).wait(1).to({graphics:mask_graphics_89,x:51.5,y:21}).wait(1).to({graphics:mask_graphics_90,x:51.5,y:17}).wait(79).to({graphics:mask_graphics_169,x:51.5,y:17}).wait(1).to({graphics:mask_graphics_170,x:51.3,y:8.7}).wait(1).to({graphics:mask_graphics_171,x:51.2,y:0.5}).wait(1).to({graphics:mask_graphics_172,x:51.1,y:-7.8}).wait(1).to({graphics:mask_graphics_173,x:51,y:-16.1}).wait(1).to({graphics:mask_graphics_174,x:50.9,y:-24.4}).wait(1).to({graphics:mask_graphics_175,x:50.8,y:-32.6}).wait(1).to({graphics:mask_graphics_176,x:50.7,y:-40.9}).wait(1).to({graphics:mask_graphics_177,x:50.6,y:-49.2}).wait(1).to({graphics:mask_graphics_178,x:50.5,y:-57.5}).wait(1).to({graphics:null,x:0,y:0}).wait(4));

	// PIC1
	this.instance_2 = new lib._336x280air();
	this.instance_2.setTransform(-1,-58,0.902,0.902);

	this.instance_3 = new lib.Tween11("synched",0);
	this.instance_3.setTransform(150.5,43);
	this.instance_3._off = true;

	this.instance_2.mask = this.instance_3.mask = mask;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2}]}).to({state:[{t:this.instance_3}]},40).to({state:[{t:this.instance_3}]},9).to({state:[{t:this.instance_3}]},31).to({state:[{t:this.instance_3}]},10).to({state:[{t:this.instance_3}]},79).to({state:[{t:this.instance_3}]},9).to({state:[]},1).wait(4));
	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(40).to({_off:false},0).to({regX:-7.4,regY:4.5,scaleX:0.69,scaleY:0.69,x:46.5,y:68},9).wait(31).to({startPosition:0},0).to({x:40.5,y:30.1},10).wait(79).to({startPosition:0},0).to({y:-59},9).to({_off:true},1).wait(4));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_80 = new cjs.Graphics().p("ArYLjIAA3FIWxAAIAAXFg");
	var mask_1_graphics_81 = new cjs.Graphics().p("AhnLjIAA3FIWyAAIAAXFg");
	var mask_1_graphics_82 = new cjs.Graphics().p("AhmLjIAA3FIWyAAIAAXFg");
	var mask_1_graphics_83 = new cjs.Graphics().p("AhlLjIAA3FIWyAAIAAXFg");
	var mask_1_graphics_84 = new cjs.Graphics().p("AhlLjIAA3FIWyAAIAAXFg");
	var mask_1_graphics_85 = new cjs.Graphics().p("AhkLjIAA3FIWyAAIAAXFg");
	var mask_1_graphics_86 = new cjs.Graphics().p("AhjLjIAA3FIWyAAIAAXFg");
	var mask_1_graphics_87 = new cjs.Graphics().p("AhjLjIAA3FIWyAAIAAXFg");
	var mask_1_graphics_88 = new cjs.Graphics().p("AhiLjIAA3FIWyAAIAAXFg");
	var mask_1_graphics_89 = new cjs.Graphics().p("AhhLjIAA3FIWyAAIAAXFg");
	var mask_1_graphics_90 = new cjs.Graphics().p("ArZLjIAA3FIWzAAIAAXFg");
	var mask_1_graphics_169 = new cjs.Graphics().p("ArZLjIAA3FIWzAAIAAXFg");
	var mask_1_graphics_170 = new cjs.Graphics().p("AhhLjIAA3FIWyAAIAAXFg");
	var mask_1_graphics_171 = new cjs.Graphics().p("AhiLjIAA3FIWyAAIAAXFg");
	var mask_1_graphics_172 = new cjs.Graphics().p("AhjLjIAA3FIWyAAIAAXFg");
	var mask_1_graphics_173 = new cjs.Graphics().p("AhkLjIAA3FIWyAAIAAXFg");
	var mask_1_graphics_174 = new cjs.Graphics().p("AhkLjIAA3FIWyAAIAAXFg");
	var mask_1_graphics_175 = new cjs.Graphics().p("AhlLjIAA3FIWyAAIAAXFg");
	var mask_1_graphics_176 = new cjs.Graphics().p("AhmLjIAA3FIWyAAIAAXFg");
	var mask_1_graphics_177 = new cjs.Graphics().p("AhnLjIAA3FIWyAAIAAXFg");
	var mask_1_graphics_178 = new cjs.Graphics().p("ArYLjIAA3FIWxAAIAAXFg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(80).to({graphics:mask_1_graphics_80,x:198,y:58}).wait(1).to({graphics:mask_1_graphics_81,x:135.6,y:54}).wait(1).to({graphics:mask_1_graphics_82,x:135.6,y:50}).wait(1).to({graphics:mask_1_graphics_83,x:135.7,y:46}).wait(1).to({graphics:mask_1_graphics_84,x:135.8,y:42}).wait(1).to({graphics:mask_1_graphics_85,x:135.9,y:38}).wait(1).to({graphics:mask_1_graphics_86,x:135.9,y:34}).wait(1).to({graphics:mask_1_graphics_87,x:136,y:30}).wait(1).to({graphics:mask_1_graphics_88,x:136.1,y:26}).wait(1).to({graphics:mask_1_graphics_89,x:136.1,y:22}).wait(1).to({graphics:mask_1_graphics_90,x:199.4,y:18}).wait(79).to({graphics:mask_1_graphics_169,x:199.4,y:18}).wait(1).to({graphics:mask_1_graphics_170,x:136.1,y:7.8}).wait(1).to({graphics:mask_1_graphics_171,x:136,y:-2.4}).wait(1).to({graphics:mask_1_graphics_172,x:136,y:-12.6}).wait(1).to({graphics:mask_1_graphics_173,x:135.9,y:-22.8}).wait(1).to({graphics:mask_1_graphics_174,x:135.8,y:-33.1}).wait(1).to({graphics:mask_1_graphics_175,x:135.7,y:-43.3}).wait(1).to({graphics:mask_1_graphics_176,x:135.7,y:-53.5}).wait(1).to({graphics:mask_1_graphics_177,x:135.6,y:-63.7}).wait(1).to({graphics:mask_1_graphics_178,x:198,y:-74}).wait(1).to({graphics:null,x:0,y:0}).wait(4));

	// PIC2
	this.instance_4 = new lib._336x280dev();
	this.instance_4.setTransform(95,-8);

	this.instance_5 = new lib.Tween15("synched",0);
	this.instance_5.setTransform(179,62);
	this.instance_5._off = true;

	this.instance_4.mask = this.instance_5.mask = mask_1;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_4}]},40).to({state:[{t:this.instance_5}]},40).to({state:[{t:this.instance_5}]},10).to({state:[{t:this.instance_5}]},79).to({state:[{t:this.instance_5}]},9).to({state:[]},1).wait(4));
	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(80).to({_off:false},0).to({y:40},10).wait(79).to({startPosition:0},0).to({y:-53},9).to({_off:true},1).wait(4));

	// PIC shad
	this.instance_6 = new lib.HTML5rastershad_1();
	this.instance_6.setTransform(168,142.1,1,1,0,0,0,0,10);
	this.instance_6.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(80).to({y:102},10).wait(79).to({y:7},9).to({_off:true},1).wait(4));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_0 = new cjs.Graphics().p("A7VC5IAAlwMA2qAAAIAAFwg");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:mask_2_graphics_0,x:150,y:164.6}).wait(49).to({graphics:null,x:0,y:0}).wait(134));

	// HEAD
	this.instance_7 = new lib.HEAD1();
	this.instance_7.setTransform(244.5,189,1,1,0,0,0,119.5,27);

	this.instance_7.mask = mask_2;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({_off:true},80).wait(103));

	// HEAD2
	this.instance_8 = new lib.HEAD2();
	this.instance_8.setTransform(125,144,1,1,0,0,0,-1.5,31.9);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(90).to({_off:false},0).to({_off:true},79).wait(14));

	// CTA
	this.instance_9 = new lib.CTA();
	this.instance_9.setTransform(244.5,73,1,1,0,0,0,119.5,40);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(178).to({_off:false},0).to({_off:true},4).wait(1));

	// Close
	this.instance_10 = new lib.Close();
	this.instance_10.setTransform(125,97,1,1,0,0,0,-1.5,24);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(178).to({_off:false},0).to({_off:true},4).wait(1));

	// head bkgd
	this.instance_11 = new lib.headbkgd();
	this.instance_11.setTransform(167.1,106.8,1,0.891,0,0,0,168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(80).to({x:168,y:50.8},10).wait(79).to({scaleY:1,y:-2},9).to({_off:true},4).wait(1));

	// tag
	this.instance_12 = new lib._2016TAG();
	this.instance_12.setTransform(125,218.6,1.25,1.25,0,0,0,0,2.7);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(178).to({_off:false},0).to({_off:true},4).wait(1));

	// logo
	this.instance_13 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_13.setTransform(362.4,261.7,1.103,1.103,0,0,0,215.3,63.1);
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(90).to({_off:false},0).wait(79).to({startPosition:0},0).to({regX:215.2,regY:63,scaleX:1.23,scaleY:1.23,x:388.6,y:225.7},9).to({_off:true},4).wait(1));

	// logo rule
	this.instance_14 = new lib._2016_SCU_logoruleai();
	this.instance_14.setTransform(228.3,205.5,1.267,1.267,0,0,0,81.5,0.5);
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(178).to({_off:false},0).to({_off:true},4).wait(1));

	// logo box
	this.instance_15 = new lib.box1();
	this.instance_15.setTransform(134,82.3,0.893,1.786,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_15).to({_off:true},182).wait(1));

	// com
	this.instance_16 = new lib.comhoriz();
	this.instance_16.setTransform(62,242.2,0.687,0.687,0,0,0,0,4.5);
	this.instance_16._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(100,107,361,268);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;