(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 120,
	height: 600,
	fps: 18,
	color: "#CCCCCC",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/HTML5rastershad.png", id:"HTML5rastershad"},
		{src:"images/SCU201609_Air_120x600_AdR_atlas_NP_.jpg", id:"SCU201609_Air_120x600_AdR_atlas_NP_"}
	]
};



lib.ssMetadata = [
		{name:"SCU201609_Air_120x600_AdR_atlas_NP_", frames: [[0,0,336,224],[338,0,168,141]]}
];


lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib._336x280air = function() {
	this.spriteSheet = ss["SCU201609_Air_120x600_AdR_atlas_NP_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib._336x280dev = function() {
	this.spriteSheet = ss["SCU201609_Air_120x600_AdR_atlas_NP_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.Tween6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._336x280air();
	this.instance.setTransform(-124.8,-83.2,0.743,0.743);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-124.8,-83.2,249.8,166.5);


(lib.Tween5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._336x280air();
	this.instance.setTransform(-124.8,-83.2,0.743,0.743);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-124.8,-83.2,249.8,166.5);


(lib.Tween2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._336x280dev();
	this.instance.setTransform(-84,-70);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-84,-70,168,141);


(lib.Tween1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._336x280dev();
	this.instance.setTransform(-84,-70);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-84,-70,168,141);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#3F3F3F").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.ncuastackai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgdAlIADgFQACABAFABQAGAAADgJIgVgsIAHAAIARAkIAOgkIAHAAIgSAuQgFANgKAAQgFAAgFgDgAFDAUQgHgHAAgLQAAgJAHgHQAHgHAJABQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgAFIgJQgEAFAAAFIAAABQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgGABgHIAAgBQgBgFgFgFQgEgFgHAAQgIAAgEAFgAEOATQgHgGAAgLQAAgIAGgIQAGgGAKAAQAKAAAGAGQAGAIAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEADQgHAJgMAAQgKAAgGgHgAEsAAQgCgPgNAAQgGABgEAEQgEAEgBAGIAeAAIAAAAgAC0AVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOANAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgJAAgEgFgAB/ATIADgFQAIAGAIAAQAKAAAAgIQAAgEgMgDQgPgFAAgHQAAgGAFgEQAEgDAHAAQAJgBAIAGIgDAFQgIgEgGgBQgJAAAAAHQAAAFAMADQAPADAAAJQAAAGgFAFQgEADgIAAQgLAAgIgHgAh8AXQgGgFAAgHQAAgHAGgEQAGgCAJAAQAFAAAJACIAAgBQAAgNgOAAQgHAAgHAEIgCgGQAIgEAJAAQAKAAAFAFQAEAEABAKIAAAaIgHAAIAAgHQgGAIgLAAQgHAAgFgDgAh7ALQABAJALAAQAHABAFgEQAEgDAAgGIAAgFQgHgCgGAAQgOAAgBAKgAjRATQgHgGAAgLQAAgIAGgIQAHgGAJAAQAKAAAGAGQAGAIAAAIIAAADIglAAQABAHAEAEQAFAEAGAAQAIAAAHgGIAEADQgIAJgLAAQgKAAgGgHgAizAAQgCgPgNAAQgGABgEAEQgEAEgBAGIAeAAIAAAAgAkNAUQgHgHAAgLQAAgJAHgHQAHgHAJABQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgAkIgJQgEAFAAAFIAAABQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgGABgHIAAgBQgBgFgFgFQgEgFgHAAQgIAAgEAFgAlCATQgHgGAAgLQAAgIAGgIQAGgGAKAAQAKAAAGAGQAGAIAAAIIAAADIglAAQACAPAOAAQAIAAAHgGIAEADQgHAJgMAAQgKAAgGgHgAkkAAQgCgPgNAAQgGABgEAEQgEAEgBAGIAeAAIAAAAgADnAZIAAgsIAHAAIAAALQAGgMANAAIAAAHIgBAAQgIAAgEAFQgGAGAAAJIAAASgABtAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAEQAFAFAAAJIAAAbgAA1AZIAAgsIAHAAIAAAsgAgyAZIAAg/IAIAAIAAA/gAhJAZIAAg/IAHAAIAAA/gAigAZIAAgsIAHAAIAAALQAGgMANAAIAAAHIAAAAQgIAAgGAFQgFAGAAAJIAAASgAlkAZIAAgnIgGAAIAAgFIAGAAIAAgFQAAgHAEgEQAEgEAGAAIAIABIAAAGIgHgBQgIAAAAAKIAAAEIAPAAIAAAFIgPAAIAAAngAA0gdIAAgIIAIAAIAAAIg");
	this.shape.setTransform(0,4.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhwAlIACgFIAHACQAGAAAEgJIgVgsIAHAAIARAkIAPgkIAIAAIgUAtQgFANgKAAQgGAAgEgCgACFAXQgGgFAAgHQAAgNAUAAQAGAAAIACIAAgBQAAgNgNAAQgHAAgIAEIgCgGQAJgEAIAAQALAAAEAFQAFAEAAAKIAAAaIgHAAIAAgHQgFAIgLAAQgHAAgFgDgACGALQAAAJAMAAQAHABAEgEQAEgDAAgGIAAgFQgGgCgHAAQgOAAAAAKgABPAVQgEgFAAgIIAAgbIAHAAIAAAZQAAAOAMAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgFAJgLAAQgIAAgFgFgAAcATQgHgHAAgKQAAgIAHgIQAHgGAKAAQAKgBAJAJIgFAEQgHgHgHAAQgHABgFAFQgFAFAAAFIAAABQAAAHAFAGQAFAFAHAAQAIAAAHgHIAEAEQgIAJgLAAQgKAAgHgHgAigAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgLALABQAJgBAGAHQAHAHAAAIIAAABQAAALgHAGQgGAHgJAAQgMAAgGgKgAibgJQgGAFAAAFIAAABQAAAHAGAGQAFAFAGAAQAHAAAFgFQAFgFAAgIQAAgGgFgFQgFgFgHAAQgGAAgFAFgAACAZIAAgZQAAgOgLAAQgGAAgEAEQgEAEAAAGIAAAZIgGAAIAAgsIAGAAIAAAIQAHgJAJAAQAHAAAFAEQAEAFAAAJIAAAbg");
	this.shape_1.setTransform(0,14.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-36.3,0,72.7,18.9);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F78E1E").s().p("AgLAMIAAgYIAXAAIAAAYg");
	this.shape.setTransform(43.6,96.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F78E1E").s().p("AgSAwQgOgHgGgEIAKgQQAIAGAIADQAJADAGAAQAHAAAEgDQAEgDAAgFIAAAAQAAgFgHgEQgDgCgKgDQgPgFgGgDQgFgDgDgEQgDgFAAgIIAAAAQAAgHADgFQADgHAFgDQAFgFAGgCQAHgBAFAAQAJAAAKACQAKADAIAGIgJAQQgHgEgIgDQgHgDgGABQgFAAgEACQgDAEAAAEIAAAAQAAAFAGAEIAOAFIALAEQAGADAEABQAFAEACAEQADAFAAAHIAAAAQAAAIgDAFQgCAHgFADQgFAFgHABQgHACgIAAQgJAAgLgDg");
	this.shape_1.setTransform(36.2,93.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F78E1E").s().p("AgSAwQgOgHgGgEIAKgQQAIAGAIADQAJADAGAAQAHAAAEgDQAEgDAAgFIAAAAQAAgFgHgEQgDgCgKgDQgPgFgGgDQgFgDgDgEQgDgFAAgIIAAAAQAAgHADgFQADgHAFgDQAFgFAGgCQAHgBAFAAQAJAAAKACQAKADAIAGIgJAQQgHgEgIgDQgHgDgGABQgFAAgEACQgDAEAAAEIAAAAQAAAFAGAEIAOAFIALAEQAGADAEABQAFAEACAEQADAFAAAHIAAAAQAAAIgDAFQgCAHgFADQgFAFgHABQgHACgIAAQgJAAgLgDg");
	this.shape_2.setTransform(26.7,93.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F78E1E").s().p("AgQAwQgJgEgHgGQgIgIgDgJIgDgKIgBgLQAAgKAEgJQADgJAHgIQAGgHAJgEIAKgDIAIgBIALABIAKADQAGADAJAJQAGAIADAJQADAKAAAJIgBAGIhHAAQABAGACAGIAHAIIAJAEQAEACAEAAQAIAAAHgDQAFgDAHgGIAOAMQgEAEgEADIgJAHIgMADIgNACQgJAAgJgEgAAZgFQgBgHgCgEQgBgFgDgDQgEgEgEgCQgEgCgGAAQgEAAgEACQgEACgDADIgHAJIgCALIAxAAIAAAAg");
	this.shape_3.setTransform(16.4,93.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F78E1E").s().p("AAWAzIAAg3QgBgGgBgFQgBgEgDgDIgHgFQgEgCgFAAQgDAAgEACIgHAFQgDADgCAFQgCAEABAGIAAA3IgYAAIAAhjIAYAAIAAAQQAFgIAGgEIAJgEQADgCAFAAQAJAAAHADQAGADAFAFQAEAFADAHQACAHAAAJIAAA+g");
	this.shape_4.setTransform(4.8,93.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F78E1E").s().p("AgKBEIAAhiIAVAAIAABigAgLgtIAAgWIAXAAIAAAWg");
	this.shape_5.setTransform(-3.8,91.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F78E1E").s().p("AgSAwQgOgHgGgEIAKgQQAIAGAIADQAJADAGAAQAHAAAEgDQAEgDAAgFIAAAAQAAgFgHgEQgDgCgKgDQgPgFgGgDQgFgDgDgEQgDgFAAgIIAAAAQAAgHADgFQADgHAFgDQAFgFAGgCQAHgBAFAAQAJAAAKACQAKADAIAGIgJAQQgHgEgIgDQgHgDgGABQgFAAgEACQgDAEAAAEIAAAAQAAAFAGAEIAOAFIALAEQAGADAEABQAFAEACAEQADAFAAAHIAAAAQAAAIgDAFQgCAHgFADQgFAFgHABQgHACgIAAQgJAAgLgDg");
	this.shape_6.setTransform(-11.4,93.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F78E1E").s().p("AgXAwQgHgDgFgFQgEgFgDgHQgCgHAAgJIAAg+IAYAAIAAA3QAAAGABAFQABAEADAEQADADADABQAEACAFAAIAIgCQAEgBADgEQADgDABgEQACgFABgGIAAg3IAWAAIAABjIgWAAIAAgQQgGAIgHAFQgEACgFABQgCACgGAAQgJAAgGgDg");
	this.shape_7.setTransform(-21.9,93.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F78E1E").s().p("AgFBEQgFgBgEgCQgHgFgGgIIAAAQIgXAAIAAiJIAXAAIAAA3QAGgJAHgEIAKgEQAEgCAFAAQAJAAAIAEQAIADAHAHQAHAHADAJQAEAMAAAIIAAABIgBAMIgDAKQgDAJgHAHQgGAHgJADQgIAEgJAAQgFAAgFgCgAgKgKQgFACgEAEQgEAEgDAEQgCAGAAAHIAAABQAAAHACAGQADAGAEAEQAEAEAFADQAGACAEAAQAFAAAGgCQAFgDAEgEQAEgEACgGQACgGAAgHIAAgBQAAgHgCgGQgCgEgEgEQgEgEgGgCQgFgDgFAAQgEAAgGADg");
	this.shape_8.setTransform(-33.9,91.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#F78E1E").s().p("AAWBFIAAg5QgBgGgBgFQgCgCgCgDIgHgFQgEgCgFAAQgDAAgEACIgHAFQgDADgCADQgBAEgBAGIAAA5IgXAAIAAiJIAXAAIAAA2QAGgIAGgEIAJgEQADgCAFAAQAJAAAHADQAHADAEAFQAEAFADAHQACAHAAAHIAABAg");
	this.shape_9.setTransform(14.8,64.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#F78E1E").s().p("AAAA/QgFgCgEgDQgEgEgCgFQgCgGAAgIIAAgzIgNAAIAAgUIANAAIAAgbIAVAAIAAAbIAbAAIAAAUIgbAAIAAAvQAAAHADADQADADAGAAQAIAAAGgEIAAATIgJAEIgLABQgHAAgDgBg");
	this.shape_10.setTransform(4.9,64.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#F78E1E").s().p("AgKBEIAAhiIAVAAIAABigAgLgtIAAgWIAXAAIAAAWg");
	this.shape_11.setTransform(-1.6,64.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#F78E1E").s().p("AAWAyIgWhCIgVBCIgVAAIgghjIAXAAIAVBDIAWhDIARAAIAXBDIAUhDIAXAAIghBjg");
	this.shape_12.setTransform(-12.5,66.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#F78E1E").s().p("AgSAwQgOgHgGgEIAKgQQAIAGAIADQAJADAGAAQAHAAAEgDQAEgDAAgFIAAAAQAAgFgHgEQgDgCgKgDQgPgFgGgDQgFgDgDgEQgDgGAAgHIAAAAQAAgHADgFQADgHAFgDQAFgFAGgBQAHgCAFAAQAJAAAKACQAKADAIAGIgJAQQgHgEgIgDQgHgDgGABQgFAAgEACQgDAEAAAEIAAAAQAAAFAGAEIAOAFIALAEQAGADAEABQAFADACAFQADAFAAAHIAAAAQAAAIgDAFQgCAHgFADQgFAFgHABQgHACgIAAQgJAAgLgDg");
	this.shape_13.setTransform(35.9,39.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#F78E1E").s().p("AgSAwQgOgHgGgEIAKgQQAIAGAIADQAJADAGAAQAHAAAEgDQAEgDAAgFIAAAAQAAgFgHgEQgDgCgKgDQgPgFgGgDQgFgDgDgEQgDgGAAgHIAAAAQAAgHADgFQADgHAFgDQAFgFAGgBQAHgCAFAAQAJAAAKACQAKADAIAGIgJAQQgHgEgIgDQgHgDgGABQgFAAgEACQgDAEAAAEIAAAAQAAAFAGAEIAOAFIALAEQAGADAEABQAFADACAFQADAFAAAHIAAAAQAAAIgDAFQgCAHgFADQgFAFgHABQgHACgIAAQgJAAgLgDg");
	this.shape_14.setTransform(26.4,39.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#F78E1E").s().p("AgQAwQgJgEgHgGQgHgIgEgJIgDgKIgBgLQAAgKADgJQAEgJAGgIQAIgHAIgEIAJgDIAJgBIALABIAKADQAGADAJAJQAGAIADAJQADAKAAAJIAAAGIhIAAQABAGADAGIAGAIIAJAEQAEACAEAAQAIAAAGgDQAHgDAGgGIANAMQgDAEgFADIgJAHIgLADIgMACQgJAAgKgEgAAZgFQAAgHgCgEQgCgFgEgDQgDgEgEgCQgFgCgFAAQgEAAgEACQgFACgDADIgFAJIgEALIAyAAIAAAAg");
	this.shape_15.setTransform(16.1,39.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#F78E1E").s().p("AAVAzIAAg3QAAgGgBgFQgBgEgDgDIgHgFQgEgCgFAAQgDAAgEACIgHAFQgDADgCAFQgBAEAAAGIAAA3IgYAAIAAhjIAYAAIAAAQQAFgIAHgEIAIgEQADgCAGAAQAIAAAHADQAHADAEAFQAFAFACAHQACAHABAJIAAA+g");
	this.shape_16.setTransform(4.5,39.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#F78E1E").s().p("AgKBEIAAhiIAVAAIAABigAgLgtIAAgWIAXAAIAAAWg");
	this.shape_17.setTransform(-4.1,37.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#F78E1E").s().p("AgSAwQgOgHgGgEIAKgQQAIAGAIADQAJADAGAAQAHAAAEgDQAEgDAAgFIAAAAQAAgFgHgEQgDgCgKgDQgPgFgGgDQgFgDgDgEQgDgGAAgHIAAAAQAAgHADgFQADgHAFgDQAFgFAGgBQAHgCAFAAQAJAAAKACQAKADAIAGIgJAQQgHgEgIgDQgHgDgGABQgFAAgEACQgDAEAAAEIAAAAQAAAFAGAEIAOAFIALAEQAGADAEABQAFADACAFQADAFAAAHIAAAAQAAAIgDAFQgCAHgFADQgFAFgHABQgHACgIAAQgJAAgLgDg");
	this.shape_18.setTransform(-11.7,39.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#F78E1E").s().p("AgXAwQgHgDgEgFQgFgFgDgHQgBgHAAgJIAAg+IAWAAIAAA3QAAAGACAFQABAEADAEQADADAEABQAEACAEAAIAIgCQAEgBADgEQADgDABgEQACgFAAgGIAAg3IAYAAIAABjIgYAAIAAgQQgFAIgHAFQgEACgEABQgDACgGAAQgIAAgHgDg");
	this.shape_19.setTransform(-22.2,39.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#F78E1E").s().p("AgFBEQgFgBgEgCQgHgFgGgIIAAAQIgXAAIAAiJIAXAAIAAA3QAGgJAHgEIAKgEQAEgCAFAAQAJAAAIAEQAIADAHAHQAHAHADAJQAEAMAAAIIAAABIgBAMIgDAKQgDAJgHAHQgGAHgJADQgIAEgJAAQgFAAgFgCgAgKgKQgFACgEAEQgEAEgDAEQgCAGAAAHIAAABQAAAHACAGQADAGAEAEQAEAEAFADQAGACAEAAQAFAAAGgCQAFgDAEgEQAEgEACgGQACgGAAgHIAAgBQAAgHgCgGQgCgEgEgEQgEgEgGgCQgFgDgFAAQgEAAgGADg");
	this.shape_20.setTransform(-34.2,37.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#F78E1E").s().p("AAWAzIAAg3QgBgGgBgFQgBgEgDgDIgHgFQgEgCgFAAQgDAAgEACIgHAFQgDADgCAFQgCAEABAGIAAA3IgYAAIAAhjIAYAAIAAAQQAFgIAGgEIAJgEQADgCAFAAQAJAAAHADQAGADAFAFQAEAFADAHQACAHAAAJIAAA+g");
	this.shape_21.setTransform(33.6,12.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#F78E1E").s().p("AgKBEIAAhiIAVAAIAABigAgLgtIAAgWIAXAAIAAAWg");
	this.shape_22.setTransform(25,10.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#F78E1E").s().p("AgQAwQgJgEgHgGQgIgIgDgJIgDgKIgBgLQAAgKAEgJQADgJAHgIQAGgHAJgEIAJgDIAJgBIALABIAKADQAGADAJAJQAGAIADAJQADAKAAAJIAAAGIhIAAQABAGACAGIAHAIIAJAEQAEACAEAAQAIAAAHgDQAGgDAGgGIANAMQgDAEgEADIgJAHIgMADIgMACQgJAAgKgEgAAZgFQgBgHgCgEQgBgFgDgDQgDgEgFgCQgEgCgGAAQgEAAgEACQgEACgDADIgGAJIgDALIAxAAIAAAAg");
	this.shape_23.setTransform(10.9,12.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#F78E1E").s().p("AgcAzIAAhjIAXAAIAAAXIAFgKIAHgIQAEgEAGgBQAFgCAHABIAAAYIgCAAQgHAAgGACQgHADgEAFQgDAFgCAHQgDAGAAAKIAAAmg");
	this.shape_24.setTransform(1.7,12.1);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#F78E1E").s().p("AgOAQQAIgBAEgEQADgFgBgGIgIAAIAAgaIAXAAIAAAXQAAAFgBAGQgCAGgEAEQgEADgEACIgMADg");
	this.shape_25.setTransform(-5.5,6.6);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#F78E1E").s().p("AgQAwQgJgEgHgGQgIgIgDgJIgDgKIgBgLQAAgKADgJQAEgJAGgIQAIgHAIgEIAKgDIAIgBIALABIAKADQAGADAJAJQAGAIADAJQADAKAAAJIgBAGIhHAAQABAGADAGIAFAIIAJAEQAFACAEAAQAIAAAGgDQAGgDAHgGIAOAMQgEAEgFADIgJAHIgKADIgOACQgIAAgKgEgAAZgFQgBgHgBgEQgCgFgEgDQgCgEgFgCQgFgCgFAAQgDAAgFACQgFACgDADIgGAJIgDALIAyAAIAAAAg");
	this.shape_26.setTransform(-13.5,12.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#F78E1E").s().p("AAgBDIggheIgfBeIgUAAIgviEIAZAAIAhBgIAghhIASAAIAgBhIAghgIAYAAIguCEg");
	this.shape_27.setTransform(-28.8,10.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80,0,160,104);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgLAMIAAgYIAXAAIAAAYg");
	this.shape.setTransform(40.8,107.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgJAyIgphjIAYAAIAaBIIAbhIIAYAAIgpBjg");
	this.shape_1.setTransform(32.6,104.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgQAwQgJgEgHgHQgIgHgDgJIgDgKIgBgLQAAgJADgKQAEgKAGgGQAIgIAIgEIAJgDIAJgBIALABIAKADQAGADAJAJQAGAIADAKQADAJAAAJIgBAHIhHAAQABAGADAFIAFAIIAJAEQAFACAEAAQAIAAAGgDQAHgDAGgGIANAMQgDAEgFADIgJAHIgKADQgHACgHAAQgIAAgKgEgAAZgGQgBgFgBgFQgCgFgEgDQgDgEgEgCQgFgCgFAAQgEAAgEACQgFACgDADIgFAJIgEAKIAyAAIAAAAg");
	this.shape_2.setTransform(21.3,104.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgVBCQgJgDgGgHQgHgHgDgJIgDgKIgBgMIAAgBQAAgIADgMQAEgJAHgHQAGgHAJgDQAIgEAJAAQAEAAAFACIAKAEQAHAEAGAIIAAg2IAXAAIAACJIgXAAIAAgRQgGAJgHAEQgFADgFABQgFACgEAAQgJAAgIgEgAgKgKQgFACgEAEQgEAEgCAEQgCAGAAAHIAAABQAAAHACAGQACAGAEAEQAEAEAGADQAFACAEAAQAFAAAGgCQAFgDAEgEQAEgEACgGQADgGAAgHIAAgBQAAgHgDgGQgCgEgEgEQgEgEgFgCQgGgDgFAAQgEAAgGADg");
	this.shape_3.setTransform(8.9,102.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgFBEQgFgBgEgCQgHgFgGgIIAAAQIgXAAIAAiJIAXAAIAAA3QAGgJAHgEIAKgEQAEgCAFAAQAJAAAIAEQAIADAHAHQAHAHADAJQAEAMAAAIIAAABIgBAMIgDAKQgDAJgHAHQgGAHgJADQgIAEgJAAQgFAAgFgCgAgKgKQgFACgEAEQgEAEgDAEQgCAGAAAHIAAABQAAAHACAGQADAGAEAEQAEAEAFADQAGACAEAAQAFAAAGgCQAFgDAEgEQAEgEACgGQACgGAAgHIAAgBQAAgHgCgGQgCgEgEgEQgEgEgGgCQgFgDgFAAQgEAAgGADg");
	this.shape_4.setTransform(-9,102.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgQAwQgJgEgHgHQgHgHgEgJIgDgKIgBgLQAAgJADgKQAEgKAGgGQAIgIAIgEIAJgDIAJgBIALABIAKADQAGADAJAJQAGAIADAKQADAJAAAJIAAAHIhIAAQABAGADAFIAGAIIAJAEQAEACAEAAQAIAAAGgDQAHgDAGgGIANAMQgDAEgFADIgJAHIgLADQgGACgGAAQgJAAgKgEgAAZgGQAAgFgCgFQgCgFgEgDQgDgEgEgCQgFgCgFAAQgEAAgEACQgFACgDADIgFAJIgEAKIAyAAIAAAAg");
	this.shape_5.setTransform(-21.3,104.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAWAyIgWhCIgVBCIgVAAIgghjIAXAAIAVBDIAWhDIARAAIAXBDIAUhDIAXAAIghBjg");
	this.shape_6.setTransform(-35.2,104.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgKAzIgKgDQgJgFgIgHQgHgGgEgKIgDgKIgBgKIAAAAQAAgFAEgOQAEgJAHgIQAIgHAJgDIAKgEIAKgBQAHAAAOAEQAKAEAHAHQAHAIAEAJQAEANAAAGIAAAAIgBAKIgDAJQgEAKgHAHQgIAHgJAFQgOAEgHAAgAgLgcQgGACgEAFQgEAEgCAGQgCAGAAAFIAAAAQAAAGACAGQADAGAEAEQADAFAGADQAGACAFAAQAHAAAFgCQAFgDAFgEQADgFACgGQADgGAAgGIAAAAQAAgFgDgGQgCgGgDgEQgFgFgFgCQgHgDgFAAQgGAAgFADg");
	this.shape_7.setTransform(3.9,81.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAAA/QgFgCgEgDQgEgEgCgFQgCgGAAgIIAAgzIgNAAIAAgUIANAAIAAgbIAVAAIAAAbIAbAAIAAAUIgbAAIAAAvQAAAHADADQADADAGAAQAIAAAGgEIAAATIgJAEIgLABQgHAAgDgBg");
	this.shape_8.setTransform(-6.3,79.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgSAvQgOgFgGgFIAKgQQAIAGAIADQAJADAGAAQAHAAAEgDQAEgDAAgFIAAAAQAAgFgHgEQgDgCgKgDQgPgFgGgDQgFgDgDgEQgDgGAAgHIAAAAQAAgHADgFQADgHAFgDQAFgFAGgCQAHgBAFAAQAJAAAKACQAKADAIAGIgJAQQgHgEgIgDQgHgDgGABQgFAAgEACQgDADAAAEIAAABQAAAFAGAEIAOAFIALAEQAGADAEABQAFADACAFQADAFAAAHIAAAAQAAAIgDAFQgCAGgFAFQgFADgHACQgHACgIAAQgJAAgLgEg");
	this.shape_9.setTransform(38.2,58.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgcAzIAAhjIAXAAIAAAXIAFgKIAHgIQAEgEAGgBQAFgCAHABIAAAYIgCAAQgHAAgGACQgHADgEAFQgDAFgCAHQgDAGAAAKIAAAmg");
	this.shape_10.setTransform(30.2,58.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgQAwQgJgEgHgGQgHgIgEgJIgDgKIgBgLQAAgJADgKQAEgKAGgGQAIgIAIgEIAJgDIAJgBIALABIAKADQAGADAJAJQAGAIADAKQADAJAAAJIAAAHIhIAAQABAFADAGIAGAIIAJAEQAEACAEAAQAIAAAGgDQAHgDAGgGIANAMQgDAEgFADIgJAHIgLADIgMACQgJAAgKgEgAAZgFQAAgGgCgFQgCgFgEgDQgDgEgEgCQgFgCgFAAQgEAAgEACQgFACgDADIgFAJIgEALIAyAAIAAAAg");
	this.shape_11.setTransform(20.1,58.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgKBEIAAhiIAVAAIAABigAgLgtIAAgWIAXAAIAAAWg");
	this.shape_12.setTransform(11.7,56.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgKBFIAAiJIAVAAIAACJg");
	this.shape_13.setTransform(6.3,56.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgyBCIAAiBIAXAAIAAARQAGgJAHgFIAKgEQAEgBAFAAQAJAAAIADQAIAEAHAGQAHAIADAJQAEAOAAAIIAAABIgBALIgDAIQgDAKgHAHQgGAGgJAEQgIADgJAAQgFAAgFgBQgFgBgEgCQgHgFgGgIIAAAugAgKgrQgFACgEAFQgEAEgDAGQgCAGAAAHIAAABQAAAGACAGQADAEAEAFQAEAEAFADQAGABAEAAQAFAAAGgBQAFgDAEgEQAEgFACgEQACgGAAgGIAAgBQAAgHgCgGQgCgGgEgEQgEgFgGgCQgFgCgFAAQgEAAgGACg");
	this.shape_14.setTransform(-2.5,59.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgyBCIAAiBIAXAAIAAARQAGgJAHgFIAKgEQAEgBAFAAQAJAAAIADQAIAEAHAGQAHAIADAJQAEAOAAAIIAAABIgBALIgDAIQgDAKgHAHQgGAGgJAEQgIADgJAAQgFAAgFgBQgFgBgEgCQgHgFgGgIIAAAugAgKgrQgFACgEAFQgEAEgDAGQgCAGAAAHIAAABQAAAGACAGQADAEAEAFQAEAEAFADQAGABAEAAQAFAAAGgBQAFgDAEgEQAEgFACgEQACgGAAgGIAAgBQAAgHgCgGQgCgGgEgEQgEgFgGgCQgFgCgFAAQgEAAgGACg");
	this.shape_15.setTransform(-15.2,59.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgXAwQgGgDgFgFQgFgFgCgHQgCgHAAgJIAAg+IAWAAIAAA3QABAGABAFQABAEADAEQADADAEABQAEACAEAAQADAAAFgCQAEgBADgEQADgDACgEQABgFAAgGIAAg3IAYAAIAABjIgYAAIAAgQQgFAIgHAFQgEACgEABQgDACgGAAQgJAAgGgDg");
	this.shape_16.setTransform(-27.7,58.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgSAvQgOgFgGgFIAKgQQAIAGAIADQAJADAGAAQAHAAAEgDQAEgDAAgFIAAAAQAAgFgHgEQgDgCgKgDQgPgFgGgDQgFgDgDgEQgDgGAAgHIAAAAQAAgHADgFQADgHAFgDQAFgFAGgCQAHgBAFAAQAJAAAKACQAKADAIAGIgJAQQgHgEgIgDQgHgDgGABQgFAAgEACQgDADAAAEIAAABQAAAFAGAEIAOAFIALAEQAGADAEABQAFADACAFQADAFAAAHIAAAAQAAAIgDAFQgCAGgFAFQgFADgHACQgHACgIAAQgJAAgLgEg");
	this.shape_17.setTransform(-38.5,58.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAAA/QgFgCgEgDQgEgEgCgFQgCgGAAgIIAAgzIgNAAIAAgUIANAAIAAgbIAVAAIAAAbIAbAAIAAAUIgbAAIAAAvQAAAHADADQADADAGAAQAIAAAGgEIAAATIgJAEIgLABQgHAAgDgBg");
	this.shape_18.setTransform(30.5,33.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgRBGIAAhPIgMAAIAAgTIAMAAIAAgHQAAgJACgGQADgHADgEQAEgEAFgCQAEgCAIAAQAKAAAIADIAAAUQgHgDgGAAQgGAAgEAEQgEADAAAIIAAAGIAbAAIAAATIgaAAIAABPg");
	this.shape_19.setTransform(23.4,33.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgWAyQgGgCgFgFQgFgDgDgGQgDgGAAgIQAAgIADgGQADgGAFgCQAGgFAHgBQAIgCAIAAQALAAAPADIAAgBQAAgFgBgFQgBgEgEgDQgDgCgEgBQgFgCgEAAQgIAAgHACIgOAEIgGgSQAJgEAIgCQAKgDAJAAQALAAAIAEQAJADAFAFQAGAFADAIQACAIAAAKIAAA6IgXAAIAAgNQgFAGgIAEQgKAFgHAAQgHAAgHgCgAgIAFIgHACQgDACgCAEQgBADAAADIAAAAQAAAHAGAFQAFADAIABQAEgBAFgBIAIgFQAEgDACgDQACgEAAgFIAAgGQgOgDgJAAIgIABg");
	this.shape_20.setTransform(13.8,35.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgcAzIAAhjIAXAAIAAAXIAFgKIAHgIQAEgEAGgBQAFgCAHABIAAAYIgCAAQgHAAgGACQgHADgEAFQgDAFgCAHQgDAGAAAKIAAAmg");
	this.shape_21.setTransform(5,35.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgEAzIgKgEQgJgDgIgIQgGgGgEgKQgEgKAAgKIAAAAQAAgJAEgJQAEgKAGgIQAIgHAJgDIAKgEIAJgBQAHAAAGABQAGACAEACQAHADAKAJIgOAQQgGgHgGgCQgGgEgIAAQgFAAgFADQgFACgEAFQgEAEgCAGQgCAGAAAFIAAAAQAAAGACAGQACAGAEAFQAFAEAFACQAEADAGAAQAIAAAGgEQAGgCAGgHIAOAOQgLAKgGADIgLAFQgGABgHAAg");
	this.shape_22.setTransform(-4.6,35.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgcAzIAAhjIAXAAIAAAXIAFgKIAHgIQAEgEAGgBQAFgCAHABIAAAYIgCAAQgHAAgGACQgHADgEAFQgDAFgCAHQgDAGAAAKIAAAmg");
	this.shape_23.setTransform(-13.6,35.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgKBEIAAhiIAVAAIAABigAgLgtIAAgWIAXAAIAAAWg");
	this.shape_24.setTransform(-20.6,33.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgWAyQgGgCgFgFQgFgDgDgGQgDgGAAgIQAAgIADgGQADgGAGgCQAFgFAHgBQAIgCAIAAQALAAAPADIAAgBQABgFgCgFQgCgEgDgDQgDgCgEgBQgGgCgDAAQgIAAgHACIgOAEIgGgSQAJgEAIgCQAKgDAJAAQALAAAJAEQAHADAGAFQAFAFADAIQADAIAAAKIAAA6IgXAAIAAgNQgFAGgIAEQgJAFgIAAQgIAAgGgCgAgIAFIgHACQgDACgCAEQgBADAAADIAAAAQAAAHAGAFQAFADAIABQAEgBAFgBIAIgFQAEgDACgDQACgEAAgFIAAgGQgOgDgJAAIgIABg");
	this.shape_25.setTransform(-29.2,35.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AA1AzIAAg3QAAgGgCgFQgBgEgDgDQgCgEgEgBQgEgCgFAAQgEAAgEACQgEABgDAEQgDADgBAEQgCAFAAAGIAAA3IgVAAIAAg3IgBgLQgCgEgCgDQgDgEgEgBQgEgCgEAAQgFAAgEACQgEACgDADQgDADgBAFQgCAFAAAFIAAA3IgXAAIAAhjIAXAAIAAAQQAGgIAGgEIAIgEQAFgCAGAAQAFAAAFACQAEABAEACIAFAGQADADACAEQAGgIAIgFQAEgCAFgBQAFgCAGAAQAIAAAGADQAHACAEAFQAFAFACAHQADAIAAAJIAAA+g");
	this.shape_26.setTransform(16.4,12.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgKAyIgKgCQgJgEgIgHQgHgIgEgJIgDgJIgBgLIAAAAQAAgGAEgNQAEgJAHgIQAIgHAJgEIAKgDIAKgBQAHAAAOAEQAJAEAIAHQAHAIAEAJQAEANAAAGIAAAAIgBAKIgDAKQgEAJgIAIQgHAHgJAEQgOAEgHAAgAgLgdQgGADgEAEQgEAFgCAGQgCAGAAAFIAAAAQAAAGACAGQACAGAFAEQAEAFAFADQAGACAFAAQAHAAAFgCQAGgDAEgFQADgEACgGQADgFAAgHIAAAAQAAgFgDgGQgCgGgDgEQgFgFgFgCQgHgDgFAAQgGAAgFACg");
	this.shape_27.setTransform(1.1,12.2);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgcAzIAAhjIAXAAIAAAXIAFgKIAHgIQAEgEAGgBQAFgCAHABIAAAYIgCAAQgHAAgGACQgHADgEAFQgDAFgCAHQgDAGAAAKIAAAmg");
	this.shape_28.setTransform(-8.6,12.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgwBCIAAiDIBhAAIAAAVIhJAAIAAAkIBAAAIAAAUIhAAAIAAA2g");
	this.shape_29.setTransform(-18.7,10.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-91,0,182,115);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#5169A8").s().p("EgMfAo7MAAAhR2IY/AAMAAABR2g");
	this.shape.setTransform(80,262);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,160,524);


(lib.EqualHousingOpportunityrevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// EqualHousingOpportunity-rev.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyZSUIAAw4IixAAIAAlsIU+uDIAZAAIU+ODIAAFwIivAAIAAQ0gAtyhwIAAOUIbpAAIAAuPIt3pUgAnQJ9IAAmDIOmAAIAAGDgAnSC9IAAl/IOmAAIAAF/g");
	this.shape.setTransform(135.6,117.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AEDBvQgWgLgIgWQgKgWAAgmIAAiHIAfAAIAACHQAAAgAHANQAFAPAOAJQAPAHAUAAQAiAAAPgPQAPgQAAgtIAAiHIAfAAIAACHQABAjgJAWQgIAUgVAOQgVAOgjAAQghAAgVgMgAmwBrQgbgSgNgbQgOgbAAghQABg4AfgiQAgghAzgBQAgAAAaAQQAbAQAOAcQAOAcAAAiQAAAkgOAcQgPAdgbAPQgaAOggABQghAAgbgQgAmthHQgYAXAAAzQAAAsAXAYQAXAZAjAAQAkAAAWgZQAYgZAAguQgBgbgJgWQgKgWgTgLQgSgMgYgBQgiAAgYAYgAxoBrQgbgRgNgcQgOgbAAghQAAg4AggiQAfghAzgBQAhAAAaAQQAbAQAOAcQANAcAAAiQABAlgPAbQgNAcgcAQQgaAOggABQgiAAgagQgAxmhHQgYAXAAAzQAAAqAYAaQAXAZAiAAQAlAAAWgZQAXgZAAguQAAgcgKgVQgJgVgUgMQgSgMgYgBQggAAgaAYgAQhB2IAAhkIhciHIAmAAIBHBvIBIhvIAlAAIhfCHIAABkgANPB2IAAjPIhOAAIAAgcIC9AAIAAAcIhPAAIAADPgAK7B2IAAjrIAfAAIAADrgAJkB2Ih9i5IAAC5IgeAAIAAjrIAhAAIB9C4IAAi4IAeAAIAADrgABMB2IAAjPIhMAAIAAgcIC6AAIAAAcIhPAAIAADPgAgwB2IgggxIgWghQgLgMgFgEQgGgDgJgDIgSgBIgkAAIAABpIgfAAIAAjrIBpAAQAfgBASAHQARAHAJAQQAKAQAAAUQAAAYgRATQgPAOgjAFQAMAGAHAGQAPAOALASIApBAgAi7gNIBEAAQAWABAMgFQAMgEAGgKQAHgJgBgMQAAgRgMgLQgLgLgbAAIhMAAgAq5B2IAAjrIBaAAQAWAAAOACQASADAMAIQALAIAHAPQAIAOAAASQgBAggSASQgUAVgyAAIg+AAIAABggAqagEIA+AAQAfAAANgMQAMgLAAgVQAAgPgIgKQgHgLgMgDQgHgCgWAAIg+AAgAuTB2IAAjrIBaAAQAXAAANACQASADAMAIQALAIAIAPQAHAPAAARQAAAfgUATQgTAVgyAAIg9AAIAABggAtzgEIA9AAQAeAAAOgMQANgLAAgVQgBgPgHgKQgJgLgLgDQgIgCgVAAIg9AAg");
	this.shape_1.setTransform(135.7,277.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AtCBXQgXANgcAAQgcAAgWgOQgXgNgMgZQgNgYAAgdQAAgeANgZQALgYAYgOQAXgNAcAAQAcAAAXAOQAWANANAZQAMAYAAAeQAAAYgIAUQgIAUgPAPQAQAMATAHIgIATQgWgHgWgSgAunhDQgUAWAAAoQAAAnAUAVQAUAVAfAAQAOABANgGQgMgIgPgEIAHgUQAYAIAPAMQAYgWAAgqQAAgZgJgSQgIgTgRgKQgPgKgVAAQgeAAgVAUgAP7BWQgZgNgMgYQgNgZAAgcQAAgdANgaQAMgaAYgNQAXgNAfAAQAYABARAGQARAIALAMQAKAMAFAWIgYAHQgEgPgIgKQgHgJgMgFQgOgFgPAAQgSgBgOAHQgNAFgJAJQgJALgEAJQgIAVAAAVQAAAZAKASQAJATASAJQATAJAUAAQASAAAQgHQARgGAJgIIAAgmIg9AAIAAgWIBXAAIAABJQgTARgWAIQgVAIgXAAQgfgBgYgNgAIXBcQgSgJgMgQQgKgQgBgVIAagCQACAQAGAKQAHAIAOAHQANAGASAAQARAAALgEQAMgFAGgIQAFgIAAgKQAAgJgFgIQgFgHgOgFQgKgEgagFQgbgFgNgGQgOgIgIgMQgHgKAAgPQAAgQAJgNQAJgOARgHQAPgGAWgBQAWABATAGQARAIAJAPQAKAOABARIgbACQgBgSgNgLQgLgKgZAAQgYAAgLAKQgMAIAAANQAAALAIAHQAIAIAhAHQAfAHAPAGQARAIAJALQAJANAAAQQAAARgKAOQgJAPgSAIQgQAIgXAAQgdAAgSgIgAFPBaQgTgLgHgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAFAMAMAHQAMAHASAAQAeAAAMgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgGATgTAMQgSAKgeABQgegBgRgJgAB1BVQgWgNgNgZQgLgYAAgZQAAgzAbgdQAcgdArAAQAdAAAWAOQAXANAMAZQAMAYAAAfQAAAbgMAaQgNAZgXANQgXANgbAAQgegBgWgOgAB4hEQgVAUAAAuQAAAlAUAUQAUAVAeAAQAeAAAUgVQAUgWAAgmQAAgYgIgTQgKgUgPgJQgRgKgUAAQgdAAgUATgArOBaQgSgLgIgSQgIgSAAghIAAh1IAbAAIAAB1QAAAZAFAOQAGAMALAHQANAHARAAQAeAAANgNQANgOAAgmIAAh1IAbAAIAAB1QAAAegHASQgHATgTAMQgRAKgfABQgdgBgSgJgAOGBgIhsifIAACfIgaAAIAAjLIAcAAIBsCfIAAifIAaAAIAADLgAK3BgIAAjLIAcAAIAADLgAALBgIAAhgIhpAAIAABgIgbAAIAAjLIAbAAIAABUIBpAAIAAhUIAbAAIAADLgAliBgIAAjLIAcAAIAACzIBlAAIAAAYgAmXBgIgYg+IhWAAIgWA+IgdAAIBPjLIAdAAIBUDLgAm3AMIgVg3IgPgrQgEAWgHARIgXA7IBGAAgAyGBgIAAjLICUAAIAAAYIh5AAIAAA/IByAAIAAAWIhyAAIAABGIB+AAIAAAYg");
	this.shape_2.setTransform(135.2,250.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,271.2,289.4);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.Close = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F78E1E").s().p("AgLAMIAAgYIAXAAIAAAYg");
	this.shape.setTransform(27.2,150.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F78E1E").s().p("AgcAzIAAhjIAXAAIAAAXIAFgKIAHgIQAEgEAGgBQAFgCAHABIAAAYIgCAAQgHAAgGACQgHADgEAFQgDAFgCAHQgDAGAAAKIAAAmg");
	this.shape_1.setTransform(22.2,147.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F78E1E").s().p("AgQAwQgJgEgHgGQgIgIgDgJIgDgKIgBgLQAAgKADgJQAEgJAGgIQAIgHAIgEIAJgDIAJgBIALABIAKADQAGADAJAJQAGAIADAJQADAKAAAJIgBAGIhHAAQABAGADAGIAFAIIAJAEQAFACAEAAQAIAAAGgDQAHgDAGgGIANAMQgDAEgFADIgJAHIgKADIgOACQgIAAgKgEgAAZgFQgBgHgBgEQgCgFgEgDQgDgEgEgCQgFgCgFAAQgEAAgEACQgFACgDADIgFAJIgEALIAyAAIAAAAg");
	this.shape_2.setTransform(13.2,147.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F78E1E").s().p("AAAA/QgFgCgEgDQgEgEgCgFQgCgGAAgIIAAgzIgNAAIAAgUIANAAIAAgbIAVAAIAAAbIAbAAIAAAUIgbAAIAAAvQAAAHADADQADADAGAAQAIAAAGgEIAAATIgJAEIgLABQgHAAgDgBg");
	this.shape_3.setTransform(4.4,145.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F78E1E").s().p("AgSAwQgOgHgGgEIAKgQQAIAGAIADQAJADAGAAQAHAAAEgDQAEgDAAgFIAAAAQAAgFgHgEQgDgCgKgDQgPgFgGgDQgFgDgDgEQgDgGAAgHIAAAAQAAgHADgFQADgHAFgDQAFgFAGgCQAHgBAFAAQAJAAAKACQAKADAIAGIgJAQQgHgEgIgDQgHgDgGABQgFAAgEACQgDAEAAAEIAAAAQAAAFAGAEIAOAFIALAEQAGADAEABQAFADACAFQADAFAAAHIAAAAQAAAIgDAFQgCAHgFADQgFAFgHABQgHACgIAAQgJAAgLgDg");
	this.shape_4.setTransform(-3.2,147.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F78E1E").s().p("AgWAxQgHgBgEgFQgFgEgDgFQgDgGAAgHQAAgJADgHQADgFAFgDQAGgDAIgDQAHgCAIAAQALAAAPAFIAAgDQAAgEgBgFQgCgDgDgDQgDgDgEgCQgFgBgEAAQgIAAgIACIgNAFIgGgTQAJgEAIgCQAKgDAJABQALAAAIACQAJADAFAGQAFAFAEAIQACAIAAAKIAAA5IgXAAIAAgMQgFAHgIAEQgJADgIAAQgIAAgGgCgAgIAEIgHADQgDADgBADQgCACAAAEIAAABQAAAGAFAFQAGADAJAAQADAAAFgBIAIgEQAEgDACgEQACgEAAgFIAAgGQgOgEgJAAIgIABg");
	this.shape_5.setTransform(-12.7,147.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F78E1E").s().p("AgRBFIAAhOIgNAAIAAgTIANAAIAAgIQAAgIACgGQADgGADgFQAEgDAFgCQAEgCAIAAQAJAAAKADIAAASQgIgBgGAAQgHgBgDAEQgDAEAAAHIAAAGIAaAAIAAATIgaAAIAABOg");
	this.shape_6.setTransform(-20.3,145.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F78E1E").s().p("AgJBDQgIgCgHgDQgHgCgHgEQgGgEgGgGIAPgQQAFAGAOAGQAFADAFABIAKABIAKgBQAEgBADgDQADgBACgEQACgDAAgDIAAgBQAAgDgBgDIgFgGIgJgEIgNgEIgTgGQgJgDgFgCQgGgFgCgGQgDgHAAgJIAAAAQgBgJAEgHQADgHAGgFQAHgFAIgDQAIgDAJAAIAMABIAOADQAHADAOAKIgMARQgKgGgIgEQgKgDgHAAIgIABQgFABgCACQgGAFAAAHIAAAAIABAGQABADAEADQAEACAFADIAPAEQALADAHADQAIADAFADQAGAEACAHQADAFAAAJQAAAKgEAHQgDAHgGAGQgGAFgJACQgJADgLAAIgMgBg");
	this.shape_7.setTransform(40.8,118.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F78E1E").s().p("AgwBCIAAiDIBgAAIAAAVIhJAAIAAAiIBBAAIAAATIhBAAIAAAkIBKAAIAAAVg");
	this.shape_8.setTransform(29.8,118.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#F78E1E").s().p("AgKBCIAAg0Ig1hPIAbAAIAkA7IAlg7IAbAAIg0BOIAAA1g");
	this.shape_9.setTransform(17.3,118.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#F78E1E").s().p("AgKAyIgKgCQgKgEgHgHQgHgIgEgJIgDgJIgBgLIAAAAQAAgGAEgNQAEgJAHgIQAHgHAKgEIAKgDIAKgBQAHAAAOAEQAJAEAIAHQAHAIAEAJQAEANAAAGIAAAAIgBAKIgDAKQgEAJgHAIQgIAHgJAEQgOAEgHAAgAgMgdQgFADgEAFQgEAEgCAGQgCAGAAAFIAAAAQAAAGACAGQACAGAEAEQAFAFAFADQAGACAFAAQAGAAAGgCQAGgDADgFQAEgEADgGQACgFAAgHIAAAAQAAgFgCgGQgDgGgEgEQgEgFgGgCQgFgDgGAAQgFAAgHACg");
	this.shape_10.setTransform(0.6,120.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#F78E1E").s().p("AAAA/QgFgCgEgDQgEgEgCgFQgCgGAAgIIAAgzIgNAAIAAgUIANAAIAAgbIAVAAIAAAbIAbAAIAAAUIgbAAIAAAvQAAAHADADQADADAGAAQAIAAAGgEIAAATIgJAEIgLABQgHAAgDgBg");
	this.shape_11.setTransform(-8.6,118.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#F78E1E").s().p("AAAA/QgFgCgEgDQgEgEgCgFQgCgGAAgIIAAgzIgNAAIAAgUIANAAIAAgbIAVAAIAAAbIAbAAIAAAUIgbAAIAAAvQAAAHADADQADADAGAAQAIAAAGgEIAAATIgJAEIgLABQgHAAgDgBg");
	this.shape_12.setTransform(-20.1,118.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#F78E1E").s().p("AgQAwQgJgEgHgGQgHgIgEgJIgDgKIgBgLQAAgKAEgJQADgJAHgIQAGgHAJgEIAKgDIAIgBIALABIAKADQAGADAJAJQAGAIADAJQADAKAAAJIgBAGIhHAAQABAGACAGIAGAIIAJAEQAFACAEAAQAIAAAHgDQAFgDAHgGIAOAMQgEAEgEADIgJAHIgLADIgOACQgJAAgJgEgAAZgFQgBgHgCgEQgBgFgDgDQgDgEgFgCQgEgCgGAAQgDAAgFACQgEACgDADIgHAJIgCALIAxAAIAAAAg");
	this.shape_13.setTransform(-28.5,120.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#F78E1E").s().p("AgYA/QgMgDgJgGIAIgRQAIAFAJADQAJACAKAAQAFAAAGgCQAGgBAEgEQAEgEACgGQADgGAAgHIAAgIQgJAKgGADQgEADgGABQgEABgFAAQgJAAgIgDQgIgDgGgGQgHgGgEgJQgDgHAAgLIAAAAQAAgHADgNQAEgIAHgHQAGgGAIgDQAIgDAJAAQAFAAAFABQAFABAEADQAIAEAGAIIAAgPIAXAAIAABOQAAAMgDAKQgDAJgGAHIgIAGIgKAEQgPADgHAAQgMAAgLgDgAgKgsQgFACgEAEIgGAIQgCAGAAAGIAAAAQAAAGACAFQACAFAEACQAEAEAFACQAFACAFAAQAFAAAGgCQAFgCAEgEQAEgCACgFQADgFAAgGIAAAAQAAgGgDgFQgCgFgEgEQgEgEgFgCQgGgCgFAAQgFAAgFACg");
	this.shape_14.setTransform(-39.9,121.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#F78E1E").s().p("AAVAzIAAg3QABgGgCgFQgCgEgCgDIgHgFQgEgCgFAAQgDAAgEACIgHAFQgEADgBAFQgBAEgBAGIAAA3IgWAAIAAhjIAWAAIAAAQQAGgIAHgEIAIgEQADgCAGAAQAIAAAHADQAGADAFAFQAEAFADAHQADAHAAAJIAAA+g");
	this.shape_15.setTransform(25.8,93.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#F78E1E").s().p("AgWAxQgGgBgFgFQgFgEgDgFQgDgGAAgHQAAgJADgHQADgFAGgDQAFgDAHgDQAIgCAIAAQALAAAPAFIAAgDQABgEgCgFQgCgEgDgCQgDgDgEgCQgGgBgDAAQgIAAgHACIgOAFIgGgTQAJgEAIgCQAJgDAKABQALAAAJACQAIADAFAGQAFAFADAIQADAIAAAKIAAA5IgXAAIAAgMQgFAHgIAEQgJADgIAAQgHAAgHgCgAgIAEIgHADQgDADgCACQgBADAAAEIAAABQAAAGAGAEQAFAEAIAAQAEAAAFgBIAIgEQAEgDACgEQACgEAAgFIAAgGQgOgDgJgBIgIABg");
	this.shape_16.setTransform(15,93.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#F78E1E").s().p("AgEAyIgKgCQgJgEgIgHQgGgIgEgJQgEgJAAgLIAAAAQAAgJAEgKQAEgJAGgIQAIgHAJgEIAKgDIAJgBQAHAAAGACQAGABAFACQAGADAKAKIgOAOQgGgFgFgEQgHgDgIAAQgFAAgEACQgGADgEAFQgEAEgCAGQgCAGAAAFIAAAAQAAAGACAGQADAGAEAEQADAFAGADQAEACAGAAQAHAAAIgDQAFgDAGgGIAOANQgLAKgGAEIgLADQgGACgHAAg");
	this.shape_17.setTransform(5.5,93.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#F78E1E").s().p("AgQAwQgJgEgHgGQgHgIgEgJIgDgKIgBgLQAAgKADgJQAEgJAHgIQAGgHAJgEIAJgDIAJgBIALABIAKADQAGADAJAJQAGAIADAJQADAKAAAJIAAAGIhIAAQABAGACAGIAHAIIAJAEQAEACAEAAQAIAAAGgDQAHgDAGgGIANAMQgDAEgFADIgJAHIgLADIgMACQgJAAgKgEgAAZgFQAAgHgDgEQgBgFgEgDQgDgEgEgCQgFgCgFAAQgDAAgFACQgEACgDADIgGAJIgDALIAxAAIAAAAg");
	this.shape_18.setTransform(-9.5,93.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#F78E1E").s().p("AAWAyIgWhCIgVBCIgVAAIgghjIAXAAIAVBDIAWhDIARAAIAXBDIAUhDIAXAAIghBjg");
	this.shape_19.setTransform(-22.4,93.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#F78E1E").s().p("AgOARQAIgCAEgFQADgEgBgGIgIAAIAAgZIAXAAIAAAWQAAAGgBAFQgCAGgEAEQgEAEgEACQgFACgHAAg");
	this.shape_20.setTransform(51.9,71.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#F78E1E").s().p("AgcAzIAAhjIAXAAIAAAXIAFgKIAHgIQAEgEAGgBQAFgCAHABIAAAYIgCAAQgHAAgGACQgHADgEAFQgDAFgCAHQgDAGAAAKIAAAmg");
	this.shape_21.setTransform(47.2,66.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#F78E1E").s().p("AgQAwQgJgEgHgGQgHgIgEgJIgDgKIgBgLQAAgKAEgJQADgJAGgIQAIgHAIgEIAKgDIAIgBIALABIAKADQAGADAJAJQAGAIADAJQADAKAAAJIgBAGIhHAAQABAGACAGIAGAIIAJAEQAFACAEAAQAIAAAHgDQAFgDAHgGIAOAMQgEAEgEADIgJAHIgLADIgOACQgJAAgJgEgAAZgFQAAgHgDgEQgBgFgDgDQgDgEgFgCQgFgCgFAAQgDAAgFACQgFACgCADIgHAJIgDALIAyAAIAAAAg");
	this.shape_22.setTransform(38.2,66.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#F78E1E").s().p("AgVBCQgJgDgGgHQgHgHgDgJIgDgKIgBgMIAAgBQAAgIADgMQAEgJAHgHQAGgHAJgDQAIgEAJAAQAEAAAFACIAKAEQAHAEAGAIIAAg2IAXAAIAACJIgXAAIAAgRQgGAJgHAEQgFADgFABQgFACgEAAQgJAAgIgEgAgKgKQgFACgEAEQgEAEgCAEQgCAGAAAHIAAABQAAAHACAGQACAGAEAEQAEAEAGADQAFACAEAAQAFAAAGgCQAFgDAEgEQAEgEACgGQADgGAAgHIAAgBQAAgHgDgGQgCgEgEgEQgEgEgFgCQgGgDgFAAQgEAAgGADg");
	this.shape_23.setTransform(26.8,64.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#F78E1E").s().p("AAVAzIAAg3QABgGgCgFQgCgEgCgDIgHgFQgEgCgFAAQgDAAgEACIgHAFQgEADgBAFQgBAEgBAGIAAA3IgWAAIAAhjIAWAAIAAAQQAGgIAHgEIAIgEQADgCAGAAQAIAAAHADQAGADAFAFQAEAFADAHQADAHAAAJIAAA+g");
	this.shape_24.setTransform(15.9,66.1);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#F78E1E").s().p("AgQAwQgJgEgHgGQgHgIgEgJIgDgKIgBgLQAAgKADgJQAEgJAGgIQAIgHAIgEIAJgDIAJgBIALABIAKADQAGADAJAJQAGAIADAJQADAKAAAJIAAAGIhIAAQABAGADAGIAGAIIAJAEQAEACAEAAQAIAAAGgDQAHgDAGgGIANAMQgDAEgFADIgJAHIgLADIgMACQgJAAgKgEgAAZgFQAAgHgCgEQgCgFgEgDQgDgEgEgCQgEgCgGAAQgEAAgEACQgFACgDADIgFAJIgEALIAyAAIAAAAg");
	this.shape_25.setTransform(5.3,66.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#F78E1E").s().p("AgtBCIAAiDIAXAAIAABuIBEAAIAAAVg");
	this.shape_26.setTransform(-4.9,64.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#F78E1E").s().p("AAsBCIgOgfIg8AAIgOAfIgYAAIA6iEIAVAAIA6CEgAAWANIgWgzIgWAzIAsAAg");
	this.shape_27.setTransform(-22.4,64.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#F78E1E").s().p("Ag2BCIAAiDIA5AAQAMAAAJADQAJADAFAFQAFAFACAFQACAGAAAHQAAAGgBAFQgBAFgEADQgEAHgIAEIAKACIAIAHQAEAEACAFQACAGAAAGIAAABQAAAIgEAHQgDAHgHAFQgGAEgJACQgJADgMAAgAgfAtIAlAAQAGAAAFgBQAEgBADgCQAEgCABgEQACgEAAgEIAAgBQABgEgCgDIgGgFQgDgDgFgBIgMgBIgjAAgAgfgJIAfAAIAKgBQAEgBADgCQADgDACgDQACgEAAgEIAAgBQAAgEgCgDQgBgCgDgCQgDgDgEgBQgEgBgGgBIggAAg");
	this.shape_28.setTransform(-35.4,64.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#F78E1E").s().p("AgKBDQgGgCgIgDQgHgCgHgEIgMgKIAOgQQAHAGANAGQAFADAGABIAJABIAKgBQAFgBADgDQADgBABgEQACgDAAgDIAAgBQAAgDgCgDIgEgGIgJgEIgNgEIgTgGQgJgDgFgCQgGgFgCgGQgEgHAAgJIAAAAQABgJADgHQADgHAHgFQAGgFAHgDQAJgDAJAAIANABIAMADQAIADAOAKIgNARQgIgGgKgEQgIgDgIAAIgJABQgDABgEACQgFAFAAAHIAAAAIABAGQACADADADQADACAHADIANAEQALADAIADQAIADAGADQAFAEADAHQACAFAAAJQAAAKgDAHQgEAHgGAGQgGAFgJACQgJADgKAAIgOgBg");
	this.shape_29.setTransform(-47.8,64.6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#F78E1E").s().p("AgVBCQgJgDgGgHQgHgHgDgJIgDgKIgBgMIAAgBQAAgIADgMQAEgJAHgHQAGgHAJgDQAIgEAJAAQAEAAAFACIAKAEQAHAEAGAIIAAg2IAXAAIAACJIgXAAIAAgRQgGAJgHAEQgFADgFABQgFACgEAAQgJAAgIgEgAgKgKQgFACgEAEQgEAEgCAEQgCAGAAAHIAAABQAAAHACAGQACAGAEAEQAEAEAGADQAFACAEAAQAFAAAGgCQAFgDAEgEQAEgEACgGQADgGAAgHIAAgBQAAgHgDgGQgCgEgEgEQgEgEgFgCQgGgDgFAAQgEAAgGADg");
	this.shape_30.setTransform(35,37.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#F78E1E").s().p("AgQAwQgJgEgHgGQgHgIgEgJIgDgKIgBgLQAAgKAEgJQADgJAGgIQAIgHAIgEIAKgDIAIgBIALABIAKADQAGADAJAJQAGAIADAJQADAKAAAJIgBAGIhHAAQABAGACAGIAGAIIAJAEQAFACAEAAQAIAAAHgDQAFgDAHgGIAOAMQgEAEgEADIgJAHIgLADIgOACQgJAAgJgEgAAZgFQAAgHgDgEQgBgFgDgDQgDgEgFgCQgFgCgFAAQgDAAgFACQgFACgDADIgGAJIgCALIAxAAIAAAAg");
	this.shape_31.setTransform(24.2,39.2);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#F78E1E").s().p("AgcAzIAAhjIAXAAIAAAXIAFgKIAHgIQAEgEAGgBQAFgCAHABIAAAYIgCAAQgHAAgGACQgHADgEAFQgDAFgCAHQgDAGAAAKIAAAmg");
	this.shape_32.setTransform(16,39.1);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#F78E1E").s().p("AgcAzIAAhjIAXAAIAAAXIAFgKIAHgIQAEgEAGgBQAFgCAHABIAAAYIgCAAQgHAAgGACQgHADgEAFQgDAFgCAHQgDAGAAAKIAAAmg");
	this.shape_33.setTransform(9.2,39.1);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#F78E1E").s().p("AgQAwQgJgEgHgGQgIgIgDgJIgDgKIgBgLQAAgKAEgJQADgJAHgIQAGgHAJgEIAKgDIAIgBIALABIAKADQAGADAJAJQAGAIADAJQADAKAAAJIgBAGIhHAAQABAGACAGIAHAIIAJAEQAEACAEAAQAIAAAHgDQAFgDAHgGIAOAMQgEAEgEADIgJAHIgMADIgNACQgJAAgJgEgAAZgFQgBgHgCgEQgBgFgDgDQgEgEgEgCQgEgCgGAAQgEAAgEACQgEACgDADIgHAJIgCALIAxAAIAAAAg");
	this.shape_34.setTransform(0.2,39.2);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#F78E1E").s().p("AgRBFIAAhOIgMAAIAAgTIAMAAIAAgIQAAgIACgGQACgGAEgFQAEgEAFgBQAFgCAHAAQAKAAAJADIAAASQgIgBgGAAQgHgBgDAEQgEAEABAHIAAAGIAaAAIAAATIgaAAIAABOg");
	this.shape_35.setTransform(-7.9,37.2);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#F78E1E").s().p("AgQAwQgJgEgHgGQgHgIgEgJIgDgKIgBgLQAAgKAEgJQADgJAHgIQAGgHAJgEIAKgDIAIgBIALABIAKADQAGADAJAJQAGAIADAJQADAKAAAJIgBAGIhHAAQABAGACAGIAGAIIAJAEQAFACAEAAQAIAAAHgDQAFgDAHgGIAOAMQgEAEgEADIgJAHIgLADIgOACQgJAAgJgEgAAZgFQgBgHgCgEQgBgFgDgDQgDgEgFgCQgEgCgGAAQgDAAgFACQgEACgDADIgHAJIgCALIAxAAIAAAAg");
	this.shape_36.setTransform(-16.4,39.2);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#F78E1E").s().p("AgcAzIAAhjIAXAAIAAAXIAFgKIAHgIQAEgEAGgBQAFgCAHABIAAAYIgCAAQgHAAgGACQgHADgEAFQgDAFgCAHQgDAGAAAKIAAAmg");
	this.shape_37.setTransform(-24.6,39.1);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#F78E1E").s().p("AgyBCIAAiDIAyAAQAMAAAJADQAKADAGAGQAHAGADAIQAEAJAAAKIAAAAIgBALIgDAIQgEAHgIAGQgHAFgKAEQgJACgJAAIgaAAIAAArgAgaACIAaAAQAFAAAFgCQAGAAADgCQAFgDACgFQABgFAAgEIAAgBQAAgFgBgFQgCgEgFgDQgDgDgGgCQgFgBgFgBIgaAAg");
	this.shape_38.setTransform(-33.7,37.6);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#F78E1E").s().p("AgWAxQgGgBgFgFQgFgEgDgFQgDgGAAgHQAAgJADgHQADgFAGgDQAFgDAHgDQAIgCAJAAQAKAAAQAFIAAgDQgBgEgBgFQgCgEgDgCQgDgDgFgCQgFgBgDAAQgIAAgIACIgNAFIgGgTQAJgEAIgCQAJgDAKABQALAAAJACQAHADAGAGQAFAFADAIQADAIAAAKIAAA5IgWAAIAAgMQgHAHgHAEQgKADgHAAQgHAAgHgCgAgIAEIgHADQgDADgCADQgBACAAAEIAAABQAAAGAFAFQAGADAIAAQAEAAAFgBIAIgEQAEgDACgEQACgEAAgFIAAgGQgOgEgJAAIgIABg");
	this.shape_39.setTransform(13.8,12.2);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#F78E1E").s().p("AgSAwQgOgHgGgEIAKgQQAIAGAIADQAJADAGAAQAHAAAEgDQAEgDAAgFIAAAAQAAgFgHgEQgDgCgKgDQgPgFgGgDQgFgDgDgEQgDgGAAgHIAAAAQAAgHADgFQADgHAFgDQAFgFAGgCQAHgBAFAAQAJAAAKACQAKADAIAGIgJAQQgHgEgIgDQgHgDgGABQgFAAgEACQgDAEAAAEIAAAAQAAAFAGAEIAOAFIALAEQAGADAEABQAFADACAFQADAFAAAHIAAAAQAAAIgDAFQgCAHgFADQgFAFgHABQgHACgIAAQgJAAgLgDg");
	this.shape_40.setTransform(-0.1,12.2);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#F78E1E").s().p("AAsBCIgOgfIg8AAIgOAfIgYAAIA6iEIAVAAIA6CEgAAWANIgWgzIgWAzIAsAAg");
	this.shape_41.setTransform(-11.2,10.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-57.5,0,115,158);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border160x600 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("EgJNgutISbAAMAAABdbIybAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60,-300,120,600);


(lib._2016_SCU_tagvertai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACAATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgACJgKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgGgFgEQgEgFgHAAQgHAAgEAFgAizATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAiqgKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgGgFgEQgEgFgHAAQgHAAgEAFgAm4ATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgAmwgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgGgEgEQgFgFgHAAQgGAAgFAFgAC5ADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAl/ADIAAgcIALAAIAAAcQAAANAMAAQALAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgWAAAAgXgAHpAaIAAgMIAMAAIAAAMgAHOAaIAAgVIgUgeIANAAIANAVIAMgVIANAAIgUAeIAAAVgAGzAaIgFgMIgWAAIgEAMIgMAAIAWgzIALAAIAWAzgAGqAEIgHgPIgHAPIAOAAgAFvAaIgMggIgMAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIAMAiIAKgiIAMAAIgRAzgAESAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAD+AAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgABYAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAAcAaIAAgMIAMAAIAAAMgAABAaIAAgVIgSgeIANAAIALAVIAMgVIANAAIgUAeIAAAVgAg+AaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgAhUAaIgaggIAAAgIgLAAIAAgzIALAAIAYAfIAAgfIALAAIAAAzgAjRAaIAAghIgOAVIgBAAIgOgUIAAAgIgLAAIAAgzIAMAAIAOAWIANgWIANAAIAAAzgAkmAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAFAGQAFAEAAAIQAAAKgLAEIAMATgAk6AAIALAAQAJAAAAgHQAAgHgJAAIgLAAgAngAaIAAgVIgUgeIANAAIANAVIAMgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(50.2,12.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AkLADIAAgcIALAAIAAAcQAAANAMAAQALAAAAgNIAAgcIALAAIAAAcQAAAYgWAAQgXAAAAgYgAlEATQgIgIAAgLQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKIAAAAQAAALgHAIQgIAIgMAAQgMAAgIgIgAk8gKQgEAEAAAGIAAAAQAAAHAEAEQAFAFAHAAQAHAAAEgFQAEgEAAgHQAAgFgEgFQgFgFgGAAQgHAAgFAFgADHASIAHgIQAHAGAIAAQAIAAAAgFQAAgEgLgCQgJgDgDgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAIAAQAMAAAIAGIgGAJQgIgFgGAAQgHAAAAAEIAAABQAAAEAMACQAQAEAAAKQAAAQgTAAQgNAAgJgIgAF1AaIAAgMIAMAAIAAAMgAFMAaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAGQgGAEgJAAIgJAAIAAAQgAFYAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAE0AaIAAgzIALAAIAAAzgAEbAaIAAgVIgVAAIAAAVIgMAAIAAgzIAMAAIAAAVIAVAAIAAgVIAMAAIAAAzgAC0AaIgLgRIgJAAIAAARIgLAAIAAgzIAXAAQAKAAAGAGQAEAEAAAIQAAAKgLAEIANATgACgAAIAMAAQAJAAAAgHQAAgHgKAAIgLAAgABiAaIAAgzIAoAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAAtAaIAAgzIAYAAQAIAAAFAFQAEADAAAGIAAAAQAAAHgHAEQAKACAAAJQAAAPgUAAgAA4AQIANAAQAJAAAAgGQAAgGgJAAIgNAAgAA4gDIAKAAQAJAAAAgGIAAAAQAAgGgIAAIgLAAgAAUAaIAAggIgOAUIgBAAIgMgUIAAAgIgLAAIAAgzIAMAAIAMAXIAOgXIAMAAIAAAzgAhEAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAhcAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAXIAOgXIAMAAIAAAzgAiyAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAFAGQAFAEAAAIQAAAKgLAEIAMATgAjGAAIALAAQAJAAAAgHQAAgHgJAAIgLAAgAlsAaIAAgVIgUgeIANAAIANAVIAMgVIAOAAIgVAeIAAAVg");
	this.shape_1.setTransform(50.2,2.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,100.4,14.9);


(lib._2016_SCU_logoruleTHICKai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#5169A8").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0,1,2.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,-1,162.9,2);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib._2016_SCU_BBSvertai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACVASIAHgIQAIAGAJAAQAHAAAAgEQAAgFgKgCQgKgDgEgCQgEgCAAgHIAAgBQgBgHAGgEQAFgFAJAAQAKAAAJAHIgGAJQgHgGgHAAQgGAAAAAFIAAABQAAAAAAABQAAAAAAABQAAAAABABQAAAAAAAAIAKAEQAQADAAAKQABARgUAAQgNAAgKgJgAA0ATQgIgIAAgLQAAgKAIgIQAIgIAMAAQAMAAAIAIIgHAJQgGgGgHAAQgHAAgFAFQgEAFAAAFQAAAHAEAFQAFAEAHAAQAHAAAGgGIAIAHQgIAKgNAAQgMAAgIgIgAi/ASIAHgIQAIAGAJAAQAHAAAAgEQAAgFgKgCQgKgDgEgCQgEgCAAgHIAAgBQgBgHAGgEQAFgFAJAAQAKAAAJAHIgGAJQgIgGgGAAQgGAAAAAFIAAABQgBADALAEQARADABAKQgBAIgFAFQgFAEgJAAQgNAAgKgJgAgRAaIgWgzIAOAAIANAjIAMgjIAMAAIgTAzgABmAaIAAgzIApAAIAAAKIgdAAIAAALIAZAAIAAAJIgZAAIAAAKIAdAAIAAALgAAVAaIAAgzIAMAAIAAAzgAg3AaIgMgRIgJAAIAAARIgLAAIAAgzIAYAAQAKAAAFAGQAFAEAAAHQAAALgMAEIAOATgAhMAAIAMAAQAJAAAAgHIAAAAQAAgIgJAAIgMAAgAiKAaIAAgzIAoAAIAAAKIgdAAIAAALIAZAAIAAAJIgZAAIAAAKIAdAAIAAALg");
	this.shape.setTransform(0,22);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACLAUQgIgJAAgLQAAgKAIgIQAHgIAMAAQAOAAAHAHIgHAJQgFgFgJAAQgHAAgDAFQgFAEAAAGQAAAHAFAFQAEAEAHAAQAGAAAFgDIAAgIIgMAAIAAgIIAYAAIAAAWQgLAIgNAAQgMAAgHgHgABvAaIgaggIAAAgIgMAAIAAgzIALAAIAZAeIAAgeIAMAAIAAAzgAAwAaIAAgzIAMAAIAAAzgAAaAaIgQgXIgGAHIAAAQIgJAAIAAgzIAJAAIAAAXIAVgXIAPAAIgWAWIAXAdgAgdAaIgZggIAAAgIgMAAIAAgzIALAAIAZAeIAAgeIALAAIAAAzgAhWAaIgFgMIgWAAIgGAMIgLAAIAWgzIAMAAIAWAzgAhfAEIgHgQIgIAQIAPAAgAi1AaIAAgzIAZAAQAKAAAEAEQAEAEAAAFIAAABQAAAHgHAEQAJACAAAKQAAAOgTAAgAipAQIAOAAQAIAAAAgGQAAgGgJAAIgNAAgAipgEIALAAQAIAAAAgFIAAgBQAAgFgHAAIgMAAg");
	this.shape_1.setTransform(0,12.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ACVATIAHgJQAIAHAIgBQAIAAAAgEQAAgEgLgEQgKgBgDgDQgFgCAAgIIAAAAQAAgHAFgFQAGgEAIAAQALAAAJAHIgHAIQgIgEgFAAQgHgBAAAFQAAAEALADQARAEAAAKIAAABQAAAQgTAAQgNAAgKgIgABlATIAHgJQAIAHAIgBQAIAAgBgEQABgEgLgEQgJgBgDgDQgFgCgBgIIAAAAQABgHAFgFQAFgEAIAAQAMAAAIAHIgGAIQgIgEgGAAQgHgBAAAFQAAAEAMADQAQAEABAKIAAABQAAAQgUAAQgNAAgKgIgAhRATIAGgJQAIAHAIgBQAIAAAAgEQAAgEgLgEQgJgBgEgDQgEgCAAgIIAAAAQgBgHAGgFQAFgEAIAAQALAAAJAHIgGAIQgIgEgGAAQgHgBAAAFQAAAEALADQASAEgBAKIAAABQAAAQgTAAQgNAAgJgIgAiIADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAYgXAAQgXAAAAgYgAA2AaIAAgzIAoAAIAAALIgdAAIAAAKIAaAAIAAAIIgaAAIAAALIAdAAIAAALgAAfAaIgaggIAAAgIgJAAIAAgzIAJAAIAZAeIAAgeIALAAIAAAzgAgdAaIAAgzIAMAAIAAAzgAi+AaIAAgzIAYAAQAKAAAFAEQADAEAAAFIAAABQAAAHgHAEQAKACAAAKQAAAOgUAAgAizAQIAOAAQAIAAAAgGQAAgGgIAAIgOAAgAizgEIALAAQAJAAAAgFIAAgBQgBgFgHAAIgMAAg");
	this.shape_2.setTransform(0,2.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-19.2,0,38.4,24.8);


(lib._2016TAGvert = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._2016_SCU_tagvertai();
	this.instance.setTransform(-0.1,7.5,1,1,0,0,0,50.1,7.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-50.2,0,100.4,14.9);


// stage content:
(lib.SCU201609_Air_120x600_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_177 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(177).call(this.frame_177).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.setTransform(99,448,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(177).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	this.clickthru_btn.setTransform(0,0,0.357,2.143);
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},178).wait(1));

	// ncua
	this.instance = new lib.ncuastackai();
	this.instance.setTransform(60,576.7,1.153,1.153,0,0,0,0,3.6);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(177).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_1 = new lib.border160x600();
	this.instance_1.setTransform(60,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({_off:true},178).wait(1));

	// PIC1
	this.instance_2 = new lib._336x280air();
	this.instance_2.setTransform(-94,1,0.743,0.743);

	this.instance_3 = new lib.Tween5("synched",0);
	this.instance_3.setTransform(30.9,84.3);
	this.instance_3._off = true;

	this.instance_4 = new lib.Tween6("synched",0);
	this.instance_4.setTransform(30.9,65.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2}]}).to({state:[{t:this.instance_3}]},169).to({state:[{t:this.instance_4}]},8).to({state:[]},1).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(169).to({_off:false},0).to({_off:true,y:65.3},8).wait(2));

	// PIC2
	this.instance_5 = new lib.Tween1("synched",0);
	this.instance_5.setTransform(60,98);
	this.instance_5._off = true;

	this.instance_6 = new lib.Tween2("synched",0);
	this.instance_6.setTransform(60,237.5);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(39).to({_off:false},0).to({_off:true,y:237.5},7).wait(133));
	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(39).to({_off:false},7).wait(123).to({startPosition:0},0).to({y:201.5},8).to({_off:true},1).wait(1));

	// pic shad
	this.instance_7 = new lib.HTML5rastershad_1();
	this.instance_7.setTransform(60,176.5,1,1,0,0,0,0,10);
	this.instance_7.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(39).to({y:177.5},0).to({y:317},7).wait(123).to({y:281},8).to({_off:true},1).wait(1));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("AubGdIAAs5Ic3AAIAAM5g");
	var mask_graphics_39 = new cjs.Graphics().p("AubGzIAAtlIc3AAIAANlg");
	var mask_graphics_40 = new cjs.Graphics().p("AubGvIAAtdIc3AAIAANdg");
	var mask_graphics_41 = new cjs.Graphics().p("AubGrIAAtVIc3AAIAANVg");
	var mask_graphics_42 = new cjs.Graphics().p("AubGoIAAtPIc3AAIAANPg");
	var mask_graphics_43 = new cjs.Graphics().p("AubGkIAAtHIc3AAIAANHg");
	var mask_graphics_44 = new cjs.Graphics().p("AubGhIAAtBIc3AAIAANBg");
	var mask_graphics_45 = new cjs.Graphics().p("AubGdIAAs5Ic3AAIAAM5g");
	var mask_graphics_46 = new cjs.Graphics().p("AubGZIAAsxIc3AAIAAMxg");
	var mask_graphics_88 = new cjs.Graphics().p("EgNMAkZIAA3IIaYAAIAAXIg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:61.5,y:233.5}).wait(39).to({graphics:mask_graphics_39,x:61.5,y:235.4}).wait(1).to({graphics:mask_graphics_40,x:61.5,y:253.2}).wait(1).to({graphics:mask_graphics_41,x:61.5,y:271}).wait(1).to({graphics:mask_graphics_42,x:61.5,y:288.8}).wait(1).to({graphics:mask_graphics_43,x:61.5,y:306.6}).wait(1).to({graphics:mask_graphics_44,x:61.5,y:324.4}).wait(1).to({graphics:mask_graphics_45,x:61.5,y:342.2}).wait(1).to({graphics:mask_graphics_46,x:61.5,y:360}).wait(1).to({graphics:null,x:0,y:0}).wait(41).to({graphics:mask_graphics_88,x:60.5,y:233}).wait(8).to({graphics:null,x:0,y:0}).wait(83));

	// HEAD
	this.instance_8 = new lib.HEAD1();
	this.instance_8.setTransform(179.5,236,1,1,0,0,0,119.5,27);

	this.instance_8.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(39).to({y:359},7).wait(42).to({y:493},7).to({_off:true},1).wait(83));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_169 = new cjs.Graphics().p("EgOMAkeIAA2+IcaAAIAAW+g");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(169).to({graphics:mask_1_graphics_169,x:60,y:233.5}).wait(9).to({graphics:null,x:0,y:0}).wait(1));

	// HEAD2
	this.instance_9 = new lib.HEAD2();
	this.instance_9.setTransform(58.5,233.9,1,1,0,0,0,-1.5,31.9);
	this.instance_9._off = true;

	this.instance_9.mask = mask_1;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(88).to({_off:false},0).to({y:365.9},7).wait(74).to({y:501.9},8).to({_off:true},1).wait(1));

	// Close
	this.instance_10 = new lib.Close();
	this.instance_10.setTransform(60,213,1,1,0,0,0,0,54);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(169).to({_off:false},0).to({y:342},8).to({_off:true},1).wait(1));

	// head bkgd
	this.instance_11 = new lib.headbkgd();
	this.instance_11.setTransform(148,124.8,1,0.891,0,0,0,168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({_off:true},178).wait(1));

	// BBS
	this.instance_12 = new lib._2016_SCU_BBSvertai();
	this.instance_12.setTransform(134.5,540.3,1.9,1.9,0,0,0,39.2,7.7);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(88).to({_off:false},0).to({_off:true},89).wait(2));

	// tag
	this.instance_13 = new lib._2016TAGvert();
	this.instance_13.setTransform(60.1,526.2,1.014,1.014,0,0,0,0,2.6);
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(177).to({_off:false},0).to({_off:true},1).wait(1));

	// logo
	this.instance_14 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_14.setTransform(204.9,528.5,0.673,0.673,0,0,0,215.2,63.1);
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(88).to({_off:false},0).to({_off:true},90).wait(1));

	// logo rule
	this.instance_15 = new lib._2016_SCU_logoruleTHICKai();
	this.instance_15.setTransform(116.8,518.8,0.696,0.696,0,0,0,81.5,0.5);
	this.instance_15._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(88).to({_off:false},0).to({_off:true},90).wait(1));

	// shad
	this.instance_16 = new lib.HTML5rastershad_1();
	this.instance_16.setTransform(41.1,476.9,1,1,0,0,0,0,10);
	this.instance_16.alpha = 0.301;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).to({_off:true},178).wait(1));

	// logo box
	this.instance_17 = new lib.box1();
	this.instance_17.setTransform(51.2,197.4,0.475,4.282,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_17).to({_off:true},178).wait(1));

	// EHO
	this.instance_18 = new lib.EqualHousingOpportunityrevai("synched",0);
	this.instance_18.setTransform(-5.9,454,0.07,0.07,0,0,0,135,145);
	this.instance_18._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(177).to({_off:false},0).to({_off:true},1).wait(1));

	// com
	this.instance_19 = new lib.comhoriz();
	this.instance_19.setTransform(60,586.2,0.683,0.683,0,0,0,0,0.9);
	this.instance_19._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_19).wait(177).to({_off:false},0).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-66.9,300,355,600);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;