(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 300,
	height: 250,
	fps: 18,
	color: "#CCCCCC",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/HTML5rastershad.png", id:"HTML5rastershad"},
		{src:"images/SCU201609_Elec_300x250_AdR_atlas_NP_.jpg", id:"SCU201609_Elec_300x250_AdR_atlas_NP_"}
	]
};



lib.ssMetadata = [
		{name:"SCU201609_Elec_300x250_AdR_atlas_NP_", frames: [[0,0,336,224],[338,0,168,140]]}
];


lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib._336x280elec = function() {
	this.spriteSheet = ss["SCU201609_Elec_300x250_AdR_atlas_NP_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib._336x280retail = function() {
	this.spriteSheet = ss["SCU201609_Elec_300x250_AdR_atlas_NP_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.HTML5rastershad = function() {
	this.initialize(img.HTML5rastershad);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,20);


(lib.Tween14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._336x280retail();
	this.instance.setTransform(-84,-70);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-84,-70,168,140);


(lib.Tween13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._336x280retail();
	this.instance.setTransform(-84,-70);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-84,-70,168,140);


(lib.Tween11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._336x280elec();
	this.instance.setTransform(-151.5,-101,0.902,0.902);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-151.5,-101,303,202);


(lib.replaybtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#666666").s().p("Ak9BwIAAjgIJ6AAIAADgg");
	this.shape.setTransform(9.1,9.8,0.438,1.268,0,0,0,-0.2,0);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BFBFBF").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_1.setTransform(8.4,9.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#666666").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_2.setTransform(8.4,9.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgEBGQghgDgWgXQgXgZAAgfQAAgQAGgQQAOggAfgNQARgGAOgBQAiAAAYAZQAZAYAAAjIgUAAQAAgbgTgSQgSgTgaAAQgZAAgSATQgTATAAAaQAAAXARASQAQASAZACIgNgcIBVAnIhWAlg");
	this.shape_3.setTransform(8.4,9.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,16.7,19.4);


(lib.ncuahorizai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A5AFD4").s().p("AEOAmIADgGQADACAEAAQAGAAADgJIgUgsIAHAAIARAlIAPglIAHAAIgTAuQgFANgLAAQgGAAgEgCgAjbAmIADgGQACACAFAAQAGAAADgJIgVgsIAHAAIARAlIAQglIAHAAIgUAuQgFANgKAAQgGAAgEgCgAIGAXQgGgFAAgGQAAgOAUAAQAFAAAKACIAAgBQgBgNgOAAQgGAAgHAEIgDgGQAIgEAJAAQALAAAEAFQAFAFAAAJIAAAaIgGAAIAAgHQgHAIgKAAQgIAAgEgDgAIHALQAAAKAMAAQAGAAAFgEQAEgDABgGIAAgEQgIgCgGAAQgOAAAAAJgAHLAIIAAgbIAIAAIAAAZQgBAOANAAQAHAAADgEQAFgEAAgHIAAgYIAGAAIAAAsIgGAAIAAgIQgHAJgKAAQgRAAgBgSgAGdATQgHgHAAgKQAAgIAHgHQAHgHAKAAQAKAAAJAIIgFAFQgIgHgGAAQgIAAgEAFQgFAFAAAGIAAAAQAAAIAFAFQAFAFAHAAQAIAAAGgHIAFAEQgIAJgLAAQgKAAgHgHgADfAQIAAAJIgHAAIAAg/IAHAAIAAAcQAHgKALAAQAIAAAGAGQAIAHgBAJIAAAAQABALgIAHQgGAGgIAAQgMAAgGgKgADjgJQgEAFAAAGIAAAAQAAAIAEAFQAGAFAGAAQAHAAAFgFQAEgFAAgIQAAgGgEgFQgFgFgHAAQgGAAgGAFgACFAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgACKgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgABQAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQAAAHAGAEQAEAEAGAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgABuAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAgIAVQgFgFAAgIIAAgbIAHAAIAAAZQAAAOALAAQAGAAAEgEQAEgEAAgHIAAgYIAHAAIAAAsIgHAAIAAgIQgGAJgKAAQgHAAgEgFgAg9ATIADgFQAIAGAIAAQAKAAAAgHQAAgFgMgDQgPgFAAgHQAAgGAFgDQAEgEAHAAQAJAAAIAFIgDAFQgIgEgGAAQgJAAAAAHQAAAEAMADQAPADAAAJQAAAHgFAEQgEADgIAAQgLAAgIgHgAk6AXQgGgFAAgGQAAgIAGgEQAGgCAJAAQAFAAAJACIAAgBQAAgNgOAAQgHAAgHAEIgCgGQAIgEAJAAQAKAAAFAFQAEAFABAJIAAAaIgHAAIAAgHQgGAIgLAAQgHAAgFgDgAk5ALQABAKALAAQAHAAAFgEQAEgDAAgGIAAgEQgHgCgGAAQgOAAgBAJgAmPAUQgHgHAAgLQAAgIAGgHQAHgHAJAAQAKAAAGAHQAGAHAAAIIAAADIglAAQABAHAEAEQAFAEAGAAQAIAAAHgGIAEAEQgIAIgLAAQgKAAgGgGgAlxAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAnLAUQgHgHAAgLQAAgJAHgHQAHgGAJAAQAKAAAIAKIAAgcIAGAAIAAA/IgGAAIAAgJQgIAKgKAAQgJAAgHgGgAnGgJQgEAFAAAGIAAAAQAAAIAEAFQAFAFAHAAQAHAAAEgFQAFgFABgIIAAAAQgBgGgFgFQgEgFgHAAQgIAAgEAFgAoAAUQgHgHAAgLQAAgIAGgHQAGgHAKAAQAKAAAGAHQAGAHAAAIIgBADIgkAAQACAPAOAAQAIAAAHgGIAEAEQgHAIgMAAQgKAAgGgGgAniAAQgCgOgNAAQgGAAgEAEQgEAEgBAGIAeAAIAAAAgAGDAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAApAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIgBAAQgIAAgEAGQgGAGAAAIIAAASgAhPAZIAAgZQAAgOgMAAQgHAAgDAEQgFAEAAAGIAAAZIgHAAIAAgsIAHAAIAAAIQAGgJALAAQAHAAAFAFQAFAFAAAIIAAAbgAiHAZIAAgsIAHAAIAAAsgAjwAZIAAg/IAHAAIAAA/gAkHAZIAAg/IAHAAIAAA/gAleAZIAAgsIAHAAIAAAMQAGgNANAAIAAAHIAAAAQgIAAgGAGQgFAGAAAIIAAASgAoiAZIAAgmIgGAAIAAgGIAGAAIAAgEQAAgIAEgEQAEgEAGAAIAIABIAAAGIgHgBQgIAAAAAKIAAAEIAPAAIAAAGIgPAAIAAAmgAiIgdIAAgIIAIAAIAAAIg");
	this.shape.setTransform(0,4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.3,0,110.7,8.1);


(lib.HTML5rastershad_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.HTML5rastershad();
	this.instance.setTransform(-168,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,0,336,20);


(lib.HEAD2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgTAUIAAgnIAmAAIAAAng");
	this.shape.setTransform(104.6,53.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgdBMQgXgKgJgIIAPgZQANAKAOAFQANAEAKAAQAMABAGgFQAHgEAAgJIAAAAQAAgIgKgFQgGgDgRgGQgZgIgJgFQgIgFgDgHQgFgJAAgKIAAgBQAAgLAFgKQAEgIAHgGQAIgHAKgDQALgEAKAAQAPABAPAEQAPAFANAIIgOAaQgMgHgMgEQgMgEgJAAQgJAAgFAFQgHAEAAAHIAAAAQABAIAKAGIAXAJIARAGQAKAEAHADQAHAGAEAHQAFAIAAAKIAAABQAAAMgFAJQgFAJgHAHQgJAGgKADQgLADgNAAQgOAAgSgFg");
	this.shape_1.setTransform(92.9,48);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgdBMQgXgKgKgIIARgZQAMAKAOAFQANAEALAAQALABAHgFQAGgEAAgJIAAAAQAAgIgLgFQgFgDgSgGQgXgIgKgFQgHgFgFgHQgEgJAAgKIAAgBQAAgLAEgKQAFgIAIgGQAHgHALgDQAKgEAJAAQAPABAQAEQAPAFANAIIgPAaQgMgHgLgEQgLgEgKAAQgIAAgHAFQgFAEAAAHIAAAAQAAAIALAGIAWAJIARAGQAKAEAGADQAIAGAEAHQAEAIABAKIAAABQgBAMgEAJQgEAJgJAHQgHAGgMADQgKADgNAAQgPAAgRgFg");
	this.shape_2.setTransform(77.9,48);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgaBMQgPgFgLgLQgLgMgGgPIgFgQIgBgRIAAAAQAAgPAGgPQAFgPAKgMQALgMAOgFIAPgGIAOgBQAKAAAIABIAPAGQAKAEAOAOQAKAMAEAPQAFAQAAAPIAAAKIhzAAQACAJAEAJQAEAHAGAFQAGAFAHADQAIADAHgBQANAAAKgEQAKgFAKgKIAVATQgGAHgGAGQgHAFgIAEQgIAEgKACQgJACgLAAQgPAAgPgGgAAogKQgBgJgDgHQgDgIgFgFQgFgGgHgDQgHgDgJgBQgGABgHADQgHADgGAFQgFAGgDAHQgEAIgBAJIBPAAIAAAAg");
	this.shape_3.setTransform(61.5,48);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAiBQIAAhYQAAgJgCgHQgDgHgEgFQgEgFgGgDQgHgDgHAAQgHAAgGADQgHADgEAFQgFAFgDAHQgCAIAAAJIAABXIgkAAIAAicIAkAAIAAAZQAJgNAKgHQAHgEAGgCQAHgCAIAAQAOAAAKAEQAKAEAIAIQAHAIAEALQADAMAAANIAABjg");
	this.shape_4.setTransform(43.3,47.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgQBsIAAidIAiAAIAACdgAgShJIAAgiIAlAAIAAAig");
	this.shape_5.setTransform(29.6,45.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgdBMQgXgKgJgIIAPgZQANAKAOAFQANAEAKAAQAMABAGgFQAHgEAAgJIAAAAQAAgIgKgFQgGgDgRgGQgZgIgJgFQgIgFgDgHQgFgJAAgKIAAgBQAAgLAFgKQAEgIAHgGQAIgHAKgDQALgEAKAAQAOABAQAEQAPAFANAIIgOAaQgMgHgMgEQgMgEgJAAQgJAAgFAFQgHAEAAAHIAAAAQABAIAKAGIAXAJIARAGQAKAEAHADQAHAGAEAHQAFAIAAAKIAAABQAAAMgFAJQgFAJgHAHQgJAGgKADQgLADgNAAQgOAAgSgFg");
	this.shape_6.setTransform(17.6,48);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AglBMQgLgEgHgJQgHgHgDgMQgFgLAAgOIAAhjIAlAAIAABYQAAAKACAHQADAHADAFQAFAFAGADQAHACAHAAQAHAAAGgDQAGgCAGgFQAEgGADgGQADgIAAgJIAAhYIAkAAIAACdIgkAAIAAgYQgKAMgKAHQgGAEgIACQgFACgJABQgNgBgLgEg");
	this.shape_7.setTransform(0.9,48.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgIBsQgIgCgHgEQgMgHgJgMIAAAYIgkAAIAAjZIAkAAIAABXQAKgOALgHQAHgEAIgCQAIgCAIAAQAOAAANAFQANAGALAKQAKALAGAPQAGAUAAANIAAAAIgBATIgFAQQgGAPgKALQgLAKgNAGQgNAGgOAAQgIAAgIgDgAgQgRQgJADgGAHQgHAHgDAHQgEAKAAALIAAAAQAAAMAEAJQADAJAHAHQAGAHAJADQAIAEAIAAQAIAAAJgEQAIgDAGgHQAGgGAEgKQADgJAAgMIAAAAQAAgLgDgKQgEgHgGgHQgGgHgIgDQgJgEgIAAQgIAAgIAEg");
	this.shape_8.setTransform(-17.9,45.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAiBtIAAhaQABgJgDgHQgDgFgEgGQgEgFgGgCQgGgDgJAAQgFAAgHADQgGADgGAFQgEAFgDAFQgDAIAAAJIAABZIgkAAIAAjZIAkAAIAABWQAJgOALgGQAGgFAHgBQAHgCAIAAQANAAALADQALAFAGAIQAIAIAEALQADAMAAALIAABlg");
	this.shape_9.setTransform(-46.6,45);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBBkQgIgDgGgFQgGgGgEgJQgDgJAAgNIAAhRIgUAAIAAgfIAUAAIAAgsIAiAAIAAAsIArAAIAAAfIgrAAIAABMQAAAKAGAFQAEAFAKAAQAMAAAKgGIAAAeQgHAEgHACQgJACgJAAQgLAAgGgCg");
	this.shape_10.setTransform(-62.3,45.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgQBsIAAidIAiAAIAACdgAgShJIAAgiIAlAAIAAAig");
	this.shape_11.setTransform(-72.5,45.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAjBPIgjhqIgiBqIghAAIgzidIAlAAIAgBrIAjhsIAdAAIAjBsIAhhrIAkAAIg0Cdg");
	this.shape_12.setTransform(-89.7,48);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgdBLQgXgKgKgHIARgZQAMAKAOAFQANAEALAAQALABAHgFQAGgFAAgHIAAgBQAAgIgLgGQgFgDgSgFQgXgIgKgFQgHgFgFgIQgEgIAAgKIAAgBQAAgMAEgIQAFgKAIgFQAHgHALgDQAKgDAJgBQAPAAAQAFQAPAFANAIIgPAaQgMgHgLgEQgLgEgKAAQgIAAgHAEQgFAFAAAHIAAAAQAAAIALAGIAWAJIARAGQAKAEAGADQAIAGAEAHQAEAIAAAKIAAABQAAAMgEAKQgEAIgJAHQgHAGgLADQgLAEgNAAQgPgBgRgGg");
	this.shape_13.setTransform(122.9,18.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgdBLQgWgKgLgHIAQgZQANAKAOAFQANAEALAAQALABAHgFQAGgFAAgHIAAgBQAAgIgLgGQgFgDgRgFQgZgIgJgFQgHgFgEgIQgFgIAAgKIAAgBQAAgMAFgIQADgKAIgFQAIgHALgDQAKgDAJgBQAQAAAPAFQAPAFANAIIgPAaQgMgHgKgEQgMgEgKAAQgIAAgGAEQgHAFABAHIAAAAQgBAIALAGIAXAJIASAGQAJAEAHADQAHAGAEAHQAFAIgBAKIAAABQABAMgFAKQgEAIgJAHQgHAGgMADQgKAEgMAAQgPgBgSgGg");
	this.shape_14.setTransform(107.9,18.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgaBMQgPgGgLgLQgLgLgGgPIgFgPIgBgSIAAAAQAAgQAGgPQAFgPAKgLQALgLAOgHIAPgEIAOgCQAKAAAIACIAPAEQAKAFAOAOQAKAMAEAPQAFAPAAAQIAAAKIhzAAQACAJAEAJQAEAHAGAFQAGAFAHADQAIACAHAAQANAAAKgEQAKgFAKgKIAVATQgGAHgGAGQgHAFgIAEQgIAEgKACQgJACgLAAQgPAAgPgGgAAogKQgBgIgDgIQgDgIgFgGQgFgFgHgDQgHgDgJAAQgGAAgHADQgHACgGAGQgFAGgDAHQgEAIgBAJIBPAAIAAAAg");
	this.shape_15.setTransform(91.5,18.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAjBQIAAhYQgBgJgCgHQgCgHgEgFQgFgFgGgDQgGgDgJAAQgGAAgGADQgHADgFAFQgEAFgDAHQgCAIgBAJIAABXIgjAAIAAicIAjAAIAAAZQAKgNAKgHQAGgEAIgCQAFgCAJAAQAOAAAKAEQAKAEAHAIQAIAIADALQAFAMAAANIAABjg");
	this.shape_16.setTransform(73.3,17.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgRBsIAAidIAiAAIAACdgAgShIIAAgjIAlAAIAAAjg");
	this.shape_17.setTransform(59.6,15.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgdBLQgXgKgJgHIAQgZQAMAKAOAFQANAEAKAAQAMABAGgFQAHgFAAgHIAAgBQAAgIgKgGQgGgDgSgFQgYgIgJgFQgHgFgFgIQgEgIAAgKIAAgBQAAgMAEgIQAFgKAIgFQAHgHALgDQAKgDAKgBQAPAAAPAFQAPAFANAIIgOAaQgNgHgLgEQgMgEgJAAQgIAAgHAEQgFAFgBAHIAAAAQAAAIAMAGIAWAJIARAGQAKAEAGADQAIAGAEAHQAEAIABAKIAAABQgBAMgEAKQgEAIgIAHQgJAGgKADQgLAEgNAAQgPgBgRgGg");
	this.shape_18.setTransform(47.6,18.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AglBMQgLgEgHgJQgHgHgDgMQgEgLgBgOIAAhjIAlAAIAABYQAAAKACAHQACAHAEAFQAFAFAHADQAFADAIAAQAGgBAHgDQAHgCAEgFQAFgGADgHQACgHAAgJIAAhYIAkAAIAACdIgkAAIAAgZQgIANgLAHQgHAEgGACQgGADgJgBQgOABgKgFg");
	this.shape_19.setTransform(30.9,18.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgIBsQgIgCgHgEQgMgHgJgMIAAAYIgkAAIAAjZIAkAAIAABXQAKgOALgHQAHgEAIgCQAIgCAIAAQAOAAANAFQANAGALAKQAKALAGAPQAGAUAAANIAAAAIgBATIgFAQQgGAPgKALQgLAKgNAGQgNAGgOAAQgIAAgIgDgAgQgRQgJADgGAHQgHAHgDAHQgEAKAAALIAAAAQAAAMAEAJQADAJAHAHQAGAHAJADQAIAEAIAAQAIAAAJgEQAIgDAGgHQAGgGAEgKQADgJAAgMIAAAAQAAgLgDgKQgEgHgGgHQgGgHgIgDQgJgEgIAAQgIAAgIAEg");
	this.shape_20.setTransform(12.1,15.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAiBQIAAhYQAAgJgCgHQgDgHgEgFQgEgFgGgDQgHgDgHAAQgHAAgGADQgHADgEAFQgFAFgDAHQgCAIAAAJIAABXIgkAAIAAicIAkAAIAAAZQAJgNAKgHQAHgEAGgCQAHgCAIAAQAOAAAKAEQAKAEAIAIQAHAIADALQAEAMAAANIAABjg");
	this.shape_21.setTransform(-16.6,17.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgQBsIAAidIAiAAIAACdgAgShIIAAgjIAlAAIAAAjg");
	this.shape_22.setTransform(-30.2,15.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgaBMQgPgGgLgLQgLgLgGgPIgFgPIgBgSIAAAAQAAgQAGgPQAFgPAKgLQALgLAOgHIAPgEIAOgCQAKAAAIACIAPAEQAKAFAOAOQAKAMAEAPQAFAPAAAQIAAAKIhzAAQACAJAEAJQAEAHAGAFQAGAFAHADQAIACAHAAQANAAAKgEQAKgFAKgKIAVATQgGAHgGAGQgHAFgIAEQgIAEgKACQgJACgLAAQgPAAgPgGgAAogKQgBgIgDgIQgDgIgFgGQgFgFgHgDQgHgDgJAAQgGAAgHADQgHACgGAGQgFAGgDAHQgEAIgBAJIBPAAIAAAAg");
	this.shape_23.setTransform(-52.6,18.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgtBQIAAicIAkAAIAAAjQAFgJAEgHQAEgHAHgFQAHgFAIgDQAKgDAKABIAAAmIgDAAQgMAAgJAEQgKAEgIAIQgFAIgDAMQgFAKAAAPIAAA8g");
	this.shape_24.setTransform(-67.1,17.9);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgYAaQAOgCAHgHQAEgIgBgJIgNAAIAAgpIAmAAIAAAjQAAAKgDAKQgDAIgGAGQgGAHgHADQgIADgMABg");
	this.shape_25.setTransform(-78.4,9.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgaBMQgPgGgLgLQgLgLgGgPIgFgPIgBgSIAAAAQAAgQAGgPQAFgPAKgLQALgLAOgHIAPgEIAOgCQAKAAAIACIAPAEQAKAFAOAOQAKAMAEAPQAFAPAAAQIAAAKIhzAAQACAJAEAJQAEAHAGAFQAGAFAHADQAIACAHAAQANAAAKgEQAKgFAKgKIAVATQgGAHgGAGQgHAFgIAEQgIAEgKACQgJACgLAAQgPAAgPgGgAAogKQgBgIgDgIQgDgIgFgGQgFgFgHgDQgHgDgJAAQgGAAgHADQgHACgGAGQgFAGgDAHQgEAIgBAJIBPAAIAAAAg");
	this.shape_26.setTransform(-91.1,18.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAzBqIgziWIgyCWIggAAIhJjSIAoAAIAyCaIAzibIAdAAIA0CbIAziaIAmAAIhJDSg");
	this.shape_27.setTransform(-116.8,15.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-170,0,337,63.9);


(lib.HEAD1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgSATIAAglIAkAAIAAAlg");
	this.shape.setTransform(128.9,50.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgbBHQgWgJgJgIIAPgXQAMAJANAFQAMAEAKAAQALAAAGgEQAGgEAAgIIAAAAQAAgIgKgFIgVgIQgXgHgJgFQgHgFgDgHQgFgIAAgKIAAAAQAAgLAFgIQADgJAIgGQAHgFAKgEQAJgDAJAAQAOAAAPAFQAOAEAMAIIgNAYQgLgGgLgEQgLgEgJAAQgIAAgGAEQgFAFAAAGIAAABQAAAHAKAFIAVAJIARAGQAJADAGADQAHAFADAHQAFAIAAAJIAAABQAAALgFAJQgEAJgHAGQgIAGgKADQgKADgMAAQgOAAgQgGg");
	this.shape_1.setTransform(117.8,45.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgqBMIAAiTIAiAAIAAAhQAEgIAEgHQADgHAHgFQAHgFAIgCQAJgDAJABIAAAkIgCAAQgMAAgJAEQgJADgHAIQgEAHgEALQgEAKAAAOIAAA5g");
	this.shape_2.setTransform(105.9,44.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgYBIQgOgGgKgKQgLgLgGgOIgEgPIgCgQIAAAAQAAgPAGgOQAFgOAKgKQAKgLANgGIAOgFIANgBQAJAAAIABQAIACAHADQAIAEAOAOQAJAKAEAPQAFAOAAAPIgBAJIhrAAQABAJAEAIQADAGAGAFQAGAFAHADQAHACAHAAQAMAAAKgEQAJgFAJgJIAUASIgMAMQgGAFgIADQgHAEgJACQgJACgKAAQgOAAgOgFgAAmgJQgBgJgDgHQgDgHgEgFQgFgFgHgDQgHgDgIAAQgGAAgGACQgHADgFAFQgFAGgDAHQgEAHgBAJIBLAAIAAAAg");
	this.shape_3.setTransform(90.9,45.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgPBmIAAjMIAfAAIAADMg");
	this.shape_4.setTransform(78.4,42.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgPBmIAAiTIAgAAIAACTgAgRhEIAAghIAjAAIAAAhg");
	this.shape_5.setTransform(70.3,42.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgiBKQgJgDgHgGQgIgGgEgIQgEgJAAgLIAAgBQAAgMAEgJQAEgJAJgEQAIgHALgDQALgDANAAQAQAAAYAHIAAgDQgBgIgCgGQgCgGgFgEQgEgEgIgCQgHgCgGAAQgMAAgLADIgUAGIgJgbQANgGAMgDQAOgEAPAAQARAAAMAFQAMAEAJAIQAIAIAEAMQAEALAAAPIAABXIgiAAIAAgTQgIAKgLAGQgQAGgLAAQgLAAgKgDgAgNAHQgGACgFADQgEADgCAEQgCAEgBAGIAAAAQAAAKAJAHQAIAFAMAAQAHAAAHgCQAHgCAGgFQAFgEADgFQADgGAAgHIAAgJQgVgGgNAAQgGAAgHACg");
	this.shape_6.setTransform(57.6,45.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgBBeQgHgDgGgFQgGgFgDgIQgDgJAAgMIAAhMIgTAAIAAgeIATAAIAAgpIAgAAIAAApIAoAAIAAAeIgoAAIAABHQAAAJAFAFQAFAEAIAAQALAAALgFIAAAcQgHAEgHACQgIACgJAAQgKAAgGgCg");
	this.shape_7.setTransform(43.7,43.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgYBIQgOgGgKgKQgLgLgGgOIgEgPIgCgQIAAAAQAAgPAGgOQAFgOAKgKQAKgLANgGIAOgFIANgBQAJAAAIABQAIACAHADQAIAEAOAOQAJAKAEAPQAFAOAAAPIgBAJIhrAAQABAJAEAIQADAGAGAFQAGAFAHADQAHACAHAAQAMAAAKgEQAJgFAJgJIAUASIgMAMQgGAFgIADQgHAEgJACQgJACgKAAQgOAAgOgFgAAmgJQgBgJgDgHQgDgHgEgFQgFgFgHgDQgHgDgIAAQgGAAgGACQgHADgFAFQgFAGgDAHQgEAHgBAJIBLAAIAAAAg");
	this.shape_8.setTransform(29.6,45.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgqBMIAAiTIAiAAIAAAhQAEgIAEgHQADgHAHgFQAHgFAIgCQAIgDAKABIAAAkIgCAAQgMAAgIAEQgKADgHAIQgEAHgEALQgEAKAAAOIAAA5g");
	this.shape_9.setTransform(16,44.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgYBIQgOgGgKgKQgLgLgGgOIgEgPIgCgQIAAAAQAAgPAGgOQAFgOAKgKQAKgLANgGIAOgFIANgBQAJAAAIABQAIACAHADQAIAEAOAOQAJAKAEAPQAFAOAAAPIgBAJIhrAAQABAJAEAIQADAGAGAFQAGAFAHADQAHACAHAAQAMAAAKgEQAJgFAJgJIAUASIgMAMQgGAFgIADQgHAEgJACQgJACgKAAQgOAAgOgFgAAmgJQgBgJgDgHQgDgHgEgFQgFgFgHgDQgHgDgIAAQgGAAgGACQgHADgFAFQgFAGgDAHQgEAHgBAJIBLAAIAAAAg");
	this.shape_10.setTransform(-7.5,45.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAgBLIAAhSQAAgJgCgHQgCgGgEgFQgEgEgGgDQgGgDgIABQgFgBgGADQgGADgFAEQgEAFgDAHQgCAHAAAIIAABSIgiAAIAAiSIAiAAIAAAWQAIgMAKgGQAGgDAHgCQAFgCAIgBQANABAKAEQAKADAGAIQAHAHAEALQADALAAANIAABcg");
	this.shape_11.setTransform(-24.7,44.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgPBmIAAiTIAgAAIAACTgAgRhEIAAghIAjAAIAAAhg");
	this.shape_12.setTransform(-37.5,42.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgQBmIAAjMIAhAAIAADMg");
	this.shape_13.setTransform(-45.5,42.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAgBLIAAhSQAAgJgCgHQgCgGgEgFQgEgEgGgDQgGgDgIABQgFgBgGADQgGADgFAEQgEAFgDAHQgCAHAAAIIAABSIgiAAIAAiSIAiAAIAAAWQAIgMAKgGQAGgDAHgCQAFgCAIgBQANABAKAEQAKADAGAIQAHAHAEALQADALAAANIAABcg");
	this.shape_14.setTransform(-58.3,44.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgPBMIgPgFQgOgGgLgLQgLgKgGgOIgFgOIgBgQIAAAAQAAgJAGgUQAGgOALgKQALgLAOgGIAPgFIAPgBQAMAAAUAGQAOAGAKAKQALALAGAOQAGATAAAKIAAAAIgBAPIgFAPQgGANgLALQgKALgPAGQgUAGgLAAgAgSgrQgIAEgGAHQgFAGgEAJQgDAIAAAJIAAAAQABAJADAJQADAJAGAGQAHAHAHAEQAJAEAIAAQAKAAAIgEQAJgEAGgHQAGgGADgJQADgIAAgKIAAAAQAAgIgDgJQgDgJgHgGQgGgHgIgEQgJgDgJAAQgJAAgJADg");
	this.shape_15.setTransform(-76.4,45.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgPBMIgPgFQgOgGgMgLQgKgKgGgOIgFgOIgBgQIAAAAQAAgJAHgUQAFgOALgKQALgLAOgGIAQgFIAOgBQAMAAATAGQAPAGAKAKQAMALAFAOQAGATAAAKIAAAAIgCAPIgEAPQgGANgLALQgLALgOAGQgUAGgLAAgAgRgrQgJAEgGAHQgFAGgEAJQgCAIAAAJIAAAAQgBAJAEAJQADAJAGAGQAGAHAJAEQAIAEAIAAQAKAAAJgEQAHgEAHgHQAFgGAEgJQADgIAAgKIAAAAQAAgIgEgJQgDgJgGgGQgGgHgIgEQgJgDgJAAQgJAAgIADg");
	this.shape_16.setTransform(-103.3,45.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgBBeQgIgDgFgFQgGgFgDgIQgDgJAAgMIAAhMIgTAAIAAgeIATAAIAAgpIAgAAIAAApIAoAAIAAAeIgoAAIAABHQAAAJAFAFQAEAEAJAAQAMAAAJgFIAAAcQgGAEgHACQgIACgJAAQgKAAgGgCg");
	this.shape_17.setTransform(-118.6,43.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgbBHQgWgJgJgIIAPgXQAMAJANAFQAMAEAKAAQALAAAGgEQAGgEAAgIIAAAAQAAgIgKgFIgVgIQgXgHgJgFQgHgFgDgHQgFgIAAgKIAAAAQAAgLAFgIQADgJAIgGQAHgFAKgEQAJgDAJAAQAOAAAPAFQAOAEAMAIIgNAYQgLgGgLgEQgLgEgJAAQgIAAgGAEQgFAFAAAGIAAABQAAAHAKAFIAVAJIARAGQAJADAGADQAHAFADAHQAFAIAAAJIAAABQAAALgFAJQgEAJgHAGQgIAGgKADQgKADgMAAQgOAAgQgGg");
	this.shape_18.setTransform(115.6,16.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAgBMIAAhTQAAgJgCgHQgCgGgEgFQgEgFgGgCQgGgCgIgBQgFABgGACQgGADgFAEQgEAFgDAHQgCAHAAAIIAABTIgiAAIAAiUIAiAAIAAAYQAIgNAKgGQAGgDAHgCQAFgCAIAAQANAAAKADQAKAEAGAIQAHAHAEALQADALAAAMIAABeg");
	this.shape_19.setTransform(100,16.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgiBKQgJgDgHgGQgIgGgEgIQgEgJAAgLIAAgBQAAgMAEgJQAFgJAIgEQAIgHALgDQALgDANAAQAQAAAXAHIAAgDQAAgIgCgGQgCgGgFgEQgFgEgGgCQgHgCgHAAQgMAAgLADIgUAGIgJgbQAOgGALgDQAPgEAOAAQARAAANAFQAMAEAIAIQAIAIAEAMQAEALAAAPIAABXIgiAAIAAgTQgIAKgLAGQgQAGgLAAQgLAAgKgDgAgMAHQgHACgFADQgEADgCAEQgDAEAAAGIAAAAQAAAKAJAHQAIAFANAAQAGAAAHgCQAHgCAGgFQAFgEADgFQADgGAAgHIAAgJQgVgGgNAAQgGAAgGACg");
	this.shape_20.setTransform(82.6,16.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgPBmIAAiTIAgAAIAACTgAgRhEIAAghIAjAAIAAAhg");
	this.shape_21.setTransform(70.6,14.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgGBMIgPgFQgOgGgLgLQgKgKgGgOQgGgOAAgQIAAAAQAAgOAGgPQAGgNAKgLQALgLAOgGIAPgFIAOgBQAKAAAJACQAJABAHAEQAKAEAOAOIgVAXQgIgJgJgEQgJgFgMAAQgIAAgIADQgHAEgGAHQgGAGgDAJQgDAIAAAJIAAAAQAAAJADAJQADAJAGAHQAGAGAIAEQAHAEAJAAQAMAAAKgGQAIgEAJgJIAVAUQgQAPgKAFQgHAEgJACQgJACgKAAg");
	this.shape_22.setTransform(58.8,16.9);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgPBmIAAiTIAgAAIAACTgAgRhEIAAghIAjAAIAAAhg");
	this.shape_23.setTransform(46.5,14.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgqBMIAAiTIAiAAIAAAhQAEgIAEgHQADgHAHgFQAHgFAIgCQAJgDAJABIAAAkIgCAAQgMAAgJAEQgJADgHAIQgEAHgEALQgEAKAAAOIAAA5g");
	this.shape_24.setTransform(37.4,16.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgBBeQgHgDgGgFQgGgFgDgIQgDgJAAgMIAAhMIgTAAIAAgeIATAAIAAgpIAgAAIAAApIAoAAIAAAeIgoAAIAABHQAAAJAFAFQAFAEAIAAQALAAALgFIAAAcQgHAEgHACQgIACgJAAQgKAAgGgCg");
	this.shape_25.setTransform(24.9,15);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgGBMIgPgFQgOgGgLgLQgKgKgGgOQgGgOAAgQIAAAAQAAgOAGgPQAGgNAKgLQALgLAOgGIAPgFIAOgBQAKAAAJACQAJABAHAEQAKAEAOAOIgVAXQgIgJgJgEQgJgFgMAAQgIAAgIADQgHAEgGAHQgGAGgDAJQgDAIAAAJIAAAAQAAAJADAJQADAJAGAHQAGAGAIAEQAHAEAJAAQAMAAAKgGQAIgEAJgJIAVAUQgQAPgKAFQgHAEgJACQgJACgKAAg");
	this.shape_26.setTransform(11.4,16.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgYBIQgOgGgKgKQgLgLgGgOIgEgPIgCgQIAAAAQAAgPAGgOQAFgOAKgKQAKgLANgGIAOgFIANgBQAJAAAIABQAIACAHADQAIAEAOAOQAJAKAEAPQAFAOAAAPIgBAJIhrAAQABAJAEAIQADAGAGAFQAGAFAHADQAHACAHAAQAMAAAKgEQAJgFAJgJIAUASIgMAMQgGAFgIADQgHAEgJACQgJACgKAAQgOAAgOgFgAAmgJQgBgJgDgHQgDgHgEgFQgFgFgHgDQgHgDgIAAQgGAAgGACQgHADgFAFQgFAGgDAHQgEAHgBAJIBLAAIAAAAg");
	this.shape_27.setTransform(-5.3,16.9);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgQBnIAAjMIAgAAIAADMg");
	this.shape_28.setTransform(-17.8,14.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgYBIQgOgGgKgKQgLgLgGgOIgEgPIgCgQIAAAAQAAgPAGgOQAFgOAKgKQAKgLANgGIAOgFIANgBQAJAAAIABQAIACAHADQAIAEAOAOQAJAKAEAPQAFAOAAAPIgBAJIhrAAQABAJAEAIQADAGAGAFQAGAFAHADQAHACAHAAQAMAAAKgEQAJgFAJgJIAUASIgMAMQgGAFgIADQgHAEgJACQgJACgKAAQgOAAgOgFgAAmgJQgBgJgDgHQgDgHgEgFQgFgFgHgDQgHgDgIAAQgGAAgGACQgHADgFAFQgFAGgDAHQgEAHgBAJIBLAAIAAAAg");
	this.shape_29.setTransform(-30.4,16.9);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("ABPBMIAAhTQAAgJgCgHQgCgHgEgEQgEgFgGgCQgFgCgIgBQgHABgFACQgGACgEAFQgFAFgCAGQgCAIAAAIIAABTIghAAIAAhUQAAgIgCgHQgCgHgEgEQgDgFgGgCQgGgCgHgBQgHABgGACQgGADgEAEQgEAGgCAGQgDAHAAAIIAABTIgiAAIAAiUIAiAAIAAAXQAJgMAJgGQAGgDAGgCQAIgCAIAAQAIAAAHACQAGABAGADQAFAEADAFQAEAEADAHQAKgNALgHQAHgDAHgBQAHgCAJAAQAMgBAJAEQAKAEAHAHQAHAIADAKQAEALAAANIAABeg");
	this.shape_30.setTransform(-60.7,16.8);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgPBMIgPgFQgOgGgMgLQgKgKgGgOIgFgOIgBgQIAAAAQAAgJAHgUQAFgOALgKQALgLAOgGIAPgFIAPgBQAMAAATAGQAPAGAKAKQAMALAFAOQAGATAAAKIAAAAIgCAPIgEAPQgGANgLALQgLALgOAGQgUAGgLAAgAgRgrQgIAEgHAHQgFAGgEAJQgCAIAAAJIAAAAQgBAJAEAJQADAJAGAGQAGAHAJAEQAIAEAIAAQAKAAAJgEQAHgEAHgHQAFgGAEgJQADgIAAgKIAAAAQAAgIgEgJQgDgJgGgGQgGgHgIgEQgJgDgJAAQgJAAgIADg");
	this.shape_31.setTransform(-83.4,16.9);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgqBMIAAiTIAiAAIAAAhQAEgIAEgHQAEgHAGgFQAHgFAIgCQAIgDAKABIAAAkIgCAAQgLAAgJAEQgKADgHAIQgFAHgDALQgEAKAAAOIAAA5g");
	this.shape_32.setTransform(-97.8,16.7);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AhIBiIAAjDICRAAIAAAfIhvAAIAAA2IBiAAIAAAeIhiAAIAABQg");
	this.shape_33.setTransform(-112.9,14.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-158.5,0,317,60.2);


(lib.CTA_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(168,140);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.CTA = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("AgbBGQgNgDgKgHIAJgTQAJAFAJAEQAKADALAAQAHAAAHgCQAGgDAEgEQAFgEACgHQADgGAAgJIAAgIQgKALgHAEQgEACgGABQgFACgGAAQgJAAgJgEQgKgDgHgGQgHgIgEgJQgEgIAAgLIAAgBQAAgJAEgNQAEgJAIgIQAHgGAJgEQAJgDAJAAQAGAAAFACQAGAAAFADQAIAFAHAJIAAgRIAaAAIAABXQAAAOgEAKQgDAKgHAHQgEAEgFACIgKAGQgRADgIAAQgOAAgMgDgAgLgxQgGADgEADQgFAEgCAGQgCAGAAAHIAAAAQAAAHACAFQACAGAFACQAEAFAGACQAGACAFAAQAGAAAGgCQAGgCAEgFQAFgCACgGQADgFAAgGIAAgBQAAgHgDgGQgCgFgFgFQgEgDgGgDQgGgCgGAAQgFAAgGACg");
	this.shape.setTransform(121.1,14.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#002663").s().p("AAYA4IAAg9QAAgHgCgFQgBgEgDgEQgDgEgFgBQgEgCgGAAQgDAAgFACQgFABgDAEQgDAEgCAFQgCAFAAAGIAAA9IgZAAIAAhtIAZAAIAAARQAGgIAIgGIAJgDQAEgCAGAAQAJAAAHADQAIADAFAFQAFAGADAIQACAIAAAKIAABEg");
	this.shape_1.setTransform(107.9,13.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#002663").s().p("AgLBMIAAhtIAXAAIAABtgAgMgyIAAgZIAZAAIAAAZg");
	this.shape_2.setTransform(98.4,11.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#002663").s().p("AAWBMIgfgwIgQARIAAAfIgZAAIAAiXIAZAAIAABaIAsgwIAfAAIgsAsIAtBBg");
	this.shape_3.setTransform(89.9,11.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#002663").s().p("AAYA4IAAg9QAAgHgCgFQgBgEgDgEQgDgEgFgBQgEgCgGAAQgDAAgFACQgFABgDAEQgDAEgCAFQgCAFAAAGIAAA9IgZAAIAAhtIAZAAIAAARQAGgIAIgGIAJgDQAEgCAGAAQAJAAAHADQAIADAFAFQAFAGADAIQACAIAAAKIAABEg");
	this.shape_4.setTransform(76.7,13.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#002663").s().p("AgYA3QgIgCgFgFQgGgFgDgFQgDgIAAgIIAAAAQAAgJAEgHQADgGAGgDQAGgFAIgCQAIgCAKAAQAMAAARAFIAAgCQAAgHgCgEQgCgEgDgDIgJgFQgFgCgFABQgIAAgIABIgPAGIgHgVQAKgEAJgCQAKgDALAAQAMAAAJADQAJADAHAGQAGAHADAIQADAJAAALIAABAIgZAAIAAgOQgHAHgIAEQgLAFgIAAQgIAAgHgCgAgJAFQgFABgDADQgDABgCADQgCAEAAAEIAAAAQAAAIAHAFQAFADAKABQAEgBAFgBQAGgCAEgDQAEgDACgEQACgEAAgGIAAgGQgPgEgKgBQgEABgFABg");
	this.shape_5.setTransform(63.7,13.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#002663").s().p("Ag8BJIAAiRIBAAAQANAAAJADQAKAEAHAGQAEAFADAGQACAGAAAHIAAABQAAAGgBAGQgCAEgDAFQgFAHgKAFIAMADQAGADADAEQAEAEACAGQADAGAAAIQAAAKgEAHQgEAIgHAEQgHAGgKACQgKADgNAAgAgiAyIAoAAIAMgBQAGgCADgCQAEgCACgEQACgEAAgFIAAAAQAAgFgCgEQgCgDgEgDQgEgDgFgBIgOgBIgmAAgAgigKIAiAAIAKgBQAFgCAEgCQAEgDACgDQACgEAAgFIAAAAQAAgEgCgEQgCgDgDgDQgDgDgFgBIgLgBIgjAAg");
	this.shape_6.setTransform(50.7,11.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#002663").s().p("AgUA1QgQgHgGgFIALgRQAJAGAJADQAKAEAGAAQAIAAAFgEQAEgCABgGIAAAAQAAgGgIgEIgPgGQgSgFgGgEQgFgDgDgFQgDgGAAgHIAAgBQAAgHADgHQADgGAFgFQAGgEAHgDQAHgCAHAAQAJAAAMADQAKAEAJAGIgKASQgIgFgIgDQgJgCgGgBQgFAAgFADQgEAEAAAEIAAABQAAAFAIAEIAPAGIANAFQAGADAEABQAGAEACAFQADAGAAAHIAAABQAAAIgDAGQgCAHgGAFQgGAEgHACQgIACgIAAQgLAAgMgEg");
	this.shape_7.setTransform(31,13.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#002663").s().p("AgUA1QgQgHgGgFIALgRQAIAGAKADQAJAEAHAAQAIAAAFgEQAEgCAAgGIAAAAQAAgGgHgEIgQgGQgQgFgHgEQgFgDgDgFQgDgGAAgHIAAgBQAAgHADgHQADgGAGgFQAEgEAIgDQAHgCAHAAQAJAAALADQALAEAJAGIgKASQgIgFgIgDQgJgCgGgBQgFAAgEADQgFAEAAAEIAAABQAAAFAIAEIAPAGIAMAFQAHADAEABQAGAEACAFQAEAGAAAHIAAABQAAAIgEAGQgDAHgFAFQgGAEgHACQgIACgJAAQgKAAgMgEg");
	this.shape_8.setTransform(20.5,13.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#002663").s().p("AgSA1QgKgEgHgIQgJgHgDgLIgEgLIgBgMIAAAAQAAgLAEgKQAEgLAHgHQAIgJAJgEIALgDIAJgBIANABIALADQAGADAKAKQAHAIADALQADALAAAKIAAAHIhQAAQACAHACAFQADAGAEADQAFAEAEACQAGABAEAAQAJAAAHgDQAIgDAGgHIAPANIgIAJIgLAHIgMAEIgOABQgKAAgLgEgAAcgGQAAgHgDgFQgCgFgEgEQgDgEgFgCQgFgDgGAAQgEAAgFADQgFACgEADQgEAEgCAGQgCAFgBAHIA3AAIAAAAg");
	this.shape_9.setTransform(9.1,13.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#002663").s().p("AAYA4IAAg9QAAgHgCgFQgBgEgDgEQgDgEgFgBQgEgCgGAAQgDAAgFACQgFABgDAEQgDAEgCAFQgCAFAAAGIAAA9IgZAAIAAhtIAZAAIAAARQAGgIAIgGIAJgDQAEgCAGAAQAJAAAHADQAIADAFAFQAFAGADAIQACAIAAAKIAABEg");
	this.shape_10.setTransform(-3.7,13.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#002663").s().p("AgLBMIAAhtIAXAAIAABtgAgMgyIAAgZIAZAAIAAAZg");
	this.shape_11.setTransform(-13.2,11.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#002663").s().p("AgUA1QgQgHgGgFIALgRQAJAGAJADQAKAEAGAAQAIAAAFgEQAEgCABgGIAAAAQAAgGgIgEIgQgGQgRgFgGgEQgFgDgDgFQgDgGAAgHIAAgBQAAgHADgHQADgGAFgFQAGgEAHgDQAHgCAHAAQAJAAAMADQAKAEAJAGIgKASQgIgFgIgDQgJgCgGgBQgFAAgFADQgEAEAAAEIAAABQAAAFAIAEIAPAGIANAFQAGADAEABQAGAEACAFQADAGAAAHIAAABQAAAIgDAGQgCAHgGAFQgGAEgHACQgIACgIAAQgLAAgMgEg");
	this.shape_12.setTransform(-21.6,13.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#002663").s().p("AgZA1QgIgDgFgGQgFgFgCgIQgDgIAAgKIAAhEIAZAAIAAA9QAAAGACAFQACAFADAEQADADAEACQAEACAFAAQAFAAAEgCQAFgCADgDQADgEACgFQACgFAAgHIAAg8IAZAAIAABtIgZAAIAAgRQgGAJgHAEQgFADgFABQgDACgHAAQgJAAgHgDg");
	this.shape_13.setTransform(-33.3,13.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#002663").s().p("Ag8BJIAAiRIBAAAQANAAAJADQAKAEAHAGQAEAFADAGQACAGAAAHIAAABQAAAGgBAGQgCAEgDAFQgFAHgKAFIAMADQAGADADAEQAEAEACAGQADAGAAAIQAAAKgEAHQgEAIgHAEQgHAGgKACQgKADgNAAgAgiAyIAoAAIAMgBQAGgCADgCQAEgCACgEQACgEAAgFIAAAAQAAgFgCgEQgCgDgEgDQgEgDgFgBIgOgBIgmAAgAgigKIAiAAIAKgBQAFgCAEgCQAEgDACgDQACgEAAgFIAAAAQAAgEgCgEQgCgDgDgDQgDgDgFgBIgLgBIgjAAg");
	this.shape_14.setTransform(-46.9,11.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#002663").s().p("AgXBJQgKgDgHgIQgHgIgFgKIgDgLIgBgOQAAgJAEgNQAEgKAIgIQAHgHAJgFQAJgDAKAAQAFAAAGACIAKADQAIAGAHAIIAAg8IAaAAIAACYIgaAAIAAgTQgHAKgIAFQgFADgFABQgGADgFAAQgJAAgJgFgAgLgLQgGACgEAEQgEAFgDAFQgCAHAAAHQAAAIACAIQADAGAEAEQAFAFAFADQAGACAFAAQAGAAAGgCQAGgDAEgFQAFgFACgFQADgIAAgIQAAgHgDgHQgCgFgFgFQgEgEgGgCQgGgDgGAAQgFAAgGADg");
	this.shape_15.setTransform(-68.5,11.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#002663").s().p("AAYA4IAAg9QAAgHgCgFQgBgEgDgEQgDgEgFgBQgEgCgGAAQgDAAgFACQgFABgDAEQgDAEgCAFQgCAFAAAGIAAA9IgZAAIAAhtIAZAAIAAARQAGgIAIgGIAJgDQAEgCAGAAQAJAAAHADQAIADAFAFQAFAGADAIQACAIAAAKIAABEg");
	this.shape_16.setTransform(-81.7,13.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#002663").s().p("AgZA1QgIgDgFgGQgFgFgCgIQgDgIAAgKIAAhEIAZAAIAAA9QAAAGACAFQACAFADAEQADADAEACQAEACAFAAQAFAAAEgCQAFgCADgDQADgEACgFQACgFAAgHIAAg8IAZAAIAABtIgZAAIAAgRQgGAJgHAEQgFADgFABQgDACgHAAQgJAAgHgDg");
	this.shape_17.setTransform(-94.8,13.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#002663").s().p("AgLA4IgMgDQgKgFgIgIQgIgIgEgKIgEgLIgBgLIAAAAQAAgGAFgPQAEgKAIgIQAJgIAKgFIAMgDIAKgBQAIAAAPAEQALAEAIAIQAIAIAEALQAFAOgBAHIgBALIgDALQgEAKgIAIQgJAIgKAFQgPAEgIAAgAgNgfQgFACgFAFQgFAFgCAGQgCAHAAAGQAAAHACAGQADAHAEAFQAFAFAGACQAGADAGAAQAHAAAGgDQAHgCAEgFQAEgFADgGQACgHAAgHIAAAAQAAgGgDgGQgCgHgEgFQgFgFgGgCQgHgDgGAAQgGAAgHADg");
	this.shape_18.setTransform(-108.1,13.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#002663").s().p("AgLBJQgIgBgHgDQgJgDgGgEQgIgFgHgGIAQgSQAHAGAOAJIANADIAKABIALgBIAIgEQAEgCACgDQABgEAAgFQABgEgCgDQgCgDgDgCIgKgFIgPgFQgNgDgIgDQgJgEgGgDQgGgFgEgHQgDgHAAgKIAAAAQABgKADgIQAEgHAHgGQAHgGAIgDQAKgDAKAAIAOABIAOADQAIAEAQALIgOATQgKgIgKgDQgKgEgIAAIgKABQgEABgDADQgHAFAAAHIAAAAQAAAFABADQADADADADIALAFIAPAFQAMADAIAEQAJADAHADQAFAFAEAHQACAHAAAJQAAAKgDAJQgEAHgIAGQgGAGgKADQgJADgMAAQgHAAgIgCg");
	this.shape_19.setTransform(-121.8,11.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-167,0,334,25);


(lib.comhoriz = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A5AFD4").s().p("AJfAqQgLgLAAgRQAAgOALgLQALgLARgBQARABALALQAKALABAOIAAAAQgBAQgKALQgLAMgRAAQgRAAgLgLgAJngFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAMAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgMAAQgNAAgHAIgAIQAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAFGAqQgKgMAAgQQAAgOAKgLQALgLARgBQAUABAKAMIgIAIQgIgKgOgBQgMAAgHAIQgIAGAAANIAAAAQAAAMAIAJQAHAIAMAAQAOgBAJgKIAHAHQgKANgUABQgRAAgLgLgAgdAqQgLgLAAgRQAAgOALgLQALgLARgBQAPABALALQAKALABAOIAAAAQgBAQgKALQgLAMgPAAQgRAAgLgLgAgVgFQgHAHgBAMIAAAAQABAMAHAJQAIAIAMAAQAKAAAIgIQAHgJAAgMQAAgMgIgGQgHgJgKAAQgNAAgHAIgAq7AqQgLgKAAgSQAAgPAKgLQAKgLAQAAQAQABAJALQAJALABAPIgBAEIg7AAQACALAHAHQAHAGALAAQAOAAAJgKIAHAGQgKANgVABQgQAAgKgLgAqzgGQgGAGgCAKIAwAAQgBgKgGgGQgFgHgMgBQgJABgHAHgAGXAtQgHgJAAgNIAAgsIALAAIAAApQAAAWAUABQAKAAAGgHQAGgGABgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgKAAQgOAAgHgIgADpArQgKgKgBgTIAAAAQABgRAKgKQALgKAOAAQAKAAAHAFQAHAEAFAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgHAFQgHAFgKAAQgOAAgLgKgADxgFQgHAFAAAOIAAAAQAAANAIAIQAHAIALAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgIAIgAA7AtQgHgJAAgNIAAgsIALAAIAAApQABAWAUABQAJAAAHgHQAGgGAAgLIAAgoIALAAIAABIIgLAAIAAgNQgEAGgGAFQgGAEgJAAQgOAAgIgIgAhhAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAjGAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAkeAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAkbAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgAmLAyQgJgDgGgFIAGgIQAMAJANAAQAPAAABgMQAAgFgGgDQgFgDgIgCQgJgCgIgFQgHgEAAgIIAAAAQAAgKAHgGQAHgFALgBQAOABANAIIgFAIQgLgHgLAAQgOABgBAKQABADAFADQAGADAHACQAJACAIAFQAHAEAAAKQAAALgHAGQgIAGgLAAQgIAAgIgDgAoxAvQgIgGAAgLIAAgBQAAgMAIgGQAJgGAOAAQAOAAAJADIAAgCQAAgSgWAAQgNAAgJAFIgEgJQAMgGAPAAQAQAAAIAIQAIAHAAANIAAAtIgLAAIAAgLQgEAFgGAEQgHAEgKAAQgLAAgIgGgAouAdIAAAAQAAAHAFAEQAGAEAIAAQAKAAAHgGQAHgFAAgJIAAgHQgIgDgNAAQgWABAAAOgApkAwQgGgFAAgMIAAgrIgKAAIAAgJIAKAAIAAgXIALAAIAAAXIAYAAIAAAJIgYAAIAAAqQABANAMgBQAFABAGgDIAAAJQgGADgIABQgJAAgGgFgAsYArQgLgKAAgTIAAAAQAAgRALgKQAKgKAOAAQALAAAHAFQAHAEAEAHIAAgtIALAAIAABnIgLAAIAAgPQgFAHgGAFQgHAFgLAAQgOAAgKgKgAsQgFQgHAFgBAOIAAAAQABANAHAIQAIAIAKAAQALAAAIgIQAIgIAAgNIAAAAQAAgNgIgGQgIgIgLAAQgLAAgHAIgAMZAzIAAgrQAAgUgTgBQgJAAgGAGQgGAGAAAJIAAArIgLAAIAAgsQgBgTgSgBQgJAAgGAHQgGAGAAAJIAAAqIgLAAIAAhIIALAAIAAAMQAEgFAFgFQAGgEAJAAQAJAAAGAEQAGAFADAGQAEgGAHgFQAGgEAKAAQANAAAHAIQAHAIAAAMIAAAugAHnAzIAAgPIANAAIAAAPgADCAzIAAgrQAAgUgUgBQgKAAgGAHQgHAGAAAJIAAAqIgLAAIAAhIIALAAIAAANQAEgHAGgEQAGgEAKAAQANAAAIAIQAHAIAAAMIAAAugAm6AzIAAhnIALAAIAABngAnhAzIAAhIIALAAIAABIgAnigmIAAgMIANAAIAAAMg");
	this.shape.setTransform(0.1,0.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-80.4,-4.5,161,10.8);


(lib.Close = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMANIAAgZIAZAAIAAAZg");
	this.shape.setTransform(122.4,36.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgdA1IAAhnIAYAAIAAAXQACgGADgEQADgFAEgEQAFgDAGgCQAFgCAHABIAAAZIgBAAQgIAAgGADQgIACgEAGQgDAFgCAIQgDAGAAAKIAAAog");
	this.shape_1.setTransform(116.1,32.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgRAzQgKgEgHgIQgIgHgEgKIgCgKIgBgMIAAAAQAAgKADgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAHADAJAJQAGAIAEALQADAKAAAJIgBAHIhMAAQABAGADAGIAHAIQAEADAFACQAFACAEAAQAJAAAGgDQAHgDAHgHIAOANIgJAIQgEAEgFACIgMAEQgHACgGAAQgKAAgKgEgAAagGQAAgGgCgFQgCgFgEgEQgDgEgFgCQgFgCgFAAQgEAAgFACQgEACgEAEIgFAJQgDAFgBAGIA0AAIAAAAg");
	this.shape_2.setTransform(105.5,32.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAABCQgGgCgEgDQgEgEgCgGQgCgGgBgIIAAg2IgMAAIAAgVIAMAAIAAgdIAXAAIAAAdIAcAAIAAAVIgcAAIAAAyQAAAHADADQADADAHAAQAHAAAIgEIAAAUIgKAEQgGACgGAAQgHAAgDgCg");
	this.shape_3.setTransform(95.3,31.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgTAyQgPgGgGgGIAKgQQAJAGAJAEQAJADAGAAQAIAAAEgDQAEgDABgFIAAgBQgBgFgHgEIgOgGQgQgEgGgEQgGgDgCgFQgDgFAAgIQAAgHADgGQADgGAFgFQAFgEAGgCQAIgCAGAAQAJAAAKADQALADAIAGIgKARQgHgFgIgCQgHgDgHAAQgFAAgEADQgEADAAAFIAAAAQAAAFAHAEIAPAGIALAEIALAEQAFAEADAFQACAFAAAHIAAAAQAAAIgCAHQgEAGgFAEQgFAEgHACQgHACgIAAQgKAAgMgEg");
	this.shape_4.setTransform(86.1,32.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgXA0QgHgCgFgEQgGgFgCgFQgDgHAAgIIAAAAQAAgIADgHQADgGAFgDQAGgEAIgCQAIgCAJgBQALAAARAFIAAgCQAAgFgCgEQgCgFgDgDQgEgDgFgBQgEgBgEgBQgJABgIABQgGABgIAEIgGgTIASgHQAKgCAKAAQAMAAAIADQAJADAGAFQAGAHADAIQACAIAAALIAAA8IgXAAIAAgNQgHAHgIAEQgKAEgIAAQgIAAgGgCgAgIAEIgIAEIgFAFQgCADAAAEIAAAAQABAIAFAEQAGAEAJAAQAEAAAFgBQAFgCAEgDQAEgDACgEQACgFAAgEIAAgGQgPgFgJAAIgIABg");
	this.shape_5.setTransform(75.2,32.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgSBJIAAhTIgNAAIAAgUIANAAIAAgIQAAgIADgHQACgGAEgFQAEgEAFgCQAFgCAIAAQAKAAAJADIAAAUQgHgCgHAAQgHgBgDAEQgEAFAAAHIAAAGIAcAAIAAAUIgbAAIAABTg");
	this.shape_6.setTransform(66,30.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgKBGIgPgEIgOgHIgOgKIAPgRQAHAFAOAIQAFACAGACIAKABIALgBIAHgEQAEgCABgDQACgEAAgEIAAAAQAAgEgBgDIgFgFQgDgDgHgCIgNgEIgUgGQgJgEgGgDQgGgEgDgHQgDgHAAgKIAAAAQAAgJAEgIQADgHAGgFQAHgFAJgDQAIgDAKgBIANACIANADQAJADAPAKIgOASQgJgGgKgEQgJgDgIAAIgJABIgHADQgGAFAAAHIAAABIABAHIAFAFQAEADAGACIAPAEQALADAIAEQAJADAFADQAGAFADAGQADAGAAAKQAAAKgEAIQgDAHgHAFQgHAGgJACQgJADgLAAIgOgBg");
	this.shape_7.setTransform(49.5,31);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgzBFIAAiJIBmAAIAAAVIhNAAIAAAlIBEAAIAAAUIhEAAIAAAmIBOAAIAAAVg");
	this.shape_8.setTransform(36.9,31);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgLBFIAAg3Ig3hSIAdAAIAlA+IAog+IAcAAIg4BRIAAA4g");
	this.shape_9.setTransform(22.7,31);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgLA2IgKgEQgKgEgIgHQgHgIgFgKIgDgKIgBgLIAAAAQAAgGAEgOQAFgKAHgHQAIgIAKgEIALgDIAKgCQAIAAAOAFQAKAEAIAIQAHAHAFAKQAEAOAAAGIAAAAIgBALIgDAKQgFAKgHAHQgIAIgKAEQgPAFgHAAgAgMgeQgGADgEAFQgEAEgCAGQgDAGAAAGIAAAAQAAAGADAHQACAGAEAFQAFAEAGADQAGADAFAAQAHAAAGgDQAGgDAEgEQAEgFACgGQADgGAAgHIAAAAQAAgFgDgGQgCgHgEgEQgFgFgGgDQgGgCgGAAQgGAAgGACg");
	this.shape_10.setTransform(3,32.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAABCQgGgCgEgDQgEgEgCgGQgCgGAAgIIAAg2IgOAAIAAgVIAOAAIAAgdIAWAAIAAAdIAdAAIAAAVIgdAAIAAAyQAAAHAEADQADADAGAAQAHAAAIgEIAAAUIgKAEQgGACgGAAQgHAAgDgCg");
	this.shape_11.setTransform(-7.7,31.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAABCQgGgCgEgDQgEgEgCgGQgDgGABgIIAAg2IgOAAIAAgVIAOAAIAAgdIAWAAIAAAdIAdAAIAAAVIgdAAIAAAyQAAAHADADQADADAHAAQAIAAAHgEIAAAUIgKAEQgGACgGAAQgHAAgDgCg");
	this.shape_12.setTransform(-21.9,31.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgRAzQgJgEgIgIQgIgHgDgKIgEgKIgBgMIAAAAQAAgKAEgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAGADAKAJQAGAIADALQAEAKAAAJIgBAHIhMAAQACAGACAGIAHAIQAEADAFACQAFACAEAAQAJAAAGgDQAHgDAHgHIAOANIgJAIQgEAEgFACIgMAEQgGACgIAAQgJAAgKgEgAAagGQAAgGgCgFQgCgFgEgEQgDgEgFgCQgEgCgGAAQgEAAgEACQgFACgEAEIgGAJQgCAFgBAGIA0AAIAAAAg");
	this.shape_13.setTransform(-31.9,32.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgaBCQgMgDgKgGIAJgSQAJAFAIADQAKADAKAAQAHAAAGgCQAGgCAEgEQAEgEADgGQACgGAAgIIAAgJQgJALgHADQgEADgGABQgEACgFAAQgJAAgJgDQgJgEgHgGQgGgHgEgJQgEgHAAgMQAAgIAEgNQAEgJAGgGQAIgHAIgDQAJgEAJAAQAFAAAFACIAKAEQAIAEAHAIIAAgPIAYAAIAABSQAAANgEAKQgDAKgHAGQgDAEgFADIgKAEQgQAEgHAAQgNAAgMgEgAgLguQgFACgEAEQgEAEgDAFQgCAGAAAGIAAAAQAAAHACAFQADAFAEACQAEAEAFACQAGACAFAAQAFAAAGgCQAGgCAEgEQAFgCACgFQACgFAAgHQAAgGgCgGQgCgFgFgEIgKgGQgGgCgFAAQgFAAgGACg");
	this.shape_14.setTransform(-44.9,34.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAXA1IAAg5QAAgGgCgGQgBgEgDgEQgDgDgEgBQgFgCgFAAQgDAAgEACQgFABgDADQgDAEgCAFQgCAFAAAGIAAA5IgYAAIAAhnIAYAAIAAAQQAGgIAIgEQADgDAFgCQAEgCAFAAQAJAAAIAEQAGADAFAFQAFAFADAIQACAHAAAKIAABAg");
	this.shape_15.setTransform(-63.5,32.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgXA0QgHgCgFgEQgFgFgDgFQgEgHAAgIIAAAAQAAgIAEgHQADgGAGgDQAFgEAIgCQAIgCAJgBQALAAAQAFIAAgCQAAgFgBgEQgCgFgDgDQgDgDgFgBQgFgBgFgBQgIABgHABQgHABgIAEIgHgTIASgHQALgCAKAAQALAAAJADQAJADAGAFQAFAHAEAIQACAIAAALIAAA8IgYAAIAAgNQgGAHgHAEQgLAEgIAAQgIAAgGgCgAgIAEIgIAEIgFAFQgBADgBAEIAAAAQAAAIAHAEQAFAEAJAAQAEAAAFgBQAFgCAEgDQAEgDACgEQACgFAAgEIAAgGQgPgFgJAAIgIABg");
	this.shape_16.setTransform(-75.9,32.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgEA2IgLgEQgJgEgIgHQgHgIgEgKQgEgKAAgLIAAAAQAAgKAEgKQAEgKAHgHQAIgIAKgEIAKgDIAJgCQAIAAAGACIALAEQAHADALAKIgPAQQgGgHgGgDQgHgDgJAAQgFAAgFACQgFADgFAFQgEAEgCAGQgCAGAAAGIAAAAQAAAHACAGQACAGAFAFQAEAEAGADQAEADAGAAQAIAAAIgEQAGgDAGgHIAOAPQgKALgHADIgMAEQgGACgIAAg");
	this.shape_17.setTransform(-87.1,32.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgRAzQgJgEgIgIQgHgHgFgKIgCgKIgBgMIAAAAQgBgKAEgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAHADAJAJQAGAIAEALQACAKAAAJIAAAHIhMAAQACAGACAGIAHAIQAEADAFACQAFACAEAAQAIAAAIgDQAGgDAGgHIAPANIgIAIQgFAEgFACIgMAEQgHACgGAAQgKAAgKgEgAAagGQAAgGgCgFQgCgFgDgEQgEgEgEgCQgGgCgFAAQgDAAgGACQgEACgEAEIgFAJQgDAFgBAGIA0AAIAAAAg");
	this.shape_18.setTransform(-104.9,32.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAXA1IgXhGIgXBGIgVAAIgihpIAYAAIAWBHIAXhHIATAAIAXBHIAWhHIAYAAIgjBpg");
	this.shape_19.setTransform(-119.5,32.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgPASQAJgCAEgFQACgFAAgGIgJAAIAAgbIAZAAIAAAYQAAAGgCAGQgBAGgEAEQgFAEgEACQgFACgIABg");
	this.shape_20.setTransform(133.3,18.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgeA1IAAhnIAZAAIAAAXQADgGACgEQADgFAEgEQAFgDAGgCQAFgCAHABIAAAZIgBAAQgIAAgGADQgIACgEAGQgDAFgDAIQgCAGAAAKIAAAog");
	this.shape_21.setTransform(127.3,12.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgRAzQgKgEgHgIQgIgHgDgKIgDgKIgCgMIAAAAQAAgKAEgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAHADAJAJQAGAIADALQAEAKAAAJIgBAHIhMAAQACAGACAGIAHAIQAEADAFACQAFACAEAAQAJAAAGgDQAHgDAHgHIAOANIgJAIQgEAEgFACIgMAEQgGACgIAAQgJAAgKgEgAAagGQAAgGgCgFQgCgFgEgEQgDgEgFgCQgFgCgFAAQgEAAgEACQgFACgEAEIgGAJQgCAFgBAGIA0AAIAAAAg");
	this.shape_22.setTransform(116.7,12.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgXBGQgIgEgHgGQgHgIgEgKIgDgKIgBgNIAAgBQAAgIAEgNQAEgJAHgIQAGgHAJgEQAJgEAKAAQAEABAFABQAGABAEAEQAIAEAHAIIAAg4IAYAAIAACQIgYAAIAAgSQgHAJgIAFIgKAEQgFACgEgBQgJABgKgEgAgKgLQgGADgEAEQgEAEgCAFQgDAGAAAHIAAABQAAAHADAHQACAGAEAFQAEAEAGADQAFACAFAAQAFgBAGgCQAFgCAFgEQAFgFACgGQACgHAAgHIAAgBQAAgHgCgGQgCgFgFgEQgFgEgFgDQgGgDgFAAQgFAAgFADg");
	this.shape_23.setTransform(103.7,10.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAXA2IAAg7QAAgGgCgFQgBgEgDgEQgDgDgEgBQgEgCgGgBQgDABgEACQgFACgDACQgDAEgCAFQgBAFgBAGIAAA6IgYAAIAAhoIAYAAIAAAQQAGgJAIgDQADgEAFgBQADgBAHgBQAIAAAIADQAGAEAFAFQAFAFADAIQACAHAAAKIAABBg");
	this.shape_24.setTransform(91.1,12.6);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgRAzQgJgEgIgIQgHgHgFgKIgDgKIAAgMIAAAAQAAgKADgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAHADAJAJQAGAIAEALQACAKAAAJIAAAHIhLAAQABAGACAGIAHAIQAEADAFACQAFACAEAAQAIAAAIgDQAGgDAGgHIAPANIgIAIQgFAEgFACIgMAEQgHACgGAAQgKAAgKgEgAAbgGQgBgGgCgFQgCgFgDgEQgEgEgEgCQgFgCgGAAQgDAAgGACQgEACgDAEIgGAJQgDAFAAAGIA0AAIAAAAg");
	this.shape_25.setTransform(78.8,12.7);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgwBGIAAiLIAZAAIAAB0IBIAAIAAAXg");
	this.shape_26.setTransform(67.1,11);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAvBGIgPgiIhAAAIgPAiIgYAAIA9iLIAVAAIA+CLgAAXAOIgXg2IgXA2IAuAAg");
	this.shape_27.setTransform(46.5,11);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("Ag5BGIAAiLIA9AAQAMABAJADQAKADAGAGQAEAFADAFQACAGAAAHIAAAAQAAAGgCAGQgBAEgDAFQgFAGgJAFIALACIAJAHQAEAFACAFQACAGAAAHIAAAAQAAAJgEAIQgDAHgHAFQgHAEgKADQgJACgMABgAghAwIAnAAIAMgCQAFgBADgCQAEgDABgDQACgEAAgFIAAAAQAAgEgCgEQgBgDgEgCIgJgFIgNgBIglAAgAghgKIAhAAIAKAAIAIgEQAEgCACgEQABgEAAgEIAAgBQAAgEgBgEIgFgFIgIgEIgKAAIgiAAg");
	this.shape_28.setTransform(31.8,11);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgKBGIgPgEIgOgHIgOgKIAPgRQAHAFAOAIQAFADAGABIAKABIALgBIAHgEQAEgCABgDQACgEAAgEIAAAAQAAgFgBgCIgFgGQgDgCgHgCIgNgFIgUgFQgJgEgGgCQgGgFgDgHQgDgHAAgJIAAgBQAAgJAEgHQADgIAGgFQAHgFAJgDQAIgEAKAAIANABIANAEQAJADAPAKIgOASQgJgGgKgEQgJgEgIABIgJABIgHADQgGAFAAAHIAAABIABAGIAFAGQAEADAGABIAPAFQALADAIAEQAJADAFADQAGAEADAHQADAHAAAJQAAAJgEAJQgDAHgHAGQgHAFgJADQgJACgLAAIgOgBg");
	this.shape_29.setTransform(17.7,11);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgXBGQgIgEgHgGQgHgIgEgKIgDgKIgBgNIAAgBQAAgIAEgNQAEgJAHgIQAGgHAJgEQAJgEAKAAQAEABAFABQAGABAFAEQAHAEAHAIIAAg4IAYAAIAACQIgYAAIAAgSQgHAJgHAFIgLAEQgFACgEgBQgJABgKgEgAgKgLQgFADgFAEQgEAEgCAFQgDAGAAAHIAAABQAAAHADAHQACAGAEAFQAFAEAFADQAFACAFAAQAFgBAGgCQAFgCAFgEQAFgFACgGQACgHAAgHIAAgBQAAgHgCgGQgCgFgFgEQgFgEgFgDQgGgDgFAAQgFAAgFADg");
	this.shape_30.setTransform(-1.5,10.8);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgRAzQgJgEgIgIQgHgHgFgKIgCgKIgBgMIAAAAQgBgKAEgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAHADAJAJQAGAIAEALQACAKAAAJIAAAHIhMAAQACAGACAGIAHAIQAEADAFACQAFACAEAAQAIAAAIgDQAGgDAGgHIAPANIgIAIQgFAEgFACIgMAEQgHACgGAAQgKAAgKgEgAAagGQAAgGgCgFQgCgFgDgEQgEgEgEgCQgGgCgFAAQgDAAgGACQgEACgEAEIgFAJQgDAFgBAGIA0AAIAAAAg");
	this.shape_31.setTransform(-14,12.7);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgeA1IAAhnIAZAAIAAAXQADgGACgEQACgFAFgEQAFgDAGgCQAGgCAGABIAAAZIgBAAQgIAAgHADQgGACgFAGQgDAFgDAIQgCAGAAAKIAAAog");
	this.shape_32.setTransform(-23.7,12.6);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgdA1IAAhnIAYAAIAAAXQACgGADgEQADgFAEgEQAFgDAFgCQAGgCAHABIAAAZIgBAAQgIAAgGADQgIACgEAGQgDAFgCAIQgDAGAAAKIAAAog");
	this.shape_33.setTransform(-31.9,12.6);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgRAzQgKgEgHgIQgIgHgEgKIgCgKIgBgMIAAAAQAAgKADgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAHADAJAJQAGAIAEALQADAKAAAJIgBAHIhMAAQABAGADAGIAHAIQAEADAFACQAFACAEAAQAJAAAGgDQAHgDAHgHIAOANIgJAIQgEAEgFACIgMAEQgHACgGAAQgKAAgKgEgAAagGQAAgGgCgFQgCgFgEgEQgDgEgFgCQgFgCgFAAQgEAAgFACQgEACgEAEIgFAJQgDAFgBAGIA0AAIAAAAg");
	this.shape_34.setTransform(-42.5,12.7);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgSBJIAAhTIgNAAIAAgUIANAAIAAgIQAAgJADgGQACgHAEgEQAEgEAFgCQAFgCAIAAQAKAAAJACIAAAVQgHgDgHAAQgHAAgDAEQgEAFAAAHIAAAGIAcAAIAAAUIgbAAIAABTg");
	this.shape_35.setTransform(-52.1,10.7);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgRAzQgJgEgIgIQgIgHgDgKIgEgKIgBgMIAAAAQAAgKAEgKQAEgKAHgHQAHgIAJgEIAKgDIAJgCIAMACIAKADQAGADAKAJQAGAIADALQAEAKAAAJIgBAHIhMAAQACAGACAGIAHAIQAEADAFACQAFACAEAAQAJAAAGgDQAHgDAHgHIAOANIgJAIQgEAEgFACIgMAEQgGACgIAAQgJAAgKgEgAAagGQAAgGgCgFQgCgFgEgEQgDgEgFgCQgEgCgGAAQgEAAgEACQgFACgEAEIgGAJQgCAFgBAGIA0AAIAAAAg");
	this.shape_36.setTransform(-62.1,12.7);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgdA1IAAhnIAYAAIAAAXQACgGADgEQACgFAFgEQAFgDAFgCQAHgCAHABIAAAZIgCAAQgIAAgGADQgIACgEAGQgDAFgCAIQgDAGAAAKIAAAog");
	this.shape_37.setTransform(-71.8,12.6);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("Ag1BGIAAiLIA1AAQANAAAKAEQAJADAHAHQAHAFAEAJQAEAJAAALIgBALIgEAKQgEAGgIAHQgHAFgLAEQgKACgJABIgcAAIAAAtgAgcADIAcAAQAFgBAGgCQAGAAAEgCIAGgIQACgFAAgFIAAgBQAAgGgDgFQgCgEgEgDQgDgEgGgCQgGgBgFAAIgcAAg");
	this.shape_38.setTransform(-82.5,11);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgXA0QgHgCgFgEQgFgFgEgFQgDgHAAgIIAAAAQAAgJADgGQAEgGAFgDQAHgEAHgDQAIgCAKAAQAKABAQAEIAAgCQAAgFgBgFQgCgEgDgDQgDgCgGgCQgEgBgFgBQgIABgIABQgGACgHADIgIgTIASgHQALgCAKAAQALAAAKADQAIADAGAGQAFAFADAIQAEAJAAALIAAA8IgZAAIAAgNQgFAHgJAEQgKAEgIAAQgHAAgHgCgAgJAEIgHAEIgFAFQgBADAAAEIAAAAQAAAHAFAFQAGAEAJAAQAEAAAFgBQAFgCAEgDQAEgDACgEQACgFAAgEIAAgGQgPgEgJgBIgJABg");
	this.shape_39.setTransform(-101.8,12.8);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgTAyQgPgGgGgGIALgQQAIAGAJAEQAJADAGAAQAIAAAEgDQAFgDgBgFIAAgBQABgFgIgEIgOgGQgQgEgHgEQgEgDgEgFQgCgFAAgIQAAgHACgGQADgGAGgFQAFgEAHgCQAHgCAFAAQAKAAALADQAJADAJAGIgJARQgIgFgIgCQgIgDgGAAQgFAAgEADQgEADAAAFIAAAAQAAAFAHAEIAPAGIAMAEIAKAEQAFAEADAFQADAFAAAHIAAAAQAAAIgDAHQgEAGgEAEQgGAEgHACQgHACgIAAQgKAAgMgEg");
	this.shape_40.setTransform(-118.6,12.7);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AAvBGIgPgiIhAAAIgPAiIgZAAIA+iLIAVAAIA+CLgAAXAOIgXg2IgXA2IAuAAg");
	this.shape_41.setTransform(-131.3,11);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-170,0,337,44);


(lib.box1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#002663").s().p("A6PK8IAA13MA0eAAAIAAV3g");
	this.shape.setTransform(168,70);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,140);


(lib.border336x280 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,0,3).p("A3RzXMAujAAAMAAAAmvMgujAAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-125,300,250);


(lib._2016TAG = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIQATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAIYgKQgEAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgFAFgADbATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAHAIAAAKQAAALgIAIQgIAIgMAAQgMAAgHgIgADjgKQgEAEAAAGQAAAGAEAFQAFAFAHAAQAGAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgGAAgFAFgAgpATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAGAIAAAKQAAALgGAIQgIAIgMAAQgMAAgIgIgAgggKQgFAEAAAGQAAAGAFAFQAFAFAGAAQAHAAAFgFQAEgEAAgHIAAAAQAAgFgEgFQgFgFgHAAQgHAAgEAFgAtIATQgIgIAAgLIAAAAQAAgKAIgIQAIgIAMAAQAMAAAIAIQAIAIAAAKQAAALgIAIQgIAIgMAAQgMAAgIgIgAs/gKQgFAEAAAGQAAAGAFAFQAEAFAHAAQAHAAAEgFQAFgEAAgHIAAAAQAAgFgFgFQgEgFgHAAQgHAAgEAFgAL+AaIgMggIgLAgIgKAAIgSgzIAMAAIALAiIAMgiIAKAAIALAiIALgiIAMAAIgSAzgAJJADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAAOADIAAgcIAMAAIAAAcQAAANALAAQAMAAAAgNIAAgcIALAAIAAAcQAAAXgXAAQgXAAAAgXgAk7ASIAHgIQAIAGAIAAQAHAAAAgFQAAgEgKgCQgJgDgEgCQgFgCAAgHIAAgBQAAgHAFgEQAFgEAJAAQAMAAAHAGIgGAJQgIgFgGAAQgGAAAAAEQAAAFALACQARAEAAAKQAAAQgUAAQgNAAgJgIgAsPADIAAgcIAMAAIAAAcQAAANALAAQALAAAAgNIAAgcIAMAAIAAAcQAAAXgXAAQgXAAAAgXgAN5AaIAAgMIAMAAIAAAMgANdAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgANDAaIgFgMIgWAAIgFAMIgMAAIAXgzIAKAAIAXAzgAM6AEIgHgPIgHAPIAOAAgAKiAaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgAKOAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAHoAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVgAGsAaIAAgMIAMAAIAAAMgAGQAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAFQAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAE5AaIgZggIAAAgIgLAAIAAgzIAKAAIAZAfIAAgfIALAAIAAAzgAC9AaIAAggIgPAUIgOgUIAAAgIgMAAIAAgzIANAAIANAWIAOgWIANAAIAAAzgABoAaIgMgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgABTAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAhRAaIAAgVIgUgeIAOAAIAMAVIANgVIANAAIgUAeIAAAVgAiNAaIAAgMIAMAAIAAAMgAi2AaIAAgzIAWAAQAJAAAFAFQAGAFAAAIIAAABQAAAGgGAFQgGAFgJAAIgJAAIAAAQgAiqAAIAJAAQAJAAAAgGQAAgIgJAAIgJAAgAjOAaIAAgzIALAAIAAAzgAjnAaIAAgVIgVAAIAAAVIgLAAIAAgzIALAAIAAAVIAVAAIAAgVIAMAAIAAAzgAlOAaIgLgRIgJAAIAAARIgLAAIAAgzIAYAAQAJAAAGAGQAEAEAAAIQAAAKgLAEIANATgAliAAIAMAAQAJAAAAgHQAAgHgJAAIgMAAgAmfAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAcAAIAAALgAnVAaIAAgzIAYAAQAJAAAFAFQADADAAAGIAAAAQAAAIgHADQAKACAAAJQAAAPgTAAgAnKAQIAOAAQAIAAAAgGQAAgGgJAAIgNAAgAnKgEIALAAQAIAAAAgFQAAgGgIAAIgLAAgAntAaIAAggIgPAUIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgApIAaIAAgzIAnAAIAAALIgcAAIAAAKIAZAAIAAAIIgZAAIAAALIAdAAIAAALgApgAaIAAggIgPAUIAAAAIgPgUIAAAgIgLAAIAAgzIAMAAIAOAWIAOgWIAMAAIAAAzgAq2AaIgLgRIgJAAIAAARIgMAAIAAgzIAYAAQAKAAAGAGQAEAFAAAHQAAAKgLAEIANATgArKAAIAMAAQAIAAAAgHQAAgHgJAAIgLAAgAtwAaIAAgVIgUgeIANAAIANAVIANgVIANAAIgUAeIAAAVg");
	this.shape.setTransform(0,2.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-90.1,0,180.4,5.5);


(lib._2016_SCU_logoruleai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F78E1E").s().p("AspAEQgEAAAAgEQAAgDAEAAIZSAAQAFAAAAADQAAAEgFAAg");
	this.shape.setTransform(0,0.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-81.4,0,162.9,1);


(lib._2016_SCU_logorevai = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALeAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAIOAgQgKAAgDgDQgDgDAAgJIAAghQAAgJADgDQADgDAKAAIAwAAQAJAAAEADQADADAAAJIAAAhQAAAJgDADQgEADgJAAgAINAUIAyAAIAAgnIgyAAgAGhAgIAAg/IAPAAIAAA/gAFHAgIg1grIAAArIgNAAIAAg/IAKAAIAuAlIAIAHIgBgMIAAggIAOAAIAAA/gAB8AgQgJAAgEgDQgDgDAAgJIAAgwIAPAAIAAAzIArAAIAAgzIAQAAIAAAwQAAAJgEADQgDADgKAAgAg7AgIAAgzIgeAAIAAgMIBLAAIAAAMIgeAAIAAAzgAimAgIAAg/IAPAAIAAA/gAk8AgIAAg/IAqAAQASAAAKAJQAJAIAAAOQAAASgOAJQgIAFgTAAgAktAUIATAAQAPAAAHgEQAHgFAAgLQAAgTgVAAIgbAAgAnHAgIAAg/IBDAAIAAALIg0AAIAAAPIAeAAIAAAJIgeAAIAAAQIA0AAIAAAMgAogAgIgbgYIgOAAIAAAYIgPAAIAAg/IA4AAQAPAAAAANIAAAPQAAALgPAAIgJAAIAfAYgApJgBIAiAAQAHAAAAgGIAAgIQAAgFgHAAIgiAAgArXAgQgKAAgDgDQgEgDAAgJIAAghQAAgJAEgDQADgDAKAAIAnAAQAJAAADADQAEADAAAJIAAAHIgPACIAAgMIgpAAIAAAnIApAAIAAgOIAPADIAAAIQAAAJgEADQgDADgJAAg");
	this.shape.setTransform(-0.4,36);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AiLCBIAAgHIAJAAQAOAAAGgFQAFgFABgMIAAjAQgBgMgFgFQgGgFgOAAIgJAAIAAgIIA4gDQAfgDATAAQA0AAAiAKQAiALAXAXQAeAdgBAvQAAA5gnAoQgbAaglAJQgWAFgiAAgAg5hwIAADOQAAAOAIAEQAHAEAYAAQA2AAAagbQAZgaAAg7QAAh2hsAAIgkACg");
	this.shape_1.setTransform(62,12.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("ABrCAIjAjTIAACeQgBAZAIAJQAHAJAWgBIAGAAIAAAHIheAAIAAgHQAVgBAHgGQAGgFABgQIAAi+QgTgTgOAAIgIAAIAAgHIBQAAICiCxIAAiLQAAgQgIgHQgIgIgSAAIgIAAIAAgHIBWAAIABAHQgRABgFAGQgHAGAAAPIAADcg");
	this.shape_2.setTransform(28.8,13.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhBBzQgsgVAAg0IAAiMQAAgMgGgFQgFgFgPAAIgHAAIAAgHIBxAAIAAAHIgHAAQgOAAgGAFQgGAFAAAMIAACOQAAAlARARQASASAjAAQAlAAATgSQAUgSAAghIAAiMQAAgQgFgGQgGgFgQAAIgHAAIAAgHIBdAAIAAAHIgJAAQgOAAgGAFQgGAEAAAMIAACHQAAAzghAWQgbATgxAAQgmAAgagNg");
	this.shape_3.setTransform(-4.7,13.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhfBeQglgkAAg6QAAg4AlgkQAlglA6AAQA+AAAlAnQAiAkAAA2QAAA5glAlQglAkg7AAQg6AAglgkgAg/hTQgHAMgFAZQgFAZAAAYQAAArAOAdQAVArAwAAQAqAAATghQAHgMAFgYQAFgZAAgYQAAg3gWgfQgWgfglAAQgrAAgUAig");
	this.shape_4.setTransform(-38.3,13.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguB9IgQgCQgGAAgEAEIgHAAIgBgGIgKgyIAGgCQAJAVAPAMQAXAQAhAAQAaAAARgNQARgNAAgVQAAgPgMgLQgLgLghgQQgpgSgVgTQgTgVAAgXQAAgeAXgSQAWgSAkAAQASAAAcAGQAJADAIAAQAGAAABgEIAHAAIABA3IgGAAQgFgRgHgJQgTgWgkAAQgVAAgOAKQgOAKAAAQQAAAPALAKQALAKAdAOQArAUATAPQAWAVAAAdQAAAjgaAVQgZAVgpAAQgWAAgXgFg");
	this.shape_5.setTransform(-66.7,13.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-75.9,0,151.9,39.3);


(lib.headbkgd = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F78E1E").s().p("A6PV3MAAAgruMA0eAAAMAAAArug");
	this.shape.setTransform(150,140,0.893,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// shad
	this.instance = new lib.HTML5rastershad_1();
	this.instance.setTransform(168,290,1,1,0,0,0,0,10);
	this.instance.alpha = 0.398;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,336,300);


// stage content:
(lib.SCU201609_Elec_300x250_AdR = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
	}
	this.frame_181 = function() {
		this.stop();
		 
		this.replay_btn.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		function fl_ClickToGoToAndPlayFromFrame() 
		{
		this.gotoAndPlay(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(181).call(this.frame_181).wait(2));

	// replay btn
	this.replay_btn = new lib.replaybtn();
	this.replay_btn.setTransform(276,148.6,0.75,0.75);
	this.replay_btn._off = true;
	new cjs.ButtonHelper(this.replay_btn, 0, 1, 2, false, new lib.replaybtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.replay_btn).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// cta btn
	this.clickthru_btn = new lib.CTA_btn();
	new cjs.ButtonHelper(this.clickthru_btn, 0, 1, 2, false, new lib.CTA_btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.clickthru_btn).to({_off:true},182).wait(1));

	// com
	this.instance = new lib.comhoriz();
	this.instance.setTransform(67,242.2,0.687,0.687,0,0,0,0,4.5);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// ncua
	this.instance_1 = new lib.ncuahorizai();
	this.instance_1.setTransform(233,240.4,1.03,1.03,0,0,0,0,3.6);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(181).to({_off:false},0).to({_off:true},1).wait(1));

	// border
	this.instance_2 = new lib.border336x280();
	this.instance_2.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({_off:true},182).wait(1));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("A6OLuIAA3bMA0eAAAIAAXbg");
	var mask_graphics_40 = new cjs.Graphics().p("A6OLuIAA3bMA0eAAAIAAXbg");
	var mask_graphics_41 = new cjs.Graphics().p("A4nLuIAA3bMAxPAAAIAAXbg");
	var mask_graphics_42 = new cjs.Graphics().p("A3ALuIAA3bMAuBAAAIAAXbg");
	var mask_graphics_43 = new cjs.Graphics().p("A1YLuIAA3bMAqxAAAIAAXbg");
	var mask_graphics_44 = new cjs.Graphics().p("AzxLuIAA3bMAnjAAAIAAXbg");
	var mask_graphics_45 = new cjs.Graphics().p("AyJLuIAA3bMAkTAAAIAAXbg");
	var mask_graphics_46 = new cjs.Graphics().p("AwiLuIAA3bMAhFAAAIAAXbg");
	var mask_graphics_47 = new cjs.Graphics().p("Au7LuIAA3bId3AAIAAXbg");
	var mask_graphics_48 = new cjs.Graphics().p("AtTLuIAA3bIanAAIAAXbg");
	var mask_graphics_49 = new cjs.Graphics().p("ArsLuIAA3bIXZAAIAAXbg");
	var mask_graphics_80 = new cjs.Graphics().p("ArsLuIAA3bIXZAAIAAXbg");
	var mask_graphics_81 = new cjs.Graphics().p("ArsLtIAA3ZIXZAAIAAXZg");
	var mask_graphics_82 = new cjs.Graphics().p("ArsLuIAA3bIXZAAIAAXbg");
	var mask_graphics_83 = new cjs.Graphics().p("ArsLtIAA3ZIXZAAIAAXZg");
	var mask_graphics_84 = new cjs.Graphics().p("ArsLuIAA3bIXZAAIAAXbg");
	var mask_graphics_85 = new cjs.Graphics().p("ArsLtIAA3ZIXZAAIAAXZg");
	var mask_graphics_86 = new cjs.Graphics().p("ArsLuIAA3bIXZAAIAAXbg");
	var mask_graphics_87 = new cjs.Graphics().p("ArsLuIAA3aIXZAAIAAXag");
	var mask_graphics_88 = new cjs.Graphics().p("ArsLtIAA3aIXZAAIAAXag");
	var mask_graphics_89 = new cjs.Graphics().p("ArsLuIAA3bIXZAAIAAXbg");
	var mask_graphics_90 = new cjs.Graphics().p("ArsLtIAA3ZIXZAAIAAXZg");
	var mask_graphics_169 = new cjs.Graphics().p("ArsLtIAA3ZIXZAAIAAXZg");
	var mask_graphics_170 = new cjs.Graphics().p("ArrLaIAA2zIXXAAIAAWzg");
	var mask_graphics_171 = new cjs.Graphics().p("ArrLHIAA2NIXXAAIAAWNg");
	var mask_graphics_172 = new cjs.Graphics().p("ArqKzIAA1lIXVAAIAAVlg");
	var mask_graphics_173 = new cjs.Graphics().p("ArqKgIAA0/IXVAAIAAU/g");
	var mask_graphics_174 = new cjs.Graphics().p("ArpKMIAA0XIXTAAIAAUXg");
	var mask_graphics_175 = new cjs.Graphics().p("ArpJ5IAAzxIXTAAIAATxg");
	var mask_graphics_176 = new cjs.Graphics().p("AroJlIAAzJIXRAAIAATJg");
	var mask_graphics_177 = new cjs.Graphics().p("AroJSIAAyjIXRAAIAASjg");
	var mask_graphics_178 = new cjs.Graphics().p("ArnI+IAAx7IXPAAIAAR7g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:167.2,y:57}).wait(40).to({graphics:mask_graphics_40,x:167.2,y:57}).wait(1).to({graphics:mask_graphics_41,x:156.8,y:57}).wait(1).to({graphics:mask_graphics_42,x:146.5,y:57}).wait(1).to({graphics:mask_graphics_43,x:136.1,y:57}).wait(1).to({graphics:mask_graphics_44,x:125.8,y:57}).wait(1).to({graphics:mask_graphics_45,x:115.4,y:57}).wait(1).to({graphics:mask_graphics_46,x:105.1,y:57}).wait(1).to({graphics:mask_graphics_47,x:94.7,y:57}).wait(1).to({graphics:mask_graphics_48,x:84.4,y:57}).wait(1).to({graphics:mask_graphics_49,x:74.1,y:57}).wait(31).to({graphics:mask_graphics_80,x:74.1,y:57}).wait(1).to({graphics:mask_graphics_81,x:74.1,y:53}).wait(1).to({graphics:mask_graphics_82,x:74.1,y:49}).wait(1).to({graphics:mask_graphics_83,x:74.2,y:45}).wait(1).to({graphics:mask_graphics_84,x:74.2,y:41}).wait(1).to({graphics:mask_graphics_85,x:74.3,y:37}).wait(1).to({graphics:mask_graphics_86,x:74.3,y:33}).wait(1).to({graphics:mask_graphics_87,x:74.3,y:29}).wait(1).to({graphics:mask_graphics_88,x:74.4,y:25}).wait(1).to({graphics:mask_graphics_89,x:74.4,y:21}).wait(1).to({graphics:mask_graphics_90,x:74.5,y:17}).wait(79).to({graphics:mask_graphics_169,x:74.5,y:17}).wait(1).to({graphics:mask_graphics_170,x:74.5,y:8.7}).wait(1).to({graphics:mask_graphics_171,x:74.5,y:0.5}).wait(1).to({graphics:mask_graphics_172,x:74.5,y:-7.8}).wait(1).to({graphics:mask_graphics_173,x:74.5,y:-16.1}).wait(1).to({graphics:mask_graphics_174,x:74.5,y:-24.3}).wait(1).to({graphics:mask_graphics_175,x:74.5,y:-32.6}).wait(1).to({graphics:mask_graphics_176,x:74.5,y:-40.9}).wait(1).to({graphics:mask_graphics_177,x:74.5,y:-49.1}).wait(1).to({graphics:mask_graphics_178,x:74.5,y:-57.4}).wait(1).to({graphics:null,x:0,y:0}).wait(4));

	// PIC1
	this.instance_3 = new lib._336x280elec();
	this.instance_3.setTransform(-1,-24,0.902,0.902);

	this.instance_4 = new lib.Tween11("synched",0);
	this.instance_4.setTransform(150.5,77);
	this.instance_4._off = true;

	this.instance_3.mask = this.instance_4.mask = mask;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3}]}).to({state:[{t:this.instance_4}]},40).to({state:[{t:this.instance_4}]},9).to({state:[{t:this.instance_4}]},31).to({state:[{t:this.instance_4}]},10).to({state:[{t:this.instance_4}]},79).to({state:[{t:this.instance_4}]},9).to({state:[]},1).wait(4));
	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(40).to({_off:false},0).to({regX:-7.4,regY:4.5,scaleX:0.69,scaleY:0.69,x:63.5,y:68},9).wait(31).to({startPosition:0},0).to({y:50},10).wait(79).to({startPosition:0},0).to({y:-43},9).to({_off:true},1).wait(4));

	// PIC2
	this.instance_5 = new lib._336x280retail();
	this.instance_5.setTransform(134,-8);

	this.instance_6 = new lib.Tween13("synched",0);
	this.instance_6.setTransform(218,62);
	this.instance_6._off = true;

	this.instance_7 = new lib.Tween14("synched",0);
	this.instance_7.setTransform(216,22);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_5}]},40).to({state:[{t:this.instance_6}]},40).to({state:[{t:this.instance_7}]},10).to({state:[{t:this.instance_7}]},79).to({state:[{t:this.instance_7}]},9).to({state:[]},1).wait(4));
	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(80).to({_off:false},0).to({_off:true,x:216,y:22},10).wait(93));
	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(80).to({_off:false},10).wait(79).to({startPosition:0},0).to({y:-69},9).to({_off:true},1).wait(4));

	// PIC shad
	this.instance_8 = new lib.HTML5rastershad_1();
	this.instance_8.setTransform(168,142.1,1,1,0,0,0,0,10);
	this.instance_8.alpha = 0.199;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(80).to({y:102},10).wait(79).to({y:7},9).to({_off:true},1).wait(4));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_0 = new cjs.Graphics().p("A7VC5IAAlxMA2qAAAIAAFxg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:mask_1_graphics_0,x:150,y:161.6}).wait(49).to({graphics:null,x:0,y:0}).wait(134));

	// HEAD
	this.instance_9 = new lib.HEAD1();
	this.instance_9.setTransform(270.1,180,1,1,0,0,0,119.5,27);

	this.instance_9.mask = mask_1;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({_off:true},80).wait(103));

	// HEAD2
	this.instance_10 = new lib.HEAD2();
	this.instance_10.setTransform(150,137,1,1,0,0,0,-1.5,31.9);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(90).to({_off:false},0).to({_off:true},79).wait(14));

	// CTA
	this.instance_11 = new lib.CTA();
	this.instance_11.setTransform(269.5,67,1,1,0,0,0,119.5,40);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(178).to({_off:false},0).to({_off:true},4).wait(1));

	// Close
	this.instance_12 = new lib.Close();
	this.instance_12.setTransform(150,87,1,1,0,0,0,-1.5,24);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(178).to({_off:false},0).to({_off:true},4).wait(1));

	// head bkgd
	this.instance_13 = new lib.headbkgd();
	this.instance_13.setTransform(167.1,106.8,1,0.891,0,0,0,168,140);

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(80).to({x:168,y:50.8},10).wait(79).to({scaleY:1,y:-2},9).to({_off:true},4).wait(1));

	// tag
	this.instance_14 = new lib._2016TAG();
	this.instance_14.setTransform(150,218.6,1.25,1.25,0,0,0,0,2.7);
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(178).to({_off:false},0).to({_off:true},4).wait(1));

	// logo
	this.instance_15 = new lib._2016_SCU_logorevai("synched",0);
	this.instance_15.setTransform(387.4,261.7,1.103,1.103,0,0,0,215.3,63.1);
	this.instance_15._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(90).to({_off:false},0).wait(79).to({startPosition:0},0).wait(9).to({regX:215.2,regY:63,scaleX:1.23,scaleY:1.23,x:413.6,y:225.7},0).to({_off:true},4).wait(1));

	// logo rule
	this.instance_16 = new lib._2016_SCU_logoruleai();
	this.instance_16.setTransform(253.3,205.5,1.267,1.267,0,0,0,81.5,0.5);
	this.instance_16._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(178).to({_off:false},0).to({_off:true},4).wait(1));

	// logo box
	this.instance_17 = new lib.box1();
	this.instance_17.setTransform(134,82.3,0.893,1.786,0,0,0,150,46.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_17).to({_off:true},182).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(142.1,107,344,298);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;